cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
cnee --replay -f math.xnl --time 1
