** Inquiry 							      :drill:
Have you ever read about a topic or watched a program about something and wanted to know more about it? 
When you learn more about a topic, you are [building] on what you already know. The same principle applies to science.

This lesson will explore scientific theory as the basis for new [knowledge], the evaluation of scientific work, 
and how new scientific methods and technologies are developed.

** Inquiry 							      :drill:
The field of science is constantly growing and changing. New observations are made, and new theories are formed. 
All of this becomes a part of what we know as science.

Science is a body of knowledge based on the [observations] of scientists. 
It is the state of knowing [facts] about the world and testing that information through the [scientific] [method].

** Inquiry 							      :drill:
[New] ideas and theories are based on [old] ideas and theories.

When a scientist finds a way of explaining a topic or completing an operation, he or she does not stop there.

It is at this point that other scientists will take an interest in the idea and work to develop it even further.

This is the way that science continues to develop and grow.

An idea or [theory] is formed. A [theory] is a belief or idea based on the information or knowledge available about a subject.

That [theory] is then further developed and expanded.

** Inquiry 							      :drill:
A [scientist] is a person who is knowledgeable in a specific area of science and tries to find out how things in nature work.

They try to better understand the world and find ways to improve our lives.

The more that is learned, the more information is available to build new ideas.

Photography is a good example of this.  The primary theories used in photography had been around for hundreds of years.

Eventually, the new idea of capturing an image in print was built on old theories.

** Inquiry 							      :drill:
Scientists often make observations or conduct experiments to gather data on a topic and decide how best to resolve a situation.

Numerous measurements are required to be made while making [observations] or conducting [experiments].

These measurements must be [accurate].

That means they should not contain any mistakes.

** Inquiry 							      :drill:
There are times when scientists cannot find the necessary tools or effective methods to complete their work.

This could be the case if they are exploring a topic that has not been explored before or developing new technology.

In these cases, they may need to develop new methods or tools to complete these measurements and gather [data].

** Inquiry 							      :drill:
Once [data] has been collected, it is [published] for review and evaluation.

It is through this process that the [data] is refined and checked for accuracy.

Just as we discussed earlier in the lesson, new ideas are built on old ones.

For this reason, it is important for scientific [data] to be accurate.

** Inquiry 							      :drill:
If new ideas are built on past information that is flawed and filled with mistakes, the new ideas will be flawed as well.

Scientists work together to check and recheck [data] to ensure that it is as [accurate] as possible.

When scientists conduct observations or experiments, they must make [measurements].

When they have completed these measurements, they are then able to evaluate their work and draw conclusions from the [results].

It is this process of evaluation and drawing conclusions that provides us with additional knowledge about the field of science.


** Data Collection 						      :drill:
Today's society uses [data] in a vast number of ways and in many professions.

Data is another word for [information].

People interested in selling products collect [data] about what people buy.

** Data Collection 						      :drill:
Scientists who want to learn more about something must [collect] data about the topic.

This data can come from either the [previous] work of other scientists or new [experiments] and [observations] they conduct.

This data is often in the form of [mathematical] figures.

** Data Collection 						      :drill:
These are only a few examples of the types of measurements scientists might make.

Most measurements made by scientists to gather data are expressed as [numbers] or other mathematical [figures].

Here is an example of how the process of [collecting], presenting, calculating, organizing, and [evaluating] data might work.

Most people like to know what the weather is going to be the next day or even the next week.

** Data Collection 						      :drill:
[Measurement] is accurate and precise information gathered by scientists with the use of special tools.

[Measurements] are made daily, or even hourly, all over the world documenting the temperatures at specific locations.

The [measurements] have been made at the same time and in the same way for decades.

This [data] is then averaged.  This is how the "normal" temperature for a specific location is determined.

** Data Collection 						      :drill:
[Evaluation] is involved in all areas of science.

Scientists [evaluate] the work of others to ensure it is accurate.

The use of mathematics in this process ensures that all scientists, regardless of what language they speak, will be able to look over the data and [evaluate] it.

Mathematics is a universal [language] in itself.

** Data Collection 						      :drill:
Meteorology is now a trusted part of our everyday life.

Technology has greatly increased the speed and accuracy of this science over the years.

We rely on local meteorologists to give an accurate [forecast] of the [weather] each day and to alert us of inclement or hazardous weather.

With the development of technology, scientists are able to gather more [data] in a shorter period of time and with more [accuracy].

** Data Collection 						      :drill:
[Computers] have had a significant impact on the way scientists gather data.

Scientists once made difficult calculations that took hours to complete, and they often made mistakes.

It is now possible for a [computer] to make these same calculations without error in a matter of seconds.

The way [scales] now weigh objects has become incredibly precise.

The [microscope] has become more advanced and can show the smallest parts of a cell.

** Data Collection 						      :drill:
Scientists must use a variety of methods of gathering data based on the question to be answered.

Two examples of methods that could be used are [observation] and [experimentation].

[Observation] is anything noticed about a problem.

[Experimentation] is collecting information by trying new things.

An [experiment] would be an appropriate method to find how ice affects the temperature of water.

To find the average temperature of a location over time, [observation] would be an appropriate method to use.

With either method, careful [measurement] is crucial to the accuracy of the data.


** Science Skills 						      :drill:
Throughout the day, everyone is faced with problems that need to be solved or questions that need to be answered.

What steps do you take to solve problems and answer questions?

Scientists search for answers to questions by using the scientific [method].

In this lesson, you will learn the steps of the scientific [method] and how it can be used in everyday life to help solve problems.

You will also learn how to use [deductive] and [inductive] reasoning to draw conclusions.

** Science Skills 						      :drill:
Scientists use a [systematic] approach to investigate research problems as an integral part of their profession.

They call this system the [scientific method].

** Science Skills 						      :drill:
The scientific method is an orderly arrangement of [steps] that scientists use in [problem] [solving].

It is not a set of rigid rules, but rather a general [process] used to solve problems.

Let us look at the steps included in the scientific method.

** Science Skills 						      :drill:
1) What is the [problem]?

Before conducting research or expending time, energy, or money, scientists first state or identify the [problem].

Scientists must determine the questions they are seeking to [answer].

** Science Skills 						      :drill:
2) Obtaining [Information]

This is the research phase in which the scientist gathers all the background material.

Other scientists may have already discovered relevant and important [information] concerning this question.

After a careful study of the background [information], the scientist is ready to make an educated guess as to the solution to the research problem.

** Science Skills 						      :drill:
3) Formation of a [Hypothesis]

A [hypothesis] is an educated guess of what you think will happen in an experiment.
It is the result of careful [observation], research, and study.

A [hypothesis] is formed after the question has been asked and the information has been gathered and studied.
This is done prior to performing any [experiments].

** Science Skills 						      :drill:
4) [Experimentation] (after forming a hypothesis).

Students often think science is nothing more than one [experiment] after another.  This is not true.
A great deal of work goes into a study before any [experimentation] is ever attempted.

Even more work follows after the [experiment] has yielded results.
[Experiments] must follow certain guidelines to be considered valid or true.

** Science Skills 						      :drill:
5) [Analyzing] Data

Following the completion of the experiment, all the collected information, or [data], must be [analyzed].

This process may require the compilation of data tables or the creation of new graphs.

** Science Skills 						      :drill:
6) Drawing a [Conclusion]

Following this extensive study, a conclusion may be reached.  The answers may or may not be known.

The [conclusion] might show that more experimentation or another approach may be needed.

Remember, in science, we learn from [failures] as well as from [successes].

** Science Skills 						      :drill:
You might use the [scientific method] to solve a problem of your own.

Look at an example:
1.  You notice your allowance does not seem to be going as far as it once did.
2.  You decide to keep a record of all your expenses for a week.
3.  You look at your list and discover you are buying three soft drinks a day from the machine at school.  These sell for 75 cents each.
4.  You decide to have only one soft drink a day for the next two weeks.
5.  You have saved $15.00 and now have extra cash for the weekend.

Congratulations! You have just used the [scientific method] to solve a problem.

** Science Skills 						      :drill:
Remember the following steps:

1.  The scientific method begins with an [observation].
2.  The [observation] leads you to ask a [question].
3.  You gather [information] to answer the [question].
4.  You make an educated guess and form a [hypothesis].
5.  You test your [hypothesis] by performing an [experiment] (or by [observing] the subject).
6.  You review and [analyze] data.
7.  You draw a [conclusion].

** Science Skills 						      :drill:
Scientists use both [inductive] and [deductive] reasoning when solving problems using the scientific method.

[Deductive] reasoning moves from [general] to [specific] in order to reach a conclusion.

[Inductive] reasoning moves from [specific] facts to [general] in order to reach a conclusion.

** Science Skills 						      :drill:
Look at an example of [inductive] reasoning:

Observation: The addition of saltwater to roses results in the death of the roses.

Inductive reasoning:
1.  Saltwater kills roses.
2.  Roses are flowering plants.
3.  Therefore, saltwater would probably kill all flowering plants.

This reasoning moved from [specific] to [general].

** Science Skills 						      :drill:
Now, look at an example of [deductive] reasoning.

Observation: Butterflies change through metamorphosis from eggs, to larva (caterpillar), to pupa, and finally to adult butterflies.

This reasoning moved from [general] to [specific].

** Science Skills 						      :drill:
Scientists discover a new species of caterpillar while doing research in Peru.
Scientists know that caterpillars undergo metamorphosis and become butterflies.

Using [deductive] reasoning, this caterpillar should transform into a pupa and finally into a new species of butterfly.

** Science Skills 						      :drill:
Science is often associated with experimentation.
If data is to be valid, the experiment must be [controlled].

A [controlled] experiment is one in which only one [variable], or single condition, is changed at a time.

Look at an example.
Suppose you bake some cookies, and they taste awful and look terrible.

You start over, but this time you add two more eggs, 1/2 cup more sugar, and a cup of chocolate chips to the recipe.
You bake them at a higher temperature than the first batch.

Now the cookies are delicious.

Which [variable] caused the success?
[Because so many changes were made at the same time, we do not know which variable caused the cookies to be so much better the second time.]

** Science Skills 						      :drill:
In a controlled experiment, only [one] variable is changed at a time.

** Science Skills 						      :drill:
Scientists use the scientific [method] every day to answer questions and solve problems.

The scientific method involves making an [observation], asking a question, gathering [information], 
forming a [hypothesis], performing a [controlled] experiment, analyzing [data], and finally drawing a [conclusion].

Conclusions can be formed by using [inductive] or [deductive] reasoning.


** Science Fair Project 					      :drill:
The [scientific method] is six organized steps to finding answers.

They are as follows:
1) state the [problem] (topic)
2) [gather] information
3) form a [hypothesis]
4) [experiment]
5) [record] and [analyze] data
6) develop a [conclusion]

** Science Fair Project 					      :drill:
It is a good idea to state your purpose in the first step.

If your purpose is well worded, you will have little difficulty writing a [title] for your project.

** Science Fair Project 					      :drill:
The next step is gathering information.

In this step, you research and gather all the information possible about your topic.  This includes interviews 
with professional people, library research, observations, and even research on the Internet.

This information will help you form a [hypothesis]:  A statement of what you think will happen as you investigate and [experiment].

** Science Fair Project 					      :drill:
Remember to complete a [bibliography] of all research you do and be sure to keep it current.

List alphabetically all books, articles, people, and other [sources] that you used for researching and writing.

** Science Fair Project 					      :drill:
Now you are ready to experiment.  The items needed for an experiment are:

1) materials
2) variables
3) step-by-step directions

List all materials used in your investigation.
Include what, how much, and what kinds of materials you used.
Keep in mind that quantities are very important.
Be sure to use only [metric] units.

** Science Fair Project 					      :drill:
A [variable] is a single condition that may vary during the course of an [experiment].

There are three types of variables.

1) [Manipulated] variable - what is purposely changed in an investigation
2) [Responding] variable - what changes by itself because you changed something in the investigation
3) Variables held constant - everything else in your investigation must be held constant, or kept the same

** Science Fair Project 					      :drill:
Your step-by-step directions are like a recipe.  Anyone who reads them will be able to [duplicate] your investigation and get the same [results].

You must keep a data sheet or log.
Data refers to [information] gathered during your investigation.

** Science Fair Project 					      :drill:
Now, let us go step-by-step all the way through a project.

Our [topic/question]: "Do all brands of paper towels absorb the same amount of water?"

Our [hypothesis]: "The cheaper the paper towel, the less water it will absorb."

** Science Fair Project 					      :drill:
To be valid and convincing, data must be analyzed and displayed.
One of the most easily read forms for displaying information is a [graph].

** Science Fair Project 					      :drill:
There are two main types of graphs: [bar] graphs and [line] graphs.

A [bar] graph uses bars to display data.
The lengths of the bars represent numerical amounts.

A [line] graph uses points connected by lines to display data.
The lines show how something changes over [time].

** Science Fair Project 					      :drill:
There are three main items which you must take into consideration and use when making a graph.

1) [Title] - the [title] is a short description of the data being displayed.
2) [Horizontal] axis - the [manipulated] variable is displayed on the [horizontal] axis.
3) [Vertical] axis - the [responding] variable is displayed on the [vertical] axis.

** Science Fair Project 					      :drill:
Before you write your conclusion, carefully examine all your data (graphs, charts, tables, etc.).

Ask yourself these questions:

1.  Did you get the [results] you expected? If not, how were the [results] different?
2.  Were there any unexpected problems that may have affected your [results]?
3.  Do you think you collected enough [data]?
4.  Do you need to revise your [hypothesis]?

** Science Fair Project 					      :drill:
9.   Are you keeping a [log]?
10.  Could someone else set up and carry out your investigation from your [step]-[by]-[step] directions?
11.  Have you presented information clearly using [graphs]?
12.  Will your data allow you to draw [conclusions] and/or support your [hypothesis]?


** The Process of Science 					      :drill:
How is scientific research done? Do new ideas replace old ones? Do scientists always agree? 

Does someone need to give his or her consent to be used as a research subject?

All of these questions and more will be answered in this lesson.

** The Process of Science 					      :drill:
A scientist is a person who studies and explores one or more of the [branches] of science.

In this lesson, you will learn about some of the things scientists do during their research.

** The Process of Science 					      :drill:
Scientists usually follow the steps of the [scientific] [method] when they do research.

This involves identifying a problem, making observations, forming and testing a hypothesis, coming to a conclusion, and reporting the findings.

This is a long process that can sometimes take years to complete.

** The Process of Science 					      :drill:
Scientific knowledge is based on evidence; however, as new knowledge is gained, old ideas may change.

Sometimes this is difficult for scientists because they do not always agree or interpret data the same way.

Scientists use critical [evaluation] when looking at new ideas because it is a basic part of science.

[Science] is the state of knowing facts about the world and testing information through the scientific method.

** The Process of Science 					      :drill:
Scientific knowledge is always based on [evidence]: It shows [proof].

** The Process of Science 					      :drill:
In science, every accepted idea must have evidence and be able to be proven.

If other scientists are not able to [duplicate] a method and prove it, they will not know if it is valid or not.

Experimental proof and evidence are what make scientific observations [valid].

If there is a lack of evidence, scientists cannot find out if the theory is correct or not.

** The Process of Science 					      :drill:
Change in knowledge is going to happen.
New ideas are going to be formed, and new observations are going to challenge popular theories.
As new knowledge is gained, ideas about the natural world may change.

Regardless of how well a theory explains a set of observations, it is possible that another theory will be created to better [explain] it.

Making improvements to ideas, and sometimes completely changing them, happens often in science.

** The Process of Science 					      :drill:
Sometimes it is hard for scientists to accept a new theory regardless of how much evidence there is to support it.

However, theories are judged by their results.

If a new idea answers more questions and produces more results, it eventually takes the place of the old one.

When new ideas are developed and tested, they go through critical [evaluation] by other scientists before they are [accepted].

The researching scientist must provide accurate reports and steps for others to read and follow.

** The Process of Science 					      :drill:
Scientists carefully test, study, and evaluate the theory.

Observations and experiments are repeated so the results can be evaluated.

The scientific community will only accept an idea after it has been [evaluated] and [tested] many times by other scientists.

The more a hypothesis is tested and proven, the more confidence scientists have in it.

Repeating a process many times and getting the same results [validates] the conclusion.

** The Process of Science 					      :drill:
When a hypothesis fails, the scientific community loses confidence in it.

Sometimes scientists evaluate an idea or a procedure and disagree with it.

Rather than rejecting it, they try to find ways to change it to try to make the idea better.

Scientists gain knowledge and understanding from [mistakes].

** The Process of Science 					      :drill:
The process of science depends on observations and theories.

When scientists evaluate new ideas, they make new [observations] that helps them learn and gain knowledge.

As new theories and ideas develop, scientists acquire new [information].

As they evaluate and test this new [information], they come to new understandings about the world.

** The Process of Science 					      :drill:
Sometimes scientists do not [interpret] data the same way.

This can cause disagreements among the scientific community.

Scientists work with each other to resolve their issues.

They do this by collecting additional evidence to support or dispute the idea in question.

** The Process of Science 					      :drill:
Scientists sometimes disagree about the value of certain types of evidence.

They may not believe it is relevant to the theory or important enough to base a decision on.

Other times, scientists make [assumptions] in their testing.  An [assumption] is what someone thinks, and it usually cannot be proven.

Therefore, it cannot be backed up with evidence.  However, if there is evidence that supports an [assumption], scientists may accept it.

** The Process of Science 					      :drill:
Sometimes scientists disagree with evidence or data that is [biased].

[Bias] is a prejudiced outlook.

Scientific data can be [biased] in how it is collected, interpreted, or reported.

** The Process of Science 					      :drill:
A scientist's race, gender, religion, or political opinions can affect his or her perception, and therefore affect what data is believed to be important.

Scientists are expected to be aware of possible biases in their own work, as well as in the work of others.

That is one reason scientists evaluate each other's work.

If they detect [biased] data, they will question its [validity].

Different explanations can sometimes be given for the same data or evidence.

It is not always possible to know which explanation is right.

** The Process of Science 					      :drill:
Scientists do many different types of scientific research.

Science that affects the well-being of humans must eventually be tested on human subjects.

Scientists must follow [ethical] guidelines in testing.

One of the most important rules is ensuring that proper [consent] is given.

Each subject should be respected as a person who can make his or her own decisions.

He or she must be fully informed of the purpose of the research.

** The Process of Science 					      :drill:
Subjects should know with whom the researcher is affiliated, and who is funding the research project.

Subjects should be made aware of any procedures or methods they will be a part of.

They must be told of all the potential [risks] and the expected [benefits] involved in the experiment.

They should also be made aware of any stress or discomfort that may be experienced.

Subjects should be allowed to ask questions and get clear answers from the scientists involved in the research.

** The Process of Science 					      :drill:
Special care must be given to human subjects who are not capable of making [informed] decisions on their own.

Children, people who are legally incompetent, and those who are physically or mentally incapable of giving 
consent can participate in a study as long as someone who is legally authorized gives consent in their behalf.

However, these groups should never be used unless there is no alternative.

Although it is necessary to use human subjects in order for science to progress, research involving 
humans has important [ethical] implications.

This is why having guidelines that protect human rights and health is so important.

Scientific research is part of our daily world, and it will continue to be.

It is important to understand the process researchers take to make scientific advancements.


** Contributions Made by Scientists 				      :drill:
This lesson will introduce two important scientists and the contributions they have made to society.
You will see that scientists come from a variety of cultures, and you will learn how the new ideas introduced by scientists are sometimes difficult for society to accept.

** Contributions Made by Scientists 				      :drill:

** Contributions Made by Scientists 				      :drill:
Throughout history, many scientists, people who are experts in at least one area of science, have done things to make the world a better place to live.
Scientists have been experimenting and inventing for a long time.
Scientists live all over the world and come from all cultures and ethnic backgrounds.

Charles Drew was born in Washington, D.C., in 1904 as the first son of an African American carpet layer and a schoolteacher.
As a child, Charles did very well in school and excelled in a variety of sports.
He attended Amherst College in Massachusetts on an athletic scholarship.
Charles worked hard to keep high grades.
He received many awards and honors for his athletic performance and was very popular.

** Contributions Made by Scientists 				      :drill:
By the time he graduated from Amherst, Charles had decided to go to medical school.
However, his family did not have the money for him to continue his education until he worked for a few years.

After two years, Charles began applying to medical schools.
However, there were only two medical schools in the United States that would accept applications from African American students.
After rejections from both of them, Charles applied to McGill University in Montreal, Canada, and was accepted.

** Contributions Made by Scientists 				      :drill:
Charles studied anatomy at McGill with an instructor named Dr.
John Beattie and became interested in blood transfusions.
A blood transfusion is a way of transferring blood from one person to another.

At this time, blood typing had just been discovered.
Doctors did not give patients blood that was different from their type because of the negative effects it caused.
Because blood was usable only for a few days, doctors did not always have the correct blood type available for patients who needed it.

** Contributions Made by Scientists 				      :drill:
Although Charles Drew was an African American in a time when racial discrimination was common, he achieved a high level of education, which he continued at Columbia University.

While at Columbia, Drew researched and developed a technique for storing blood for longer periods of time.
He experimented with the use of plasma in transfusions rather than using whole blood.
Plasma is the liquid part of blood that contains blood cells and platelets.
Charles Drew discovered that if plasma was separated from the blood and kept at cool temperatures, the blood and plasma could be combined and used for transfusions later.

He also discovered that by removing the red blood cells, the part that contains blood type, from the plasma, a match between donor and patient was not necessary because plasma is the same for everyone regardless of blood type.

** Contributions Made by Scientists 				      :drill:
Drew's discoveries led to the development of blood banks across the country.
During World War II, blood banks were set up in Europe and Drew began the use of "bloodmobiles," refrigerated trucks used to transport blood.

Because of his success, Drew became the director of the American Red Cross blood bank.
He organized a massive blood drive for the United States Army and Navy.
The military demanded that blood typing be done by race of the donor and that African Americans be turned away.

** Contributions Made by Scientists 				      :drill:
This outraged Charles Drew, who declared the military's demand to be unscientific.
He stated that blood was not related to race.
Other scientists supported his statement, and the military eventually allowed African American volunteers to give blood.
Charles Drew's persistence saved many lives.

Charles Drew is remembered as the inventor of the blood bank and the first director of the American Red Cross blood bank.
Regardless of the positive effects that blood transfusions have had on human lives, some cultures (as in all science) find new technology hard to accept due to their cultural beliefs.

Jehovah's Witnesses have religious beliefs that taking blood into the body is morally wrong.
They will not accept whole blood or plasma; therefore, blood transfusions are not allowed for people of this religion.

** Contributions Made by Scientists 				      :drill:
Adults of the Christian Science religion  usually will not accept a blood transfusion but will sometimes allow it for their children if it is necessary.

Other religions believe blood transfusions to be unclean.
They have concerns about the contamination that is brought into the body by the transfusion.
Blood transfusions are one of many ideas in science that are difficult for some cultures and religions to accept.

** Contributions Made by Scientists 				      :drill:
Lise Meitner was born in Vienna, Austria, in 1878 to a Jewish family.
Her family did not want Lise to go to a university to study science.
They did not believe that to be an appropriate choice for a woman.

However, she was determined to go to college and was successful in her educational endeavors.
She became the first woman to get a PhD in physics at the University of Vienna.

** Contributions Made by Scientists 				      :drill:
After finishing her education, Lise went to Berlin where she began working with a chemist named Otto Hahn.
Lise and Otto began a long investigation of radioactivity using her knowledge of physics and his knowledge of chemistry.

Together, they discovered the first long-lived isotope of protactinium and declared it a new element.
They also discovered nuclear fission, which is the splitting of uranium atoms.

** Contributions Made by Scientists 				      :drill:
Lise Meitner was the first person to understand that the nucleus of an atom can be split into smaller parts.
Meitner realized that it was possible for a chain reaction to occur, thus creating the potential to create an explosion.
She never realized that her research would result in nuclear weapons.

Throughout her career, Lise Meitner met many challenges because of her cultural background and because she was a woman.

** Contributions Made by Scientists 				      :drill:
After Nazi Germany took over Austria, Meitner tried to leave the country.
Because of her Jewish heritage, she had not been given a passport for over ten years.
She was almost not allowed to leave Germany but eventually escaped.

Lise Meitner also met challenges after completing her research with Hahn.
It became politically impossible for Meitner and Hahn to publish their findings together because Lise had been banished from the country, so they were forced to publish their findings separately.
Consequently, Hahn received the Nobel Prize while Meitner did not.

** Contributions Made by Scientists 				      :drill:
Scientists from different cultures and ethnic backgrounds continue to contribute to science still today.

Charles Drew and Lise Meitner are two examples of significant contributors of the scientific community.


** Careers in Science 						      :drill:
This lesson will introduce some of the exciting careers in engineering.
Engineering is a very broad subject, and there are many different kinds of careers that interest all types of people.

What everyday activities involve science and engineering? What careers are available in engineering? What types of people can be scientists and engineers? All these questions and more will be answered in this lesson.

** Careers in Science 						      :drill:

** Careers in Science 						      :drill:
A career is a profession that someone trains for and chooses to work in throughout most of his or her life.
That is different from a job.
A job is a duty that has an end.
A person can have many jobs throughout his or her career.

Science is the state of knowing facts about the world and testing information through the scientific method.
A scientist is a person who tries to find out how things in the world work.
Scientists must be intelligent, ethical, and unbiased.

** Careers in Science 						      :drill:
Scientists must have human intellect, or intelligence.
Inventing a theory to understand how things in the world work is a very creative process which requires intelligence.
Scientists should also be able to think of things that no one has ever thought of before.

Scientists must be able to explain their processes and develop real ways to make them work.
They should also have the ability to do experiments to test and prove their ideas.
All of this takes human intellect.

** Careers in Science 						      :drill:
Scientists must be ethical and unbiased.
To be ethical is to follow professional standards of conduct.
Some of the ethics of science include keeping accurate records, sharing information, and having work repeated for evaluation by the scientific community.

When scientists withhold information or falsify data so they can be the first to publish an idea, they violate the ethics of science.
This type of behavior is unacceptable in the scientific world and can cause a scientist to lose a grant or not get work published.

** Careers in Science 						      :drill:
Bias is a prejudiced outlook.
Scientific data can be biased in how it is collected, interpreted, or reported.
A scientist's race, gender, religion, or political opinions can influence his or her perception and affect what data he or she believes to be important.

Scientists are expected to be aware of possible biases not only in their own work, but also in the work of others.
That is one reason scientists share and evaluate each other's work.
If they detect biased data, they should question its legitimacy.

** Careers in Science 						      :drill:
Science is an individual endeavor, and sometimes it involves collaboration.
 Scientists may begin by working alone.
However, at some point, they share their results with other scientists.

Working with others by sharing information is called collaboration.
Collaboration helps scientists form more complete ideas and allows them to improve their methods.
Scientists sometimes share their work with others to compare their results and check for accuracy.
This is called corroboration.
Through collaboration and corroboration, scientists are able to make advancements in science.

Have you ever thought about what kind of career you would like to have? Do you enjoy solving problems? Are you interested in how things are designed?  Engineering might be the career for you.

** Careers in Science 						      :drill:
Engineers use theories and ideas from math and science to solve a variety of problems.
Their work is the link between a scientific discovery and the way science is used in the world.
There are many different kinds of engineers.

One of the oldest branches of engineering is civil engineering.
Civil engineers design and supervise the construction of buildings, roads, transportation systems, bridges, airports, sewage systems, and much more.
Have you ever ridden a roller coaster? If so, you have experienced a design developed by civil engineers.

** Careers in Science 						      :drill:
Civil engineers begin by meeting with clients and contractors and visiting project sites.
They give presentations to local planning boards and communicate with other engineers on the project.
Civil engineers are responsible for the work done to build roads, buildings, or even airports.

Mechanical engineering is one of the broadest branches of engineering.
Mechanical engineers work in a wide range of areas.
If you have ever ridden in a car or been in a house with air conditioning, you have experienced the work of mechanical engineers.

** Careers in Science 						      :drill:
Some mechanical engineers work in the automotive industry designing engines, gears, and other mechanical equipment.
Other mechanical engineers work for companies designing more efficient heating units, as well as air conditioning, refrigeration, and ventilation.

Mechanical engineers are responsible for things such as jet and rocket engines, piping systems, laser technology, and robots.
Mechanical engineers can work in production operations, maintenance, sales, or management.
Environmental engineers design equipment to clean and protect the environment.
They work to develop ways to remove pollutants from the air and water and clean chemicals from the soil.
They also educate companies in environmental law and help them to comply with those laws.

If you have a water filter on your kitchen faucet, you have enjoyed the benefits of the work of environmental engineers.
They are responsible for designing equipment that cleans water and makes it safe to drink.

** Careers in Science 						      :drill:
Do you recycle? Environmental engineers often work with cities to design and supervise their recycling programs.
They also prevent ground contamination by devising ways to properly dispose of solid wastes.

Do you have a cell phone? Do you watch television or listen to a CD player? You probably use many objects that have been designed by electrical engineers.
Electrical engineers design, develop, test, and supervise the manufacture of products that contain electronic systems.

** Careers in Science 						      :drill:
Can you think of items in an automobile that an electrical engineer may have designed? There are many! Some examples are airbags, security systems, automatic seat belts, radios, antilock brakes, power steering, GPS systems, transmissions, cruise control, and  ignitions.

Have you ever flown in an airplane? You have enjoyed benefits created by aerospace engineers.
Aerospace engineers design, develop, and test equipment associated with flight.

** Careers in Science 						      :drill:
Aerospace engineers develop aircraft such as single engine airplanes, helicopters, and commercial airliners.
They also work with the military to develop defense systems, missiles, and different types of military airplanes and helicopters.
Aerospace engineers design a variety of equipment for the space program too.
They are responsible for rockets, satellites, and spacecraft.
There are many more careers in engineering than the ones discussed in this lesson.
Engineering is a very broad field that satisfies a variety of interests.
If you enjoy problem solving and figuring out how things work, you may enjoy a career in engineering.


** Hazards 							      :drill:
This lesson is about natural hazards and the safety concerns that go along with them.
Some hazards are caused by people, and others occur naturally.
One hazard you will learn about is a social hazard called terrorism.

Everyone has heard about the terrorist attacks on September 11, 2001 (also known as 9/11).
What can people do to be prepared for attacks such as these? Everyone should be aware of the risks and have a plan.
It is always better to be prepared in any kind of hazard than  to be caught off guard.

** Hazards 							      :drill:

** Hazards 							      :drill:
A natural hazard is an event caused by nature that is not expected.
It is a threat to the lives and activities of people.
When a natural hazard causes major destruction of property or causes injury or death, it is called a natural disaster.

Each natural hazard has its own safety issues.
Hurricanes are natural hazards that affect people who live in coastal areas.
In the United States, more than half the people live within 50 miles of a coast.
Hurricanes can occur on the Atlantic or Gulf coasts.

** Hazards 							      :drill:
Hurricanes cause hazards such as strong winds, high waves, strong currents, and flooding.
They can also produce tornadoes, landslides, and coastal erosion.
They can be as large as 400 miles wide.

Hurricanes can sometimes affect the energy supply.
More than one fourth of our oil production comes from the Gulf of Mexico.
When a hurricane approaches, production must be discontinued until the danger has passed and needed repairs have been made.

** Hazards 							      :drill:
Hurricane season is from June to November.
The peak of the season is August and September.
The deadliest natural disaster in the United States was the hurricane of 1900 in Galveston, Texas.
It caused an estimated 8,000 deaths.

One of the safety concerns of a hurricane is the risk of food spoilage and water contamination.
People or animals should not drink tapwater after a hurricane until it has been determined to be safe.

** Hazards 							      :drill:
More deaths are caused by flooding rains brought by hurricanes than by the other hazards associated with them.
Flooding is a major problem after a hurricane.

Children must stay out of the floodwaters.
Even very shallow water can sweep a child off his or her feet.
People should never play around high water or storm drains.
A few inches of rain may be hiding an electrical power line.
A downed electric line in water could cause electrical shock.

** Hazards 							      :drill:
Do not wait until you are thirsty to get a drink.
When the body gets dehydrated, it may feel less thirsty.

It is also important to wear loose-fitting clothes and a hat so the body can sweat.
At the first signs of heat-related injury, people should get out of the sun and rest.

Signs of heat exhaustion are cool, clammy, pale skin, sweating, dry mouth, extreme fatigue, dizziness, vomiting, and muscle cramps.
Heat-related injuries can happen after a hurricane or any time the weather is hot and humid.
Heat-related injuries include heat fatigue, heat rash, fainting, heat cramps, heat exhaustion, and heat stroke.

The summer months across the United States can be extreme, and special caution needs to be taken in relation to these injuries.

To avoid a heat-related injury, drink plenty of fluids and stay away from drinks that have sugar and caffeine.

** Hazards 							      :drill:
If you experience any of these symptoms, you should get to a cooler place and rest.
You should also slowly rehydrate by drinking fluids.

To eliminate the risk of heat-related injuries, limit the amount of time you spend outside during the hottest part of the day.
Plan any outdoor activities for early or late in the day.
It is also important to wear sunscreen to protect your skin from the sun's harmful rays.

** Hazards 							      :drill:
Volcanoes are also natural hazards.
A volcano is a vent in the crust of the earth in which dangerous hot lava and gases spill out.
More than 50 volcanoes have erupted in the United States in the last 200 years.

The most active regions are in Alaska, Hawaii, California, Oregon, and Washington.
Volcanoes can cause a variety of safety concerns that can kill people and destroy property.
They can even affect people far away if their eruptions are strong.

** Hazards 							      :drill:
The ash in the clouds can cause serious hazards to jets.
About 80 jets in the last 15 years have flown into these clouds accidentally.
The ash can clog a plane's engine.
Several have almost crashed because of engine failure.
These eruption clouds can travel hundreds of miles, causing ash to fall over large areas.

** Hazards 							      :drill:
Volcanoes emit gases when they erupt.
Some common volcanic gases are hydrogen, carbon dioxide, and sulfur dioxide.
Sulfur dioxide can react with water drops in the air to create acid rain.
Acid rain can cause corrosion and harm plants.
When carbon dioxide from a volcano settles in low areas, it can be deadly to plants and animals.

** Hazards 							      :drill:
The lava flow from a volcano is extremely hot.
It can move very fast.
It can knock down and burn everything in its path.
This can cause destruction of forests, homes, and buildings.

People can prepare for a volcano eruption by knowing if they are at risk for volcanic danger.
One of the most important things you can do to prepare is to create a disaster plan with your family.
You should have a dust mask to wear to keep from breathing the ash.
Be prepared for mudslides, flash floods, falling ash, and acid rain from a volcano.
Follow the evacuation orders that are issued by authorities in the event of a volcano eruption.

** Hazards 							      :drill:
It is important to understand the safety issues that are associated with natural hazards.
Natural hazards are caused by either climatic forces or geological forces.
Some hazards are not caused by nature but by people.
Hazards that people cause are called non-natural hazards.
One example of a non-natural hazard is a rolling blackout.
Rolling blackouts occur when the power company turns off electricity to a selected area to save power.
A computer usually selects the area for the blackout to occur.
Usually the blackout will last for about an hour.
Then, the power will be turned back on, and another area will lose power.

** Hazards 							      :drill:
Blackouts usually occur during high-energy usage times, between 4:00 p.m.
and 7:00 p.m.
on weekdays.
These blackouts can affect the same area more than one time a day and can last longer than one hour.
Blackouts usually happen during hot summer months when people use more electricity to run their air conditioners.

Listen to the television or radio to find out if your area is going to have a rolling blackout.
You can also check your power company's website.
Power companies try to give people a warning when the power will be off in an area.
To stay safe during a blackout, use a flashlight for light, never candles.
Turn off any electrical equipment that may have been running before the outage.
To keep food fresh, do not open the refrigerator any more than necessary.
Leave one light on so you will know when the electricity comes back on.

** Hazards 							      :drill:
Some things can be done to prevent rolling blackouts.
If less energy is used, outages can be avoided.

Power companies recommend that you set your thermostat to 68 degrees or lower in the winter and 78 degrees or higher in the summer.
Turn off lights and computers when you are not using them and keep windows closed.

** Hazards 							      :drill:
Some hazards that are non-natural can be social or personal.
An example of this would be terrorism.
Terrorism is the use of force or violence against people or property to create fear and to get public attention for political causes.

Terrorists are criminals.
Terrorism can  include threats of violence, assassinations, kidnappings, hijackings, bomb scares, bombings, and the use of chemical and biological weapons.

** Hazards 							      :drill:
Parents and students need to know more about terrorism and how to prepare and protect themselves in case of attack.

Targets for terrorism may include government buildings, large airports, big cities, and national landmarks.
Terrorists could also target large public gatherings, food and water supplies, and electric plants.

** Hazards 							      :drill:
Being aware of your surroundings is important.
Notice the things around you.
If something does not seem quite right, tell an adult.

Know where the exits in a building are.
Do not accept packages from strangers.
If you are asked to evacuate a building, take it seriously, even if it is a drill.

** Hazards 							      :drill:
Every family needs to have a plan in the event of a disaster.
Discuss what you should do to prepare, such as making a family disaster kit.
Plan a place to meet away from your home in case of a fire (like a neighbor's house).
Know the number to call to check in if you become separated from your family.
If there is an explosion in a building, remain calm.
Leave the building as quickly as possible.
Do not stop to get anything (toys, pictures, or books) or to make a phone call.

Get under a table if things are falling and stay there until you are certain it is safe to leave.
Also, watch for weakened floors or stairs as you leave.
Remember to stay calm.

** Hazards 							      :drill:
After 9/11, the Homeland Security Advisory System was designed.
This system provides warning to the American public about the level of threat of a terrorist attack.
There are five colored levels.
The greater the risk is of an attack, the higher the threat level.

The nation's Attorney General and the Secretary of Homeland Security decide on what the level of threat is.
It is constantly being reviewed and changed when needed.

** Hazards 							      :drill:
In this lesson, you learned about a variety of different hazards.
Unexpected hazards or natural disasters can occur without warning at any time.
It is important to be prepared and know what to do when you are faced with a hazardous situation.


** Atoms 							      :drill:
Do you have any silver jewelry? If you do, you have probably noticed it is shiny in appearance and reflects light well.
Have you ever wondered what gives silver those particular properties? It is its silver atoms.

Silver is what is known as an element.
This means silver is made up entirely of only silver atoms.

Silver is only one element found on the earth.
There are many more elements.
Some are man-made, but most occur naturally.
This lesson will give you much more information about the makeup of atoms and elements.

** Atoms 							      :drill:

** Atoms 							      :drill:
Historians believe Democritus, a Greek teacher who lived about 2,000 years ago, was the first person to study matter.
Democritus guessed there were tiny particles in matter, and he named them atoms.
He thought atoms were solid particles that could not be broken apart.

In the early 1800s, John Dalton said each kind of matter was made up of different kinds of solid atoms.

Today, scientists know an atom is the smallest whole unit of any type of matter.
An atom is made of protons, neutrons, and electrons.
It has a nucleus that contains protons and neutrons surrounded by electrons.

** Atoms 							      :drill:
Protons are particles in an atom with a positive electric charge, neutrons are particles in an atom with a neutral charge, and electrons are particles in an atom with a negative electric charge.
The electron and the proton have charges equal in size but opposite in charge.
The protons and neutrons form the nucleus, a large, dense region at the center of the atom.

The proton, neutron, and electron can be further broken down into subatomic particles called leptons and quarks.
A lepton is a basic subatomic building block of an atom.
An electron is a lepton.

Quarks are the building blocks of an atom's nucleus.

Scientists believe there are at least six different kinds of quarks.
They were given strange names: up, down, strange, charm, top, and bottom.
Neutrons and protons are made of different combinations of at least two quarks.

** Atoms 							      :drill:
A stable atom contains an equal number of electrons and protons.
The positive charges of the protons are canceled out by the negative charges of the electrons, making the atom electrically neutral.

Almost all the mass of an atom (the amount of matter in an object) comes from its protons and neutrons contained in the nucleus.
Protons and neutrons are about equal in mass, but electrons have a much smaller mass.
An electron's mass is about 1,800 times smaller than a proton or neutron.

** Atoms 							      :drill:
A mental model might help you compare the sizes of these parts of an atom.

Picture an atom the size of a large football stadium.
Its nucleus would have the volume of a small marble in the center of the field.
The electrons would be like the tiny insects buzzing around high above the stadium.

The size of an entire atom is actually 100 billion times smaller than the period at the end of this sentence.

** Atoms 							      :drill:
Atoms are so tiny that scientists have had difficulty studying them.
Atoms are too small to be seen by the human eye, so scientists use a scientific model to explain them.

Models are typically used to represent objects.
Physical models are used to investigate facts of nature on any scale, whether they are very small like an atom or very large like the solar system.

A scientific model is a means by which scientists try to visually explain something they cannot easily see or observe directly.

** Atoms 							      :drill:
Since Democritus's model of the atom, other scientific models for the atom have been presented.

In 1913, Niels Bohr, a Danish physicist, suggested a new model for the atom.
His theory stated that an atom's electrons move in paths around the nucleus.
Each path was a specified distance from the nucleus.
Bohr called these paths energy levels.

Electrons were thought to be found only on these energy levels and not between them.

** Atoms 							      :drill:
In 1926, Erwin Schrdinger proposed the new electron cloud model.
This model suggested an atom consists of a tiny core with a cloud around it.

The electron cloud is not an actual cloud, but merely the space around the nucleus where electrons are likely to be found.

The electrons orbit very quickly, but they do not travel in circular orbits.

** Atoms 							      :drill:
Today, scientists believe every atom has several possible energy levels within its electron cloud.
The electrons are arranged in pairs at each level, and each level can hold a different number of electrons before it is filled.

The electrons have different amounts of energy within the atom and will fill the levels closest to the nucleus first.
The first energy level nearest the nucleus is filled when it contains 2 electrons.
The second energy level can have up to 8 electrons, or 4 pairs.
The third energy level holds up to 18 electrons, 9 pairs.

** Atoms 							      :drill:
The fourth energy level can have up to 32 electrons, or 16 pairs.
Electrons in the higher energy levels will be farther from the nucleus and have more energy than those in the lower energy levels.

Let's look at how the electrons of the hydrogen and lithium atoms fill their energy levels.
The hydrogen atom has only 1 electron, so it circles the nucleus on the first energy level.
A lithium atom has 3 electrons, so 2 electrons (one pair) fill the first energy level, and the third electron will move to the second energy level.

Most atoms have enough electrons to use more than three energy levels.
Uranium, a large atom, has 92 electrons and uses seven energy levels.

** Atoms 							      :drill:
Let us review for a moment.

Atoms are the smallest unit of matter.
Atoms are made of protons (positively charged particles), neutrons (particles with zero charge), and electrons (negatively charged particles).
The protons and neutrons are made of different combinations of quarks.

Protons and neutrons are found in the nucleus and give the atom most of its mass.
The electrons are leptons that orbit the nucleus, forming a region similar to a cloud.
The electrons fill different energy levels within the cloud.

** Atoms 							      :drill:
An element is made up of only one kind of atom.
Each different atom is a specific element.
Each element is made up of only that specific atom.

Elements on earth are found in four states: solid, liquid, gas, and plasma.

Now that you understand the makeup of an atom, let us think about why this is so important.

** Atoms 							      :drill:
All matter in the universe is made of atoms.
The number of protons in an atom determines what type of atom it is.
Each different type of atom is called an element; therefore, the identity of an element is determined by the number of protons in its atom.

Because an element is made of only one type of atom, it cannot be broken down or changed in any way.
No physical or chemical process can change the number of protons in the nucleus and make the atoms of an element become different types of atoms.

** Atoms 							      :drill:
Iron is an element.
The iron atom has 26 protons.
Any atom with 26 protons will be an iron atom and will have all the properties of iron.

Iron could be hammered, heated, cooled, electrified, or combined with another chemical mixture, but it will not affect the number of protons in the iron atoms.
The atoms will remain unchanged, so a pound of iron could be split down to the atomic level and it would still be iron and retain all the properties of iron.

** Atoms 							      :drill:
Scientists have now identified 118 different elements.
This means they have identified 118 different types of atoms.

The names of the elements have different origins.
Several are named after scientists.
Einsteinium is named for Albert Einstein.
Curium is named for Marie Curie.
Some elements are named after places.
For example, Polonium was named after the country of Poland.

** Atoms 							      :drill:
Some of the names given to elements came from mythology.

Students of Greek mythology believe that Prometheus took the fire from heaven and gave it to humans.
The element promethium was found in the wastes of a nuclear reactor.
Because it was from a nuclear "fire," it was named after Prometheus.

Most elements occur naturally in the atmosphere or earth's crust.
Some elements are common and easy to find, while others are not.

** Atoms 							      :drill:
Most elements like gold, silver, calcium, and carbon are solids at room temperature.

Two elements, mercury and bromine, occur in nature, but they are liquids at room temperature.

Hydrogen, helium, and nine other elements occur in nature as gases.

Twenty-three elements are synthetic, meaning scientists in a laboratory have produced them.
The elements or combinations of the elements form all the known matter in the universe.

** Atoms 							      :drill:
All matter in the universe is made up of atoms.
An atom consists of a nucleus that contains protons and neutrons surrounded by electrons.

Atoms have no electrical charge because the positive charges of the protons are balanced out by the negative charges of the electrons.
Neutrons do not have a charge, so the atom remains neutral.
Electrons orbit around the nucleus at different energy levels.
Electrons fill the levels closest to the nucleus first, then move to outer levels.
The farther out an electron is from the nucleus, the more energy it has.
Atoms with a full outside energy level are the most stable.

Elements are comprised of only one type of atom and cannot be changed into anything else by any physical or chemical processes.
You should now have a good understanding about the characteristics of atoms and elements.


** Matter 							      :drill:
What is a mixture? What is a compound? How are they formed?

Scientists use mixtures and compounds in their laboratories for all types of experiments.
Most of the medicines people take are mixtures formed from compounds.

However, mixtures are also things we see and use every day, such as the things we eat and drink or the soil in the yard.
Mixtures can come from all combinations of matter in its different states: solids, liquids, gases, and plasma.
The state in which matter appears can also change, usually depending on its temperature.

This lesson will discuss the categories and types of mixtures that exist and how the states of matter can change.

** Matter 							      :drill:

** Matter 							      :drill:
Chemistry is the study of matter.
Nearly everything you see around you is matter.
Anything that takes up space and has mass is matter.

There are four states of matter: solid, liquid, gas, and plasma.
The most familiar states are solids, liquids, and gases.
You may know less about plasma, but it is the most abundant form of matter in the universe.

** Matter 							      :drill:
The state of matter depends upon its temperature.
When it is cold enough, most matter changes to the solid state.

As matter warms, almost all matter changes to the liquid state.
When the temperature becomes high enough, nearly all matter becomes a gas.
Matter at its highest temperature becomes plasma.
Plasma consists of high energy, electrically charged particles.

The atoms have so much energy that the electrons are stripped, and they become a highly electrified collection of nuclei and free electrons.
Nuclei means more than one nucleus.
When you turn on a fluorescent lamp, plasma is created inside the bulb.

** Matter 							      :drill:
All matter has a melting point, a freezing point, and a boiling point.
These points are different for different types of matter.

A melting point is the temperature at which a solid becomes a liquid.
A freezing point is the temperature at which matter changes from liquid to solid.
A boiling point is the temperature at which matter changes from liquid to gas.

** Matter 							      :drill:
A gas becomes a liquid by the process of condensation.
As a gas cools, its molecules condense and become a liquid.

An example of condensation occurs with warmer, moist air around a very cold glass of water.
The warmer air next to the glass contains water vapor (gas).
As the air cools, the water vapor condenses to form water droplets on the side of the glass.

The water molecules in the cooling air condense, changing from a gaseous state to a liquid state.

** Matter 							      :drill:
Condensation also occurs in the atmosphere to form clouds.
As the air cools in the upper atmosphere, the water vapor in the air condenses to form water droplets around tiny particles of dust, making a cloud.

A liquid becomes a gas by the process of evaporation.
As a liquid heats up, its molecules begin moving faster and faster until they break free of the liquid and become a gas.

** Matter 							      :drill:
Have you ever seen dry ice change into smoke? This is sublimation.
Sublimation occurs when a solid turns directly into a gas, or a gas turns directly into a solid without first becoming a liquid.
Dry ice is the solid form of carbon dioxide.
At room temperature, carbon dioxide turns directly into a gas.

If the water vapor in the atmosphere experiences sublimation, snowflakes are formed.

** Matter 							      :drill:
Any change in matter is a physical change.
When a physical change happens to a substance, it is still the same substance.
Water is water whether it is in solid, gas, or liquid form.

A chemical change occurs when a substance is no longer the same substance.
A piece of paper that is burned produces ash, carbon dioxide, and water vapor.
It is no longer paper.

** Matter 							      :drill:
The kinetic theory says that all matter is made of tiny particles in constant motion.
The higher the temperature, the faster the motion.
The motion and spacing of the particles determine the state of matter.

Particles in a solid are packed closely together and are held in fixed positions by forces between the particles.
Particles move back and forth but do not change positions.

** Matter 							      :drill:
Liquids have almost the same volume as solids, because the particles are very close to one another.
In liquids, the forces cannot hold the particles in a fixed position, and they slide past each other.

Viscosity is a property of a liquid that describes how it pours.
Motor oil has a higher viscosity than water.
The higher the viscosity, the slower the liquid pours.

** Matter 							      :drill:
Gas particles are not restrained by any force.
They have so much energy that they move in straight lines.
They change directions only when they strike a wall, container, or other particles.

Gas is mostly empty space.
The smell of bread baking fills a room.
The aroma moves easily in the empty space of the room.

** Matter 							      :drill:
All matter is made of tiny particles called atoms.
An atom is the smallest part of an element.
When two or more atoms bond covalently, they form a neutral particle called a molecule.

An element is a substance that cannot be broken down into anything else.
There are 118 elements.
Ninety-four of these elements have been identified in nature by scientists.
Another 23 synthetic elements are man-made and have been produced in the laboratory.
One element, Ununseptium, has been named but has not yet been created or discovered.

** Matter 							      :drill:
Every substance on earth is made of one or more elements.
Elements can be liquids, gases, or solids.
Here are some examples of elements in each form:

Liquid elements: mercury, bromine

Gaseous elements: hydrogen, oxygen, nitrogen, helium

Solid elements: gold, silver, iron, carbon, sulfur, copper, magnesium

** Matter 							      :drill:
Some substances are composed of only one element.
The lead in your pencil is composed of one element--graphite (carbon).

An iron bar is composed of only iron.
Mercury is a silver-colored liquid element.
Oxygen, an invisible gas, is an element.
Aluminum is an element.

An element is made of only one kind of atom.

** Matter 							      :drill:
A compound is composed of two or more different elements in a definite ratio.
Pure water is composed of two hydrogen atoms for every one atom of oxygen.
There is a constant 2:1 ratio of hydrogen to oxygen in all pure water.

Table salt is a compound of sodium and chlorine.
Ammonia is also a compound.
A compound cannot be broken down into smaller parts by a physical change.
A substance is the classification of elements and compounds.
Every substance always has a definite composition.

To review: An element is made of only one kind of atom.
A compound is a substance made of two or more different kinds of elements joined together, always in the same ratio.

** Matter 							      :drill:
Most common matter is a mixture of substances.
A mixture is two or more substances put together that can be separated by physical means.
The substances keep their own properties.
There is no definite chemical composition.
There is no chemical formula for a mixture.

Mixtures can be made with solids, liquids, gases, or a combination.
There are two categories of mixtures: heterogeneous and homogeneous.

** Matter 							      :drill:
In a heterogeneous mixture, the substances are not spread out evenly.
A bottle of oil and vinegar salad dressing is one example.
The liquids separate in the salad dressing, and the solid spices settle to the bottom of the bottle.

Trail mix is a heterogeneous mixture of solids.
The parts of trail mix can be easily separated.

** Matter 							      :drill:
In a homogeneous mixture, the substances are evenly spread throughout.

Vinegar is an example of a homogeneous mixture.
It is made of a ratio of water and acetic acid.
The ratio of acetic acid and water can vary, but the solution does not separate over time.

Other examples of homogeneous mixtures are soft drinks, seawater, air, steel, and brass.

** Matter 							      :drill:
There are three types of mixtures: solutions, colloids, and suspensions.
The type of mixture is dependent on the size of the particles in the mixture and how the particles are distributed throughout the mixture.

A solution is a homogeneous mixture.
A solution is formed when one kind of molecule fills the spaces between another kind of molecule.
Particles of a solution are very small and never separate.
Solutions can be passed through ordinary filter paper and remain unchanged.

** Matter 							      :drill:
A colloid is a mixture formed when small particles are suspended in a liquid or a gas.
The particles in a colloid are larger than those of a solution but are usually spread evenly.
Thus, most colloids are homogeneous.

Some examples of colloids are foam, aerosol, and fog.
The particles neither dissolve nor sink.
Blood and gelatin are also examples of colloids.
If a colloid were filtered, the mixture would not separate.

** Matter 							      :drill:
Looking through a microscope at a colloid, you would see the colloidal particles moving in a constant, zigzag motion.

The particles are constantly hit by smaller, invisible molecules in the mixture.
This random motion of particles in a colloid is called Brownian motion.

** Matter 							      :drill:
A suspension is a heterogeneous mixture.
The particles are large enough to be seen either by the eye or by a microscope.
The particles are affected by gravity.
In time, they will settle out of the mixture.
When the mixture is shaken, the particles suspend again.

When the water in a pond or river is stirred, the sediment, rocks, and sand in it become suspended.
In time, when the water calms, the suspended particles settle back to the bottom.
The particles are larger than those in a solution.
If the suspension were filtered through ordinary filter paper, the particles would separate.

** Matter 							      :drill:
Colloids and suspensions have a property that solutions do not have.
Colloids and suspensions may scatter light.

If a light beam is passed through a colloid or suspension, the beam becomes visible.
A search light at night is an example of light scattered by a suspension.
As light is passed through the suspension, air and the particles in the air (like dust, smoke, and water droplets) scatter the light.

** Matter 							      :drill:
To summarize, mixtures can be separated into two categories and three types.

Heterogeneous mixtures have substances which are not spread evenly.
Suspensions are heterogeneous mixtures.

Homogeneous mixtures have substances that are spread evenly throughout.
Homogeneous mixtures include solutions and colloids.

** Matter 							      :drill:
Matter is made up of atoms formed into molecules and compounds.
Molecules and compounds can be combined to form mixtures.

All of these are the building blocks which make up the matter that surrounds you every day.
Matter can be found in four different states: solid, liquid, gas, and plasma.

While solids, liquids, and gases are the most common forms of matter on earth, plasma is the most common form in the universe.
Stars, the most common source of matter, are made of plasma.

Matter will change from one state to another depending on its temperature.
Matter in its coldest state is typically a solid.
As matter heats, it usually becomes a liquid, then a gas, then plasma.


** Chemical Reactions 						      :drill:
Everything, whether alive, dead, or nonliving, is made up of atoms.
The whole universe is a collection of atoms and the space between them.

The atoms present today are the same atoms that have been present since time began.
When anything new appears in the world, it is really the same old atoms that were here all along.
The atoms are arranged in a new way.
Matter cannot be created.
It also cannot be destroyed.
Matter can only be changed into another form.
The properties of matter can change when an atom chemically bonds with other atoms to create molecules and compounds, creating entirely new substances.

Why do atoms bond? Do all atoms bond in the same way? This lesson will answer those questions and explain how matter changes from single elements to the objects you see around you every day.

** Chemical Reactions 						      :drill:

** Chemical Reactions 						      :drill:
An atom is the smallest whole unit of any kind of matter.
An atom's electrons orbit the nucleus in different energy levels.
A molecule is formed when two or more atoms of any kind are chemically joined.

An element is made up of atoms of one kind.
A compound is formed when two or more different elements are chemically joined.
When a compound is formed, the properties of the elements are different than the properties of the compound.

** Chemical Reactions 						      :drill:
Almost everything on earth is made of compounds.
Compounds can be made in millions of ways.
Once a compound is formed, it stays in that form unless a chemical change occurs, breaking apart the atoms or combining them with other atoms.

An example is water.
Water is made of two atoms of hydrogen and one atom of oxygen.
Water will remain water unless more chemicals are added to it, which could change its makeup to another substance entirely.

** Chemical Reactions 						      :drill:
A physical change is a change in the size, shape, or state of matter.

For example, as a baby grows to be an adult, it changes in size, shape, and weight.

Water changing from liquid to water vapor when it is boiled is a physical change because the molecules of water are not changed in any way.
They still consist of one oxygen atom bonded to two hydrogen atoms.

** Chemical Reactions 						      :drill:
Here is another example.

You have a board that is 12 feet long.
If you saw the board into two pieces, it has gone through a physical change.

The compound that makes up the board has not changed.
No chemical change has occurred.

** Chemical Reactions 						      :drill:
A chemical change occurs when elements join together to make compounds or when compounds join together to make new compounds.

A chemical change has also occurred if a compound or molecule is broken down to its original atoms.

A chemical change can be called a chemical reaction.
Matter and energy cannot be destroyed or created in a chemical reaction.

** Chemical Reactions 						      :drill:
When compounds are formed, the atoms in them are held together by chemical bonds.
They combine in a particular pattern.
Scientists explain this theory by drawing these patterns.

This graphic is an example of an electron dot diagram.
The dots represent the electrons in an atom's outer shell, or energy level.
It is the electrons in the outer level that determine how an atom will bond to other atoms in a chemical reaction.

** Chemical Reactions 						      :drill:
It is the nature of atoms to be stable.
When you lose your balance, you try to stabilize yourself, so you will not fall.
Atoms do the same thing.

When an atom's electrons fill its outer energy level, the atom is stable.
The fuller the outer level, the more stable the atom.

An atom that needs several electrons to fill its outer level is unbalanced, or unstable.
It will try to stabilize itself by forming molecules and compounds to fill its outer shell.

** Chemical Reactions 						      :drill:
Heat can break down the chemical bonds of molecules.
Caramelization is an example of heat breaking down a chemical bond.
Caramelization occurs when sugar is heated.
The heat adds energy to the atoms, giving them enough energy to break the bonds that hold the molecules together.

When the chemical bonds are broken, the substance is no longer sugar and does not keep the properties of sugar.

** Chemical Reactions 						      :drill:
There are two kinds of chemical bonds: covalent bonds and ionic bonds.

A covalent (ko-VAY-lent) compound is composed of atoms that are chemically bonded because the atoms share electrons.

Water is a covalent compound.
The hydrogen and oxygen share the electrons in their outer levels when they form chemical bonds.

** Chemical Reactions 						      :drill:
An ionic (eye-ON-ik) compound is composed of negatively and positively charged atoms.
The positive and negative atoms are attracted to each other and create a chemical bond.

When the elements of a metal and a nonmetal are combined, they form an ionic compound.
Ionic compounds are similar to magnets.
There are positive and negative attractions.

It is the same with atoms and chemicals.
An atom that has a positive or a negative charge is called an ion.
Positive and negative ions attract each other.

** Chemical Reactions 						      :drill:
Salt is an example of an ionic compound created from the elements sodium and chlorine.
The chlorine atom needs one electron to fill its outer shell, and sodium only has one electron in its outer shell.

Chlorine will take the one electron in sodium's outer shell.
Losing the negatively charged electron gives sodium a positive charge, making it a positive ion.

** Chemical Reactions 						      :drill:
Chlorine gains a negatively charged electron, giving it a negative charge and making it a negative ion.
The positive and negative ions are now chemically attracted to one another and form a chemical bond that creates a molecule of salt.

All molecules and compounds are formed through chemical bonds.
Chemical bonds occur when one atom is attracted to another because it can fill the outer level of the atom with electrons.
Atoms strive to fill their outer shells with electrons because this stabilizes the atom.

** Chemical Reactions 						      :drill:
Two types of chemical bonds are ionic and covalent.
In ionic bonds, electrons are transferred from one atom to another, changing the charge of the atoms and making them positive or negative ions.
The positive and negative ions are attracted to each other and form a chemical bond.
In covalent bonds, the atoms equally share electrons.
Therefore, the atom's charge is not changed and remains neutral.
The shared electrons fill the shell of each atom, making the molecule or compound stable.

Atoms bond to become stable.
This process creates the building blocks of all material.


** Energy and Simple Machines 					      :drill:
Have you ever done a job for someone? Maybe you cleaned your room and someone said, "You put a lot of energy into your work."

What does that mean? It means you put a lot of effort into the work you did.

Work and energy in scientific terms refer to the motion of an object.
Energy is what gives something the ability to move.
There are many different forms of energy.
Work is motion that transfers energy.
A machine is anything that makes work or motion easier to accomplish.

This lesson will explain the different forms of energy and how machines allow less force to be used to accomplish work.

** Energy and Simple Machines 					      :drill:

** Energy and Simple Machines 					      :drill:
Energy is the ability to do work.
An object has energy if it is able to produce change in itself or its surroundings.

There are two major types of energy: kinetic energy and potential energy.

** Energy and Simple Machines 					      :drill:
Kinetic energy is the energy of motion.
The amount of kinetic energy an object has depends on its mass (the amount of matter contained in the object) and its velocity (the object's speed and direction).

A moving train has more kinetic energy than a car going the same velocity because its mass is greater.
If two objects have the same mass but one is moving faster, the one moving faster will have more kinetic energy.

** Energy and Simple Machines 					      :drill:
Potential energy is the energy stored in an object as a result of a change in its position or condition.

Think about a bowling ball.
It has potential energy when you lift it.
When you throw the ball, it gains kinetic energy because it is moving.
When the ball strikes the pins, it becomes mechanical energy because it moved objects.
The bowling ball's energy changed from one form to another.

** Energy and Simple Machines 					      :drill:
Many different forms of energy exist, but each form can be grouped into either potential or kinetic energy.

potential energy:
 potential mechanical
 nuclear
 chemical

kinetic energy:
 kinetic mechanical
 thermal
 radiant
 electrical

** Energy and Simple Machines 					      :drill:
Nuclear energy is the energy stored in the nucleus of an atom.
It is a highly concentrated form of energy because the bonds holding a nucleus together are incredibly strong.

A terrific amount of energy is released when the nuclear bond is altered.
When the nucleus splits or is fused with another nucleus, energy is released and changed to kinetic energy, which can be used to generate electricity.
Radiant energy is energy in the form of waves that can travel through empty space.

The energy we get from the sun is radiant energy.
Radio waves and x-rays are also forms of radiant energy.

** Energy and Simple Machines 					      :drill:
Chemical energy is energy released during a chemical reaction.
The way atoms are put together in some objects causes the objects to have chemical energy.

Gasoline has chemical energy which is released when it is burned, causing the compound to be broken apart.
Homes are heated by the chemical energy stored within coal or gas.

** Energy and Simple Machines 					      :drill:
Electrical energy is energy from moving electrons in a closed circuit.
We use electrical energy to heat and light our homes, listen to a radio, and watch television.

Electrical energy runs most of the appliances that make our lives easier and more enjoyable.

** Energy and Simple Machines 					      :drill:
Mechanical energy is energy in moving things.
Lifting an object higher adds to its potential mechanical energy.
Moving an object faster or with more force adds to its kinetic mechanical energy.

For instance, the more forcefully a hammer hits a nail, the farther the nail will go into a piece of wood.

Mechanical energy is found in working machines, in wind, in moving water, and in falling rock.

** Energy and Simple Machines 					      :drill:
Here is an example of how energy changes from one form to another.
Suppose a truck is parked on a hill with a 10-degree incline and the brakes fail.
The truck rolls 5 meters into a tree.
Think about the amount of damage done to the tree.

Now, suppose the same truck were parked on a hill with a 45-degree incline and the brakes fail.
The truck still rolls 5 meters and hits a tree.
How does this accident compare to the first one? Which truck would cause the most damage to the tree?

** Energy and Simple Machines 					      :drill:
Both parked trucks have potential mechanical energy.
The potential energy begins changing to kinetic energy when the trucks begin rolling.
If you said the truck on the 45-degree incline would cause more damage, you were right.

Let's look at why this is true.
The truck on the 45-degree incline will move faster than on the 10-degree incline.
The faster-moving truck would have more kinetic energy, meaning it can do more work.
In this case, more work means more damage to the tree.

** Energy and Simple Machines 					      :drill:
Thermal energy is usually thought of as heat.
It is energy transferred between different objects of different temperatures.
Think about an ice cube in a cup of water.
The ice cube absorbs heat energy from the drink, making the drink colder.
When the ice absorbs this heat energy, it warms and begins to melt.

Rub your hands together and notice they get warmer.
The kinetic energy of your hands in motion creates friction, which changes to thermal energy as heat.

** Energy and Simple Machines 					      :drill:
The law of conservation of energy says energy can change forms, but the total amount of energy does not change.

Radiant energy from the sun is changed into chemical energy in plants.
We eat the plants, and the chemical energy is changed into mechanical energy when we walk or move.
We then feel the thermal energy of our body heat.
Our thermal energy is radiated back out into the atmosphere.
The amount of energy used by the plant gets passed on to us, and nothing is lost or gained.

** Energy and Simple Machines 					      :drill:
Work is the transfer of energy as a result of motion.
Work is not done unless a force makes something move.

Work equals the amount of force exerted multiplied by the distance through which the force acts.
The amount of work can be calculated using the following formula:

work = force x distance moved

** Energy and Simple Machines 					      :drill:
Machines make work easier.
They can use a force to make an object easier to move.
Machines can make a force larger.
They can also make objects move farther.
A simple machine consists of one or two parts that change the direction or amount of force needed to do work.

Examples of simple machines include an inclined plane, wedge, lever, pulley, and a wheel and axle.

** Energy and Simple Machines 					      :drill:
An inclined plane is a flat surface that is tilted.
A ramp is an example of an inclined plane.
Inclined planes help make moving objects from one level to another easier.
An example would be moving an object off a truck down to the ground.

A screw is an inclined plane wrapped around a central bar to form a spiral.
The closer the threads, or ridges, the less effort is needed to make the machine work.
Screws can also be found on light bulbs and inside jar lids.

** Energy and Simple Machines 					      :drill:
A wedge is an inclined plane.
A wedge could be a piece of wood or metal that is thinner on one end.

A knife and an ax are two examples of wedges.
When an ax is moved through matter, like a tree, it creates a path or opening.

** Energy and Simple Machines 					      :drill:
Have you ever tried to open a can of paint using just your hands? It would be very difficult.
A screwdriver could be used to make the work easier by putting the force needed to open the can in just the right place.
A screwdriver is an example of a lever.

A lever is a simple machine with a fulcrum, an effort arm, and a resistance arm.
The fulcrum is the point where the lever is supported.
The effort arm is the side of the lever where the force is used.
The resistance, or load, is the object moved by the lever.
The resistance arm is the distance between the resistance and the fulcrum.

** Energy and Simple Machines 					      :drill:
 The effort arm is from the handle to the edge of the can.

 The load is the lid.

 The resistance arm is the distance from the fulcrum on the paint can rim to where it touches the lid.

When force is applied downward to the effort arm, its direction is changed at the fulcrum, and the resistance arm pushes up on the lid.
In the screwdriver example, the edge of the can where the screwdriver touches is the fulcrum.

** Energy and Simple Machines 					      :drill:
A lever gives you a mechanical advantage.
Mechanical advantage (MA) is the number of times a machine multiplies the effort that you use.
Mechanical advantage can be calculated using these formulas:
(length of effort arm) / (length of resistance arm) for an increase in force

or

(length of resistance arm) / (length of effort arm) for an increase in distance
In the first formula, the mechanical advantage can be increased by making the effort arm longer.
For example, the farther out you hold the screwdriver, the more force you apply to the lid.

** Energy and Simple Machines 					      :drill:
Let's calculate the mechanical advantage of a lever with an effort arm of 5 cm and a resistance arm of 2 cm.

(length of effort arm) / (length of resistance arm) = force
(5) / (2) = 2.5

The mechanical advantage is 2.5 times greater when using the lever.
It increases the force by 2.5 times.
Now let's calculate the mechanical advantage of the same lever when the effort arm is increased to 14 cm.

(length of effort arm) / (length of resistance arm) = force
(14) / (2) = 7

The mechanical advantage is 7 times greater when using this lever.
It increases the force by 7 times.

You can see how much more power is produced by increasing the effort arm on a lever.

** Energy and Simple Machines 					      :drill:
If you have ever raised or lowered a window shade, you have used another simple machine called a pulley.
A pulley is a rope, chain, or belt wrapped around a grooved wheel.
It can change the direction of a force or the amount of force.

If you needed to lift a very large rock, it would be much easier to thread a rope around a pulley and pull down on the rope.
The flag on a flagpole is raised and lowered with the use of a pulley.

** Energy and Simple Machines 					      :drill:
A wheel and axle is a simple machine made of two circular objects of different sizes.
The wheel is the larger object, and the axle is the smaller one.
The wheel turns around the axle.

Bicycles, Ferris wheels, gears, wrenches, doorknobs, and steering wheels are all examples of wheels and axles.

** Energy and Simple Machines 					      :drill:
Let's review.
When anything moves or changes position, work has been done.
A force of some kind is needed to make something move and do work.
The force requires energy.

There are two types of energy: stored (potential) energy and movement (kinetic energy).
All the different forms of energy, such as radiant, electrical, chemical, thermal, and nuclear can be classified as either potential or kinetic.
Energy is never created or destroyed.
It is in a continual cycle of change from one form to another.
Machines make work easier.
They allow us to multiply force or distance.
How much they increase force or distance determines their mechanical advantage.

The next time you move something, think about what form of energy you used and if you used a machine to help you accomplish the job.


** Electricity 							      :drill:
In 1752, Benjamin Franklin showed that lightning is electricity.
Perhaps you have seen pictures of Franklin standing in a rainstorm with his kite.

This was one of the first times the properties of electricity were observed and identified.
Franklin's observations led to the study and understanding of electrical properties.
This lesson will explain some of those properties.

** Electricity 							      :drill:

** Electricity 							      :drill:
Benjamin Franklin attached a stiff wire to the top of his kite.
He then tied a piece of silk thread near the free end of the kite string.

He tied a metal key to the thread.
Lightning struck the wire, and electricity traveled down the wet string to the key.
The electricity caused a spark to jump from the key to Franklin's hand, which was near the key.

** Electricity 							      :drill:
It is a cold, dry day, and a boy walks across a carpet, touches a doorknob, and feels a shock.
What has happened?

As he walked, his shoes rubbed electrons off the carpet.

As two objects are rubbed together, electrons move from one object to another.
The electrons collected on the boy's body stayed there and gave his body a negative charge.
Such a buildup of electrons on an object is called static electricity.
Static means not moving.
When the boy touched the doorknob, the electrons moved to the doorknob and gave him a charge.

** Electricity 							      :drill:
The movement of the extra electrons is called an electric discharge.
After the discharge, the boy becomes neutral again.

Lightning is another example of a discharge of static electricity.
Lightning is caused by a buildup of electrons in a cloud.
When the difference between the charge on the ground and the charge on the cloud is big enough, an electric discharge occurs.
This discharge is seen as lightning.

** Electricity 							      :drill:
Current electricity is the movement of electrons along a conductor.
A conductor is usually a metal wire that allows the electrons to move easily along a path.
This path is the circuit.
An electric circuit provides a complete, closed path for an electric current.

An electric circuit is made of a source of energy, the load (the resistance), wires, and a switch.
The source will be a battery, thermocouple, generator, or a power plant.

** Electricity 							      :drill:
The load is the device that uses the electricity.
This can be anything that runs on electricity.
It could be a light bulb, a television, a toaster oven, or a motor.

The load offers resistance.
The energy is changed into heat, light, or mechanical energy.

** Electricity 							      :drill:
There are two types of electric circuits.
The type depends on how the parts of the circuit are arranged.

If all the parts are connected one after another, the circuit is a series circuit.
In a series circuit, there is only one path for the electrons to follow.

** Electricity 							      :drill:
If there is a break in any part of a series circuit, the entire circuit is opened and no electric current can flow.

Sometimes Christmas lights work this way.
If one bulb goes out, the entire string goes out.
Series circuits are best for items such as flashlights or portable radios because they have only one load and one job to do.
One battery (source) allows a flashlight to illuminate.
Several batteries (source) allow one radio to play.
If the circuit breaks (dead battery), the job stops.
Remember, a series circuit has only one path for electricity to travel.
Electricity travels in a series.
If any part is broken, the entire path is broken.
This break could be a burned out bulb or even a broken wire.

** Electricity 							      :drill:
In parallel circuits, different parts of an electric circuit are on separate branches.
More than one path is available for the electrons to take.
If there is a break on one of the branches, the current continues to flow.
Parallel circuits are connected by more than one path, so electrons can continue to travel.

Our homes, schools, cars, and buildings are wired with parallel circuits.
In our homes, for example, there is only one source of electrical power.
This electrical source serves everything electrical that we use.

** Electricity 							      :drill:
In a home or building, we can use electricity to power many things at once without breaking the circuit.
We can plug something in and turn it on.
We can turn lights on and off when we choose.

Turning something off does not break the circuit.
We can use more than one electrical appliance at a time.

** Electricity 							      :drill:
We can use lights, a television, and a hair dryer at the same time.
Because our homes have parallel circuits, we do not have to use our appliances all at once or one at a time.

Can you imagine the inconvenience of a home that was wired with series circuits? If something as minor as the light bulb in the refrigerator burned out, there would be no electrical power! The rest of your appliances would not work.

** Electricity 							      :drill:
Our homes have a great deal of electricity passing through them at all times.
If too many appliances are operated at once or if the wires become old and frayed, heat can build up in the wiring.
A fire is a real danger if the wires in the walls get too hot.
There are two devices that serve to protect us from this danger.

A fuse box with fuses protects against too much current flowing at once.
 These fuses serve as emergency switches.

** Electricity 							      :drill:
Inside each fuse is a strip of metal.
If the current becomes too high, the strip of metal melts and breaks the flow of electricity.

Have you ever had part of your electricity in your home go out because you have "blown a fuse"? This is a safety feature of an electrical system.
Most times, one can go to the fuse box and replace the fuse because the current has been reduced.

** Electricity 							      :drill:
Fuses have a disadvantage.
Once they burn out, they must be replaced with new ones.
For this reason, circuit breakers are often used instead of fuses.

Just like fuses, circuit breakers protect a circuit from becoming too hot or overloaded.
Modern circuit breakers have a switch that can flip open when the current flow gets too high.
These circuit breakers can easily be reset and used again once the problem has been corrected.
Circuit breakers are easier to
use than fuses.

** Electricity 							      :drill:
Let's review.
Two types of electricity are static and current.
In static electricity, a build up of electrons occurs, and they have nowhere to go.

When a circuit is formed, the electrons move, often creating a spark.
Lightning is an example of static electricity.
In current electricity, the electrons move in a closed path called an electric circuit.

An electrical circuit consists of an energy source, the load, wires, and a switch.

** Electricity 							      :drill:
A series circuit is used for simple electronics, like a flashlight, because there is only one path for the electrons to follow.
Parallel circuits have many paths for the electrons to follow, allowing for several uses of electricity at the same time.
The fuse and the circuit breaker are devices used to stop the flow of electricity from becoming too great in a circuit.

Electricity is very useful when managed properly.
You should now have a better understanding of how electricity works.


** Motion 							      :drill:
What is motion?

You might think of motion simply as any kind of movement.
Scientists study many different aspects of motion.
They study how the earth moves around the sun, how ships move through water, and how electrons move around the nucleus of an atom.

This lesson will cover many different properties and concepts associated with motion and give you a better understanding of the scientific principles dealing with motion.

** Motion 							      :drill:

** Motion 							      :drill:
Motion is a change in the position of an object.

When you describe something that is moving, you are comparing it to something that is not moving.
The object which does not move is called the reference point.

Think about when you are in a moving car.
You are moving in reference to the houses, but you are not moving in reference to your seat in the car.

** Motion 							      :drill:
Three measurements are key to the study of motion: distance, speed, and time.

Distance is the length between two points or places.
Distance can be measured in units like feet, miles, meters, or kilometers.

Time is how long it takes an object to move from one place to another.
Time can be measured in units like minutes or hours.
Speed is the rate at which an object moves.
The faster the rate of motion, the faster the speed.
Speed is measured in units like miles per hour (mph), feet per second (f/s), or kilometers per hour (km/h).

Vehicles do not normally travel at a constant speed.
Their speed continually increases or decreases, so an average speed is often used.

** Motion 							      :drill:
Imagine that you and your family are planning a 300-mile trip.
You will travel at an average speed of 60 miles per hour (mph).
How long will it take you to get to your destination?

Scientists use math to solve problems like this.
When any two measurements of motion are known, you can find the other.
Scientists use three related equations to do this.

** Motion 							      :drill:
In the first problem, the distance (300 miles) and speed (60 mph) are known, so we can use equation #2 to find the time.

time = (distance)/(speed)
time = (300)/(60)
time = 5 hours

It will take 5 hours for your family to travel 300 miles.

** Motion 							      :drill:
Let's try another problem.
Your family is going on a 280-mile trip, and it will take 4 hours to arrive.
What is your average speed?

In this problem, we know distance (280 miles) and time (4 hours), so we can find the average speed.
Equation #3 is used.

speed = (distance)/(time)
speed = (280)/(4)
speed = 70 mph

Your family will drive at an average speed of 70 mph.

** Motion 							      :drill:
Here is one more example.
How far would a plane travel if it flies for 6.5 hours at an average speed of 325 miles per hour?

In this problem, we know the speed (325 mph) and the time (6.5 hours), so we need to use equation #1.

distance = (speed) x (time)
distance = (325) x (6.5)
distance = 2112.5 miles

The plane would travel a distance of 2112.5 miles.

** Motion 							      :drill:
Velocity and speed are closely related.
Velocity is the speed of an object moving in a specific direction.
Velocity always has two components, speed and direction.

If a ball is tossed up in the air at 25 miles per hour, the speed of the motion is 25 miles per hour, and the velocity of the motion is 25 miles per hour, upward.

** Motion 							      :drill:
If a car is traveling eastbound on a highway at 55 miles per hour, its speed is 55 miles per hour, and its velocity is 55 miles per hour, east.

If one student pedals his or her bike at 10 km/h east and another student pedals at 10 km/h west, they are traveling at the same speed but not the same velocity, because they are not moving in the same direction.

** Motion 							      :drill:
Velocity requires a change in position.
An object's motion must end in a different place than where it started.

If you run around a track at 7 mph and finish in the same place where you started, your speed would be 7 mph, but your velocity would be zero.

** Motion 							      :drill:
Mass has an effect on the motion of an object.
Mass is the amount of matter in an object.
A sponge has less mass than a book of the same size, because it is made up of less matter than the book.
The matter in a book is packed together tightly, so more matter can fit into the space, giving it greater mass.
The matter is packed together less tightly in a sponge, so it has less mass.

The amount of matter in an object never changes.
Its mass always remains the same.

** Motion 							      :drill:
The weight of an object is a measurement of how much gravity pulls on the matter in the object.

A sponge does not have much matter for gravity to pull on, so it does not weigh much.

A book has a lot of matter on which gravity can pull, so it is heavier than a sponge of the same size.

** Motion 							      :drill:
Gravity does not pull with the same strength everywhere in the universe.
Gravity on the moon is not as strong as it is on the earth.

Because the moon's gravity is not as strong, it would not pull as hard on the particles of matter, or mass, of an object.
This will cause a rock to weigh less on the moon than it does on the earth.

** Motion 							      :drill:
The mass of a rock on the moon would remain the same as it is on earth, because taking a rock to the moon would not change the amount of matter it contains.
The weight of an object depends on how hard gravity pulls on the particles in the object, while mass depends on how much matter is in the object.

Both the mass and the weight of an object affect the motion of the object.
Objects with more mass are typically more difficult to move.
The property of inertia shows why this is true.

** Motion 							      :drill:
Inertia is the tendency of an object to maintain its state of motion.
Inertia can be thought of as laziness.

An object tends to keep doing whatever it is doing.
If an object is at rest, it will stay at rest until a force makes it move.
If it is moving, it will continue moving until a force makes it stop.

** Motion 							      :drill:
Have you ever pulled a wagon with something heavy in it? It was probably difficult to get the wagon moving.
However, once you got the wagon moving, you could stop pulling it and the wagon would keep moving.
This is inertia.

You are not pulling the wagon anymore, but inertia keeps it moving in the same direction until friction or some other force causes it to stop.

** Motion 							      :drill:
Inertia is related to both the velocity and the mass of an object.
An object will have more inertia when it has more mass.

Think about a car and a train.
Both can have the same velocity, 25 mph north, but which one would take longer to come to a complete stop? The train would, because it has more mass, giving it more inertia and making it more difficult to stop.

** Motion 							      :drill:
Here's another example.
Which football player would you rather be tackled by:

 the center, who weighs 300 lbs.
running toward you at 5 mph

 or the kicker who weighs 175 lbs.
running toward you at 5 mph?

They both have the same velocity, but which one has less inertia? You would probably rather be tackled by the kicker, because he weighs less and therefore has less mass and less inertia.

** Motion 							      :drill:
Velocity works the same way.
Objects of equal mass will have more or less inertia depending on their velocity.

All baseballs have the same mass, but a baseball will have more inertia and will travel a farther distance the faster it is thrown.

Both mass and velocity affect the inertia of an object, thus affecting its motion.

** Motion 							      :drill:
In this lesson, you learned that the motion of an object is affected by many things.

An object's mass and velocity affect how well or easily the object moves or comes to a stop.
They affect an object's inertia.
Speed, distance, and time are measurements that are used in making calculations about an object's motion.

Scientists work with these concepts as they study the motion of objects.
This knowledge helps scientists develop objects that move better and more efficiently.


** Cells 							      :drill:
Have you ever wondered how scientists have learned so much about living things?

In this lesson, you will learn about the history behind the research scientists did to develop the microscope and the cell theory.

We will also discover the characteristics of cells and the differences between plant cells and animal cells.

** Cells 							      :drill:

** Cells 							      :drill:
A person must look through a good microscope to see a cell clearly.
What is a microscope? What is a cell?

These are things that have been learned about through much scientific research.

** Cells 							      :drill:
A Dutch lens maker, Zacharias Janssen, invented the first compound microscope in the late sixteenth century.

A microscope is an instrument that makes objects look larger through the use of a lens.

Janssen's compound microscope was a handheld microscope capable of magnifying objects up to ten times their actual size.

** Cells 							      :drill:
Anton van Leeuwenhoek (1632-1723) made a single-lens microscope many years later.
Although this microscope only had one lens, it was powerful enough to magnify objects up to three hundred times their actual size.

Other microscopes were later patterned from Leeuwenhoek's microscope.

** Cells 							      :drill:
Englishman Robert Hooke (1635-1703) placed a thin slice of cork under a microscope.
He found the cork was made up of tiny boxes.
He named these boxes cells because they looked like the tiny rooms called cells in which monks lived.

In 1675, Anton van Leeuwenhoek was the first person to observe living cells.
 He carefully documented what he saw through the microscope, but all of the facts about living cells were not yet known.

** Cells 							      :drill:
In the 1800s, Matthias Schleiden (1804-1881) used a microscope to study parts of many plants.
He found one characteristic that continued to be consistent with every plant.
All the plants were made up of cells.

Theodore Schwann (1810-1882), a German scientist, studied parts of different animals under the microscope and came to the same conclusion about these organisms.
All the animals were also made up of cells.

** Cells 							      :drill:
Another German scientist and physician, Rudolf Virchow (1821-1902), studied the work of many scientists, including Hooke, Schleiden, and Schwann.
He was trying to find out how disease affects living things.

By using their outcomes and his research, he was able to conclude that all living cells come from other living cells.
Cells are the smallest living unit that can carry out life processes.
This conclusion and the work of all of these men led to the development of one of the most important theories in history, the cell theory.

** Cells 							      :drill:
The cell theory is important because it shows that all living things share a common structure.

The cell theory has three basic components:

1) All organisms are made up of one or more cells.

2) All cells come from existing living cells.

3) The basic units of structure and function of all living things are cells.

** Cells 							      :drill:
Some living things, also known as organisms, are made of one cell.
These single-celled organisms are called unicellular because the prefix uni- means one.

Other organisms are made up of millions of cells.
Living things made up of many cells are called multicellular because the prefix multi- means many.

** Cells 							      :drill:
Cells must continue all the life processes regardless of whether the organism is made up of one cell or many cells.
All these processes are necessary for an organism to stay alive.

** Cells 							      :drill:
Growth is an increase in size.
Plants, animals, and even bacteria grow.
All living things also experience movement.
Even flowers move by opening and closing their petals.

All living things can make others just like themselves.
This is called reproduction.
Reproduction occurs when parents produce offspring, or babies.

** Cells 							      :drill:
The process of removing waste products from the body is known as excretion, or elimination.
All living things get rid of waste products such as sweat, tears, urine, and carbon dioxide.

Are you hungry? All living things must take in nutrients to survive.
Animals eat a variety of foods to get the proper nutrients they need.
Plants make their own food using sunlight in a process called photosynthesis.
All living things metabolize their food.
This means their bodies use the nutrients they take in.

** Cells 							      :drill:
All living things respond to the environment around them.
An animal may run away if it hears a loud noise.
A plant may lean toward a window to position itself in the sunlight.

Organisms obtain and release energy in a process called respiration.
Respiration is breathing.
People and animals breathe in oxygen and breathe out carbon dioxide.
Plants take in carbon dioxide and give off oxygen.

** Cells 							      :drill:
Every living organism is made up of cells.
Every cell has three main parts: the nucleus (NOO-clee-us), the cytoplasm (SY-toe-plaz-um), and the cell membrane.
Both plant and animal cells have these three parts.

** Cells 							      :drill:
The nucleus is the control center of the cell.
It directs all the activities of the cell.
The nucleus contains structures called chromosomes (KRO-muh-zomz).

Chromosomes are string-like structures that carry instructions for the cell's activities.
All the information cells need to survive, perform their functions, and reproduce is found here.
Chromosomes are made of deoxyribonucleic acid, also known as DNA.

The nucleus has a covering called a nuclear membrane.
This membrane protects the nucleus and controls the amount of materials coming in and out of the nucleus.

** Cells 							      :drill:
Every cell is held together and protected by a covering called a cell membrane.
Food, water, oxygen, waste, and other materials must pass through the cell membrane when entering or leaving the cell.
This process is called diffusion.

Bacteria and viruses can attack cells.
 When something attacks and destroys the cell membrane, the cell dies because the life processes cannot continue.
When too many cells die, the organism dies.

** Cells 							      :drill:
Cytoplasm (CY-toh-plas-um) is the material between the nucleus and the cell membrane.
The cytoplasm is a clear, jelly-like substance which surrounds the nucleus and is held together by the cell membrane.

Inside the cytoplasm are tiny structures called organelles (OR-guh-nelz).
There are several different kinds of organelles.
Each organelle has a specific job to do within a cell.

** Cells 							      :drill:
The endoplasmic reticulum (en-doh PLAZ-mihk rih-TIK-yuh-lum) and the golgi are organelles that work together as a packaging system.

They package molecules in fluid-filled pockets and either store them to use at another time or send them out of the cell.

** Cells 							      :drill:
Ribosomes (REI-buh-zomz) are the organelles that make proteins.
Proteins are made up of amino acids and are used for growth and repair.

Mitochondria (MIT-uh-KON-dree-uh) are organelles that produce energy.
They are known as the powerhouse of the cell.
Mitochondria make energy by breaking down food molecules, which causes energy to be released.

** Cells 							      :drill:
Vacuoles (VAC-you-olz) are the storage bubbles in the cell.
These small sacs in the cytoplasm of a cell contain liquid.
Some vacuoles store water, while others store food.
Some vacuoles help eliminate waste.
Others store waste until it can be removed.

Animal cells have several small vacuoles, while plant cells have one larger vacuole.
The plant vacuole is filled with water.
This makes the plant firm.
If the plant needs water, it becomes limp and looks wilted.

** Cells 							      :drill:
In addition to the difference in vacuoles, plant and animal cells have many more differences.

Both plant and animal cells have a cell membrane; however, plant cells have another protective covering called the cell wall.
The cell wall gives plant cells support, shape, and strength.

** Cells 							      :drill:
Plant cells also contain chlorophyll.
Chlorophyll is the chemical that makes some plants green.
The chlorophyll is contained in an organelle called the chloroplast, (CLOR-o-plast) which is the food producer of the plant cell.

Animal cells do not have cell walls or chloroplasts.

** Cells 							      :drill:
The discovery of the cell took many years of scientific research.
Throughout time, scientists have discovered a variety of cell characteristics.

Through careful investigation and the use of scientific instruments such as the microscope, scientists have identified the many parts of cells and the function of each.
In addition, they have recognized the differences between plant cells and animal cells.


** Cells: Mitosis 						      :drill:
Have you ever wondered how living things grow? Growth occurs when cells reproduce.
What is the process of cell reproduction? Do all cells reproduce in the same way?

This lesson will explain the process of cell division, which occurs in two steps: mitosis followed by cytokinesis.
You will also discover how genetic traits from DNA are passed down from a parent to a child.

** Cells: Mitosis 						      :drill:

** Cells: Mitosis 						      :drill:
All living things are made up of cells.
 A cell is the smallest part of living matter.

One of the most important functions of all living things is reproduction.
All living things reproduce.
This means they create a living copy of themselves.

** Cells: Mitosis 						      :drill:
You are made up of cells.
Each hour, thousands of your cells die and are replaced.

Did you know scientists say that two generations of your skin cells will reproduce, live, and die within 24 hours? That is a very fast rate of reproduction.
Not all cells reproduce at this rate.
Some cells reproduce much slower than two generations in 24 hours.

** Cells: Mitosis 						      :drill:
According to the cell theory, cells produce new cells.
Living things begin as one cell.
Cells divide to make new cells.

The parent cell produces two new, identical daughter cells.
Two cells develop into four cells, four cells develop into eight cells, eight cells develop into sixteen cells, and the pattern continues.

** Cells: Mitosis 						      :drill:

** Cells: Mitosis 						      :drill:
Single-celled organisms, such as  amoebas, split into two organisms in a process called fission.

The new organisms that are produced by fission are identical to each other and to the parent cell.

** Cells: Mitosis 						      :drill:
Sex cells reproduce in a process called meiosis.
Meiosis is different than mitosis.

Meiosis is a special cell division that reduces the number of chromosomes by one half.

** Cells: Mitosis 						      :drill:
Cells in multi-celled organisms reproduce by mitosis followed by cytokinesis.

Mitosis is one type of cell division that produces an exact replica of the cell.
Mitosis is a continuous process, meaning cells continue to reproduce.

** Cells: Mitosis 						      :drill:
Before a cell experiences mitosis, it goes through a period of growth called interphase.
The cell spends most of its life in interphase.
All life activities except for reproduction occur during this time.
Interphase is not one of the phases of mitosis.

During interphase, the DNA in the cells is duplicated.
The chromosomes also duplicate and join together at one point called the centromere.

** Cells: Mitosis 						      :drill:
DNA, deoxyribonucleic acid, is the chemical that makes up most of the chromosomes in a cell.

Chromosomes are string-like structures that carry instructions for the cell's activities.
All the information cells need to survive, perform their functions, and reproduce is found here.

** Cells: Mitosis 						      :drill:
A DNA code for one trait is called a gene.
There are hundreds of genes in one chromosome.

Genes carry the information that makes an organism what it is.
Genes determine physical traits.
A trait is a characteristic passed from a parent to its offspring.

** Cells: Mitosis 						      :drill:
For humans, some of these hereditary traits might be eye color, hair color, height, and many more physical characteristics.

All living organisms pass traits to their offspring through their genes.

** Cells: Mitosis 						      :drill:
Once a cell duplicates its chromosomes and DNA, it begins the process of dividing into two cells through mitosis.

There are four phases of mitosis:

 prophase
 metaphase
 anaphase
 telophase

** Cells: Mitosis 						      :drill:
Prophase (PRO-faze) is the first phase of mitosis.
The cell prepares to divide.

The chromosomes begin to twist and thicken.
The nucleus breaks apart, and the chromosomes begin to move toward the center of the cell.

** Cells: Mitosis 						      :drill:
Small organelles called centrioles are found in cells during mitosis.
Centrioles are there to help the cell divide.
They can only be seen during cell division.

Thin tubes called spindle fibers begin to form between the centrioles.
The centrioles move toward each end, or pole, of the cell.

** Cells: Mitosis 						      :drill:
The second phase of mitosis is metaphase (MET-uh-faze).
In this phase, everything must line up before the cell can begin to split apart.

During this phase, the spindle fibers move by pushing and pulling the chromosomes until they line up across the center of the cell.
The chromosomes are held in place, and the spindle fibers are attached to each pair.

** Cells: Mitosis 						      :drill:
Anaphase (A-na-faze) is the third phase of mitosis.
It is now time to divide.

During this phase, the spindle fibers shorten and pull the chromosomes apart at the centromere.
Half the chromosomes go to one side of the cell while the other half go to the other side.

** Cells: Mitosis 						      :drill:
Telophase (TELL-uh-faze) is the last phase of mitosis.

When the separated chromosomes reach the end of the cell, telophase begins.
The chromosomes untwist and become longer and thinner.
The nuclear membrane closes.

** Cells: Mitosis 						      :drill:
Cytokinesis (SY-toh-ki-NEE-sis) occurs at the end of telophase.
Cytokinesis is the splitting of the cytoplasm where it is divided evenly between both of the new daughter cells.
Cytokinesis occurs in both plant and animal cells.

The cell is now divided into two new cells.
Each new cell has half the original DNA.
The daughter cells are an exact and complete copy of the parent cell.

** Cells: Mitosis 						      :drill:
Cells spend the majority of their lives in interphase before reproducing.
Mitosis, along with cytokinesis, is one type of cell division that produces an exact replica of the cell.

The four stages of mitosis are prophase, metaphase, anaphase, and telophase.
Each phase contains specific processes.
Once mitosis is complete and the cytoplasm is split, two new cells are present.


** Classification of Organisms 					      :drill:
Have you ever noticed the way items in a grocery store are organized? Everything is grouped together according to what type of food it is.
All the milk is together in the milk case.
The bread is all together on the bread aisle.
The canned soups are all together on a shelf.
The soup cans are even organized by different flavors and brand names.

Organizing things according to a classification system makes finding things in that system much easier.
In this lesson, you will learn how all living things are classified into different groups so that scientists can identify and study them.

You will discover what characteristics are used to organize the classification categories of living things and learn about the five different kingdoms.

** Classification of Organisms 					      :drill:

** Classification of Organisms 					      :drill:
To classify is to group things according to a system.
What are some ways you classify things? You might classify items more often than you realize.
You may even classify things without thinking.

You may group objects of a certain color, the gender of friends, the value of coins in your pocket, or perhaps the number of sides a shape has.

** Classification of Organisms 					      :drill:
All living things are known as organisms.
Organisms are classified into groups by their similarities and differences.
Scientists have found and identified millions of organisms on the earth.

In the eighteenth century, new organisms were constantly being discovered and named.
There was not a specific system for classifying and organizing these new discoveries; therefore, there was much confusion among the scientific community.

** Classification of Organisms 					      :drill:
A scientist named Carl Linnaeus knew that plant names varied from language to language.
He thought it would be helpful to give all living things formal two-part names.
This process would be called binomial nomenclature.

In time, Carl Linnaeus's classification system was used for naming animals as well.
He is responsible for the naming process still used today.

** Classification of Organisms 					      :drill:
There are seven classification categories for living things:

kingdom
phylum
class
order
family
genus
species

Each category is more specific than the one before it.

** Classification of Organisms 					      :drill:
The scientific name includes the subgroups genus and species.
The genus is the first part of the scientific name and is more general, while the species is more specific and refers to one group of organisms.
The species (SPEE-seez) is the smallest subgroup of organisms that have the same traits.

An organism's scientific name is a two-part Latin name that identifies each organism.
Because scientists throughout the world had different names for the same organisms, a universal naming system was needed.
Latin was chosen for the scientific naming of organisms to eliminate confusion and allow communication among scientists all over the world.

Homo sapiens is Latin for the human species.
When someone from China, Mexico, or America says homo sapiens, he or she is using a scientific language that everyone can recognize.

** Classification of Organisms 					      :drill:
Scientists classify organisms into kingdoms by three criteria.

1) cell structure

2) method for obtaining and using nutrients

3) method of reproduction

First, scientists study the cell structure of an organism.
Organisms that have the same cell structure are classified into one kingdom.

** Classification of Organisms 					      :drill:
Second, the organism's method for acquiring and using nutrients and energy is classified.

A cat and a tree take in and use nutrients in different ways.
The tree receives energy from sunlight and nutrients from the earth.
The cat eats other organisms for energy and nutrients.

** Classification of Organisms 					      :drill:
A third criteria for classifying organisms is by their process of reproduction.

Oak trees produce acorns.
Dogs mate to create puppies.
Flowers reproduce through fertilization to make seeds.
 Unicellular organisms divide.

** Classification of Organisms 					      :drill:
Organisms are classified into five kingdoms.

** Classification of Organisms 					      :drill:
A moneran (ma-NIR-un) is a bacterium that has no membrane around its nucleus.
It takes in food from outside its body.
It reproduces by dividing.

Some kinds of monerans can turn milk into different kinds of cheeses.

** Classification of Organisms 					      :drill:
A protist (PRO-tist) can be a unicellular or a multicellular organism.
Unicellular organisms are single-celled organisms, while multicellular living things are made up of many cells.

Protists have a membrane around each nucleus.
They receive their energy from either sunlight or nutrients in food.
Protozoa are part of the protist kingdom.

** Classification of Organisms 					      :drill:
A fungus (FUNG-gus) is an organism that absorbs food from the host on which it lives.
Fungi can be unicellular or multicellular.

Bread mold is one kind of fungus.
 Mushrooms are another.
Yeast that is used to make bread is also a fungus.

** Classification of Organisms 					      :drill:
Plants can grow on soil, water, rocks, or other places.
Most reproduce from seeds.
Plants take in nutrients from the soil and energy from the sun.
Plants are made of many cells.

** Classification of Organisms 					      :drill:
The animal kingdom includes fish, spiders, bears, birds, snakes, frogs, people, and many more.

To stay alive, animals must eat other organisms, such as plants and other animals.
They reproduce by eggs that are formed either inside their bodies or outside their bodies.
All animals are multicellular organisms.

** Classification of Organisms 					      :drill:
Classifying things into groups makes it much easier to keep them organized.
You may organize your school or office supplies.
You may organize your clothing or the dishes in your kitchen.
When objects are classified, they are much easier to find and identify.

The same is true of the classification of organisms.
Using the seven categories of classification, as well as dividing living things into the five kingdoms, allows scientists around the world to maintain consistency when they are studying organisms.


** Simple Forms of Life 					      :drill:
Many different simple forms of life exist that are neither plants nor animals.
These include monerans, protozoa, algae, and fungi.
How are these organisms similar to each other? What makes them different from plants and animals?

In this lesson, you will learn about the differences between these simple organisms.
You will also learn how viruses are different from living cells.

** Simple Forms of Life 					      :drill:
Viruses are microscopic [organisms] that are [parasitic] within living things and cause [diseases] in humans.
Viruses are different from other living things.

Viruses can reproduce only within a living [cell].
A virus invades a living [cell] before it can continue to live.
The invaded organism is called a [host].

Once a virus enters a [host], it changes the instructions in the cell's [nucleus] so new viruses are produced.
Eventually, the host cell bursts and releases the viruses which then invade other cells.

** Simple Forms of Life 					      :drill:
A virus cannot grow or respond to outside [stimuli].
Viruses have [no] [control] over their movement outside a living cell.
They can spread in the wind and travel in a sneeze, water, food, blood, or other bodily fluids.
Viruses are everywhere.

There are many different types of viruses.
Viruses can cause diseases such as polio, warts, herpes, shingles, respiratory infections, flu, fever blisters, and common colds.

** Simple Forms of Life 					      :drill:
[Bacteria] are the most common types of living things.
[Bacteria] are examples of monerans, which are members of the Kingdom Monera.

** Simple Forms of Life 					      :drill:
Bacteria are [single]-[celled] [organisms] that have a cell wall, but not a nucleus.
They reproduce very quickly by splitting into two cells.

** Simple Forms of Life 					      :drill:
Bacteria are single-celled organisms that have a cell wall, but not a nucleus.
They reproduce very quickly by [splitting] into [two] cells.

** Simple Forms of Life 					      :drill:
Some bacteria are [helpful] to living organisms, while others are [harmful].

** Simple Forms of Life 					      :drill:
[Bacteria] in your stomach help you digest food.
[Bacteria] are also used to decompose, or break down, garbage and waste products.

** Simple Forms of Life 					      :drill:
Bacteria can cause many different types of diseases such as syphilis, tetanus, tuberculosis, whooping cough, and salmonella.
A chemical substance called an [antibiotic] is often used as medication to kill bacteria that is causing an illness.

** Simple Forms of Life 					      :drill:
One kind of bacteria is called cyanobacteria, or [blue]-[green] bacteria.
This type of bacteria is what you see as scum on the surface of ponds or other standing water.
This scum is really a large mass of bacteria which is colored [blue]-[green].

** Simple Forms of Life 					      :drill:
There are several different types of blue-green bacteria.
In spite of the name, some blue-green bacteria come in different colors such as red, violet, or yellow.
The matter in cells and tissues that gives color to bacteria is called [pigment].

** Simple Forms of Life 					      :drill:
[Protozoans] are members of the Kingdom Protista.
They are single-celled organisms that do not have cell walls.

** Simple Forms of Life 					      :drill:
Protozoans are members of the Kingdom Protista.
They are [single]-[celled] organisms that do not have cell walls.

Protozoans are usually found in [untreated] [water] where they get food and oxygen.

Most protozoans can move on their own toward food or better environmental conditions.
They are like animals in this way.

** Simple Forms of Life 					      :drill:
Protozoans are grouped by their methods of [movement] and the process by which they acquire [food].
Each group of protozoa is equipped with special structures for these purposes.

The four phylum groups of protozoans are:

 sarcodines
 ciliates
 flagellates
 sporozoans

** Simple Forms of Life 					      :drill:
The [amoeba] is a common sarcodine.
It has no specific shape because it is a small mass of cytoplasm surrounded by a membrane.
It moves by using pseudopods (also known as pseudopodia), or false feet.

Pseudopods move to surround food, trapping it and bringing it inside the [amoeba].
This forms a food vacuole to digest the food.

** Simple Forms of Life 					      :drill:
The amoeba is a common sarcodine.
It has no specific [shape] because it is a small mass of [cytoplasm] surrounded by a membrane.

However, amoebic [dysentery] is a severe diarrhea caused by an amoeba.
This illness can be found where there are poor sanitation facilities.

** Simple Forms of Life 					      :drill:
The ciliates phylum is more complex.
Their entire cell is covered with hundreds of short, [hair]-like structures called cilia.
The ciliate moves through the water by means of the cilia, using them like tiny [oars].

** Simple Forms of Life 					      :drill:
The [ciliates] phylum is more complex.
Their entire cell is covered with hundreds of short, hair-like structures called cilia.
The [ciliate] moves through the water by means of the cilia, using them like tiny oars.

A paramecium is a common [ciliate] found in most ponds.
These organisms feed on small protozoans and dead plants.

** Simple Forms of Life 					      :drill:
[Flagellates] move by a long whip-like structure called flagella.
[Flagellates] can live in water, in soil, and in some animals.
Some [flagellates] are parasites.
A parasite is an organism living in or on another organism for the purpose of obtaining food.

** Simple Forms of Life 					      :drill:
Flagellates move by a long [whip]-[like] structure called [flagella].
Flagellates can live in water, in soil, and in some animals.
Some flagellates are [parasites].
A [parasite] is an organism living in or on another organism for the purpose of obtaining food.

One kind of flagellate lives in termites.
Termites eat wood, and the flagellate digests the wood.
The flagellate and the termite could not live without each other.

** Simple Forms of Life 					      :drill:
The fourth phylum is [sporozoa].
All [sporozoans] are parasites that live in the blood or in the organs of animals.

Malaria is a disease caused by a [sporozoan].
It is carried from an infected person to a new host by a mosquito.

** Simple Forms of Life 					      :drill:
The name [algae] is often used to refer to plant-like protists that have cell walls, contain 
chlorophyll, and make their own food; but they do not qualify as members of the plant kingdom.

Protists are one-celled organisms, but some may form many-celled colonies.
These [algae] are classified in the Kingdom Protista.
The different types of [algae] are distinguished by color, method of food storage, and composition of cell walls.

** Simple Forms of Life 					      :drill:
The name algae is often used to refer to plant-like protists that have cell walls, contain 
[chlorophyll], and make their own [food]; but they do not qualify as members of the [plant] [kingdom].

Protists are one-celled organisms, but some may form many-celled colonies.
These algae are classified in the Kingdom [Protista].
The different types of algae are distinguished by color, method of food storage, and composition of cell walls.

Thousands of species of each type of algae exist.
They are found in oceans, soils, freshwater, ponds, and streams.

[Plankton] are found in both fresh and saltwater.
They float near the surface of the water and are made up of microscopic, plant-like and animal-like protists.
Plankton provide oxygen and food to other organisms living in the water.

** Simple Forms of Life 					      :drill:
One of the most common species of [algae] found in freshwater is the euglena.The euglena is pushed by a long [flagellum].
It has a red-orange eyespot used as a light [detector] to guide the euglena toward brightly-lit places.

Euglena are [plant]-[like] because they have chloroplasts and can make their own food.  (plant-like, animal-like)
They are [animal]-[like] because they can move from place to place on their own.  (plant-like, animal-like)

** Simple Forms of Life 					      :drill:
There are about 1,100 different species of [red] [algae] found in the oceans.
When [red] [algae] reproduce very rapidly, they produce a red tide of toxic wastes that kills fish.
Animals can become ill if they eat shellfish that have absorbed these toxins.

[Diatoms are golden brown algae and one of the most common of all the unicellular organisms in the ocean.
Like plankton, they are one of the most important food sources for ocean animals.

** Simple Forms of Life 					      :drill:
[Slime] [molds] can move like amoeba, and they can reproduce like fungi.
They live in damp soil or on rotting logs or leaves.

[Slime] [molds] are usually brightly colored.
[Slime] [molds] creep along the ground and engulf food particles.
When food is scarce, they become spore-forming bodies.
These spores grow into new amoeba-like organisms.

** Simple Forms of Life 					      :drill:
[Fungi] are members of the [Fungi] Kingdom and live as decomposers.
A decomposer is an organism that helps break down decaying plants and animals that have died.
Mold, yeast, mildew, plant rust, smut, and mushrooms are all [fungi].

[Fungi] cannot produce their own food.
They must absorb food through their cell walls.
Some [fungi] acquire food from other living organisms, some live on dead matter, and others capture prey for food.
[Fungi] reproduce by forming spores that can be blown over a wide area.
Each spore can grow into a new organism.

** Simple Forms of Life 					      :drill:
Fungi are members of the [Fungi] Kingdom and live as decomposers.
A decomposer is an organism that helps break down decaying [plants] and [animals] that have died.
Mold, yeast, mildew, plant rust, smut, and mushrooms are all fungi.

Fungi cannot produce their own food.  They must [absorb] food through their cell [walls].

** Simple Forms of Life 					      :drill:
Any fungus with a thread-like fuzzy appearance is called a [mold].
[Molds] grow in warm, moist, dark places.
They can also grow in cold temperatures.

[Mold] is sometimes seen growing on old bread or on spoiled food in the refrigerator.

** Simple Forms of Life 					      :drill:
Any fungus with a thread-like fuzzy appearance is called a mold.
Molds grow in [warm], [moist], [dark] places.
They can also grow in cold temperatures.

Mold is sometimes seen growing on old bread or on spoiled food in the refrigerator.

** Simple Forms of Life 					      :drill:
Rusts and smuts are other types of fungi.
They destroy [grains] meant to be sold to people for food.
This costs farmers thousands of dollars each year.

[Yeasts] are single-celled sac fungi sometimes used to break down carbohydrates.
This feature makes [yeast] important to the food industry.
[Yeasts] are also used to make bread rise.

Morels, truffles, and [mushrooms] are edible fungi.
Other fungi, such as ringworm and athlete's food, cause diseases in humans.

** Simple Forms of Life 					      :drill:
As you have learned, there are many different types of simple life forms.

These living things may be [microscopic] (hint: very small); however, they are very complex organisms.
They live in a variety of environments, move in many different ways, and serve different purposes.

** Simple Forms of Life

| Species / Common Name                       | Kingdom  | Phylum                                        | Single-Celled? | Cell Wall? | Nucleus? | Parasitic? | Reproduction                      | Movement                     | Note                                                                       |
|---------------------------------------------+----------+-----------------------------------------------+----------------+------------+----------+------------+-----------------------------------+------------------------------+----------------------------------------------------------------------------|
| Virus                                       |          |                                               |                |            |          | True       |                                   |                              |                                                                            |
| Bacteria                                    | Monera   |                                               | True           |            |          |            | By splitting                      |                              | cyanobacteria, or [blue]-[green] bacteria (on ponds)                       |
| Protozons (group - common protista)         | Protista | Sarcodines, Ciliates, Flagellates, Sporozoans | True           | False      |          |            |                                   | Yes                          | found in untreated water                                                   |
| Amoeba                                      | Protista | Sarcodines                                    |                |            |          |            |                                   | pseudopods, false feet       | small mass of cytoplasm                                                    |
| Paramecium (a common Ciliate)               | Protista | Ciliates                                      | True           |            |          |            |                                   | cilia (hair-like, tiny oars) | feeds on small protozoans and dead plants                                  |
|                                             | Protista | Flagellates                                   |                |            |          | True       |                                   | flagella                     |                                                                            |
| Sporozoa (common name)                      | Protista | Sporozoans                                    |                |            |          | True       |                                   |                              | causes malaria                                                             |
| algae (plant-like protists)                 | Protista |                                               | True           | True       |          |            |                                   |                              | contains chlorophyll;  makes own food;  not a plant;  plankton             |
| euglena (common species of algae)           |          |                                               |                |            |          |            |                                   | flagellum                    | red-orange light detector;  makes own food (chloroplasts)                  |
| red algae                                   |          |                                               |                |            |          |            |                                   |                              |                                                                            |
| diatoms (golden brown algae)                |          |                                               | True           |            |          |            |                                   |                              |                                                                            |
| plankton (made of protists)                 |          |                                               |                |            |          |            |                                   |                              |                                                                            |
| slime molds                                 |          |                                               |                |            |          |            | like fungi                        | like amoeba                  |                                                                            |
| Fungi                                       | Fungi    |                                               |                |            |          |            | form spores that are blown around |                              | cannot produce it's own food;  decomposer, absorbs food through cell walls |
| Mold (fungus w/ thread-like appearance)     |          |                                               |                |            |          |            |                                   |                              |                                                                            |
| rusts, smuts, yeast, mushrooms (also fungi) |          |                                               |                |            |          |            |                                   |                              |                                                                            |


** Ocean Life  :drill:
Water takes up the majority of our planet and is essential to all living things. This lesson will discuss the location of the oceans of the world and explain the composition of ocean water.

You will discover what types of organisms inhabit various depths of the ocean and learn how different sea creatures live together in their environment.

You will also learn about the water cycle and how it affects the earth.


** Ocean Life  :drill:



** Ocean Life  :drill:
All living things must have water to live; however, water is a substance that most people take for granted.

Freshwater is one of the earth's most important natural resources. More than 500 billion liters of water are used every day in the United States.



** Ocean Life  :drill:
Hydrologists are scientists who study water on land, in the air, and in oceans.

Water is a polar covalent bond because the electron is shared unevenly.

As a result, water is an excellent solvent. A solvent is a substance into which another substance can be dissolved.



** Ocean Life  :drill:
Ocean water covers about three quarters of the earth's surface and is a mixture of gases and solids dissolved in pure water.

Ocean water is about 96% pure water. The other 4% consists of dissolved minerals. The most common dissolved mineral found in ocean water is sodium chloride, also known as salt. This is why ocean water is salty.



** Ocean Life  :drill:
Even though 4% is a small percentage, ocean water is still too salty to be useful. It is too salty to drink or to use in a bath or shower. Ocean water cannot be used to water crops or in manufacturing.

Desalination is the process of removing salts and other minerals from seawater. This is an expensive process. If the cost could be lowered, desalination could become an important source of freshwater.



** Ocean Life  :drill:
There are five major oceans on earth. Can you name them?

The Pacific Ocean is located on the west coast of North America. The Atlantic Ocean is located on the east coast of North America. The Indian Ocean is found between Africa and Asia. The Arctic Ocean is north of North America. The Southern Ocean surrounds Antarctica.

These five oceans are connected to each other. Look at their locations on the map.



** Ocean Life  :drill:
Surrounded by ocean water are large continuous land masses called continents. The earth consists of seven continents: North America, South America, Europe, Asia, Africa, Australia, and Antarctica.

Some portions of the continents' edges are actually under water. These parts are called the continental shelf.



** Ocean Life  :drill:
A saltwater marsh is an ecosystem with very shallow saltwater. A saltwater marsh is located where rivers empty into oceans.

A coral reef is the underwater buildup of limestone skeletons from certain small animals called coral. These organisms do not live in waters colder than 18 degrees Celsius. Coral reefs are found only in the warmer waters of the Caribbean Sea and Pacific Ocean.



** Ocean Life  :drill:
The ocean is full of organisms that swim, drift, or crawl along the ocean floor. Organisms that drift with the ocean currents are called plankton.  Plankton are tiny floating forms of plants and animals. Some plankton are microscopic while others are much larger.

Algae, seaweed, and jellyfish are all types of plankton. Plankton is the main food for many organisms, including whales, the largest organisms on earth.



** Ocean Life  :drill:
Benthos are the sea creatures that live on the ocean floor. Some may also live on the shallow continental shelf.

Some examples of benthos are oysters, clams, and mussels. Many benthos are used as food by humans.



** Ocean Life  :drill:
Free swimmers are organisms that swim through a variety of depths in the ocean. Dolphins, whales, sea turtles, and fish are all free swimmers. They move through the ocean in search of food, shelter, and companionship.

Ocean organisms depend upon each other for their survival.



** Ocean Life  :drill:
The food chain in the sea is just as important as the food chain on land. A food chain shows the movement of energy (in the form of food) from one organism to another.

A food chain is made up of consumers and producers. A consumer is an organism that eats other organisms. A producer is an organism, usually a plant, which can produce its own food and provide food for other organisms.



** Ocean Life  :drill:
The ocean food chain begins with plankton. Phytoplankton, a very simple form of life, are eaten by zooplankton, small shrimp-like krill, and other animal plankton. Small fish feed on zooplankton and fish larvae.

The next level of the food chain is the pelagic fish. These are fish which travel in large groups and often migrate long distances. Some pelagic fish are herring, mackerel, and tuna.



** Ocean Life  :drill:
Marine mammals are at the top of the ocean food chain. Dolphins, seals, and whales are all marine mammals.

Also connected to the food chain are bottom dwellers and dead organisms. The remains of dead organisms on the ocean floor are called ooze.

The sea is a rich source of food and minerals.



** Ocean Life  :drill:
The sun is the heat source for ocean water. Ocean water is warmer at the surface than at the bottom because the sun's heat and light cannot reach deep ocean depths. Ocean waves and currents mix the warm and cold water.

The flow of water in a definite direction is called a current. There are ocean currents as well as currents in lakes, rivers, and streams.



** Ocean Life  :drill:
Sunlight penetrates the ocean to about 200 meters. The area above this depth is called the photic zone.

Sea animals that depend on sunlight, as well as green plants that undergo photosynthesis, must live within this zone.

Photosynthesis is the process by which green plants use sunlight to make food.



** Ocean Life  :drill:
Below the photic zone is the bathyal zone. It begins at the continental shelf and extends downward about 2,000 meters.

No sunlight reaches this zone. Squid, octopus, and a few large whales live here.



** Ocean Life  :drill:
Even deeper is the abyssal zone. This zone could extend another 4,000 meters. Little food is found here, so there are few living organisms.

The organisms that do live here are usually very small and very strange. Anglerfish and anoplogaster are two of the unique organisms found in the depths of the abyssal zone.



** Ocean Life  :drill:
About 3% of the earth's water is freshwater. Freshwater is found in ice or icecaps, moving water, and standing water.

Most of the usable freshwater is found in rivers, streams, springs, ponds, lakes, and wetlands. Most living things require freshwater to live.



** Ocean Life  :drill:
Freshwater is used over and over again. It moves in a continuous cycle known as the water cycle. There are three steps in the water cycle:

evaporation
condensation
precipitation



** Ocean Life  :drill:
During evaporation, the sun's heat energy causes the surface water on the earth to evaporate, or change from liquid into a gas. The gas form of water is called water vapor.

Water evaporates from freshwater, oceans, the soil, and plants.



** Ocean Life  :drill:
During condensation, water vapor changes back to a liquid. The warm air rises and cools. This causes water droplets to form in clouds.



** Ocean Life  :drill:
Precipitation forms when water droplets in the clouds become cool and get too heavy to remain in the air.

Precipitation falls in the form of rain, snow, sleet, or hail.

The cycle begins again. A cycle has no end; it is a continuous process.



** Ocean Life  :drill:
Because water is vital to all life on earth, it is very important that we not waste it. Here are a few conservation practices that we can follow:

Wise people take quick showers, not full-tub baths.

Use the waste basket instead of the toilet for trash. Flushing wastes a lot of water.

Do not use running water to brush your teeth. Turn off the water and use only what is needed.



** Ocean Life  :drill:
We are fascinated with deep water and the ocean because it is so large and mysterious. Thousands of interesting organisms live in ocean water in a variety of habitats.

Water is essential to all living organisms, even to those that do not live in it. Water is needed for drinking, bathing, and cooking. It is used to water crops and in manufacturing. Water is a very important natural resource.





** Living Things :drill:
Have you ever wondered how so many living things are able to live together and survive? This lesson will discuss how behavioral adaptations and control systems increase an organism's chance for survival. We will also discover that living things respond to stimuli by changing their behavior patterns.



** Living Things :drill:



** Living Things :drill:
Organisms are living things, and they are all around us. There are the obvious living things such as people, animals, and plants; but other living things include bacteria, fungi, and viruses.

The surrounding environment affects these living things. They respond to a stimulus, which influences their activities and causes them to change their behavior. For example, if a cat is chasing a mouse, the mouse will respond by running away and hiding. The cat is the stimulus in this example.



** Living Things :drill:
A behavior is an action that changes the relationship between a living thing and its environment. Organisms can respond to both external and internal stimuli causing a behavior to occur.

Internal stimuli help an organism to survive. Hunger is an internal stimulus. Hunger must be satisfied with food which is necessary for the survival of living things. A polar bear knows to look for water to drink when it feels thirsty. Thirst is another example of an internal stimulus. Water is necessary for survival.



** Living Things :drill:
Living things respond to external stimuli by changing their behavior. They respond due to a change in their environment or in reaction to other organisms. An example of an external stimulus is the reaction of an animal when it sees a predator, as in the cat and mouse example.

Sometimes responses to stimuli are learned reactions, and sometimes they are innate. Innate responses are natural responses that an organism is created with.



** Living Things :drill:


** Living Things :drill:
The nervous system allows an organism to do things such as gather food and escape from predators. Over time, organisms have become more complex, and their nervous systems have continued to advance.

Most animals also have a sensory system that consists of taste, touch, sight, sound, and smell. These senses are necessary for the animals to remain aware of situations in their environment. The sensory system is useful in behaviors such as mating, nesting, food gathering, and communication.



** Living Things :drill:
Animals and other organisms are confronted with various stimuli. They must be aware of the environment around them and be able to adapt. An adaptation is any trait that gives a plant or animal an advantage in its environment. The reason for adaptation is to increase an organism's chance for survival and reproduction.

Adaptations are different for different species and can take thousands of years to evolve. When a species is no longer able to adapt, it will become extinct.



** Living Things :drill:
Behavioral adaptations affect the way a living thing acts or behaves. Animals often use their instincts to determine how they should respond in certain situations.

An instinct is a behavior that an animal is born with. Instincts help animals find food, raise their young, and protect themselves. Behavioral adaptations and instincts can increase an organism's chance for survival.



** Living Things :drill:
Some animals "play dead" so they can trick their predators or prey. Predators will sometimes leave if they think their prey is dead. In reverse, a predator may play dead to entice an animal closer so it can then attack.

Another example of behavioral adaptation is migration. Migration is the movement of an animal to a different place where there are better conditions such as food, shelter, and warmer temperatures. A bird flying south for the winter is an example of migration.



** Living Things :drill:
Another behavioral adaptation is mimicry. Mimicry is displayed when a weaker animal copies the behavior of a stronger animal in an effort to survive.

With the use of behavioral adaptations, organisms increase their chance of survival and the continuation of the existence of their species.

In addition to behavioral adaptations, living things have other internal control systems that monitor the environment and enable them to respond to changes in it.



** Living Things :drill:
As the seasons change and the temperatures get colder, some animals must protect themselves from the changing environment. These animals instinctively know that to avoid the lack of sunlight, food, and warmth, they must hibernate.

These animals survive the harsh winter months by sleeping in a safe, warm place until springtime. During hibernation, they use very little energy and live off stored fat. If they did not hibernate, the lack of food and warmth would jeopardize their survival. Some animals that hibernate are bears, snakes, and squirrels.



** Living Things :drill:
Have you ever seen an insect that blended into the tree branch that it sat on? Camouflage is another example of an internal control system that aids in the survival of an organism.

Camouflage is a protective coloration that causes a living thing to blend into its background. This allows an animal to hide from its predators or to attack its prey.



** Living Things :drill:
Some lizards change colors depending on the surface on which they are sitting. When a lizard blends into its background, the insects it is waiting to capture cannot see it.

Hibernation and camouflage are two internal control systems that increase the survival rate of some living things.
Life cannot continue if a species is unable to survive and reproduce. Adaptations, instincts, control systems, and proper response to stimuli help living things survive in our ever-changing world.

When organisms respond to internal or external stimuli, their behavior patterns change. Changing behavior patterns require the coordination of many systems.

Many organisms have a brain that controls the nervous system. The nervous system allows communication between the organism's brain and body parts. This communication system makes it possible for the body to react to internal and external stimuli.



** Living Things :drill:
The nervous system allows an organism to do things such as gather food and escape from predators. Over time, organisms have become more complex, and their nervous systems have continued to advance.

Most animals also have a sensory system that consists of taste, touch, sight, sound, and smell. These senses are necessary for the animals to remain aware of situations in their environment. The sensory system is useful in behaviors such as mating, nesting, food gathering, and communication.







** Evolution  :drill:
This lesson will explain that organisms on earth today have adapted over time. You will learn that the earth today is the result of billions of years of evolution and that fossils show these changes.



** Evolution  :drill:



** Evolution  :drill:
A History of Life on Earth

Millions of different kinds of plants and animals live on the earth. Many millions more lived on earth in the past. Where did they all come from, and why have some died out and others lived on? Why have so many different forms of life developed on the earth?

Here is a brief and incomplete history of early life on earth and how it has changed over time.



** Evolution  :drill:
When the earth first formed, it was covered with erupting volcanoes, and the air was filled with poisonous gases. There was no liquid water. When the earth was a few hundred million years old, its surface finally cooled enough for water to collect and form oceans.

Scientists believe the first life forms on earth were simple, single-celled organisms that lived more than 3 billion years ago. For more than a billion years, simple bacteria were the only form of life on earth. Some scientists think that these bacteria originated near deep-sea hydrothermal vents.



** Evolution  :drill:
Evidence for this history is found in microfossils taken from South Africa and Australia. Microfossils are too small to be seen without using a microscope.

Fossil records show that simple animals, such as jellyfish, were first seen in the ocean around 600 million years ago. Creatures such as hard-shelled trilobites appeared next around 520 million years ago. Then, fish with backbones were seen in the fossil record about 470 million years ago.



** Evolution  :drill:
Mosses and ferns were first found in water according to the fossil record. Around 400 million years ago, mosses and ferns were found in fossils from land and were followed soon after by insects and small amphibians.

In that same time, giant ferns and club mosses formed huge swampy forests. Dragonflies with wings two feet across flew among plants that grew fifty feet tall. These developed about 330 million years ago.



** Evolution  :drill:
Reptiles appeared in the fossil record around 230 million years ago. Some of those reptiles were dinosaurs. Dinosaurs were on earth for around 160 million years before they became extinct. Small mammals that evolved into large plant eaters and predators appeared around 40 million years ago.

Modern humans appeared in the Middle East and Africa around 130,000 years ago, but the history of humans goes back much farther than that.



** Evolution  :drill:
What is clear from a history of life on earth is that life has changed over time. As life forms changed through history, many plants and animals became larger and stronger. Some of the very first forms of living things, like bacteria, are still on earth and are still changing.

A Theory of Life Changes Over Time

In this lesson, the history of life on earth has been described. The next step is to explain how it happened.
Johann von Goethe (1749-1832) and Jean Baptiste de Lamarck (1744-1829) were two of the first people to develop a theory of why plants and animals changed over time.



** Evolution  :drill:
In 1858, Charles Darwin (1809-1882) and Alfred Wallace (1823-1913) separately presented theories to explain how and why new forms of life develop. Darwin became the most famous person to explain how organisms adapt over time.

This idea is called the theory of evolution. Evolution is the process by which species gradually change over time.



** Evolution  :drill:
A theory is a belief or idea based on information or knowledge people have about a subject. It is a carefully considered explanation that deals with  known facts. It is an opinion that a person offers as possibly true but not positively true.

Darwin studied plants and animals from many parts of the world. He learned the number of offspring produced is greater than the number of offspring that survive. He reasoned that if all the offspring lived, the world would have too many plants and animals. This is called overproduction.



** Evolution  :drill:
Only animals that were best able to escape predators and only plants strong enough to survive lived to become parents. Only the organisms best suited to their environment survived. Darwin called this process natural selection, or survival of the fittest.

An adaptation is any trait that gives a plant or animal an advantage in its environment. A good example of adaptation is the saguaro cactus in the deserts of southwestern United States.



** Evolution  :drill:
The saguaro cactus stem has folds that work like the pleats of an accordion. The stem of the cactus expands to store water when rain falls. Then the cactus and some animals use that stored water during the dry seasons.
The plants and animals that survive have certain natural differences. These are called genetic traits or variations. These genetic variations are features that best help the plant or animal to survive.

A genetic variation could be whether the plant or animal was taller or shorter, darker or lighter, or faster or slower. Those traits that made the organism fit for survival are passed on to offspring.



** Evolution  :drill:
The theory of evolution came about as Darwin watched species of finches that live in the Galapagos Islands. The word species is Latin for "appearance" or "kind." Darwin saw that some of the species of finches were like each other, but they were different from finches living in nearby South America.

The theory he developed from watching the finches was that a single species of finch must have flown onto the Galapagos Islands from South America. Then, that species changed little by little as each generation adapted to life on the islands.



** Evolution  :drill:
The large ground finch has a strong, wide beak that can crack open seeds. The large tree finch has a beak that can grasp and trap insects. The cactus finch has a long, pointed beak it uses to puncture the cactus plants.
The vegetarian finch has a curved beak for taking large berries from a branch. The woodpecker finch uses a long, pointed beak to hold a twig. It uses the twig to pull the larvae of insects out of holes in the trees.

Darwin noticed that the finches could no longer mate and have offspring with the finches on the mainland. They had become new species of finches. The process of a new species evolving from an existing species is called speciation.



** Evolution  :drill:
Another Theory of Change: Mutation

When some plants and animals have offspring, something unusual happens. Completely new features appear in the genetic material. These are called mutations.

Some mutations are harmful and cause the plant or animal to die. Some mutations help in a completely new way, and those traits are passed on to offspring.



** Evolution  :drill:
A plant or animal that is supposed to be born with color being born without color is a harmful mutation. An animal with this mutation is called an albino. Predators usually kill these albinos easily because they do not blend with their surroundings very well.

A useful mutation would be something that helps plants and animals blend into their surroundings. Another useful mutation would be for a fish with a flat fin on its tail to develop a curved fin. Curved fins on their tails help fish swim faster. They would then be able to get away from predators more easily.



** Evolution  :drill:
Common Origins

Many scientists believe that characteristics shared by all living things are the result of common ancestry. They believe that differences in living things are the result of adaptation to different environments.
For example, birds all have a common origin. Many scientists believe that all birds evolved from an avian-type dinosaur. As the bird ancestors spread into different environments and habitats, they adapted into different species depending on which traits were most useful and helped them survive.



** Evolution  :drill:
Some became nocturnal hunting birds like owls. Others became seed eaters or insect eaters. Some became fishing birds, and others became flightless birds, like the emu, ostrich, or penguin.

Each species adapted to the environment and food available in that area.



** Evolution :drill:
Each species, whether a mammal, amphibian, insect, or plant, spread out into different environments and habitats and adapted as needed. This is why many different types of creatures exist in the world.

Take some time to observe the different species that live around you and try to determine what might have caused that particular species to adapt from a previous species. What do you think the next adaptation might be?







** Extinction  :drill:
The dodo bird became extinct in the seventeenth century. Different species such as the sea turtle and the orca whale are now on the endangered species list. Why did the dodo become extinct? Why are some animals in this century in danger of dying out?

This lesson will explain that many species have become extinct due to environmental changes. Some changes to our planet may be slow while others are quick. You will learn how these changes affect life on earth.



** Extinction  :drill:



** Extinction  :drill:
It Takes Time

The earth is constantly changing. Some changes are slow, and some are quick. The continents are moving, and there have been ice ages and areas of the earth that change from rainforest to desert. Mountains form, and ocean levels rise or dry up.

Some places that were once under water are now deserts, and the continents have divided. We know this because fossils of fish and other water animals have been found where desert is now.
When the earth changes, it affects the plants and animals living on the surface. Sometimes the changes on the earth cause the extinction of certain kinds of life.

Earth's History Includes Mass Extinctions

Of every 100 species that have ever lived, 99 are now extinct. A species that is extinct no longer exists on earth. It has completely died out and will never again live here.



** Extinction  :drill:
The only way we know some species existed is through fossil records. Sometimes huge numbers of species died or became extinct in a very short time. These events are called mass extinctions. Two of these periods of mass extinctions are very interesting, and the cause is not completely known.

About 250 million years ago, approximately 90% of the species living in the ocean became extinct. Many land animals disappeared at the same time. This period is called the Permian extinction.



** Extinction  :drill:
During this period, the earth's continents may have moved together to form the great landmass referred to as Pangaea. This continental movement would have changed the climate on land as well as the the ocean climate. The climate change could have caused mass extinctions.

Another theory states that glaciers forming at the North Pole and South Pole caused the climate to cool. Other scientists think that volcanic eruptions in Siberia caused the climate to change. None of these theories have yet been proven to be the cause of the Permian extinction.



** Extinction  :drill:
The Cretaceous extinction occurred approximately 140 million years ago. Fifty percent of all plant and animal groups died during a short period. This is the time when dinosaurs became extinct.

Some scientists think a meteorite that was big enough to throw huge amounts of dust and water vapor into the atmosphere struck the earth. This would have caused a massive climate change. The whole world would have gotten much colder, and animals would have become extinct.



** Extinction  :drill:
Dust and heavy clouds blocked the sunlight for years. Without sunlight, plants could not survive, and plant-eating animals died. Other scientists think that this extinction was caused by increased volcanic activity. This could also cause the same type of sudden climate change.

Other extinctions have occurred because of sudden changes in the environment. Erupting volcanoes can kill all life in the area surrounding the volcano. Floods and tsunamis can wipe out life in an area. Forest fires destroy habitats that plants and animals need.



** Extinction  :drill:
These are all naturally occurring events that may explain plant and animal extinctions. Mankind has also affected the earth and caused extinctions of plant and animal life.

Five Major Causes of Extinction

There are five major causes of extinction: habitat loss, an introduced species, pollution, population growth, and overconsumption. The acronym HIPPO can help you remember the causes of extinction.



** Extinction  :drill:
Most scientists believe that more than half the species in the world live in the rainforests. Humans are causing changes in the environment by cutting down forests that contain hundreds of thousands of species of life.

Some scientists believe that as many as 150 species a day may be disappearing. That is about 50,000 species a year! Habitat loss is the major cause of extinction.



** Extinction  :drill:
In 2005, 2.4 acres (about the size of two football fields) of tropical rainforest were destroyed every second. When the area a species lives in is changed so much that it can no longer survive, the result is habitat loss.

Introducing a Species

Another cause of extinction is the introduction of another species into a habitat. A species that does not naturally occur in an area is an introduced species. These invaders can cause major problems for native plants and animals.



** Extinction  :drill:
Sometimes a species enters a new habitat by accident. The Asian long-horned beetle accidentally entered the United States in 1996. It has infected and damaged millions of acres of hardwood trees. Forestry specialists are spending millions of dollars trying to get rid of this pest.

Sometimes a species is brought to a new area on purpose. Starlings and house sparrows are birds from Europe that were brought over to North America and released. They have no natural predator here, and their populations have grown very large.



** Extinction  :drill:
Starlings and house sparrows now eat the food or use the nesting space other native birds need to survive. They do not build their own nests but take over existing nests instead. Starlings push out the eggs or baby birds so they can use the nests for themselves.

Bluebirds, swallows, wrens, robins, purple martins, and red-bellied woodpeckers are now fighting for survival. When the starlings and house sparrows were released, no one knew the damage that would be done by these European birds.



** Extinction  :drill:
Pollution

Pollution is harmful substances that are added into the water, air, or land. Acid rain caused by pollution in the air is killing vast amounts of plant and water life. Weed killers and insecticides have drained into streams and rivers. These chemicals kill the fish, and then predators eat the poisoned fish and die as well.
Oil spills kill plant and animal life in the ocean and on the shores. Cutting down all the trees in an area causes erosion, which washes dirt into the streams and rivers. Water life needs clean water to live, and silt from the erosion clogs the water.



** Extinction  :drill:
Population Growth

The human population has more than doubled in the last twenty years. This increase in human population is called population growth. In 2006, there were 6.5 billion people on the planet. We need more and more food to eat and more space in which to live, so more forests are cut down and more land is cleared.



** Extinction  :drill:
Each time people clear land for more houses or buildings, they destroy plant and animal life. Every year, plants and animals have less room to live in.

Overconsumption

People are using natural resources faster than the resources can be replaced. This is known as overconsumption. We are cutting down forests and not replanting enough trees. We are fishing and not leaving enough fish to repopulate the area.



** Extinction  :drill:
We are farming land and not giving it time to recover before more crops are planted. We are hunting animals until there are no more of them left.  Overconsumption can also mean overharvesting.

How to Prevent More Extinctions

Many species became extinct before mankind started changing the earth. Since humans have been on earth, the extinction rate has grown rapidly. More than 4,000 species are now considered threatened.
When some people realized that humans were causing plant and animal life to become extinct, they decided to do something about it. Laws have now been passed in order to prevent more species from becoming extinct.

The Endangered Species Act was created to make selling or making products that come from endangered species illegal. The American alligators, green sea turtles, African elephants, and other species have started to recover because of this law.



** Extinction  :drill:
Many countries have created wildlife habitats to protect whole ecosystems. Today, there are about 7,000 wildlife preserves, refuges, and nature parks in the world. Captive breeding was begun so animals in danger of becoming extinct could be protected.

You have learned that naturally occurring changes of the earth, whether fast or slow, can affect plant and animal life. You have also learned that people are changing the earth so quickly that they are causing the extinction of thousands of species each year.







** Green Plants  :drill:
Plants grow in every part of the world and in a variety of environments. Although different species require different growing conditions, most plants have the same requirements.

In this lesson, you will learn how and from where plants capture their energy and transfer it to different organisms through food chains. You will also understand how plants make their own food. Finally, you will understand the processes of photosynthesis, transpiration, and respiration.



** Green Plants  :drill:



** Green Plants  :drill:
Plants are very important producers in our world. A producer is a living organism that makes or produces its own food. Plants produce their own food through a complex process called photosynthesis.

Photosynthesis is the process in which plants make their food using the energy from the sun.



** Green Plants  :drill:
Green plants contain a chemical called chlorophyll that gives them their green color. Chlorophyll is stored in an organelle in a plant's cells called the chloroplast.

The chlorophyll within the chloroplast absorbs light energy from the sun, which provides the energy the plant needs to make its food.



** Green Plants  :drill:
During the summer months, the sun shines on the chlorophyll in the leaves.

As fall comes and the leaves receive less light, the plant stops making chlorophyll. Over time, the green color of the leaves begins to fade, and bright red, orange, and yellow colors emerge.

Leaves have red, orange, and yellow pigments in them which become visible as the seasons change.



** Green Plants  :drill:
The products of photosynthesis are glucose and oxygen.

During photosynthesis, carbon dioxide is joined with water by the sun's energy to produce glucose, a type of sugar, for the plant.

The glucose changes the sugar into starches, fats, and proteins.



** Green Plants  :drill:
Plants are likely to give off greater amounts of oxygen during the day because there is more sunlight.

If a plant is placed in the dark, photosynthesis will stop and the plant will die.



** Green Plants  :drill:
Animals, like humans, require oxygen to breathe. We could not exist without the oxygen plants produce. Plants require carbon dioxide to live. Plants could not exist without the carbon dioxide produced by animals.

Therefore, plants need animals, and animals need plants for survival to continue.



** Green Plants  :drill:
Photosynthesis leads to another process called respiration. Respiration is the process through which organisms obtain and release energy.

Phloem tubes carry oxygen and glucose from the leaves to all parts of the plant. Oxygen is used to break the glucose down into carbon dioxide and water. It also releases the energy known as ATP, which is stored in the glucose. ATP (adenosine triphosphate) is a substance present in living cells that provides energy for many different body processes.



** Green Plants  :drill:
Living things use energy produced by the sun. Animals eat plants, and the energy is passed on to them. Animals provide food for humans, and the energy is passed on one more time.

A food chain shows the movement of energy (in the form of food) from one organism to another. A food chain is made up of consumers and producers.



** Green Plants  :drill:
The sun provides energy for plants to grow. Plants are producers in the food chain. Plants make food. Any living thing that makes food using the energy of the sun is a producer.

Animals cannot make their own food. Animals must consume food to receive energy. When plants or animals release energy from food, they help to recycle oxygen. Anything that eats other living things is called a consumer. A food chain can contain several different consumers.



** Green Plants  :drill:
Every organism competes for space and food. The food chain is an important process because this is the way nutrients and energy flow through a group of living organisms.

This food chain is an example of how energy is passed from one organism to another. Food chains are essential for living organisms to continue their existence.



** Green Plants  :drill:
Grass is eaten by a grasshopper. The grasshopper is eaten by a frog. The frog is eaten by a snake. The snake is eaten by a hawk. This is an example of a food chain.

Energy is passed on at each level of the food chain.



** Green Plants  :drill:
People are also part of the food chain. Corn grows in fields, chickens eat corn, and people eat chicken and the eggs they produce. What plant parts do we eat directly that have stored energy?

We may eat roots. Carrots and radishes are both vegetables that are actually part of the roots. We eat seeds, such as corn and peas. Broccoli is the flower part of a plant. We even eat leaves, such as lettuce and spinach. We eat many different types of fruit, such as pumpkin, bananas, oranges, tomatoes, and apples.



** Green Plants  :drill:
Why do some plants produce fruits and vegetables that are sweet while others do not?

Phloem cells in the plant carry glucose from the leaf cells to the stems, roots, or fruits. Fruits taste sweet because sugar has been stored in their cells.

Some cells change the sugar to starch and store the starch. Potatoes and corn are starchy because starch was stored in their cells.



** Green Plants  :drill:
Water, carbon dioxide, and oxygen move in and out of leaves through the stoma. The stoma is an opening in the epidermis that allows air and water to pass in and out of the leaf.

Transpiration occurs when water is lost through the plant's stoma. When the guard cells swell, they tell the stoma that the plant has enough water. The stoma opens, and water vapor is released into the atmosphere.

Unlike animals, plants do not have a continuous circulatory system.



** Green Plants  :drill:
Plants need animals and people as much as we need plants. People and animals produce carbon dioxide when they breathe.

Plants require carbon dioxide to live, and they produce oxygen. People and animals require oxygen to breathe.
Animals and people acquire energy from plants. Plants receive energy from the sun, which they use during photosynthesis. This stored energy is eaten by other organisms and eventually by animals and humans in the food chain.

Plants are essential for life on earth to continue.







** Types of Green Plants  :drill:
There are many different types of green plants, ranging from tiny, one-celled algae to the giant sequoia tree.

What are some of the different ways plants are used? Some plants provide the food we eat such as berries, vegetables, fruits, and even some roots and leaves. Many medicines are made from plants. Fibers from plants are woven to make clothing. We even beautify our surroundings by planting flowers and trees. Plants are an important resource in our world.
There are thousands of different species of plants, each consisting of their own unique characteristics.

This lesson will discuss the difference between vascular and nonvascular plants and xylem and phloem tissue. It will also investigate the root systems of different plants and explain herbaceous and woody stems.



** Types of Green Plants  :drill:



** Types of Green Plants  :drill:
Some green plants are called vascular plants. These are land plants that have roots, stems, and leaves and are able to carry water and food throughout the plant. Some examples of vascular plants are grasses, trees, sunflowers, and water lilies.

Vascular tissue is special tissue that connects all parts of the plant, allowing it to transport nutrients and water throughout the plant's system.



** Types of Green Plants  :drill:
There are two types of vascular tissues in seed plants, the xylem (ZY-luhm) and the phloem (FLOH-ehm). These are special tube-like tissues located in the plant's roots, stems, and leaves.

Xylem tubes carry water and dissolved minerals from the roots to the leaves.

Phloem tubes carry nutrients made in the leaves to all parts of the plant.

Each plant needs both xylem and phloem tubes to survive.



** Types of Green Plants  :drill:
Vascular cambium is the growth tissue that produces phloem and xylem in the stems of woody plants. The plant grows in diameter as the vascular cambium produces phloem and xylem cells.

Capillary action is the upward motion of liquid in the thin tubes of the xylem which brings water to other parts of the plant.



** Types of Green Plants  :drill:



** Types of Green Plants  :drill:
Each year, new growth is deposited between the tree bark and the inner tissue of woody stems. This is called the annual growth ring.

The year's weather and growing conditions will cause the ring to be wide or narrow. If growing conditions are good, the tree will grow a lot, and the ring will be wide. If conditions are poor, the ring will be narrow.

Annual growth rings can also be used to estimate the age of a tree.



** Types of Green Plants  :drill:
Another type of stem is the herbaceous stem. Herbaceous stems are soft and flexible, and they die at the end of the season. Most herbaceous plants live only one season; however, some are perennials.

Plants that live only one growing season are called annuals. Radishes, potatoes, corn, and petunias are all examples of herbaceous annuals.



** Types of Green Plants  :drill:
Roots hold plants tightly to the earth. There are two kinds of root systems:

 taproot
 fibrous root

A carrot or a radish is an example of a taproot. A taproot is a main root that grows straight down, deep into the ground.



** Types of Green Plants  :drill:
Fibrous roots grow closer to the surface of the ground and spread out to collect water. There are many strands of fibrous roots that branch out. Many grasses and trees have fibrous roots.

Fine root hairs grow on both types of roots. The root hairs help the roots absorb nutrients and water.



** Types of Green Plants  :drill:
Green plants make their own food using energy from the sun in a process called photosynthesis.

Photosynthesis occurs in the plant's leaves. The sun shining on the green leaves and carbon dioxide combine to produce the plant's food. Food produced during photosynthesis is used in plant cells during respiration.

Respiration is the process through which organisms obtain and release energy.



** Types of Green Plants  :drill:
The outer protective layer of a plant is called the epidermis. It is made up of a thin layer of cells. There is an upper epidermis and a lower epidermis.

Openings in the lower epidermis and some in the upper epidermis allow air and water to pass into and out of the leaf. These openings are called stomas.



** Types of Green Plants  :drill:
Surrounding each stoma is a guard cell. When the guard cell swells with water, it causes the stoma to open and release water to evaporation.

The stoma tends to balance the water within the leaf. The process in which a plant gives off water through leaves is called transpiration.



** Types of Green Plants  :drill:
Pines, spruces, and gingkoes are good examples of gymnosperms. Many of the shrubs used in landscaping around homes and buildings are also gymnosperms. Gymnosperm means "naked seed."
Complex vascular plants have seeds. There are two kinds of complex vascular plants:

 gymnosperms
 angiosperms

Gymnosperms generally stay green all year and are usually referred to as evergreens. They lack a protective covering around their seeds.



** Types of Green Plants  :drill:
Angiosperms are flower-producing plants. They have a protective covering around their seeds.

Angiosperm means "seed in a container." Most of the plants on earth are angiosperms.



** Types of Green Plants  :drill:
Simple vascular plants such as ferns or horsetails do not produce seeds. These plants have a poor vascular system.

These plants require a constant water supply and live in warm, moist, shady areas. Scientists believe that these plants were abundant about 300 million years ago when the earth was warmer. Many fossils of these plants have been found.



** Types of Green Plants  :drill:
Nonvascular plants do not produce seeds either. They do not have true vascular tissues, roots, stems, or leaves. These plants include mosses and liverworts.



** Types of Green Plants  :drill:
Algae are also nonvascular plants. They are unicellular or multicellular organisms. There are three basic kinds of algae: green, brown, and red.

Algae contain chlorophyll and make their own food. They live in many places such as tree trunks, ponds, and oceans.



** Types of Green Plants  :drill:
There are millions of different species of plants, each with their own special characteristics and traits. In this lesson, you became familiar with the difference between vascular and nonvascular plants. Vascular plants contain xylem and phloem, while nonvascular plants do not, because they lack roots, stems, and leaves.

This lesson also revealed the characteristics of herbaceous stems and woody stems. Herbaceous plants are usually annuals, though some are perennials.
Plants are everywhere in nature. Take a look out your window. Do you see vascular plants or nonvascular plants? Are there annuals or perennials growing in your flowerbed? Does the tree in your yard have a herbaceous stem or a woody stem? Are the flowers in the park angiosperms or gymnosperms?


