** Inquiry 							      :drill:
Have you ever read about a topic or watched a program about something and wanted to know more about it? 
When you learn more about a topic, you are [building] on what you already know. The same principle applies to science.

This lesson will explore scientific theory as the basis for new [knowledge], the evaluation of scientific work, 
and how new scientific methods and technologies are developed.

** Inquiry 							      :drill:
The field of science is constantly growing and changing. New observations are made, and new theories are formed. 
All of this becomes a part of what we know as science.

Science is a body of knowledge based on the [observations] of scientists. 
It is the state of knowing [facts] about the world and testing that information through the [scientific] [method].

** Inquiry 							      :drill:
[New] ideas and theories are based on [old] ideas and theories.

When a scientist finds a way of explaining a topic or completing an operation, he or she does not stop there.

It is at this point that other scientists will take an interest in the idea and work to develop it even further.

This is the way that science continues to develop and grow.

An idea or [theory] is formed. A [theory] is a belief or idea based on the information or knowledge available about a subject.

That [theory] is then further developed and expanded.

** Inquiry 							      :drill:
A [scientist] is a person who is knowledgeable in a specific area of science and tries to find out how things in nature work.

They try to better understand the world and find ways to improve our lives.

The more that is learned, the more information is available to build new ideas.

Photography is a good example of this.  The primary theories used in photography had been around for hundreds of years.

Eventually, the new idea of capturing an image in print was built on old theories.

** Inquiry 							      :drill:
Scientists often make observations or conduct experiments to gather data on a topic and decide how best to resolve a situation.

Numerous measurements are required to be made while making [observations] or conducting [experiments].

These measurements must be [accurate].

That means they should not contain any mistakes.

** Inquiry 							      :drill:
There are times when scientists cannot find the necessary tools or effective methods to complete their work.

This could be the case if they are exploring a topic that has not been explored before or developing new technology.

In these cases, they may need to develop new methods or tools to complete these measurements and gather [data].

** Inquiry 							      :drill:
Once [data] has been collected, it is [published] for review and evaluation.

It is through this process that the [data] is refined and checked for accuracy.

Just as we discussed earlier in the lesson, new ideas are built on old ones.

For this reason, it is important for scientific [data] to be accurate.

** Inquiry 							      :drill:
If new ideas are built on past information that is flawed and filled with mistakes, the new ideas will be flawed as well.

Scientists work together to check and recheck [data] to ensure that it is as [accurate] as possible.

When scientists conduct observations or experiments, they must make [measurements].

When they have completed these measurements, they are then able to evaluate their work and draw conclusions from the [results].

It is this process of evaluation and drawing conclusions that provides us with additional knowledge about the field of science.


** Data Collection 						      :drill:
Today's society uses [data] in a vast number of ways and in many professions.

Data is another word for [information].

People interested in selling products collect [data] about what people buy.

** Data Collection 						      :drill:
Scientists who want to learn more about something must [collect] data about the topic.

This data can come from either the [previous] work of other scientists or new [experiments] and [observations] they conduct.

This data is often in the form of [mathematical] figures.

** Data Collection 						      :drill:
These are only a few examples of the types of measurements scientists might make.

Most measurements made by scientists to gather data are expressed as [numbers] or other mathematical [figures].

Here is an example of how the process of [collecting], presenting, calculating, organizing, and [evaluating] data might work.

Most people like to know what the weather is going to be the next day or even the next week.

** Data Collection 						      :drill:
[Measurement] is accurate and precise information gathered by scientists with the use of special tools.

[Measurements] are made daily, or even hourly, all over the world documenting the temperatures at specific locations.

The [measurements] have been made at the same time and in the same way for decades.

This [data] is then averaged.  This is how the "normal" temperature for a specific location is determined.

** Data Collection 						      :drill:
[Evaluation] is involved in all areas of science.

Scientists [evaluate] the work of others to ensure it is accurate.

The use of mathematics in this process ensures that all scientists, regardless of what language they speak, will be able to look over the data and [evaluate] it.

Mathematics is a universal [language] in itself.

** Data Collection 						      :drill:
Meteorology is now a trusted part of our everyday life.

Technology has greatly increased the speed and accuracy of this science over the years.

We rely on local meteorologists to give an accurate [forecast] of the [weather] each day and to alert us of inclement or hazardous weather.

With the development of technology, scientists are able to gather more [data] in a shorter period of time and with more [accuracy].

** Data Collection 						      :drill:
[Computers] have had a significant impact on the way scientists gather data.

Scientists once made difficult calculations that took hours to complete, and they often made mistakes.

It is now possible for a [computer] to make these same calculations without error in a matter of seconds.

The way [scales] now weigh objects has become incredibly precise.

The [microscope] has become more advanced and can show the smallest parts of a cell.

** Data Collection 						      :drill:
Scientists must use a variety of methods of gathering data based on the question to be answered.

Two examples of methods that could be used are [observation] and [experimentation].

[Observation] is anything noticed about a problem.

[Experimentation] is collecting information by trying new things.

An [experiment] would be an appropriate method to find how ice affects the temperature of water.

To find the average temperature of a location over time, [observation] would be an appropriate method to use.

With either method, careful [measurement] is crucial to the accuracy of the data.


** Science Skills 						      :drill:
Throughout the day, everyone is faced with problems that need to be solved or questions that need to be answered.

What steps do you take to solve problems and answer questions?

Scientists search for answers to questions by using the scientific [method].

In this lesson, you will learn the steps of the scientific [method] and how it can be used in everyday life to help solve problems.

You will also learn how to use [deductive] and [inductive] reasoning to draw conclusions.

** Science Skills 						      :drill:
Scientists use a [systematic] approach to investigate research problems as an integral part of their profession.

They call this system the [scientific method].

** Science Skills 						      :drill:
The scientific method is an orderly arrangement of [steps] that scientists use in [problem] [solving].

It is not a set of rigid rules, but rather a general [process] used to solve problems.

Let us look at the steps included in the scientific method.

** Science Skills 						      :drill:
1) What is the [problem]?

Before conducting research or expending time, energy, or money, scientists first state or identify the [problem].

Scientists must determine the questions they are seeking to [answer].

** Science Skills 						      :drill:
2) Obtaining [Information]

This is the research phase in which the scientist gathers all the background material.

Other scientists may have already discovered relevant and important [information] concerning this question.

After a careful study of the background [information], the scientist is ready to make an educated guess as to the solution to the research problem.

** Science Skills 						      :drill:
3) Formation of a [Hypothesis]

A [hypothesis] is an educated guess of what you think will happen in an experiment.
It is the result of careful [observation], research, and study.

A [hypothesis] is formed after the question has been asked and the information has been gathered and studied.
This is done prior to performing any [experiments].

** Science Skills 						      :drill:
4) [Experimentation] (after forming a hypothesis).

Students often think science is nothing more than one [experiment] after another.  This is not true.
A great deal of work goes into a study before any [experimentation] is ever attempted.

Even more work follows after the [experiment] has yielded results.
[Experiments] must follow certain guidelines to be considered valid or true.

** Science Skills 						      :drill:
5) [Analyzing] Data

Following the completion of the experiment, all the collected information, or [data], must be [analyzed].

This process may require the compilation of data tables or the creation of new graphs.

** Science Skills 						      :drill:
6) Drawing a [Conclusion]

Following this extensive study, a conclusion may be reached.  The answers may or may not be known.

The [conclusion] might show that more experimentation or another approach may be needed.

Remember, in science, we learn from [failures] as well as from [successes].

** Science Skills 						      :drill:
You might use the [scientific method] to solve a problem of your own.

Look at an example:
1.  You notice your allowance does not seem to be going as far as it once did.
2.  You decide to keep a record of all your expenses for a week.
3.  You look at your list and discover you are buying three soft drinks a day from the machine at school.  These sell for 75 cents each.
4.  You decide to have only one soft drink a day for the next two weeks.
5.  You have saved $15.00 and now have extra cash for the weekend.

Congratulations! You have just used the [scientific method] to solve a problem.

** Science Skills 						      :drill:
Remember the following steps:

1.  The scientific method begins with an [observation].
2.  The [observation] leads you to ask a [question].
3.  You gather [information] to answer the [question].
4.  You make an educated guess and form a [hypothesis].
5.  You test your [hypothesis] by performing an [experiment] (or by [observing] the subject).
6.  You review and [analyze] data.
7.  You draw a [conclusion].

** Science Skills 						      :drill:
Scientists use both [inductive] and [deductive] reasoning when solving problems using the scientific method.

[Deductive] reasoning moves from [general] to [specific] in order to reach a conclusion.

[Inductive] reasoning moves from [specific] facts to [general] in order to reach a conclusion.

** Science Skills 						      :drill:
Look at an example of [inductive] reasoning:

Observation: The addition of saltwater to roses results in the death of the roses.

Inductive reasoning:
1.  Saltwater kills roses.
2.  Roses are flowering plants.
3.  Therefore, saltwater would probably kill all flowering plants.

This reasoning moved from [specific] to [general].

** Science Skills 						      :drill:
Now, look at an example of [deductive] reasoning.

Observation: Butterflies change through metamorphosis from eggs, to larva (caterpillar), to pupa, and finally to adult butterflies.

This reasoning moved from [general] to [specific].

** Science Skills 						      :drill:
Scientists discover a new species of caterpillar while doing research in Peru.
Scientists know that caterpillars undergo metamorphosis and become butterflies.

Using [deductive] reasoning, this caterpillar should transform into a pupa and finally into a new species of butterfly.

** Science Skills 						      :drill:
Science is often associated with experimentation.
If data is to be valid, the experiment must be [controlled].

A [controlled] experiment is one in which only one [variable], or single condition, is changed at a time.

Look at an example.
Suppose you bake some cookies, and they taste awful and look terrible.

You start over, but this time you add two more eggs, 1/2 cup more sugar, and a cup of chocolate chips to the recipe.
You bake them at a higher temperature than the first batch.

Now the cookies are delicious.

Which [variable] caused the success?
[Because so many changes were made at the same time, we do not know which variable caused the cookies to be so much better the second time.]

** Science Skills 						      :drill:
In a controlled experiment, only [one] variable is changed at a time.

** Science Skills 						      :drill:
Scientists use the scientific [method] every day to answer questions and solve problems.

The scientific method involves making an [observation], asking a question, gathering [information], 
forming a [hypothesis], performing a [controlled] experiment, analyzing [data], and finally drawing a [conclusion].

Conclusions can be formed by using [inductive] or [deductive] reasoning.


** Science Fair Project 					      :drill:
The [scientific method] is six organized steps to finding answers.

They are as follows:
1) state the [problem] (topic)
2) [gather] information
3) form a [hypothesis]
4) [experiment]
5) [record] and [analyze] data
6) develop a [conclusion]

** Science Fair Project 					      :drill:
It is a good idea to state your purpose in the first step.

If your purpose is well worded, you will have little difficulty writing a [title] for your project.

** Science Fair Project 					      :drill:
The next step is gathering information.

In this step, you research and gather all the information possible about your topic.  This includes interviews 
with professional people, library research, observations, and even research on the Internet.

This information will help you form a [hypothesis]:  A statement of what you think will happen as you investigate and [experiment].

** Science Fair Project 					      :drill:
Remember to complete a [bibliography] of all research you do and be sure to keep it current.

List alphabetically all books, articles, people, and other [sources] that you used for researching and writing.

** Science Fair Project 					      :drill:
Now you are ready to experiment.  The items needed for an experiment are:

1) materials
2) variables
3) step-by-step directions

List all materials used in your investigation.
Include what, how much, and what kinds of materials you used.
Keep in mind that quantities are very important.
Be sure to use only [metric] units.

** Science Fair Project 					      :drill:
A [variable] is a single condition that may vary during the course of an [experiment].

There are three types of variables.

1) [Manipulated] variable - what is purposely changed in an investigation
2) [Responding] variable - what changes by itself because you changed something in the investigation
3) Variables held constant - everything else in your investigation must be held constant, or kept the same

** Science Fair Project 					      :drill:
Your step-by-step directions are like a recipe.  Anyone who reads them will be able to [duplicate] your investigation and get the same [results].

You must keep a data sheet or log.
Data refers to [information] gathered during your investigation.

** Science Fair Project 					      :drill:
Now, let us go step-by-step all the way through a project.

Our [topic/question]: "Do all brands of paper towels absorb the same amount of water?"

Our [hypothesis]: "The cheaper the paper towel, the less water it will absorb."

** Science Fair Project 					      :drill:
To be valid and convincing, data must be analyzed and displayed.
One of the most easily read forms for displaying information is a [graph].

** Science Fair Project 					      :drill:
There are two main types of graphs: [bar] graphs and [line] graphs.

A [bar] graph uses bars to display data.
The lengths of the bars represent numerical amounts.

A [line] graph uses points connected by lines to display data.
The lines show how something changes over [time].

** Science Fair Project 					      :drill:
There are three main items which you must take into consideration and use when making a graph.

1) [Title] - the [title] is a short description of the data being displayed.
2) [Horizontal] axis - the [manipulated] variable is displayed on the [horizontal] axis.
3) [Vertical] axis - the [responding] variable is displayed on the [vertical] axis.

** Science Fair Project 					      :drill:
Before you write your conclusion, carefully examine all your data (graphs, charts, tables, etc.).

Ask yourself these questions:

1.  Did you get the [results] you expected? If not, how were the [results] different?
2.  Were there any unexpected problems that may have affected your [results]?
3.  Do you think you collected enough [data]?
4.  Do you need to revise your [hypothesis]?

** Science Fair Project 					      :drill:
9.   Are you keeping a [log]?
10.  Could someone else set up and carry out your investigation from your [step]-[by]-[step] directions?
11.  Have you presented information clearly using [graphs]?
12.  Will your data allow you to draw [conclusions] and/or support your [hypothesis]?


** The Process of Science 					      :drill:
How is scientific research done? Do new ideas replace old ones? Do scientists always agree? 

Does someone need to give his or her consent to be used as a research subject?

All of these questions and more will be answered in this lesson.

** The Process of Science 					      :drill:
A scientist is a person who studies and explores one or more of the [branches] of science.

In this lesson, you will learn about some of the things scientists do during their research.

** The Process of Science 					      :drill:
Scientists usually follow the steps of the [scientific] [method] when they do research.

This involves identifying a problem, making observations, forming and testing a hypothesis, coming to a conclusion, and reporting the findings.

This is a long process that can sometimes take years to complete.

** The Process of Science 					      :drill:
Scientific knowledge is based on evidence; however, as new knowledge is gained, old ideas may change.

Sometimes this is difficult for scientists because they do not always agree or interpret data the same way.

Scientists use critical [evaluation] when looking at new ideas because it is a basic part of science.

[Science] is the state of knowing facts about the world and testing information through the scientific method.

** The Process of Science 					      :drill:
Scientific knowledge is always based on [evidence]: It shows [proof].

** The Process of Science 					      :drill:
In science, every accepted idea must have evidence and be able to be proven.

If other scientists are not able to [duplicate] a method and prove it, they will not know if it is valid or not.

Experimental proof and evidence are what make scientific observations [valid].

If there is a lack of evidence, scientists cannot find out if the theory is correct or not.

** The Process of Science 					      :drill:
Change in knowledge is going to happen.
New ideas are going to be formed, and new observations are going to challenge popular theories.
As new knowledge is gained, ideas about the natural world may change.

Regardless of how well a theory explains a set of observations, it is possible that another theory will be created to better [explain] it.

Making improvements to ideas, and sometimes completely changing them, happens often in science.

** The Process of Science 					      :drill:
Sometimes it is hard for scientists to accept a new theory regardless of how much evidence there is to support it.

However, theories are judged by their results.

If a new idea answers more questions and produces more results, it eventually takes the place of the old one.

When new ideas are developed and tested, they go through critical [evaluation] by other scientists before they are [accepted].

The researching scientist must provide accurate reports and steps for others to read and follow.

** The Process of Science 					      :drill:
Scientists carefully test, study, and evaluate the theory.

Observations and experiments are repeated so the results can be evaluated.

The scientific community will only accept an idea after it has been [evaluated] and [tested] many times by other scientists.

The more a hypothesis is tested and proven, the more confidence scientists have in it.

Repeating a process many times and getting the same results [validates] the conclusion.

** The Process of Science 					      :drill:
When a hypothesis fails, the scientific community loses confidence in it.

Sometimes scientists evaluate an idea or a procedure and disagree with it.

Rather than rejecting it, they try to find ways to change it to try to make the idea better.

Scientists gain knowledge and understanding from [mistakes].

** The Process of Science 					      :drill:
The process of science depends on observations and theories.

When scientists evaluate new ideas, they make new [observations] that helps them learn and gain knowledge.

As new theories and ideas develop, scientists acquire new [information].

As they evaluate and test this new [information], they come to new understandings about the world.

** The Process of Science 					      :drill:
Sometimes scientists do not [interpret] data the same way.

This can cause disagreements among the scientific community.

Scientists work with each other to resolve their issues.

They do this by collecting additional evidence to support or dispute the idea in question.

** The Process of Science 					      :drill:
Scientists sometimes disagree about the value of certain types of evidence.

They may not believe it is relevant to the theory or important enough to base a decision on.

Other times, scientists make [assumptions] in their testing.  An [assumption] is what someone thinks, and it usually cannot be proven.

Therefore, it cannot be backed up with evidence.  However, if there is evidence that supports an [assumption], scientists may accept it.

** The Process of Science 					      :drill:
Sometimes scientists disagree with evidence or data that is [biased].

[Bias] is a prejudiced outlook.

Scientific data can be [biased] in how it is collected, interpreted, or reported.

** The Process of Science 					      :drill:
A scientist's race, gender, religion, or political opinions can affect his or her perception, and therefore affect what data is believed to be important.

Scientists are expected to be aware of possible biases in their own work, as well as in the work of others.

That is one reason scientists evaluate each other's work.

If they detect [biased] data, they will question its [validity].

Different explanations can sometimes be given for the same data or evidence.

It is not always possible to know which explanation is right.

** The Process of Science 					      :drill:
Scientists do many different types of scientific research.

Science that affects the well-being of humans must eventually be tested on human subjects.

Scientists must follow [ethical] guidelines in testing.

One of the most important rules is ensuring that proper [consent] is given.

Each subject should be respected as a person who can make his or her own decisions.

He or she must be fully informed of the purpose of the research.

** The Process of Science 					      :drill:
Subjects should know with whom the researcher is affiliated, and who is funding the research project.

Subjects should be made aware of any procedures or methods they will be a part of.

They must be told of all the potential [risks] and the expected [benefits] involved in the experiment.

They should also be made aware of any stress or discomfort that may be experienced.

Subjects should be allowed to ask questions and get clear answers from the scientists involved in the research.

** The Process of Science 					      :drill:
Special care must be given to human subjects who are not capable of making [informed] decisions on their own.

Children, people who are legally incompetent, and those who are physically or mentally incapable of giving 
consent can participate in a study as long as someone who is legally authorized gives consent in their behalf.

However, these groups should never be used unless there is no alternative.

Although it is necessary to use human subjects in order for science to progress, research involving 
humans has important [ethical] implications.

This is why having guidelines that protect human rights and health is so important.

Scientific research is part of our daily world, and it will continue to be.

It is important to understand the process researchers take to make scientific advancements.

