* Part I.  Foundations of a Data-Driven Enterprise
** Introduction
*** Two ah-ha moments while working at Facebook:
1. In a data-driven company, people will consume data faster than your data team
can provide it.  This is what led to the creation of Hive at Facebook which allowed
analysts and other people to create their own ad-hoc quries with a SQL-like language.
Hive brought the power of big data to the people.
2. The second ah-ha occurred when they realized that people outside of FB wanted Hive.

*** The Emergence of the Data-Driven Organization
A data-driven organization is one that understands the importance of data.  It possesses
a culture of using data to make all business decesions.  Not the word _all_.

Why become a data-driven company?  Because it pays off:
1. The MIT Center for Digital Business surveyed 330 companies and found that the more a
company identified as being data-driven, the better it performed on objective measures.
2. The Economist Intelligence Unit showed a clear connection between how a company uses
data, and it's financial success.

According to a Harvard Review study by McKinsey executives, being a data-driven company
requires simultaneiously undertaking three interdependent initiatives:
1. Identify, combine and manage multiple sources of data
Eliminate data silos while constantly seeking out new sources to inform decesion-making.
Combine multiple independent sources of data to get better insights.
2. Build advanced analytics models for predicting and optimizing outcomes
The most effective approach is to identify a business opportunity then determine how a
model can achieve it.  Start with a problem, not the data.
3. Transform the organization and culture of the company so that data actually produces
better bsuiness decisions
Data initiatives need to be in sync with the day-to-day processes and decision-making
habits of a company, otherwise, they will run the risk of failure.

*** Moving to Self-Service Data Access
Bottlenecks between the keepers of the data and people who need data must be eliminated.

_Data delayed is data denied._  Users need to be able to get timely data in order to take
advantage of business opportunities.

A key indicator of "data democratization" is the ratio of administrators to end-users.
Experience shows that a well-designed data platform should not require more than 1 admin
for every 20 to 30 end-users.

The data infrastructure must handle both prototype and production projects, which have
different goals:  Prototype projects need agility and flexibility whereas production
projects require stability and predictability.

*** The Emergence of DataOps
Gartner's definition of DataOps:
A hub for collecting and distributing data, with a mandate to provide controlled access
to systems of record for customer and marketing performance data, while protecting privacy
usage restrictions and data integrity.

**** Aspirations for a Data-Driven Organization following a DataOps Model
At the core are executive support, a centralized data infrastructure and democrotized
data access.  The steps in this model are 1) Processed, 2) Analyzed, 3) Learn 4) Re-Use

Three things driving the DataOps movement are
1. Data isn't a static thing
2. Technology is not enough
3. Greater agility is needed

** Data and Data Infrastructure
*** A Brief History of Data

In the 1990's, data was mostly _transactional data_, and it was stored in OLTP systems
like Oracle and Teradata databases, and other types of conventional data repositories.
ERP and CRM systems, Enterprise Resource Planning and Customer Relationship Management
systems, are two examples of the types of systems that produced this type of data.

The advent of the web brought _interaction data_, data that is generated by people and/or
machines interacting with each other.  This is often semi-structured or unstructured data
like web pages, music, video and pictures.  Later, various sensors started generating data
when montitoring servers, networks, thermostats, etc.

Gartner's three-V's of Big Data:
1. Volume - The amount of data stored is doubling every two years.
2. Velocity - The amount of data stored given a time period is also increasing.
3. Variety - The types of data being stored are also increasing (eg video, sensors).

*** The Evolution of Data to Big Data
IDC estimates that global data doubles every two years.

Two trends are driving the data explosion:
1.  Increasing Connectivity
2.  Proliferation of Connected Devices

*** Challenges with Big Data
The biggest challenges with Big Data:
1.  _Connecting employees to the right data_ and helping them understand
2.  _What to do with that data_ in order to make the right business decisions.

The two biggest barriors to a Big Data project are
1.  Identifying what data to collect
2.  They don't know how to analyze the data that is being collected

*** The Evolution of Analytics

| Type         | What it does         | Examples                              | Value   |
|--------------+----------------------+---------------------------------------+---------|
| Prescriptive | What action to take? | Recommendation, Automation            | Highest |
| Predictive   | What may happen?     | Modeling, Data Science, etc           |         |
| Diagnostics  | Why has it happened? | Search, query tools, data exploration |         |
| Descriptive  | What has happened?   | BI Dashboards, KPI tracking, ETL      | Lowest  |

In the past, descrptive analytics allowed us to figure out what happened:  It is like
looking in a car's rearview mirror.  From highsight, diagnostic analytics provide insight
about why something did occurr.  Predictive analytics allow us to make predictions about
what is likely going to happen.  Prescriptive analytics consider courses of action given
a prediction.

*** The Data "Supply Chain"
The four components of the data supply chain:
1. Ingest - The process of loading, transferring, loading and processing data for later
use or storage is called _data ingestation_.
2. Data Preperation and Cleansing - Data analysis requires good, high-quality, data.  The
cleansing and preparation of data has historically been a long arduous process that is
becoming easier with the introduction of new tools.
3. Analysis - The process of modeling data with the goal of discovering useful information
in support of better decision-making.
4. Egress - Outputs of the analysis are consumed by humans and other systems.

*** Different Types of Analysis (and Related Tools)
| Type                | Who (Typically)   | Tools                            | What                                                |
|---------------------+-------------------+----------------------------------+-----------------------------------------------------|
| Ad Hoc Analysis     | Business Analysts | SQL tools like Presto and Impala | Statistical models, analytic report, data summary   |
| Machine Learning    | Data Scientists   | ML Algorithms and tools like R   | Creates predictive models                           |
| Deep Learning       | Data Scientists   | Tensor Flow                      |                                                     |
| Pipelines for Data+ | Data Engineers    | Hive and Hadoop                  | Cleanses data, creates pipelines and KPI Dashboards |

*** How Companies Adopt Data
| Stage      | Exemplified By                   | Technologies / Goals                                                   |
|------------+----------------------------------+------------------------------------------------------------------------|
| Aspiration | Access data via the data team    | Traditional data warehouse w/ production reporting and ad hoc analysis |
| Experiment | Identify a big data initiative   | Varies / Characterized by uncertainity about choices and options       |
| Expansion  | Multiple big data projects       | Top-Down architecture w/ access still being provided by a data team    |
| Inversion  | Employees "bottom-up" use-cases  | These bottom-up use-cases lead to scalability and other issues         |
| Nirvana    | Overcoming the issues in stage 4 | You've overcome all of the data challenges at this stage               |

** Data Warehouses Versus Data Lakes: A Primer
** Building a Data-Driven Organization
** Putting Together the Infrastructure to Make Data Self-Service
** Cloud Architecture and Data Infrastructure-as-a-Service
** Metadata and Big Data
** A Maturity-Model "Reality Check" for Organizations
* Part II.  Case Studies
** LinkedIn: The Road to Data Craftsmanship
** Uber: Driven to Democratize Data
** Twitter: When Everything happens in Real-Time
** Capture All Data, Decide What to Do with It Later: My Experience at eBay
** A Podcast Interview Transcript
