** The Writing Process 						      :drill:
If you wanted to bake a cake, you would have to follow a [recipe].
A [recipe] lists the ingredients and tells you how to mix them. Suppose you didn't follow 
the [recipe] and put the pan into the oven first. Then you beat the eggs and poured them into the pan.

After that, you mixed the milk and flour and poured it over the eggs. 
Get the picture? You wouldn't end up with a cake, would you?


** The Writing Process 						      :drill:
Writing is much like baking a cake. 
You must follow the instructions or certain steps if you intend to turn out a suitable product.

Writing is best done when [five] specific steps are followed.
If you use the five steps of the writing process each time you write, 
you will eventually produce excellent work.


** The Writing Process 						      :drill:
These are the five steps of the writing process:
1. [Prewrite]
2. [Rough draft]
3. Edit
4. Proofread
5. Publish


** The Writing Process 						      :drill:
These are the five steps of the writing process:
1. Prewrite
2. Rough draft
3. [Edit]
4. [Proofread]
5. [Publish]


** The Writing Process 						      :drill:
In the prewriting step, you decide what your [topic] will be, who your 
[audience] will be, and what your [purpose] for writing is (to inform, 
to entertain, to describe, or to persuade).

Next, decide what [form] you will use (narrative, poem, letter, poster, etc.). 
After you have decided on the form, gather all the information that 
you can about the topic in order to complete the assignment.


** The Writing Process 						      :drill:
There are a variety of ways to get the information you need. You can interview 
people, research, or brainstorm. The important thing is to get information. 
Take notes. Organize those notes into logical order.

Use an [outline] to help you organize the information so that it is usable. 
Decide what will come first, second, etc. The better you organize, the 
better your paper will be.


** The Writing Process 						      :drill:
The second step is very important. Writing the [rough draft] is not easy, 
but if you've organized your material well in the first step, it will 
be much easier. The [outline] will provide a "road map" to follow as you write.

Speak in your own voice. This means to [write as you would talk]. Don't worry 
about spelling, punctuation, or correct usage. Just get something on paper. 
Use a pencil. Double space so that you can make corrections later.


** The Writing Process 						      :drill:
After you have prepared a rough draft, you are ready for the third step, [editing].

Read over your paper several times. Could you have said anything better? 
Could you be more exact? Would the paper make more sense in a different order?


** The Writing Process 						      :drill:
Even professional writers [edit] and [rewrite] their work several times. If you 
plan correctly, you should be able to have a little time between the 
rough draft and the editing session.

Sometimes if you leave your work for awhile and come back to it, you will 
be able to see much more clearly what you wanted to say. You will also be 
able to spot errors more easily.


** The Writing Process 						      :drill:
[Proofreading], the next step, can be fun. Make a game of it. Read your paper 
thoroughly in search of errors in punctuation, spelling, and grammar.

You may have written an excellent paper, but if you fail to [proofread] it thoroughly 
and correct all errors, you will only get credit for having a mediocre paper.


** The Writing Process 						      :drill:
Avoid misusing words. Be sure to remember that subjects must agree with their verbs in number. 
Be sure to correctly use pronouns and correct verb tense and number.  Don't let all of your 
hard work result in a low grade because of errors in spelling, punctuation, or grammar.

This step is called [proofreading].


** The Writing Process 						      :drill:
Practice [proofreading] by correcting the errors in this sentence:

Between you and I, their isn't but four errors in this here sentence.
Did you find all four errors? Check the next screen to see if your answers were correct.


** The Writing Process 						      :drill:
Between you and I, their isn't but four errors in this here sentence.

Between is a preposition. [I] can never be the object of a preposition. 
Change [I] to [me].

Their is a possessive pronoun that does not belong in this sentence. 
Change [their] to the introductory word [there].


** The Writing Process 						      :drill:
Between you and I, their isn't but four errors in this here sentence.

Errors is the [subject] of the sentence. Isn't is an incorrect verb because errors is [plural]. 
The contraction isn't combined with the negative term but forms a double negative. Change isn't to are.

Never use this with here or that with there. This is very poor grammar.

The corrected sentence is:
Between you and me, there are but four errors in this sentence.


** The Writing Process 						      :drill:
After you have carefully proofread your paper, you are ready to [publish]. 
[Publishing] is simply sharing your work with others. You can [publish] by reading 
your paper aloud, turning it in for a grade, or submitting it to a newspaper or magazine for publication.

Follow your teacher's instructions when you [publish]. The final copy should come directly from the 
rough draft that you have reworked and proofread. Your work should be neatly written in blue or black ink or typed.


** The Writing Process 						      :drill:
As a rule of thumb, if you have any errors on your final copy, correct them and then 
[reprint] or [rewrite]. You don't want your audience to think that details are not important to you.


** The Writing Process 						      :drill:
Review the [five] steps of the writing [process] and commit them to memory. They will serve you in any kind of writing.

Who knows? You might become the next John Grisham, Mary Higgins Clark, or Stephen King.


** Parts of Speech 						      :drill:
Words are the tools we use to communicate with other people. Used correctly, words 
express emotion, give instruction, tell an interesting story, or convey a clear meaning.

To use words as effective tools, you must know that all words can be classified into 
[eight] different categories. These categories are the [eight] parts of speech.


** Parts of Speech 						      :drill:
The eight parts of speech are [nouns], [pronouns], [verbs], [adjectives], 
[adverbs], [prepositions], [conjunctions], and [interjections].

This sentence contains words from all eight parts of speech. Can you identify them?
Hey! My personal diary is not for your eyes or hers.


** Parts of Speech 						      :drill:
Hey! My personal diary is not for your eyes or hers.

_Hey_ is an [interjection]. It shows strong feeling.

_My_ is a possessive [pronoun] used as an [adjective]. It takes the place of my name.
_Personal_ is an [adjective] that tells what kind.
_Diary_ is a [noun]. It names the book.
_Is_ is the [verb]. It is a be [verb] and does not show action.


** Parts of Speech 						      :drill:
Identify the parts of speech used below:

_Hey!_  My personal diary is not for your eyes or hers. [Interjection]
_Not_ is always an [adverb] (even if it is contracted to n't).
_For_ is a [preposition]. It shows the relationship of its objects to the rest of the sentence.
_Your_ is a possessive [pronoun] used as an [adjective].
_Eyes_ is a [noun]. It is the first part of the compound object of the preposition.
_Or_ is a [conjunction]. It connects the two objects of the preposition.
_Hers_ is also a possessive [pronoun]. It is the second object of the preposition.


** Parts of Speech 						      :drill:
Each part of speech has a special [function].


** Parts of Speech 						      :drill:
[Nouns] name persons, places, things, or ideas.


** Parts of Speech 						      :drill:
[Pronouns] take the place of nouns.


** Parts of Speech 						      :drill:
[Verbs] show action or state of being.


** Parts of Speech 						      :drill:
[Adjectives] describe or modify nouns or pronouns.


** Parts of Speech 						      :drill:
[Adverbs] modify verbs, adjectives, or other adverbs.


** Parts of Speech 						      :drill:
[Prepositions] show relationships between words in a sentence.


** Parts of Speech 						      :drill:
[Conjunctions] join words or groups of words together.


** Parts of Speech 						      :drill:
[Interjections] command attention or express strong feelings.


** Parts of Speech 						      :drill:
Not all words have more than one use, but many can be used differently. The role 
of the word in a sentence determines its part of speech.

Notice the different uses of the word light in this sentence.
Turn the light off and light the fire while I check the light meter for the photograph.

The first light is a [noun]. It names something.
The second light is a [verb]. It shows action.
The third light is an [adjective]. It tells what kind of meter.  


** Parts of Speech 						      :drill:
Nouns are usually easy to identify because they name [persons], [places], [things], or [ideas].

** Parts of Speech 						      :drill:
Nouns that refer to any one of a group of the same items are [common] nouns.

Nouns that refer to specific persons, places, or things are [proper] nouns. 
[Proper] nouns always begin with [capital] letters.


** Parts of Speech 						      :drill:
[Pronouns] are used in the place of nouns. The antecedent of a [pronoun] is the noun that the [pronoun] replaces.


** Parts of Speech 						      :drill:
Pronouns are necessary because the same [noun] is often referred to several times in the 
same sentence or paragraph. Pronouns simplify sentences by making them less [awkward] and monotonous.


** Parts of Speech 						      :drill:
Notice the repetition of nouns in this paragraph.

Our family went on a trip to the beach. _The trip_ was fun. _The family and I_ went swimming. 
_The family's_ next trip will be to the mountains. _That trip_ will be fun, too!

Now look at this paragraph using pronouns.

Our family went on a trip to the beach. [It] was fun. [We] went swimming. 
[Our] next trip will be to the mountains. [It] will be fun, too!


** Parts of Speech 						      :drill:
Most [verbs] express action. This means they show that a [subject] does something.
Joe saw a tree.


** Parts of Speech 						      :drill:
A verb that does not express action expresses the condition of the [subject].
Joe is kind.

This verb connects Joe and kind but does not express action.  It is a [linking verb].


** Parts of Speech 						      :drill:
It is not always possible to express everything about a noun with only one word.  
A writer must have words that describe a particular item. This is the purpose of 
an [adjective]. It describes or tells something about a [noun].


** Parts of Speech 						      :drill:
Look how [adjectives] modify the description of a cat.

The cat cried.
The large, hungry cat cried.
The large, hungry, mean, striped cat cried.

[Adjectives] tell which one, what kind, and how many about nouns and [pronouns].


** Parts of Speech 						      :drill:
[Adverbs] also change or modify words. As the name implies, [adverbs] are added to verbs. 
They change or modify verbs by telling when, [where], how, in what manner, or to what extent.

** Parts of Speech 						      :drill:
Although [adverbs] are added to verbs, they do not have to be placed directly [beside] the verb in a sentence.

** Parts of Speech 						      :drill:
Adverbs can also change or modify [adjectives] or other [adverbs]. 

** Parts of Speech 						      :drill:
Can you identify the adverbs that modify an adjective and an adverb in this sentence?

Washington's men must have been really nervous as they rowed extremely quietly across the Delaware.

[Really] is an adverb that modifies the adjective [nervous]. 
[Nervous] is an adjective that modifies the noun [men].

[Extremely] is an adverb that modifies the adverb [quietly]. 
Remember, [quietly] modifies the verb [rowed].


** Parts of Speech 						      :drill:
[Prepositions] show the relationship of words to other parts of the sentence. 

** Parts of Speech 						      :drill:
Prepositions usually relate to [nouns] or [pronouns]. 

** Parts of Speech 						      :drill:
Prepositions always have an [object]. 

** Parts of Speech 						      :drill:
The preposition and its object (and any words between the two) are called a [prepositional phrase].

I walked _toward the house_.
I walked _around the house_.
I walked _through the house_.
I walked _into the house_.


** Parts of Speech 						      :drill:
Words that join words or groups of words are called [conjunctions]. 

** Parts of Speech 						      :drill:
Words that [join] words or groups of words are called conjunctions. 

There are three kinds of conjunctions:
[coordinating] (and, or, but, nor, for, yet, so)
[correlative] (both/and, not only/but also, neither/nor, either/or, whether/or)
[subordinating] (Subordinating conjunctions will be discussed later in a lesson on clauses.)


** Parts of Speech 						      :drill:
Our language would not be complete unless it offered the ability to express strong 
or sudden emotion. [Interjections] serve that purpose as a part of speech.

** Parts of Speech 						      :drill:
Interjections are not related to the other parts of speech. The word interjection 
comes from a Latin term that means "to throw between." Interjections are "[thrown into]" 
a sentence, usually to express [emotions] such as joy, disgust, excitement, or enthusiasm. 

They are sometimes called [exclamatory] words.


** Parts of Speech 						      :drill:
Interjections command attention. Strong interjections are followed by [exclamation marks] 
to add emphasis. Mild interjections are followed by [commas] unless they come after the sentence.

Listen, did you hear that? (Mild interjection)

Did you hear that? Listen! (Mild interjection)

Help! My house is on fire! (Strong interjection)


** Parts of Speech 						      :drill:
Remember: Every word in the English language falls into at least one of the 
[eight] [parts] of speech. If you understand the function of each word in a sentence, 
the principles of grammar will be easy to master.

Learn the parts of speech as you would learn simple mathematical facts. 
You will rely on the use of these concepts throughout your life.


** Nouns 1 							      :drill:
A noun is the part of speech that names [people], [places], [things], or [ideas].
[person]: Rachel
[place]: Michigan
[thing]: vegetable
[idea]: anger

** Nouns 1 							      :drill:
Identify each noun in the following sentences as a person, place, thing, or idea.

Cartographers ([persons]) have created a grid system ([thing]) to help us find places ([places/things]) on maps ([things]).

** Nouns 1 							      :drill:
Identify each noun in the following sentences as a person, place, thing, or idea.

They drew horizontal lines ([things]) on the grid ([thing]) as lines ([things]) of latitude ([things]).


** Nouns 1 							      :drill:
When a noun names any one of a group of the same items, it is called a [common] noun.

These are examples of some [common] nouns:
sky, day, job, youth, chair, tree, dog, table


** Nouns 1 							      :drill:
If a noun names a particular person, place, or thing, it is called a [proper] noun. 
A [proper] noun always begins with a capital letter.

These are some examples of [proper] nouns:
St. Bernard, Christmas Day, Lake Ontario, Spain

** Nouns 1 							      :drill:
Sometimes nouns are [common], and sometimes they are [proper].

** Nouns 1 							      :drill:
Notice the common and proper nouns in this sentence.
The lake ([common]) we're going to is Lake Ontario ([proper]).

** Nouns 1 							      :drill:
There is also another classification for nouns.

Nouns can be either [concrete] or abstract.

** Nouns 1 							      :drill:
Nouns can be either concrete or [abstract].

** Nouns 1 							      :drill:
[Concrete] nouns are nouns that can be seen, smelled, felt, tasted, or heard. 
In other words, [concrete] nouns can be experienced by one or more of the five [senses].
Rain fell on the red rose.


** Nouns 1 							      :drill:
Some nouns cannot be experienced by the five [senses].

Nouns such as joy, hate, anger, happiness, rudeness, patience, and moderation are called [abstract] nouns.

You can feel happy, but you can't touch happy.


** Nouns 1 							      :drill:
Identify the nouns in this sentence as common or proper and concrete or abstract.

Honesty, telling the truth, is an admirable quality.

Honesty is a [common], [abstract] noun.
Truth is a [common], [abstract] noun.
Quality is a [common], [abstract] noun.


** Nouns 1 							      :drill:
Here are some commonly used [abstract] nouns:
love, rage, bravery, shame, guilt, curiosity, hate, courage, honor, sorrow, tact, 
happiness, anger, insecurity, valor, shrewdness, shyness, cleverness, joy, fear, pride
intuition, laziness, silliness


** Nouns 1 							      :drill:
Whether a noun is common or proper, concrete or abstract, it serves the same function in a sentence.

A noun names [persons], [places], [things], or [ideas].


** Nouns 1 							      :drill:
A [noun] is a part of speech that names people, places, things, or ideas.


** Nouns 2 							      :drill:
[Plural] nouns name more than one person, place, thing, or idea. Let's look at some of the basic rules for making nouns [plural].

Add -s to most [singular] nouns to make them [plural].

book(s)
girl(s)
store(s)

** Nouns 2
Make the following nouns plural:

church [churches]
box [boxes]
waitress [waitresses]


** Nouns 2 							      :drill:
Make the following nouns plural:

turkey [turkeys]
key [keys]
toy [toys]
story [stories]
fairy [fairies]
salary [salaries]


** Nouns 2 							      :drill:
Add [s] to nouns that end with o and have another vowel immediately before 
the o to make them plural. Add [s] to musical terms that end in o.

rodeo [rodeo(s)]
solo [solo(s)]
banjo [banjo(s)]


** Nouns 2 							      :drill:
Test yourself. Write the plural form of each of these words.

city [cities]
state [states]
address [addresses]
piano [pianos]
stereo [stereos]


** Nouns 2 							      :drill:
Some nouns have special rules for forming their plurals.

Add [-s] to many nouns that end in f, fe, or ff.

cliff [cliff(s)]
chief [chief(s)]
safe [safe(s)]

Some nouns change the f or fe to [v] and add -es.

leaf [(leaves)]
wife [(wives)]
knife [(knives)]


** Nouns 2 							      :drill:
Some nouns are the same plural as they are singular.

deer
Chinese
moose


** Nouns 2
Add -s to nouns that end with ful.

spoonful(s)
basketful(s)
cupful(s)


** Nouns 2 							      :drill:
Make the most important word plural in compound nouns.

father-in-law [fathers-in-law]
attorney general [attorneys general]
flowerpot [flowerpots]

** Nouns 2 							      :drill:
Simply add [-s] to numbers and letters to make them plural.
3s    Bs

** Nouns 2 							      :drill:
Write the plural form of these words.

belief [beliefs]
shelf [shelves]
series [series]
sister-in-law [sisters-in-law]
20 [20s]


** Nouns 2 							      :drill:
Nouns can also show ownership or possession. There is one basic rule for forming [possessive] nouns.

Always add ['s] to nouns to make them [possessive] unless the noun is plural and already ends in s. In this case, add just an apostrophe.

men [(men's)]
John [(John's)]
boys [(boys')]
princess [(princess's)]
bosses [(bosses')]


** Nouns 2 							      :drill:
Decide whether these nouns are singular, singular possessive, plural, or plural possessive.

women [(plural)]
shirts [(plural)]
child [(singular)]
actress's [(singular possessive)]
child's [(singular possessive)]


** Nouns 2 							      :drill:
Decide whether these nouns are singular, singular possessive, plural, or plural possessive.

men's [(plural possessive)]
witnesses' [(plural possessive)]
calves' [(plural possessive)]
girls [(plural)]
mouse's [(singular possessive)]


** Nouns 2 							      :drill:
[Plural] nouns name more than one person, place, thing, or idea.


** Nouns 2 							      :drill:
Here are the basic rules for making nouns plural:

Add [-s] to most singular nouns.

Add [-es] to nouns ending in ch, s, sh, ss, x, or z.


** Verbs 1 							      :drill:
You have learned that verbs show action or state of being.

    Doctors use X-ray machines to find broken bones.

The verb in this sentence shows [action].

    A magnifying glass is a simple microscope.

This verb shows [state] of [being].


** Verbs 1 							      :drill:
State of being verbs are also called [linking] verbs because they [link] the subject to another word.

** Verbs 1 							      :drill:
There are nineteen [linking] verbs. If you divide them into three groups, they are easy to remember.

** Verbs 1 							      :drill:
There are seven _be_ verbs:
be, am, is, are, was, were, [been]

** Verbs 1
The verbs that express the action of the five [senses] can also be used as [linking] verbs.
look, smell, feel, taste, sound

** Verbs 1 							      :drill:
There are seven more linking verbs. 
These verbs belong to an odd group that we can call by the acronym BRAGSST. 

B = [become]      
R = [remain]        
A = [appear]    
G = [grow]
S = [seem]
S = [stay]
T = [turn]

** Verbs 1 							      :drill:
Every verb has [four] principal parts.

** Verbs 1 							      :drill:
Every verb has four principal parts: [present], present participle, [past], and past participle.

** Verbs 1 							      :drill:
Every verb has four principal parts: present, [present participle], past, and [past participle].

** Verbs 1 							      :drill:
begin
beginning
began
begun
The [present] is the basic form of the verb.
The [present] [participle] is the ing form of the present.
The [past] ends in d, ed, t, n, or en. It never has a helper.
The [past] [participle] always has a helper.

** Verbs 1 							      :drill:
Sometimes a verb's past and past participle are formed irregularly by either 
changing the spelling of the word or leaving the word in its basic form.

| Present | Past Participle | Past   |
|---------+-----------------+--------|
| do      | [done]          | [did]  |
| eat     | [eaten]         | [ate]  |
| go      | [gone]          | [went] |
| set     | [set]           | [set]  |


** Verbs 1 							      :drill:
When a verb has two or more words, it is called a [verb phrase].

John has gone.
(two-word verb phrase)

John will be going.
(three-word verb phrase)


** Verbs 1 							      :drill:
The [last] verb in the verb phrase is the main verb.

John has gone.
[Gone] is the main verb. Has is a helping or [auxiliary] verb.

John will be going.
[Going] is the main verb. Will and be are helping or [auxiliary] verbs.


** Verbs 1 							      :drill:
There are four groups of helping or auxiliary verbs. Every helping or auxiliary verb must come from one of these groups.

The [be] group of helping verbs is: am, is, are, was, were, being, been. 
These verbs are not linking verbs when they act as helping verbs, although they may help a linking verb.

(was going = action verb phrase)
(was becoming = linking verb phrase)


** Verbs 1 							      :drill:
The [have] group of helping verbs = have, has, had.

The [do] group of helping verbs = do, does, did.

A modal auxiliary verb is used with a main verb to indicate necessity, obligation, 
permission, or possibility. These include words such as can, could, shall, should, 
will, would, may, might, must, and have to.

Remember: These [four] groups are all of the helping verbs. There are no others.


** Verbs 1 							      :drill:
What is the verb phrase in this sentence?

You did not exactly tell the truth.

The verb phrase is [did tell].

[Not and exactly] do not fall into one of the four groups of helping verbs, so they 
cannot be helping verbs, even though they come between the two parts of the verb.


** Verbs 1 							      :drill:
There are some tricky verbs that you must learn. 
_Sit_ (which means to [take a seat]) is often confused with _set_ (which means to [put or place]).

The four principal parts of sit are:
sit, sitting, sat, sat

The four principal parts of set are:
set, setting, set, set


** Verbs 1 							      :drill:
Which would be correct in these sentences?

He (set, sat) on the edge of his chair.  [sat]

(Set, Sit) the pie on the windowsill to cool.  [Set]


** Verbs 1 							      :drill:
Another set of tricky verbs to watch for are lie and lay. 
_Lie_ means to rest or recline. 
_Lay_ means to put or place.

The four principal parts of lie are: lie, lying, lay, lain
The four principal parts of lay are: lay, laying, laid, laid

(Lie, Lay) [Lay] the quilt on the bed before you (lie, lay) [lie] down.


** Verbs 1 							      :drill:
Which would be correct in the following sentences?

I have (lain, laid) the floor tile.  [laid]

She cannot play because she is (laying, lying) down.  [lying]


** Verbs 1 							      :drill:
Rise and raise also often present a problem. 
_Rise_ means to [go up without help]. 
_Raise_ means to [lift something].

The four principal parts of rise are:
rise, rising, rose, risen

The four principal parts of raise are:
raise, raising, raised, raised


** Verbs 1 							      :drill:
Which word would be correct in these sentences?

He (raised, rose) from his chair to protest. [rose]

Four people (rose, raised) their hands. [raised]



** Verbs 2 							      :drill:
Every verb has four principal parts:
[present]
[present participle]
[past]
[past participle]


** Verbs 2 							      :drill:
[Regular] verbs only change endings to form different tenses. The base word stays the same.

| Present | Present Participle | Past    | Past Participle |
|---------+--------------------+---------+-----------------|
| work    | working            | worked  | worked          |
| carry   | carrying           | carried | carried         |
| slip    | slipping           | slipped | slipped         |


** Verbs 2 							      :drill:
[Irregular] verbs change the spelling of the base word or do not change at all.

| Present | Present Participle | Past | Past Participle |
|---------+--------------------+------+-----------------|
| fall    | falling            | fell | fallen          |
| bid     | bidding            | bid  | bid             |
| go      | going              | went | gone            |


** Verbs 2 							      :drill:
It is time for you to test yourself. 
Name the four principal parts of these verbs; then tell if they are regular or irregular verbs.

| Verb  | Principal Parts                  | Type        |
|-------+----------------------------------+-------------|
| write | write, writing, wrote, written   | [irregular] |
| walk  | [walk, walking, walked, walked]  | regular     |
| begin | [begin, beginning, began, begun] | [irregular] |
| see   | [see, seeing, saw, seen]         | [irregular] |
| open  | [open, opening, opened, opened]  | [regular]   |
| know  | [know, knowing, knew, known]     | [irregular] |


** Verbs 2 							      :drill:
The four principal parts of verbs are used to form the tenses. _Tense means time_. 

There are three basic (simple) tenses. (present, past, future)

** Verbs 2
There are three basic (simple) tenses.

| Tense           | Meaning                   | Example       |
|-----------------+---------------------------+---------------|
| [Present] tense | action now                | I [go].       |
| Past tense      | action [already happened] | I went.       |
| [Future] tense  | action [will happen]      | I [shall] go. |


** Verbs 2 							      :drill:
Learn the following formulas to help you form the simple tenses:

The [present] tense = the present part.
I know your name.

The [past] tense = the past part.
I knew your name.

The future tense = [shall/will] + the present part.
I shall know your name.


** Verbs 2 							      :drill:
Use [shall] with the first person (I, we) unless you are showing determination or making a promise; then use [will].

I [shall] go to the movie tonight.
I promise I [will] go to the movie tonight.

Use [will] with the second and third person (you, he, she, it, they) unless you are showing determination or making a promise; then use [shall].

He [will] go to the movie tonight.  
He promises he [shall] go to the movie tonight.


** Verbs 2 							      :drill:
There are three perfect tenses: present perfect, past perfect, and future perfect.

The present perfect tense has two main functions. It expresses an [action] that began in the past and continues to the [present].
I have gone to school all my life.

It also expresses an action that is now complete but without any mention of when it was completed.
I have eaten dinner.


** Verbs 2 							      :drill:
The past perfect tense expresses an action that happened in the [past] before another past [action].
I had gone to school before the bus arrived.

The future perfect tense expresses an action that will be [finished] before a stated time in the [future].
I shall have gone to school by the time my sister wakes.


** Verbs 2 							      :drill:
The present perfect tense = have/has + past participle.
I have known.  
He has known.

The past perfect tense = had + past participle.
I had known.

The future perfect tense = shall/will + have/has + past participle.
I shall have known.


** Verbs 2 							      :drill:
[Conjugation] is a big word that means to list all the verb forms of a verb according to tense.

[Conjugation] of the verb: _See_

| Present           | Past             | Present perfect       |
|-------------------+------------------+-----------------------+
| We see.           | I saw.           | I have seen.          |
| You see.          | You saw.         | You have seen.        |
| They see.         | He, she, it saw. | He, she, it has seen. |
| I see.            | We saw.          | We have seen.         |
| You see.          | You saw.         | You have seen.        |
| He, she, it sees. | They saw.        | They have seen.       |

** Verbs 2 							      :drill:
Determine the tense of the following verbs in the sentences below.

Scientists study living and nonliving matter. [study = present tense (present tense = present part)]

They have learned that everything is made up of matter. [have learned = present perfect (present perfect tense = have/has + past participle)]

They found that the basic building blocks of matter are atoms. [found = past tense (past tense = past part)]

Further study has shown that the number of protons and electrons in an atom determines the element. [has shown = present perfect tense (present perfect tense = have/has + past participle)]


** Verbs 2 							      :drill:
Since tense shows [time], every verb in a sentence or paragraph should normally be in the [same] tense.

Scientists know living things depend on the existence of oxygen. (Both verbs are in the present tense.)

Some (but very few) shifts in tense are necessary.

Scientists know that they will learn more about life in the future.

Know is present tense; will learn is future tense. This is a necessary [shift in tense].


** Verbs 2 							      :drill:
Are the shifts in tense in these sentences necessary?

Living things are able to grow and will respond to stimuli.  [No]

All living things reproduce and had performed certain chemical activities.  [No]


** Verbs 2 							      :drill:
This sentence contains an (necessary, unnecessary) [unnecessary] shift in tense.

All living things reproduce and had performed certain chemical activities.

** Verbs 2 							      :drill:
Does this sentence contain a shift in tense?

All living things reproduce and perform certain chemical activities.  [No]


** Verbs 3 							      :drill:
The verb is the part of speech that expresses action or makes a statement about the condition of the subject.

Most verbs [express action] and are called [action] verbs.


** Verbs 3 							      :drill:
Some verbs make a statement about the condition of the subject. These verbs are [linking] verbs.

[Linking] verbs do not show action. Instead, they act like the [links] (individual circles) in a chain. 

They connect the subject to something that comes after the verb. 

Sara is a student.

Sara and student are the same person. Is links them together. Is does not tell anything Sara does.


** Verbs 3 							      :drill:
Sara was lonely.

In this sentence, lonely describes Sara. It is a special kind of adjective. 

Was [links] the adjective (lonely) with the subject (Sara), but it does not tell anything that Sara did.


** Verbs 3 							      :drill:
Jeff is in his room.

Linking verbs can also connect a [prepositional] phrase telling where to the subject. 

The prepositional phrase (in his room) tells the location of the subject (Jeff).


** Verbs 3 							      :drill:
A [transitive] verb always has a [noun] that receives its action.

Robert threw the ball.

The ball is the noun, the thing that was thrown. Ball receives the action of threw. Therefore, threw is transitive.

In this sentence, ball is called a direct object. A direct object comes after a transitive action verb and receives the action.

A direct object cannot be used after a [linking] verb. Since direct objects receive the action, they can only be used after [action] verbs.


** Verbs 3 							      :drill:
Some action verbs do not have a direct object. They are called [intransitive] verbs.

Jim sat down.

The flower bloomed.

In each of these sentences, the subject does an action, but the subject doesn't do the 
action to something. These sentences do not have direct [objects], so the verbs are [intransitive].


** Verbs 3 							      :drill:
Which of these sentences has an intransitive verb?

Jeremy ran all the way home.
Jeremy plays the trombone.

In the first sentence, [ran is intransitive. All the way home tells where or how much, but it doesn't tell what he ran.]

In the second sentence, [plays is transitive because it has a direct object. Trombone tells what he plays. It receives the action of the verb.]


** Verbs 3 							      :drill:
Are the verbs transitive or intransitive in these sentences?

I dropped my pencil. [(transitive: the direct object is pencil)]

Jill and Helen sing. [(intransitive: no direct object)]

Every day Mike goes to the store. [(intransitive: no direct object)]

Hannah ate her lunch. [(transitive: the direct object is lunch)]


** Verbs 3 							      :drill:
Remember that a [transitive] verb has a direct [object], a word that the action of the verb is done to. 
[Intransitive] verbs do not have an [object].

Also remember that you cannot have a direct object after a linking verb because linking verbs do not show [action].

Are linking verbs transitive or intransitive?  [intransitive]


** Verbs 3 							      :drill:
Linking verbs are [intransitive]. They do not show an action, so they cannot have direct objects.


** Verbs 3 							      :drill:
Let's review what you have learned so far about verbs:

Verbs can be [action] or [linking].
Linking verbs are always [intransitive].
Action verbs may be [transitive] or [intransitive].
[Transitive] verbs have a direct object.
[Intransitive] verbs do not have a direct object.


** Verbs 3 							      :drill:
Now let's talk about another characteristic of verbs.

Verbs can be used in the active voice or the [passive] voice.

Tracy broke the dish.
The dish was broken by Tracy.

As you can see, these sentences mean the same thing, but they are written in different ways. 
In the first sentence, the subject (Tracy) did the action of the verb (broke). 
This is called active voice. 

When the subject does the action of the verb, the verb is in [active voice].


** Verbs 3 							      :drill:
Tracy broke the dish.
The dish was broken by Tracy.

In the second sentence, the subject (dish) does not do the action. Instead, the action happens or is done to the [subject].

This is called [passive voice]. Whenever someone or something besides the subject does the action of the verb, the verb is in passive voice.


** Verbs 3 							      :drill:
The dish was broken by Tracy.

Notice that the passive verb began with was and ended with the past participle.

Passive verbs must have a be verb (am, is, are, was, were, been) and end with the past participle form of the main verb. 


** Verbs 3 							      :drill:
The memo was typed by Ted.
The phone was dialed by Sue.
The students were seen by their teacher.
Lunch was eaten at noon.
The television was turned off.
Jenny and Jill are driven to school.
Rice is grown in Japan.

The first three sentences tell [who] did the action. Sometimes sentences with passive voice verbs 
tell who or what does the action of the verb. Usually this is in a [prepositional] phrase that begins with by.


** Verbs 3 							      :drill:
Remember:

Verbs can be [action] or [linking].
[Action] verbs can be transitive or intransitive.
[Linking] verbs are always intransitive.


** Verbs 3 							      :drill:
Verbs can be in the [active] or [passive] voice.

** Verbs 3 							      :drill:
When verbs are in the active voice, the [subject] does the action of the verb.

** Verbs 3 							      :drill:
When verbs are in the [passive] voice, someone or something else does the action to the verb.

** Verbs 3 							      :drill:
Passive verbs always begin with a [be] verb and end with the past participle of the main verb (was seen, is seen, were seen).


** Verbs 4 							      :drill:
If someone is making progress, would you say that they are:

going nowhere, going backward, or going ahead?


** Verbs 4 							      :drill:
Making progress means moving ahead or continuing to move.

Something that is progressive is continuing to move along.

The Martins are building a new house.

The action of building is in progress.


** Verbs 4 							      :drill:
A writer needs tools that can show this progressive state to a reader.

The tool that can indicate this is called a progressive tense verb.


** Verbs 4 							      :drill:
Writers use progressive tense verbs to show that something is in the process of happening now.


** Verbs 4 							      :drill:
Simply stated, progressive tense means continuing in time.

A progressive tense verb is formed by using a be verb and the present participle. (The present participle is the -ing form of the verb.)


** Verbs 4 							      :drill:
Jill is walking home.

Notice that the verb begins with a be verb, is, and ends with a present participle, walking.


** Verbs 4 							      :drill:
Jill is walking home.

The progressive verb is walking indicates that Jill is in the process of walking home now.


** Verbs 4 							      :drill:
I am working.

He is leaving.

We are walking.

You are smiling.

They are playing.
Each of these sentences uses a verb in the present progressive tense.


** Verbs 4 							      :drill:
A verb plus -ing and a past tense form of to be puts a verb in the past progressive tense.

I was searching for a door.

We were using the computer.


** Verbs 4 							      :drill:
A future progressive tense verb is formed by using shall/will + be + the present participle.

I shall be going to the park.

Mary will be sending her gifts soon.


** Verbs 4 							      :drill:
Progressive verbs are almost always action verbs. Since they are action verbs, they can be used in the active or passive voice.

Here are some examples of active voice verbs in the present progressive tense:

am working
is playing
are walking

So, how would you write a passive voice verb in the progressive tense?


** Verbs 4 							      :drill:


** Verbs 4 							      :drill:
Finally, remember that the passive voice always ends with a past participle:

taught
eaten
done

This past participle is the last word in the passive voice progressive verb:

am being taught
is being eaten
are being done


** Verbs 4 							      :drill:
am being taught
is being eaten
are being done

You use these verbs often. Now you know what to call them. They are present progressive verbs used in the passive voice.

Why are they in the passive voice?


** Verbs 4 							      :drill:
am being taught
is being eaten
are being done

These verbs are in the passive voice because the subject doesn't do the action of the verb. Someone or something else does the action.


** Verbs 4 							      :drill:
I am being taught how to play tennis.
(I don't teach; someone teaches me.)

The warm fresh bread is being eaten quickly.
(Bread doesn't eat; someone eats bread.)

The chores are being done.
(Chores don't do themselves; people do chores.)



	** Verbs 4 							      :drill:
The progressive meaning in passive voice can also be used in the past tense, but it is extremely unusual in the future tense.

We were being watched by the burglars.  

Dinner was being served at 6:30 p.m.


** Verbs 4 							      :drill:
Progressive Verb Form
Main Verb
Present:
is taking
is eating
are talking

take
eat
talk
Past:
lived
sat
was living
were sitting
Future:
will live
shall begin
will be living
shall be beginning


** Verbs 4 							      :drill:
Main Verb
Passive Progressive Verb Form
Present:
take
eat
see
am being taken
is being eaten
are being seen
Past:
was being lived
were being punished
lived
punished


** Verbs 5 							      :drill:
You know that verbs can be either action or linking (state of being).

Action verbs can be transitive (have a direct object) or intransitive (not have a direct object).


** Verbs 5 							      :drill:
Linking verbs are followed by a noun, an adjective, or a prepositional phrase that tells where.

The direct objects (nouns or pronouns) that follow transitive verbs and the nouns or pronouns that follow linking verbs are called complements.

Complement comes from the word complete. These nouns and pronouns complete the verb because they are necessary.


** Verbs 5 							      :drill:
Direct objects are nouns or pronouns that answer who or what after the verb.

Dr. James E. Lovelock developed the hypothesis that the earth is a living system.

Dr. James E. Lovelock developed what? Hypothesis answers this question after the action verb developed. Hypothesis is the direct object.


** Verbs 5 							      :drill:
Find the direct objects in these sentences. Ask whom or what after the verb.

As a living system, the earth provides the ingredients for survival.

In turn, the living things create a stable environment.

Let's analyze the sentences.


** Verbs 5 							      :drill:
As a living system, the earth provides the ingredients for survival.

Provides is the action verb. Ask what after the verb. Provides what? Provides ingredients. Ingredients is the direct object.


** Verbs 5 							      :drill:
In turn, the living things create a stable environment.

Create is the action verb. Create what? Create a stable environment. This example contains an adjective (stable). The adjective does not change the answer, because you are looking for a noun. Objects are always nouns or pronouns.

Create what? Create (an) environment. Environment is the direct object.


** Verbs 5 							      :drill:
Some sentences also have indirect objects. You will only find an indirect object in a sentence with a transitive verb. In other words, there must be a direct object in order for there to be an indirect object.

Indirect objects come between the action (transitive) verb and the direct object. Indirect objects answer to whom, to what, for whom, and for what. If you put one finger on the verb and one finger on the direct object and look between your fingers for a noun or pronoun that answers one of those questions, you will find the indirect object.


** Verbs 5 							      :drill:
Let's begin with a simple sentence.

Jason threw Richard the ball.

First find the direct object. It is clear that Jason did not throw Richard, so Richard is not the direct object.  

Jason threw what? Jason threw the ball. Ball is the direct object.


** Verbs 5 							      :drill:
Jason threw Richard the ball.

Now you can look for the indirect object. Jason threw the ball to whom? He threw the ball to Richard. Richard is the indirect object.

Notice, too, that if you put one finger on the verb and one finger on the direct object, the indirect object is between them.


** Verbs 5 							      :drill:
Now find the direct objects and indirect objects in these sentences.

Dr. Lovelock gave the scientists a new hypothesis to consider.

Dr. Lovelock also gave the world the electron capture detector.

The device gives scientists information about the earth's atmosphere.


** Verbs 5 							      :drill:


** Verbs 5 							      :drill:


** Verbs 5 							      :drill:
Do you remember the linking verbs?
be
am
is
are
was
were
turn
look
smell
taste
sound
feel
stay
become
remain
appear
grow
seem
been
Linking verbs can have two kinds of complements or completers: predicate nominatives or predicate adjectives.


** Verbs 5 							      :drill:
Predicate nominatives are nouns or pronouns that follow the linking verb and rename or identify the subject of the sentence. They answer the questions who or what after the linking verb.

Lovelock is a biologist.

Lovelock is what? The noun biologist renames Lovelock and answers the question what after the linking verb is. Biologist is the predicate nominative.


** Verbs 5 							      :drill:
Find the predicate nominatives in these sentences.

Lovelock is also an inventor.

Data from the electron capture detector was the foundation for Rachel Carson's book Silent Spring.

Let's analyze the sentences.


** Verbs 5 							      :drill:
Lovelock is also an inventor.

Lovelock is what? Inventor is the noun that identifies Lovelock and answers the question what after the linking verb is. Inventor is the predicate nominative.

Data from the electron capture detector was the foundation for Rachel Carson's book Silent Spring.

Data was what? Data was foundation. Foundation is the predicate nominative.


** Verbs 5 							      :drill:
Predicate adjectives are adjectives that follow the linking verb and describe or modify the subject of the sentence.

Other scientists are unsure about Lovelock's hypothesis.

Notice that unsure tells something about the scientists. It describes them. Unsure is a predicate adjective.


** Verbs 5 							      :drill:
Find the predicate adjectives in these sentences:

Evolutionary biologists are particularly unhappy with Lovelock's hypothesis.

They remain certain that the hypothesis contradicts the laws of natural selection.

Let's analyze the sentences.


** Verbs 5 							      :drill:
Evolutionary biologists are particularly unhappy with Lovelock's hypothesis.

You must be careful with this sentence, because the word after the linking verb, particularly, does not describe biologists. It is not a predicate adjective.


** Verbs 5 							      :drill:
Evolutionary biologists are particularly unhappy with Lovelock's hypothesis.

However, unhappy does tell something about the biologists. They are unhappy biologists. Unhappy is the predicate adjective.

They remain certain that the hypothesis contradicts the laws of natural selection.

Certain describes they (the evolutionary biologists.) Certain is a predicate adjective.


** Verbs 5 							      :drill:
Finally, linking verbs can be completed by prepositional phrases telling where. What are those phrases in the following sentences?

Dr. Lovelock was in the lecture hall.
The biologists stayed in their laboratory.
Mr. Williams is on the phone right now.

Dr. Lovelock was in the lecture hall.
The biologists stayed in their laboratory.
Mr. Williams is on the phone right now.

These prepositional phrases complete their linking verbs.


** Verbs 5 							      :drill:
Remember that linking verbs can be completed by predicate nominatives (nouns or pronouns), predicate adjectives, and prepositional phrases telling where.

These are also called verb complements.


** Verbs 5 							      :drill:
Let's review the rules for complements.

Action verbs can have two kinds of complements or completers: direct objects and indirect objects.

A sentence cannot have an indirect object unless it has a direct object. If there is an indirect object, it goes between the verb and the direct object.


** Verbs 5 							      :drill:
Direct objects are nouns or pronouns that answer whom or what after the action verb.

Indirect objects are nouns or pronouns that come between the action verb and direct object and answer to whom, to what, for whom, or for what.


** Pronouns 1 							      :drill:
A pronoun is a word used in place of a noun. The antecedent of the pronoun is the noun that the pronoun stands for.

Maria said she could help me.

In this sentence, Maria is the antecedent. She is the pronoun that takes the place of Maria.


** Pronouns 1 							      :drill:
Maria said she could help me.

Maria is called an antecedent. When you see ante (not anti-) at the beginning of a word, it means before.

Usually the antecedent comes before the noun. It is a lot like the word precede. The antecedent precedes the pronoun.


** Pronouns 1 							      :drill:
When a writer refers to himself or herself, he or she is writing or speaking in first person.

First person pronouns are:

I
me
mine
we
ours
us


** Pronouns 1 							      :drill:
When the writer's words speak to someone, the writing is in second person.

You and yours are the second person pronouns. You and yours are used for both the singular and the plural.

You must eat the last carrot.

You should move your cars to the parking lot.


** Pronouns 1 							      :drill:
You must eat the last carrot.

You should move your cars to the parking lot.

The first sentence is spoken to one person (singular).

The second sentence is spoken to several people (plural).


** Pronouns 1 							      :drill:
These are third person pronouns:
he
she
it
his
her
its
him
her
they
their
them
theirs
These pronouns are used when the writer is speaking or writing about someone.


** Pronouns 1 							      :drill:
Remember:

First person refers to the speaker.

I enjoy reading.

Second person refers to the person spoken to.

Do you like to read?

Third person refers to the person spoken about.

They like to read.


** Pronouns 1 							      :drill:
What are the antecedents to the pronouns in these sentences?

My dog's name is Casady. She likes to run.

Georgia has a new book. It makes her laugh out loud.

Some of the team lost their uniforms. They left them on the bus.

Mikey ate his cereal. He likes it.


** Pronouns 1 							      :drill:
The antecedents are highlighted.

My dog's name is Casady. She likes to run.

Georgia has a new book. It makes her laugh out loud.

Some of the team lost their uniforms. They left them on the bus.

Mikey ate his cereal. He likes it.


** Pronouns 1 							      :drill:
The antecedent of a pronoun can appear anywhere in
a paragraph.

However, until the antecedent is named, the reader can never be sure to which person or thing the pronoun refers.

Try not to keep the reader in suspense. Place antecedents as near as possible to the pronoun.


** Pronouns 1 							      :drill:
In your writing, be sure to tell your readers whom or what you are talking about.

They were hungry and exhausted, but they knew that if their mission was to be a success, they must keep plodding on.

This sentence never identifies they. The message of the sentence is unclear because no antecedent is named.


** Pronouns 1 							      :drill:
They were hungry and exhausted explorers, but they knew that if their mission was to be a success, they must keep plodding on.

Now the sentence has an antecedent. Notice how the message of the sentence becomes much clearer with the addition of an antecedent.


** Pronouns 2 							      :drill:
Let's review the personal pronouns that we discussed in a previous lesson:

First person: I, me, my, mine, we, us, our, ours

Second person: you, your, yours

Third person: she, he, it, him, her, his, hers, its, their, theirs

If we classify these further, they will be easier to remember, and you will understand how to use them correctly in your writing.


** Pronouns 2 							      :drill:
Personal pronouns can be classified in three ways.

Personal pronouns can be classified by case:

subjective
objective
possessive


** Pronouns 2 							      :drill:
Subjective case pronouns are those used as subjects or predicate nominatives.

Objective case pronouns are those used as direct objects, indirect objects, and objects of prepositions.

Possessive case pronouns are those used to show ownership.


** Pronouns 2 							      :drill:
Subjective Case
Singular
Plural
First person:

Second person:

Third person:
I

you

she, he, it
we

you

they


** Pronouns 2 							      :drill:
Remember: Subjective case pronouns are used as subjects and predicate nominatives. A predicate nominative is a noun or a pronoun that comes after a linking verb.

Subject: We will study earth science this year.

Predicate nominative: The winning team was they.


** Pronouns 2 							      :drill:
Objective Case
singular

me

you

her, him, it
plural

us

you

them


First person:

Second person:

Third person:


** Pronouns 2 							      :drill:
Remember: These pronouns are used as objects (direct objects, indirect objects, and objects of prepositions).

Direct object: John gave them to Mary.

Indirect object: John gave her the roses.

Object of preposition: John gave the roses to her.


** Pronouns 2 							      :drill:
Possessive Case
singular

my/mine

your/yours

his/her/hers/its
plural

our/ours

your/yours

their/theirs


First person:

Second person:

Third person:


** Pronouns 2 							      :drill:
Remember: These pronouns are used to show ownership.

That book is yours.

Mine is a little older.

Jim already has his.

NOTE: There are no apostrophes on possessive pronouns.



** Pronouns 2 							      :drill:
Alice scared herself when she looked in the mirror.

Herself refers or reflects back to the subject, Alice. In this sentence, herself is a reflexive compound personal pronoun. This is a long label for a short word.

When the words self or selves are added to personal pronouns, the personal pronouns become compound personal pronouns.


** Pronouns 2 							      :drill:
Because of their meaning, some of these are called reflexive pronouns. Reflexive comes from the same word as reflection.

To see your reflection in a mirror, you must first go to the mirror and stand in front of it. You can't have a reflection without first having a real object to reflect.

Reflexive pronouns are like mirrors, too. If you use a reflexive pronoun, you must also have a noun or a pronoun that is not reflexive.


** Pronouns 2 							      :drill:
When a compound personal pronoun receives the action of a verb (direct object), the pronoun is called a reflexive compound personal pronoun.

In other words, the pronoun reflects or refers back to the subject.


** Pronouns 2 							      :drill:
Compound Personal Pronouns:
Singular Compound Personal Pronouns

myself
yourself
herself
itself
himself
Plural Compound Personal Pronouns

yourselves
themselves
Important Note: There are no such words as theirselves, ourself, or hisself. Drop them from your vocabulary.


** Pronouns 2 							      :drill:
Some compound personal pronouns serve as intensifiers rather than reflectors of action.

I will do it myself.

Mother promised to bake the cake herself.

These compound personal pronouns could actually be dropped from the sentences without changing their meanings. Adding the pronouns to the sentences intensifies (makes greater) the emphasis on the antecedents.


** Pronouns 2 							      :drill:
Another way that personal pronouns can be classified is by person.

Person refers to whether the subject is speaking of himself or herself, is speaking to you, or is speaking about another person.

First person is used to refer to the speaker.
Second person is used to refer to you.
Third person is used to refer to another person.


** Pronouns 2 							      :drill:
Finally, pronouns can be classified by number. Number can be singular or plural.

Singular means one. Plural means more than one.


** Pronouns 2 							      :drill:
They knew that they had struck gold when they realized that they had found the missing vase.

This sentence never identifies they. The message of the sentence is unclear.


** Pronouns 2 							      :drill:
The archaeologists knew that they had struck gold when they realized that they had found the missing vase.

Notice that the message of the sentence changes with the addition of an antecedent. Can you identify the person, number, and case of this pronoun?


** Pronouns 2 							      :drill:
The archaeologists knew that they had struck gold when they realized that they had found the missing vase.

They in this paragraph is a third person, plural, subjective pronoun.


** Pronouns 3 							      :drill:
There are four more groups of pronouns that need to be discussed.

Interrogative pronouns are used to ask questions. There are five interrogative pronouns: who, whose, whom, which, and what.

What is your name?
Whom did you ask to the dance?
Who will bring the sandwiches?
Whose is that book?
Which makes the most sense to you?


** Pronouns 3 							      :drill:
Demonstrative pronouns point out specific persons, places, and things. There are four demonstrative pronouns: this, that, these, and those.

This house is old.
That monkey swung from the bars.
These toys need to be washed.
Those people are late.


** Pronouns 3 							      :drill:
This and that are singular demonstrative pronouns. They point out singular items.

These and those are plural demonstrative pronouns. They point out plural items.

this house
that monkey
these toys
those people


** Pronouns 3 							      :drill:
This and these point out items that are near. That and those point out items that are farther away.

Let's plant these trees in this lot.

That tall tree can be planted with those shrubs.


** Pronouns 3 							      :drill:
There are five relative pronouns. Relative pronouns are used to introduce subordinate clauses. We will take a closer look at subordinate clauses in a later lesson.

The relative pronouns are who, whose, whom, which, and that.


** Pronouns 3 							      :drill:
Relative pronouns look like interrogative pronouns except for that. You can tell these pronouns apart by looking at their function in a sentence.

The boy whose bicycle was wrecked is working to buy a new one.

Whose bicycle was wrecked is the subordinate clause.


** Pronouns 3 							      :drill:
Indefinite pronouns do not always refer to specific persons, places, or things, and they may not have antecedents.

There are three groups of indefinite pronouns: singular, plural, and those that can be either singular or plural.


** Pronouns 3 							      :drill:
These are singular indefinite pronouns:
someone
somebody
something
each
anyone
anybody
anything
either
everyone
everybody
everything
neither
no one
nobody
nothing
one


** Pronouns 3 							      :drill:
Do you notice a pattern? All the pronouns except each, either, and neither end with one, body, or thing.

Everyone is happy about the election.

Nothing spoils John's appetite.

These pronouns are always singular, even though sometimes it doesn't seem that they should be.


** Pronouns 3 							      :drill:
There are five plural indefinite pronouns: both, few, several, many, and others.

Several of the students rode their bikes to school.

Few will make it to the party.


** Pronouns 3 							      :drill:
There are five indefinite pronouns that can be either singular or plural, depending on what they refer to. These indefinite pronouns are: all, any, most, none, and some.

If these pronouns refer to a plural word, they are plural. If they refer to a singular word, they are singular.


** Pronouns 3 							      :drill:
All the boys were riding their bikes.

All refers to boys. Boys is plural, so all is plural.

All the milk has spoiled.

All refers to milk. Milk is singular, so all is singular.


** Pronouns 3 							      :drill:
Name the indefinite pronouns in these sentences.

Everyone is to bring an arachnid to school to study.

None of the spiders were poisonous.

Although both are arthropods, spiders are different from insects.

Some of the insects obtain food by digging; others chew.


** Pronouns 3 							      :drill:
Let's analyze the sentences.

Everyone is to bring an arachnid to school to study.

Everyone is always a singular indefinite pronoun and takes the singular verb is.

None of the spiders were poisonous.

None can be singular or plural. It refers to spiders. Spiders is plural, so none is plural.


** Pronouns 3 							      :drill:
Although both are arthropods, spiders are different from insects.

Both is always a plural indefinite pronoun and takes the plural verb are.


** Pronouns 3 							      :drill:
Some of the insects obtain food by digging; others chew.

Some can be singular or plural. It refers to insects, which is plural, so some is plural. Others is always plural and takes the plural verb chew.



** Adjectives 1 						      :drill:
Adjectives are words that modify or change nouns or pronouns. What mental picture comes to your mind when you read this sentence?

Girls went to town.

If adjectives are added, you can change this sentence (and the mental picture that you see) considerably.


** Adjectives 1 						      :drill:
Girls went to town.

Now let's add some adjectives.

Three pretty girls went to a small, nearby town.

Now we know how many girls (three) and what kind of girls (pretty) went to town. We also know what kind of town (small) and which one (nearby).


** Adjectives 1 						      :drill:
Adjectives answer these questions: which one, what kind, how many.

Which one: first girl, that boy, nearby town

What kind: pretty girls, small town, blue sky

How many: three girls, many buffalo, several boys


** Adjectives 1 						      :drill:
What question (which one, what kind, how many) do the highlighted words in these sentences answer?

Pedro Alvares Cabral claimed the largest country in South America, Brazil, for Portugal.

All of Brazil has a relatively low elevation. Its highest mountain range rises about 9,000 feet.


** Adjectives 1 						      :drill:
Pedro Alvares Cabral claimed the largest country in South America, Brazil, for Portugal.

All of Brazil has a relatively low elevation. Its highest mountain range rises about 9,000 feet.
the
largest
low
highest
mountain
9000
which one
what kind
what kind
which one
what kind
how many


** Adjectives 1 						      :drill:
All of Brazil has a relatively low elevation. Its highest mountain range rises about 9000 feet.

highest which one

mountain what kind

Notice that in this sentence, the noun mountain is used as an adjective to describe range.


** Adjectives 1 						      :drill:
A, an, and the are called articles.

A and an do not refer to any specific person, place, or thing, so they are called indefinite articles.

The refers to specific persons, places, or things, so it is called a definite article.
the house
a house
the apple
an apple


** Adjectives 1 						      :drill:
The demonstrative adjectives (this, that, these, those) look like the demonstrative pronouns, but the difference is that when they act as adjectives, they modify nouns.


** Adjectives 1 						      :drill:
This house is big.

This is an adjective that tells what kind about the house.

This is a big house.

This is the subject and cannot be a modifier. In this sentence, this is a pronoun.


** Adjectives 1 						      :drill:
Proper adjectives are adjectives that are formed by using a proper noun to modify another noun.

When the adjective is part of a title or the proper name of something, it is not considered an adjective. The proper noun functions together as one noun as in the sentence below.

Brazil is bounded by the Atlantic Ocean on the east.


** Adjectives 1 						      :drill:
Brazil is bounded by the Atlantic Ocean on the east.

Atlantic Ocean is the object of the preposition by, so it must be a noun.

Brazil's largest cities are on the Atlantic coast.

Atlantic is a proper adjective that modifies coast by telling which one. Notice that coast is not capitalized. That is because it is not a proper noun. Instead, Atlantic is a descriptive word that modifies coast.


** Adjectives 1 						      :drill:
Are the highlighted words nouns, adjectives, or pronouns?

Brazilians did not want to live in the Amazon's interior.

The Amazon River connects few cities or towns.

The Brazilian government has encouraged people to move there, but few have.


** Adjectives 1 						      :drill:
Brazilians did not want to live in the Amazon's interior.

Brazilians is the subject of the sentence and must be a noun. (After all, Brazilians are real people, and people are nouns.) Adjectives cannot be subjects. Only nouns and pronouns can be subjects.

Amazon's is the possessive case of the noun Amazon.

The possessive case of a noun is always an adjective.


** Adjectives 1 						      :drill:
The Amazon River connects few cities or towns.

Amazon River is the subject of the sentence; therefore it must be a noun.

Few is an adjective that tells how many about cities or towns.


** Adjectives 1 						      :drill:
The Brazilian government has encouraged people to move there, but few have.

Brazilian is a proper adjective modifying the noun government and telling which one about it.

Few is a pronoun, the subject of the verb have.


** Adjectives 1 						      :drill:
Remember: Adjectives that follow linking verbs and modify the subject of the sentence are called predicate adjectives.

The Amazon Basin is wetter than any other part of the country, with eighty inches of rain a year.

The linking verb is connects the adjective wetter with the subject. What kind of Amazon Basin? (wetter Amazon Basin)


** Adjectives 1 						      :drill:
The possessive case of nouns (those that end in 's) are always adjectives.
Cabral's discovery

Brazil's landscapes

the roof's shingles

the cat's paw



** Adjectives 2 						      :drill:
Adjectives are words that describe or modify nouns or pronouns. Adjectives also have another important use. They can be used to compare or contrast people, places, or things.


** Adjectives 2 						      :drill:
The Eiffel Tower in Paris is a tall monument. It is taller than many other monuments. In fact, the Eiffel Tower is one of the world's tallest landmarks.

The highlighted words in this paragraph are adjectives. They modify nouns or pronouns.


** Adjectives 2 						      :drill:
The Eiffel Tower in Paris is a tall monument.

Tall is an adjective that modifies the noun monument.

It is taller than many other monuments.

Taller is a predicate adjective following the linking verb is and modifying the pronoun it.


** Adjectives 2 						      :drill:
In fact, the Eiffel Tower is one of the world's tallest landmarks.

In this sentence, tallest is an adjective that modifies the
noun landmarks.

Three different forms of the adjective tall (tall, taller, tallest) were needed to make the comparisons.


** Adjectives 2 						      :drill:
The basic form of an adjective is sometimes referred to as the positive form.

The three forms of comparison for adjectives are positive, comparative, and superlative.


** Adjectives 2 						      :drill:
Adjectives that compare two things are called comparative adjectives. They usually end in er.
comparative

taller
happier
funnier
larger
greater
positive

tall
happy
funny
large
great


** Adjectives 2 						      :drill:
Three-syllable adjectives and some one or two-syllable adjectives cannot have er added to the end. In this case, put more or less in front of the word to form the comparative.
comparative

more intelligent
more delicious
less fun
more hopeful
positive

intelligent
delicious
fun
hopeful


** Adjectives 2 						      :drill:
The Eiffel Tower is one of the most famous monuments in the world. At 984 feet, the tower is taller than many other monuments.


** Adjectives 2 						      :drill:
Adjectives that are used to compare three or more things are called superlative adjectives. Superlative adjectives usually end in est.
positive

tall
happy
funny
large
great
superlative

tallest
happiest
funniest
largest
greatest


** Adjectives 2 						      :drill:
Three syllable adjectives and some one or two-syllable adjectives cannot have est added to the end. In this case, put most or least in front of the adjective to form the superlative.
positive

intelligent
delicious
fun
hopeful
superlative

most intelligent
most delicious
least fun
most hopeful


** Adjectives 2 						      :drill:
Paris is a famous city.
(positive or basic form of the adjective)

Paris is more famous than the city of Lyon.
(comparative form)

Paris is one of the most famous cities in the world.
(superlative form)


** Adjectives 2 						      :drill:
Test yourself to see if you can correctly use the comparative and superlative forms of a few adjectives. Write the comparative and the superlative degrees of these positive forms on a piece of paper, then go to the next screen to compare your answers with ours.
big
rare
pretty
satisfied
sweet
flexible


** Adjectives 2 						      :drill:
Positive

big
rare
pretty
satisfied
sweet
flexible
Superlative

biggest
rarest
prettiest
most satisfied
sweetest
most flexible
Comparative

bigger
rarer
prettier
more satisfied
sweeter
more flexible
Do your answers look like these? If not, study these comparisons carefully and try again.


** Adjectives 2 						      :drill:
Some adjectives form their comparative and superlative forms irregularly. You will need to learn these adjectives.
Superlative

best
worst
worst
most
most
Comparative

better
worse
worse
more
more
Positive

good
ill
bad
many
much


** Adjectives 2 						      :drill:
Paris is a good city to visit.

Paris is better to visit than Lyon.

Paris is the best city in France to visit.



** Adverbs 1 							      :drill:
Adverbs are words that modify or change verbs, adjectives, or other adverbs.

Do you remember this sentence from a previous lesson?

Three pretty girls walked to a small, nearby town.

Now let's see how we can change the mental picture this sentence gives you by adding adverbs to change or modify the adjectives and verb.


** Adverbs 1 							      :drill:
Three extremely pretty girls walked slowly to a very small nearby town.

Extremely tells to what extent the girls are pretty. Extremely modifies the adjective pretty.

Slowly tells how the girls walked to the town. Slowly modifies the verb walked.

Very tells to what extent the town was small. Very modifies the adjective small.


** Adverbs 1 							      :drill:
Adverbs answer these questions:
To what extent?

How?

When?

Where?

How often?


** Adverbs 1 							      :drill:
Consider these examples:

To what extent? terribly fast, extremely young, brilliantly shining

How? runs fast, plays well, goes quickly

When? goes now, ran yesterday, recently read

Where? went there, looked away, sat nearby

How often? sometimes tells, always sings, talk constantly


** Adverbs 1 							      :drill:
What adverb question (to what extent, how, when, where, how often) do each of the adverbs answer?

In 1991, the Soviet Union's fifteen republics willingly declared independence. Independence came quickly.

With 6,592,800 square miles, Russia is undoubtedly the largest country to come out of the breakup.

Moscow has not always been the capital of Russia.


** Adverbs 1 							      :drill:
The adverbs in the sentences answer these questions:

How? willingly

How? quickly

To what extent? undoubtedly

When? always


** Adverbs 1 							      :drill:
Two negative words should not be used in one sentence.
I did not find no book.
I don't have no paper.
The result is an error called a double negative. To correct the error, remove one of the negatives or change the word to make the correction.
I did not find any book.
I don't have any paper.


** Adverbs 1 							      :drill:
This is a list of commonly used negatives.
neither
no
none
nobody
nowhere
never
barely
hardly
scarcely
no one
nothing
not (n't)
Be careful not to use two of these to express the same thought in a sentence.


** Adverbs 1 							      :drill:
Correct the double negatives in these sentences.

No other city in Russia is not as big as Moscow, which has eight million people.

St. Petersburg, which has four million people, isn't hardly as big as Moscow.

Some countries do not consider Russia a superpower no more.


** Adverbs 1 							      :drill:
Each sentence could be corrected in several ways. Let's look at one way to correct each sentence.

No other city in Russia is not as big as Moscow which has eight million people.

corrected:

No other city in Russia is as big as Moscow, which has eight million people.


** Adverbs 1 							      :drill:
St. Petersburg, which has four million people, isn't hardly as big as Moscow.

corrected:

St. Petersburg, which has four million people, is not as big
as Moscow.


** Adverbs 1 							      :drill:
Russia is not considered a superpower no more.

corrected:

Russia is not considered a superpower anymore.


** Adverbs 1 							      :drill:
In correcting these sentences, did you remember that n't is a contraction of not, which is a negative? That means that any contraction that uses n't is a negative word.

Did you also remember that hardly is a negative?


** Adverbs 1 							      :drill:
Some adjectives can be made into adverbs by adding ly. Sometimes, though, this leads to confusion in their use.
 adverb

beautifully
clearly
happily
adjective

beautiful
clear
happy
Notice that y was changed to i before ly was added to the word happy to make happily.


** Adverbs 1 							      :drill:
If you are not certain about the spelling of a word, always be sure to check the dictionary.


** Adverbs 1 							      :drill:
Choose the adjective or adverb that correctly completes
these sentences.

(Unfortunately, Unfortunate), Russia finds it difficult to use its natural resources.

The reasons are the (vastly, vast) size and the varied climate.


** Adverbs 1 							      :drill:
Most manufacturers are far away from the resources, which makes it (expensively, expensive) to transport them.

To decide whether you need an adjective or adverb, look at what word is modified. If it is a noun or pronoun, use an adjective. Verbs, adjectives, and other adverbs require an adverb.


** Adverbs 1 							      :drill:
Here are the correct choices for each sentence:

Unfortunately - the adverb modifies the verb finds

vast - the adjective modifies the noun size

expensive - the adjective modifies the pronoun it
** Adverbs 2 							      :drill:
Adverbs, like adjectives, have three degrees of comparison.

positive: The house is near.

comparative: Her house is nearer than mine.
(Use the comparative degree to compare two people or things.)

superlative: Of all our houses, his is the nearest.
(Use the superlative degree to compare three or more people or things.)


** Adverbs 2 							      :drill:
The comparative degree is formed by adding er to the positive degree, or by putting more or less in front of the word if er cannot be added.

Er cannot be added to three-syllable words and some one- and two-syllable words.
Comparative

sooner
more smoothly
less carefully
Positive

soon
smoothly
carefully


** Adverbs 2 							      :drill:
The superlative degree is formed by adding est to the end of the positive degree, or by putting most or least in front of the word if est cannot be added.
Positive

soon
smoothly
carefully
Comparative

sooner
more smoothly
less carefully
Superlative

soonest
most smoothly
least carefully


** Adverbs 2 							      :drill:
Some adverbs have irregular forms in the comparative and superlative degrees.
Superlative

worst
best
least
most
Comparative

worse
better
less
more
Positive

badly
well
little
much
Learn these comparisons so that you don't make mistakes in using them.


** Adverbs 2 							      :drill:
John performed badly.
(positive)

James performed worse than John.
(comparative)

Jim's performance was the worst of anyone on the team.
(superlative)


** Adverbs 2 							      :drill:
Look at the degree of comparison for each of these sentences.

The Taj Mahal was built in India early in the 1600s.
(positive degree)

It is one of the most expensively built monuments in the world. (superlative degree)


** Adverbs 2 							      :drill:
Some adjectives and adverbs are often confused.

good and well:

Good is always an adjective that modifies a noun or pronoun.

good book

good idea


** Adverbs 2 							      :drill:
Well is usually an adverb that modifies a verb.

She played the piano well.
He sang well.

Well is an adjective only when it is used to describe someone's health.

Carol felt well enough to go to work.


** Adverbs 2 							      :drill:
Real and Really:

Real is always an adjective. It means genuine.

real gem
real world

Really is always an adverb. It means truly.

really happy
really slow

Do not confuse these two words.


** Adverbs 2 							      :drill:
Sure and Surely:

Sure is always an adjective. It means positive.

Are you sure?
The children are sure about the UFO.

Surely is always an adverb. It means certainly.

surely happy
surely a winner


** Adverbs 2 							      :drill:
Which adverb form in the parentheses is correct for these sentences?

I (sure, surely) wish I could see the Taj Mahal.

Emperor Shah Jahan (certain, certainly) spent a great deal of money building the Taj Mahal.

It was built (well, good) of marble and ivory.


** Adverbs 2 							      :drill:
I surely wish I could see the Taj Mahal.

Surely, the adverb meaning certainly, modifies the verb wish. (To what degree do I wish?)


** Adverbs 2 							      :drill:
Emperor Shah Jahan certainly spent a great deal of money building the Taj Mahal.

Certainly, an adverb meaning truly, modifies the verb spent. (How did he spend?)


** Adverbs 2 							      :drill:
It was built well of marble and ivory.

Well, the adverb, tells how it was built. (It was built well.)





** Prepositions 						      :drill:
A preposition shows the relationship of a noun or a pronoun to another word or words in a sentence.

The Peace Corps is a group of volunteers who work in other countries teaching new skills to the people.

In the prepositional phrases (highlighted), the first word is the preposition and the last word is its object. The preposition relates its object (always a noun or a pronoun) to some other word in the sentence.


** Prepositions 						      :drill:
The Peace Corps is a group of volunteers who work in other countries teaching new skills to the people.

Of volunteers is the first prepositional phrase in this sentence. Of is the preposition. Volunteers is the object. Of relates volunteers to group, telling what kind of group.


** Prepositions 						      :drill:
The Peace Corps is a group of volunteers who work...

If the prepositional phrase tells what kind of group, what do you think the phrase's function is?

If you think it functions as an adjective, you are correct.


** Prepositions 						      :drill:
The Peace Corps is a group of volunteers who work in other countries, teaching new skills to the people.

In the second phrase, in is the preposition. Countries is the object. In relates countries to work, telling where they work. In the last phrase, to is the preposition. People is the object. To relates people to teaching, telling how they are teaching.

The second phrase, in other countries, tells where and the third phrase, to the people, tells how.

What do you think the function of each phrase is? If you think the phrases function as adverbs, you are correct!


** Prepositions 						      :drill:
Did you notice that prepositional phrases begin with a preposition, end with an object, and sometimes include any words between the preposition and the object?

NOTE: All prepositions have objects. If you think you recognize a preposition, but you can't find a noun or pronoun object, then you have an adverb.

To find the object of the preposition, ask whom or what after the preposition.


** Prepositions 						      :drill:
Read this list of prepositions that follows on the next two screens. Learn to recognize them when you see them.
about
after
around
behind
besides
by
during
aboard
across
among
before
beside
but
down
above
against
at
below
between
concerning
except
according
along
because of
beneath
beyond
despite
for
NOTE: Some prepositions have more than one word.


** Prepositions 						      :drill:
from
inside
off
outside
through
toward
unto
within
in
instead
on
over
throughout
under
up
without
in front of
like
out
past
till
underneath
upon
without
in spite of
near
out of
since
to
until
with
Now find the prepositional phrases in the sentences on the
next screen.


** Prepositions 						      :drill:
Africa has the largest number of Peace Corps volunteers.

Developing African countries need the help of this group.

All of the United States except Alaska and Hawaii would fit into Africa nearly four times.

The equator passes through Africa.

A few miles from the equator, however, are mountains that are covered with snow year-round.


** Prepositions 						      :drill:
Africa has the largest number of Peace Corps volunteers.

Developing African countries need the help of this group.

Almost all of the United States would fit into Africa nearly four times.

The equator passes through Africa.

A few miles from the equator, however, are mountains that are covered with snow year-round.


** Prepositions 						      :drill:
You may have already discovered that there are two types of prepositional phrases: adjective prepositional phrases and adverb prepositional phrases.

Adjective prepositional phrases modify nouns and pronouns and answer the same questions that one-word adjectives answer (which one, what kind, how many).


** Prepositions 						      :drill:
Adjective prepositional phrase:

Africa has twelve million square miles of total area.

Of total area is a prepositional phrase. Of total area follows the noun miles and modifies it by telling what kind of miles. (What kind of miles? Miles of total area.)


** Prepositions 						      :drill:
Adverb prepositional phrases modify verbs, adjectives, and other adverbs and answer the same questions that one word adverbs answer (how, when, where, to what extent, how often).

Adverb prepositional phrase:

Africa is made up of fifty countries.

Of fifty countries is a prepositional phrase. Of fifty countries modifies the verb made, telling how the country is made. (Is made how? Is made of fifty countries.)


** Prepositions 						      :drill:
If a prepositional phrase comes at the beginning of a sentence, it cannot be an adjective phrase because there is no noun for it to follow.


** Prepositions 						      :drill:
An adjective prepositional phrase will always follow the noun or pronoun it modifies.

The coastline of Africa is somewhat smooth.
(Of Africa follows coastline and modifies it.)

In tropical regions, areas of tall grasslands are called savannas.
(Of tall grasslands follows areas and modifies it.)


** Prepositions 						      :drill:
An adverb prepositional phrase can come anywhere in a sentence, but if it modifies an adjective or adverb, it will usually follow that adjective or adverb.

The Sahara Desert extends from the Atlantic Ocean to the Red Sea.
(From the Atlantic Ocean modifies the verb extends.)

Mount Kilimanjaro is the highest peak in Africa.
(In Africa follows the adjective highest and modifies it.)


** Prepositions 						      :drill:
Find the prepositional phrases in these sentences and tell whether each is an adjective or adverb.

In West Africa, river blindness was a common disease among humans.

The black fly, which flourished along rapidly flowing rivers, was the cause of river blindness.

The fly transmitted microscopic worms to humans.

The worms would produce millions of smaller worms.


** Prepositions 						      :drill:
In West Africa (adverb), river blindness was a common disease among humans (adjective).

The black fly, which flourished along rapidly flowing rivers, (adverb) was the cause of river blindness (adjective).


** Prepositions 						      :drill:
The fly transmitted microscopic worms to humans (adverb).

The worms would produce millions of smaller worms (adjective).


** Prepositions 						      :drill:
Did you notice that there can be an adjective and an adverb phrase in the same sentence?

Check to see what question is being answered and what word the phrase is modifying to determine if a phrase is an adjective or adverb.


** Conjunctions 						      :drill:
A conjunction is a part of speech that is used to join words or groups of words. A conjunction can join sentences, clauses, phrases, nouns, or other words.

Look at some of the different ways conjunctions work and how they join different words or word groups.


** Conjunctions 						      :drill:
Australia is a continent and a country. (nouns)

In 1605, the Dutch discovered the northern tip of Australia and named it Cape York. (verbs)

Abel Tasman discovered New Zealand, and he also discovered the island that would later be called Tasmania. (clauses)

In 1770, after two years of sailing, the persistent and fearless Captain James Cook found the eastern coast of Australia. (adjectives)


** Conjunctions 						      :drill:
There are three kinds of conjunctions: coordinating  conjunctions, correlative conjunctions, and subordinating conjunctions.

A coordinating conjunction is used to join sentence parts that are alike.

This means that the coordinating conjunction can join nouns with nouns, verbs with verbs, adjectives with adjectives, adverbs with adverbs, phrases with phrases, and clauses with clauses.


** Conjunctions 						      :drill:
The coordinating conjunctions are and, or, but, nor, for, yet, and so.

In selecting a coordinating conjunction, a writer must know what kind of relationship is being expressed.


** Conjunctions 						      :drill:
If the relationship is addition, the conjunction should be and. If the writer wishes to express contrast, but or yet should be used. To express a result or effect, the proper conjunction is so.

Reason and cause are expressed by the conjunction for. The conjunction or expresses choice, and negative choice is shown by the use of nor.

The sentences on the next screens demonstrate examples of relationships and the proper conjunctions.


** Conjunctions 						      :drill:
Most of the people who live in Australia today come from Great Britain and Ireland. (addition)

Australia used to have laws forbidding Asians from living there, but those laws were changed in the 1950s and 1960s. (contrast)

New laws allowed Asians to immigrate to Australia, so the number of Asians is growing. (result)


** Conjunctions 						      :drill:
Very little of Australia's land is good for farming, for it gets little rain. (reason)

Only ten percent of the land, however, provides plenty of food for the Australians or for export. (choice)

The Aborigines, the first inhabitants of Australia, would not accept anything from Captain Cook, nor would they give any of their own things to Cook. (negative choice)


** Conjunctions 						      :drill:
Correlative conjunctions are similar to coordinating conjunctions because they also join sentence parts of equal rank.

Correlative conjunctions work in pairs. The pairs are both/and, either/or, neither/nor, not only/but also, and whether/or.

Both kangaroos and koala bears are marsupials and are unique to Australia.

Marsupials eat either plants or flesh.


** Conjunctions 						      :drill:
Neither the platypus nor the spiny anteater is a bird, but they lay eggs.

Not only the emu but also the cassowary, two flightless birds, are native to Australia.

The duck-billed platypus looks as if it can't make up its mind whether it is a duck or a beaver.


** Conjunctions 						      :drill:
A subordinating conjunction is used to connect clauses that are not equal in importance. Subordinate means of less importance or dependent.

A subordinate (dependent) clause depends on the main or independent clause to help it make sense. It cannot stand alone.

An independent clause is a group of words that expresses a complete thought. It can function as a complete sentence.

Find the independent clause and the subordinate clause in the sentence on the next screen.


** Conjunctions 						      :drill:
Because the Great Barrier Reef stretches 1,250 miles along the northeast coast of Australia, it is known as the world's largest coral reef.

The independent clause is: it is known as the world's largest coral reef. It makes sense by itself.

The dependent clause is: Because the great Barrier Reef stretches 1,250 miles along the northeast coast of Australia. It needs the independent clause to complete the thought.


** Conjunctions 						      :drill:
A subordinating conjunction introduces a subordinate clause. Here is a list of commonly used subordinating conjunctions.
after
as long as
before
provided
so that
until
although
as soon as
even if
in order that
than
when
as
as though
even though
if
though
where
as if
because
except
since
unless
whether


** Conjunctions 						      :drill:
Writers may express relationships by choosing certain subordinating conjunctions as follows:
Subordinating Conjunctions

after, before, once, since, until, when, whenever, while

as, because, since

in order that, so that
Relationship

time


reason or cause

result or effect


** Conjunctions 						      :drill:
Relationship

condition

contrast

location

choice
Subordinating Conjunctions

if, even if, provided that, unless

although, even though, though, whereas

where, wherever

rather than, than, whether


** Conjunctions 						      :drill:
Look at the subordinating clauses and the conjunctions that introduce them in these sentences:

After many Aborigines migrated to Australia from Asia, the land bridge that connected the countries was flooded, cutting them off from the rest of the world.

Although there are only 145,000 Aborigines left today, there were probably 300,000 when Captain Cook landed.


** Conjunctions 						      :drill:
Britain used Australia as a penal colony when the Revolutionary War ended its ability to use America as such.

Great Britain sent about 168,000 convicts to Australia while it was a penal colony.


** Conjunctions 						      :drill:
Find the conjunctions in these sentences and tell what kind of conjunction they are.

Life in Australia is much like life in the United States and Canada.

Because Australia is isolated from other continents, the animals may have developed differently.


** Conjunctions 						      :drill:
Many Aborigines were either killed by the Europeans or died of diseases the Europeans brought with them.

Australia is the world's leader not only in the production of bauxite but also in the production of lead.


** Conjunctions 						      :drill:
Life in Australia is much like life in the United States and Canada.

And is a coordinating conjunction joining the two nouns, United States and Canada.

Because Australia is isolated from other continents, the animals may have developed differently.

Because is a subordinating conjunction that introduces the subordinate clause Australia is isolated from other continents.


** Conjunctions 						      :drill:
Many Aborigines were either killed by the Europeans or died of diseases the Europeans brought with them.

Either/or is a correlative conjunction joining the verbs killed and died.

Australia is the world's leader not only in the production of bauxite but also in the production of lead.

Not only/but also is a correlative conjunction that joins in the production of bauxite and in the production of lead.


** Interjections 						      :drill:
An interjection is a word or group of words interjected, or added, into a sentence.

An interjection usually tells strong feeling or sudden emotion such as fear, anger, surprise, or joy. An interjection has no grammatical relation to the rest of the sentence.


** Interjections 						      :drill:
Hooray! It's snowing!

An exclamation point usually follows an interjection, but can sometimes be followed by a comma.


** Interjections 						      :drill:
The interjection is always an independent unit.

This means that the interjection is not considered to be a part of a sentence.

The interjection stands alone.


** Interjections 						      :drill:
These are just a few of the many words that can be used as interjections:
Ah!

Alas, ...

Dear me!
Wow!

Ha! Ha!

Oops!


** Interjections 						      :drill:
Hooray! I've finished my lesson.

Ouch! Get off my foot.

Oh! Oh! The bird ate the worm.


** Interjections 						      :drill:
Sometimes an exclamation point does not follow an interjection.

If the interjection does not seem to stand by itself but seems to be part of the sentence, then the interjection is followed by a comma.


** Interjections 						      :drill:
For example, you might write:

Alas, the boat sank!

Oh well, maybe you will hit the ball next time!


** Interjections 						      :drill:
Sometimes you may use a word as an interjection that is ordinarily a different part of speech.


** Interjections 						      :drill:
For example, you might say:

Nonsense! You can't tell me that. (noun)

Listen! Do you hear the fire alarm? (verb)



** Interjections 						      :drill:
Find the interjection in these sentences.

Whew! I'll never finish peeling all these potatoes.

You are a great person, indeed.

Wow! I just won the sweepstakes.

Aha! I caught you.


** Interjections 						      :drill:
Whew! I'll never finish peeling all these potatoes.

You are a great person, indeed.

Wow! I just won the sweepstakes.

Aha! I caught you.


** Interjections 						      :drill:
Think about emotions or feelings when you are using interjections.


** Sentences 1 							      :drill:
Sentences can be divided into two major parts: the complete subject and the complete predicate.


** Sentences 1 							      :drill:
The simple subject is who or what the sentence is about.

The simple subject of a sentence can be a noun, a pronoun, or a noun phrase.

Hannah is my best friend. (noun)

She loves to read mystery books. (pronoun)

Reading mystery books is her favorite pastime. (noun phrase)


** Sentences 1 							      :drill:
A complete subject includes the noun, pronoun, or noun phrase functioning as the simple subject and all the adjectives or phrases that modify the simple subject.


** Sentences 1 							      :drill:
The skunk under the house would not come out.

The team of astronauts landed on the moon.

The first boy in line received a red lollipop.

The subject is usually placed before the verb. Therefore, the complete subject is usually at the beginning of the sentence.


** Sentences 1 							      :drill:
The predicate is the part of the sentence that tells something about the subject.

The verb is the simple predicate.

The President of the United States will be speaking at the conference today.

Patches of slippery ice covered the sidewalk.


** Sentences 1 							      :drill:
The complete predicate is the verb and all the modifiers that are attached to it, as well as the direct and indirect objects, if the sentence has any.


** Sentences 1 							      :drill:
The President of the United States will be speaking at the conference today.

Patches of slippery ice covered the sidewalk.


** Sentences 1 							      :drill:
It is possible for either the complete subject, the complete predicate, or both to be a single word.


** Sentences 1 							      :drill:
We will arrive late.

The girls in the vocal music production dance.

Birds sing.


** Sentences 1 							      :drill:
Remember, the complete subject is who or what the sentence is about and all the modifiers.

The complete predicate, which includes the verb and all its modifiers, is the part of the sentence that tells something about the subject.


** Sentences 1 							      :drill:
A sentence must have both a subject and a predicate before it can be called a sentence.

It takes both of these sentence parts to express a complete thought or idea.

If either part of the sentence is missing, the words only form a sentence fragment or phrase.


** Sentences 1 							      :drill:
A declarative sentence is simply a sentence that makes a statement. In most declarative sentences, the subject comes before the verb.

Scientists are trying to decide which animals they must protect first from extinction.

This is called normal or natural word order. In natural word order, the subject is before the verb.


** Sentences 1 							      :drill:
An interrogative sentence is one that asks a question.

Interrogative sentences, sentences that begin with here or there, and sentences that begin with negative words have a different word order.

In these sentences, the verb or part of the verb is put before the subject. This is called inverted word order.


** Sentences 1 							      :drill:
How can humans stop the destruction of animal life?

There are many ways humans damage plant and animal life.

Nowhere is the problem worse than in the rainforests.


** Sentences 1 							      :drill:
Are these sentences in natural or inverted order?

There are several ways humans destroy the habitat of animals.

Clearing the land to grow food is one major way that humans destroy animal habitats.

Animals depend on responsible humans to protect them.


** Sentences 1 							      :drill:
There are several ways humans destroy the habitat of animals.
inverted

Clearing the land to grow food is one major way that humans destroy animal habitats.
natural

Animals depend on responsible humans to protect them.
natural


** Sentences 1 							      :drill:
Did you answer correctly? Look for the subject and the verb first. If the subject comes after the verb or any part of the verb, the sentence order is inverted.

There are several ways humans destroy the habitat of animals.

Ways is the subject of the verb are. The verb comes first. The sentence is inverted.


** Sentences 1 							      :drill:
Clearing the land to grow food is one major way that humans destroy animal habitats.

Clearing is the subject of the verb is. The subject comes first in the sentence; therefore, it is in natural order.


** Sentences 1 							      :drill:
Animals depend on responsible humans to save them.

Animals is the subject of the verb depend. The subject comes first. The sentence is in natural order.



** Sentences 2 							      :drill:
When words (parts of speech) are put together in such a way that they express a complete thought, the result is a sentence.

A complete thought leaves no questions to be answered about that thought.


** Sentences 2 							      :drill:
As you have learned, a sentence cannot express a complete thought unless it has a subject and a predicate.

Remember the two basic parts of every sentence. The subject tells what or whom the sentence is about. The predicate is the part of the sentence that tells something about the subject.


** Sentences 2 							      :drill:
Subject

The human body


Muscle, connective, nerve,
and epithelial
Predicate

is made up of four main types of tissue.


are the four kinds of tissue.


** Sentences 2 							      :drill:
Subject

Muscle tissue
Predicate

flexes and relaxes to make the body move.


** Sentences 2 							      :drill:
An incomplete sentence is called a sentence fragment. A fragment is a piece or a part or a whole thing.

Think of a fragment of glass. It is only part of the whole piece of glass.

A sentence fragment lacks either one or both of the basic parts. It lacks either the subject, the predicate, or both.


** Sentences 2 							      :drill:
Is this group of words a sentence or a fragment?

The only kind of tissue in your body.

This group of words tells what the sentence is about, but it does not tell anything about the "what." It is a complete subject without a predicate. It is a fragment.


** Sentences 2 							      :drill:
Let's analyze this complete subject to determine the simple subject.


** Sentences 2 							      :drill:
The subject of a sentence cannot be in a prepositional phrase.

A subject can only be a noun or a pronoun. That leaves only the noun kind to be the simple subject.


** Sentences 2 							      :drill:
Which basic sentence part is missing from this group of words?

Consists of thirty-three separate bones.

This time there is a complete predicate, but no subject. This is another sentence fragment.


** Sentences 2 							      :drill:
Let's analyze the complete predicate to find the simple predicate or verb.
The verb cannot come from the prepositional phrase, so the word consists is the verb, or simple predicate.


** Sentences 2 							      :drill:
There are four classifications of sentences:

Declarative sentences make a statement and end with a period.

Muscle tissue can contract, or shorten.


** Sentences 2 							      :drill:
Interrogative sentences ask a question and end with a question mark.

Did you know that connective tissue supports your body and unites its parts?


** Sentences 2 							      :drill:
Imperative sentences make a command or a request and end with a period.

Look in the mirror and see your epithelial tissue.

Did you notice that this sentence has an understood subject? Imperative sentences always have an understood you as the subject. This means that although the word you is not spoken or written, the sentence is directed at you.


** Sentences 2 							      :drill:
Exclamatory sentences show strong feeling and end with an exclamation mark.

Without nerve tissue, messages would not travel from the brain to the rest of your body!


** Sentences 2 							      :drill:
All four types of sentences, declarative, imperative, interrogative, and exclamatory, must have the basic parts of a sentence to be a complete sentence.

Every complete sentence, no matter what the type, must have a subject and a verb.


** Sentences 3 							      :drill:
You learned previously that a sentence is a group of words with a subject and a predicate that expresses a complete thought.

You also know that the complete subject is the noun that the sentence is about and all of its modifiers. The complete predicate is the verb and all of its modifiers.


** Sentences 3 							      :drill:
Japan
(complete subject)


Japan
(simple subject)
is an archipelago, or group of islands.
(complete predicate)


is
(simple predicate)


** Sentences 3 							      :drill:
A sentence can also be called an independent clause.

Independent indicates that the sentence can stand alone or make sense by itself.

A clause is a group of words that has a subject and a predicate.

Another type of clause is a dependent clause; it can have a subject and predicate but cannot stand alone.

We wear coats in the winter so we can stay warm.
(so we can stay warm cannot stand alone as a complete thought)


** Sentences 3 							      :drill:
Sometimes a sentence might have a compound subject or a compound verb; or perhaps both, but it is still just a simple sentence, or independent clause.

Remember: compound means more than one.

Honshu, Hokkaido, Shikoku, and Kyushu are the four main islands of Japan.

This sentence has a compound subject.


** Sentences 3 							      :drill:
Nearly four thousand smaller islands surround the four larger ones and complete the nation of Japan.

This sentence has a compound predicate. It is still only one sentence.

Let's see what happens when we combine both of these sentences.


** Sentences 3 							      :drill:
Honshu, Hokkaido, Shikoku, and Kyushu are the four main islands of Japan and are surrounded by four thousand smaller islands.
This sentence contains a compound subject and a compound predicate. However, there is still only one sentence.


** Sentences 3 							      :drill:
Test yourself. Determine the compound subject or compound predicate in these sentences.

The four main islands and the smaller ones lie in the North Pacific Ocean.

Mountains rise from the ocean floor and poke their peaks above the water to form the islands.

Japan has half the population of the United States but occupies an area twenty-five times smaller.


** Sentences 3 							      :drill:
The four main islands and the smaller ones lie in the North Pacific Ocean.
(compound subject)

Mountains rise from the ocean floor and poke their peaks above the water to form the islands.
(compound predicate)

Japan has half the population of the United States but occupies an area twenty-five times smaller.
(compound predicate)


** Sentences 3 							      :drill:
Did you notice that the compound subjects have the same verb and the compound verbs have the same subject?
islands and ones lie

mountains rise and poke

Japan has and occupies
This is one way you can determine that there is only one sentence.


** Sentences 3 							      :drill:
Two simple sentences can be joined to form a compound sentence.

Japan has 858 people per square mile.

The United States has only 69 people per square mile.

Japan has 858 people per square mile, and the United States has only 69 people per square mile.


** Sentences 3 							      :drill:
Japan has 858 people per square mile. The United States has only 69 people per square mile.
Each simple sentence has a subject and a predicate, but they each express a complete thought alone.


** Sentences 3 							      :drill:
complete subject

Japan
The United States
complete predicate

has 858 people per square mile
has only 69 people per square mile
simple predicate

has
has
simple subject

Japan
United States


** Sentences 3 							      :drill:
The conjunction is not considered a part of either sentence. It merely connects the two sentences.

Two simple sentences can be joined to form a compound sentence. The two sentences must be connected with a comma and a coordinating conjunction (or a semicolon if the sentences are closely related).

Coordinating conjunctions: and, or, but, nor, for, yet, and so.


** Sentences 3 							      :drill:
Japan was defeated in World War II and left in ruins, but today
it is one of the richest nations in the world.

Japan has few natural resources, so how did it become an economic giant?

Factories bought and imported raw materials; they made them
into high-quality goods and exported them.


** Sentences 3 							      :drill:
Do not join two simple sentences into a compound sentence without some form of punctuation.

This creates a run-on sentence.


** Sentences 3 							      :drill:
Incorrect:

Japan began exporting goods shortly after World War II it used the money from these sales to build new factories.

Correct:

Japan began exporting goods shortly after World War II, and it used the money from these sales to build new factories.


** Sentences 3 							      :drill:
There are other ways of correctly writing the sentences on the previous screen by either letting them remain two simple sentences or by using another coordinating conjunction such as but or yet.

If there is not a subject and a predicate in both sentences or clauses, they are fragments.


** Sentences 3 							      :drill:
A circus usually has three rings, but it can have only two.

This is an example of two independent clauses joined by the coordinating conjunction but.


** Sentences 3 							      :drill:
As your writing develops from simple sentences to compound sentences, be sure that you use each type correctly.

Join simple sentences with the correct coordinating conjunction and the correct punctuation. Avoid run-on sentences and sentence fragments.



** Sentences 4
A diagram is a plan or a sketch that explains something.

A blueprint of a house explains the structure of the house and its respective parts, just as a sentence diagram explains the structure of a sentence and its parts.



** Sentences 4
You should recall that every sentence has two basic parts: the subject and the predicate.

The complete subject includes the simple subject (noun) and all the words that modify or go with it.

The complete predicate includes the simple predicate (verb) and all the words that modify or go with it.



** Sentences 4
Because a sentence has two basic parts, a sentence diagram is divided into two basic parts.



** Sentences 4
First, draw a base line and divide it with a straight vertical line.

The subject and the verb are written on the base line on either side of the dividing line.



** Sentences 4
Modifiers of the simple subject and the simple predicate are written beneath the words they modify.

John ran a mile.



** Sentences 4
John ran a mile.

A is an article adjective that modifies the noun mile. It is written on a slanted line beneath the noun that it modifies.



** Sentences 4
(Predicate adjectives are diagramed in the same way as predicate nominatives.)

The is an article that modifies the noun captain. It is written on a slanted line beneath the noun.



** Sentences 4
John ran the mile quickly.

Quickly is an adverb that tells how John ran, so it modifies the verb. It is written on a slanted line beneath the verb that it modifies.



** Sentences 4
John ran the mile quickly for his team.

For his team is an adverb prepositional phrase that modifies the verb ran. Remember: Adjective prepositional phrases must modify the noun that precedes them. This prepositional phrase has no noun in front of it.

The adverb phrase answers the question why. (Why ran? For his team.)



** Sentences 4
John ran the mile quickly for his team.

Prepositions are placed on slanted lines beneath the word the phrase modifies.

Place the object of the preposition on a straight line parallel to the subject/predicate line. Write any words between the preposition and its object beneath the object on a slanted line. His modifies the object team.



** Sentences 4
John won his team a trophy.

Team is an indirect object and is written on a parallel line beneath the verb. Any words that modify it are written on slanted lines beneath it.

In the written sentence, indirect objects come between the direct object and the action verb, answering to whom, to what, for whom, or for what.



** Sentences 4
Give the trophy to the team.

Place understood subjects in parentheses in the subject position.



** Sentences 4
Now you have a chance to practice what you have learned so far in this lesson. Diagram the
sentence below.

Give yourself a fair chance to try your new skill. Do not go to the next screen until you have given this sentence an honest try. After you have finished, look at the correct diagram to compare your answer with ours.

The trophy was given to the school and placed in the trophy case.



** Sentences 4
We hope your diagram looks like this one.

The trophy was given to the school and placed in the trophy case.



** Sentences 4
Diagramming sentences is simply an exercise that helps you understand the structure of a sentence.

You can improve your diagramming skills by looking for various types of sentences in a newspaper and then trying to diagram them.



** Sentences 5
You already know that a simple sentence or independent clause is a group of words that has a subject and a predicate and makes a complete thought.

The United States is the fourth largest country in the world.



** Sentences 5
You know that a compound sentence is made up of two or more independent clauses joined by a comma and a coordinating conjunction or a semicolon.

The United States has 3,794,083 square miles, but Russia, Canada, and China are still larger.



** Sentences 5
You also know that a subordinate clause is a group of words that has a subject and a predicate but does not make a complete thought. Subordinate clauses can also be called dependent clauses. Subordinate clauses cannot stand alone because they are considered to be sentence fragments.

However, subordinate clauses play an important role in sentence structure because they usually define or further explain another word in the sentence.



** Sentences 5
A complex sentence has one independent clause and one or more subordinate clauses.

Even though the United States has 3,794,083 square miles, Russia, Canada, and China are larger.

The subordinate clause appears in blue. The other clause is an independent clause.



** Sentences 5
A compound-complex sentence has two or more independent clauses and one or more subordinate clauses.

Even though the United States has 3,794,083 square miles, the largest country in the world is Russia (6.6 million sq. mi.), and both Canada (3.8 mil. sq. mi.) and China (3.7 mil. sq. mi.) are also larger than the United States.

The independent clauses are highlighted and connected by a comma and the conjunction and. The subordinate clause that begins with "Even though..." is an adverb clause modifying is.



** Sentences 5
Even though the United States has 3,794,083 square miles, Russia, Canada, and China are larger.

This is an example of an adverb subordinate clause. Adverb clauses begin with some of these subordinating conjunctions:
after
as if
even though
unless
whenever
while
although
because
if
until
where
as
before
since
when
wherever



** Sentences 5
Adverb clauses modify verbs, adjectives, or adverbs within the independent clause. They answer the same questions as one-word adverbs (how, when, where, to what extent, how often, and why).

The United States has 3,794,083 square miles, but Russia, Canada, and China are larger.

Even though is the subordinating conjunction. The adverb clause modifies the predicate adjective larger.



** Sentences 5
When an adverb clause modifies an adjective or an adverb in the independent clause, it usually comes directly after that adjective or adverb. When it modifies a verb, it can be anywhere in the sentence.

When an adverb clause comes before the main clause, it is set off by a comma. When it comes after the main clause, there should not be a comma.



** Sentences 5
The United States has five landform regions which are made up of the coastal plain, the Appalachian region, the interior plains, the Rocky Mountains, and the Pacific region.

This sentence has an adjective subordinate clause. Adjective clauses begin with one of the relative pronouns, who, whose, whom, which, that, and occasionally when or where.



** Sentences 5
The United States has five landform regions which are made up of the coastal plain, the Appalachian region, the interior plains, the Rocky Mountains, and the Pacific region.

Which is the relative pronoun that begins the adjective clause.  The adjective clause modifies the noun regions.

Relative pronouns can function as part of the clause, such as the subject or direct object, but they can also serve simply as introductory words and not function as a part of the clause.



** Sentences 5
Can you tell whether which functions as a part of the adjective clause or is introducing in this sentence?

The United States has five landform regions which are made up of the coastal plain, the Appalachian region, the interior plains, the Rocky Mountains, and the Pacific region.

Which is the subject of the verb are, so it is functioning as a part of the clause.



** Sentences 5
In this sentence, find the adjective clause and then determine the relative pronoun and the clause that it modifies.

The Interstate Highway System, which is the largest highway system in the United States, provides many advantages for travelers.



** Sentences 5
The Interstate Highway System, which is the largest highway system in the United States, provides many advantages
for travelers.

The adjective clause is highlighted. The relative pronoun is which. The adjective clause modifies the noun Interstate Highway System. Which is the subject of the verb is; therefore, it is functioning as part of the clause.



** Sentences 5
Try one more. Find the adjective clause in this sentence and then determine the relative pronoun and the clause that it modifies.

One of the advantages that travelers enjoy is moving quickly from city to city.

(Don't cheat yourself by not trying. This is a learning exercise. If you try, you will be better prepared for the questions.)



** Sentences 5
One of the advantages that travelers enjoy is moving quickly from city to city.

The adjective clause appears in blue. The relative pronoun is that. The adjective clause modifies the noun advantages.

The relative pronoun does not function as part of the clause. It simply introduces it.



** Sentences 5
People who commute to jobs daily usually use the interstate.

Find the adjective clause in this sentence. Then determine the relative pronoun and the clause that it modifies.



** Sentences 5
People who commute to jobs daily usually use the interstate.

The adjective clause appears in blue. The relative pronoun is who. The adjective clause modifies the noun people. The relative pronoun is the subject of the verb commute, so it is functioning as part of the clause.



** Sentences 5
Reread the last three sentences. Some of the adjective clauses are set off with commas.

Being set off with commas indicates that the adjective clauses are nonessential (not necessary) to identify the nouns they modify. They merely give additional information about the noun modified.



** Sentences 5
In an adjective clause that is not set off with commas, it is necessary to identify the noun or pronoun it modifies. If it were not in the sentence, the reader would not know which one about the noun it modifies.

The adjective clause always modifies the noun or pronoun that appears directly in front of it.




loading
Subordinate clauses can also be called dependent clauses. Subordinate clauses cannot stand alone because they are considered to be sentence fragments.

However, subordinate clauses play an important role in sentence structure because they usually define or further explain another word in the sentence.



loading
In other lessons, you have learned about adjective and adverb subordinate clauses. The third type of subordinate clause is the noun clause.

Do you recall that adjective clauses function just as one-word adjectives do? They modify nouns and pronouns. Adverb clauses are used just as adverbs. They modify verbs, adjectives, or adverbs.



loading
You can probably guess, then, that noun clauses function just as one-word nouns do. Noun clauses can function as subjects or objects.

Do you know that Mexico City is the capital of Mexico?

The noun clause is highlighted in the sentence above.



loading
Do you know that Mexico City is the capital of Mexico?

Because this noun clause begins with the relative pronoun that, it looks like an adjective clause.

However, the word right before the clause, know, is part of the verb.



loading
Do you know that Mexico City is the capital of Mexico?

Remember, adjective clauses modify the nouns directly in front of them. If there is a verb in front of the clause, it cannot be an adjective clause.



loading
Noun clauses can function as the subject of an independent clause.

What Hernando Cortes, the Spanish conquistador, did was capture the Aztec Empire.

The complete subject of this sentence, the noun clause, is highlighted. The sentence is talking about what Hernando Cortes did.



loading
Noun clauses can function as direct objects in the independent clause.

Cortes found that the Aztecs were highly skilled in building houses and temples.

This noun clause follows the action verb and answers the question what, just as a direct object does.



loading
Noun clauses can function as objects of prepositions in the independent clause.

Cortes' men were astonished by what they found in Mexico.

This noun clause is the object of the preposition by and answers the question what. Notice that the preposition is not part of the noun clause.



loading
Noun clauses can function as predicate nominatives in the independent clause.

Mexico City is what Cortes named the Aztec capital of Tenochtitlan.

This noun clause follows the linking verb is and renames the subject Mexico City.



loading
Noun clauses can begin with any of these introductory words: who, whose, whom, which, that, when, where, what, whatever, whoever, whomever, and whether.

Since some of these words also introduce adjective and adverb clauses, you must decide carefully what job the clause does in the sentence.

Hint: The words what, whatever, whoever, and whomever only introduce noun clauses.



loading
Let's look at four sentences to see if we can locate the noun clause and determine how it functions in each sentence.

It may help you to look at the sentences and write your answer on paper before looking at the answer and the explanation.



loading
Did you know that the soil beneath Mexico City is eighty-five percent water?

The soil beneath the city is where they get their water.

Whatever water they take out causes the ground to sink.

According to what some experts say, the ground sinks up to one foot in some places each year.



loading
Did you know that the soil beneath Mexico City is eighty-five percent water?

Know is an action verb. The word that introduces the noun clause. Since this noun clause receives the action of the verb, it functions as a direct object.



loading
The soil beneath the city is where they get their water.

Look at the verb in the sentence again. Is is a linking verb. Therefore, the noun clause serves as the predicate nominative. It renames the subject, soil.



loading
Whatever water they take out causes the ground to sink.

The noun clause in this sentence begins with whatever.

The noun clause acts as the subject of the verb causes.



loading
According to what some experts say, the ground sinks up to one foot in some places each year.

The noun clause begins with what. The noun clause acts as the object of the preposition.

The preposition in this sentence is according to.



loading
Now that you can identify noun clauses and their functions, it is important that you be able to tell the difference between a noun clause and an adjective or adverb clause.

The people of Mexico are concerned because there is a shortage of land for farming.



loading
The people of Mexico are concerned because there is a shortage of land for farming.

This sentence contains an adverb clause. The clause modifies the adjective concerned.

Remember, adverb clauses begin with a subordinating conjunction, (because), and they modify verbs, adjectives, or adverbs. These clauses answer the question how, when, where, to what extent, how often, and sometimes why.



loading
The people, who are extremely sick, are also in need of shelter.

This sentence contains an adjective clause that begins with the relative pronoun who. Remember, an adjective clause modifies the noun that is written directly in front of it (people). They answer the question which one, what kind, or how many.



loading
These clauses are really very simple to master. Just take your time and practice identifying clauses in writing that you read in different places.

If you need to, review this lesson to make sure you can understand the differences between each type of clause.


