** Adverbs 2 							      :drill:
Adverbs, like adjectives, have three degrees of comparison.

[positive]: The house is near.

[comparative]: Her house is nearer than mine.  (Used to compare two people or things.)

[superlative]: Of all our houses, his is the nearest.  (Used to compare three or more people or things.)

** Adverbs 2 							      :drill:
The comparative degree is formed by adding [er] to the [positive] degree, 
or by putting [more] or [less] in front of the word if [er] cannot be added.

** Adverbs 2 							      :drill:
The superlative degree is formed by adding [est] to the end of the positive degree, 
or by putting [most] or [least] in front of the word if [est] cannot be added.

** Adverbs 2 							      :drill:
The [comparative] degree is formed by adding er to the positive degree, 
or by putting [more] or [less] in front of the word if er cannot be added.

** Adverbs 2 							      :drill:
The [superlative] degree is formed by adding est to the end of the positive degree, 
or by putting [most] or [least] in front of the word if est cannot be added.

** Adverbs 2 							      :drill:
Which degree of comparison is used in the following sentences.

James performed worse than John.  [(comparative)]

John performed badly.  [(positive)]

Jim's performance was the worst of anyone on the team.  [(superlative)]

** Adverbs 2 							      :drill:
Look at the degree of comparison for each of these sentences.

The Taj Mahal was built in India early in the 1600s.  [(positive degree)]

It is one of the most expensively built monuments in the world. [(superlative degree)]

** Adverbs 2 							      :drill:
Some adjectives and adverbs are often confused.

good and well:

Good is always an [adjective] that modifies a noun or pronoun.

Well is usually an [adverb] that modifies a verb.

Well is an adjective only when it is used to describe someone's [health].

    Carol felt well enough to go to work.

** Adverbs 2 							      :drill:
Some adjectives and adverbs are often confused.

Real and Really:

Real is always an [adjective]. It means genuine.

    real gem
    real world

Really is always an [adverb]. It means truly.

    really happy
    really slow

** Adverbs 2 							      :drill:
Some adjectives and adverbs are often confused.

Sure and Surely:

Sure is always an [adjective]. It means positive.

    Are you sure?
    The children are sure about the UFO.

Surely is always an [adverb]. It means certainly.

    surely happy
    surely a winner

** Adverbs 2 							      :drill:
Which adverb form in the parentheses is correct?

    Surely wish I could see the Taj Mahal.

[Surely], the adverb meaning certainly, modifies the verb [wish]. (To what degree do I wish?)

** Adverbs 2 							      :drill:
Which adverb form in the parentheses is correct?

    Emperor Shah Jahan certainly spent a great deal of money building the Taj Mahal.

[Certainly], an adverb meaning [truly], modifies the verb [spent]. (How did he spend?)

** Adverbs 2 							      :drill:
Which adverb form in the parentheses is correct?

    It was built well of marble and ivory.

[Well], the adverb, tells how it was built. (It was built [well].)



** Prepositions 						      :drill:
A preposition shows the relationship of a [noun] or a [pronoun] to another word or words in a sentence.

Identify the preposition below.

    The Peace Corps is a group of volunteers who work in other countries teaching new skills to the people.

[Of volunteers] is the first prepositional phrase in this sentence. [Of] is the preposition. [Volunteers] is the object. 

The second phrase, [in other countries], tells where.

The third phrase, [to the people], tells how.

** Prepositions 						      :drill:
In the sentence, "The Peace Corps is a group _of volunteers_ who work..."

If the prepositional phrase tells what kind of group, what do you think the phrase's function is?

If you think it functions as an [adjective], you are correct.


In the sentence, "... who work _in other countries_ teaching new skills _to the people_."

What do you think the function of each phrase is? If you think the phrases function as [adverbs], you are correct!

** Prepositions 						      :drill:
Prepositional phrases begin with a [preposition], end with an [object], and sometimes include [words] in between them.

NOTE: All prepositions have [objects].

If you think you recognize a preposition, but you can't find a noun or pronoun object, then you have an [adverb].

** Prepositions 						      :drill:
Read this list of [prepositions]; Learn to recognize them when you see them.

| about      | after     | around      | behind     | besides     |
| by         | during    | aboard      | across     | among       |
| before     | beside    | but         | down       | above       |
| against    | at        | below       | between    | concerning  |
| except     | according | along       | because of | beneath     |
| beyond     | despite   | for         | from       | inside      |
| off        | outside   | through     | toward     | unto        |
| within     | in        | instead     | on         | over        |
| throughout | under     | up          | without    | in front of |
| like       | out       | past        | till       | underneath  |
| upon       | without   | in spite of | near       | out of      |
| since      | to        | until       | with       |             |

** Prepositions 						      :drill:
Identify the prepostional phrases below.

Africa has the largest number of Peace Corps volunteers.  [of Peace Corps volunteers]

Developing African countries need the help of this group.  [of this group]

The equator passes through Africa.  [through Africa]

A few miles from the equator, however, are mountains that are covered with snow year-round.  [from the equator], [with snow year-round]

** Prepositions 						      :drill:
There are two types of prepositional phrases: [adjective] prepositional phrases and [adverb] prepositional phrases.

[Adjective] prepositional phrases modify [nouns] and [pronouns].

** Prepositions 						      :drill:
Is an adjective or adverb prepositional phrase used below?  [Adjective prepositional phrase]

    Africa has twelve million square miles of total area.

[Of total area] is a prepositional phrase that follows the noun [miles].

** Prepositions 						      :drill:
[Adverb] prepositional phrases modify verbs, adjectives, and other [adverbs].

** Prepositions 						      :drill:
Is an adjective or adverb prepositional phrase used below?  [Adverb prepositional phrase]

    Africa is made up of fifty countries.

[Of fifty countries] is a prepositional phrase that modifies the verb [made].

** Prepositions 						      :drill:
If a prepositional phrase comes at the beginning of a sentence, it cannot be an [adjective] phrase because there is no [noun] for it to follow.

** Prepositions 						      :drill:
An [adjective] prepositional phrase will always follow the noun or pronoun it modifies.

Identify the prepositional phrase:

    The coastline of Africa is somewhat smooth.  [(Of Africa follows coastline and modifies it.)]

    In tropical regions, areas of tall grasslands are called savannas. [(Of tall grasslands follows areas and modifies it.)]

** Prepositions 						      :drill:
An [adverb] prepositional phrase can come anywhere in a sentence, but if it modifies 
an adjective or adverb, it will usually follow that adjective or adverb.

Identify the prepositional phrase:

    The Sahara Desert extends from the Atlantic Ocean to the Red Sea.  [(From the Atlantic Ocean modifies the verb extends.)]

    Mount Kilimanjaro is the highest peak in Africa.  [(In Africa follows the adjective highest and modifies it.)]

** Prepositions 						      :drill:
Find the prepositional phrases in these sentences and tell whether each is an adjective or adverb.

In West Africa, river blindness was a common disease among humans.
[In West Africa (adverb), river blindness was a common disease among humans (adjective).]

The black fly, which flourished along rapidly flowing rivers, was the cause of river blindness.
[The black fly, which flourished along rapidly flowing rivers, (adverb) was the cause of river blindness (adjective).]

** Prepositions 						      :drill:
Find the prepositional phrases in these sentences and tell whether each is an adjective or adverb.

The fly transmitted microscopic worms to humans.
[The fly transmitted microscopic worms to humans (adverb).]

The worms would produce millions of smaller worms.
[The worms would produce millions of smaller worms (adjective).]


** Conjunctions 						      :drill:
A [conjunction] is a part of speech that is used to join words or groups of words. 

** Conjunctions 						      :drill:
A conjunction can join [sentences], [clauses], [phrases], [nouns], or other [words].

** Conjunctions 						      :drill:
Identify the type of conjunctions.

Australia is a continent and a country. [nouns - continent, country]

In 1605, the Dutch discovered the northern tip of Australia and named it Cape York. [verbs - discovered, named]

Abel Tasman discovered New Zealand, and he also discovered the island that would later be called Tasmania. [clauses - Abel..., and he... ]

In 1770, after two years of sailing, the persistent and fearless Captain James Cook found the eastern coast of Australia. [adjectives - persistent, fearless]

** Conjunctions 						      :drill:
There are three kinds of conjunctions: [coordinating]  conjunctions, [correlative] conjunctions, and [subordinating] conjunctions.

A coordinating conjunction is used to join sentence parts that are [alike].

This means that the coordinating conjunction can join [nouns] with [nouns], [verbs] with [verbs], 
[adjectives] with [adjectives], [adverbs] with [adverbs], [phrases] with [phrases], and [clauses] with [clauses].

** Conjunctions 						      :drill:
The [seven] [coordinating] conjunctions are [and], [or], [but], [nor], [for], [yet], and [so].

In selecting a [coordinating] conjunction, a writer must know what kind of relationship is being expressed.

** Conjunctions 						      :drill:
If the relationship is addition, the conjunction should be [and]. 

If the writer wishes to express contrast, [but] or [yet] should be used. 

To express a result or effect, the proper conjunction is [so].

Reason and cause are expressed by the conjunction [for].

The conjunction or expresses choice, and negative choice is shown by the use of [nor].


** Conjunctions 						      :drill:
Identify the type of relationship:  addition, contrast, result/effect, reason/cause, choice.

The Aborigines, the first inhabitants of Australia, would not accept anything from Captain Cook, nor would they give any of their own things to Cook. [(negative choice)]

Only ten percent of the land, however, provides plenty of food for the Australians or for export. [(choice)]

New laws allowed Asians to immigrate to Australia, so the number of Asians is growing. [(result)]

** Conjunctions 						      :drill:
Identify the type of relationship:  addition, contrast, result/effect, reason/cause, choice.

Most of the people who live in Australia today come from Great Britain and Ireland. [(addition)]

Very little of Australia's land is good for farming, for it gets little rain. [(reason)]

Australia used to have laws forbidding Asians from living there, but those laws were changed in the 1950s and 1960s. [[(contrast)]]

** Conjunctions 						      :drill:
Correlative conjunctions are similar to coordinating conjunctions because they also join sentence parts of [equal] rank.

Correlative conjunctions work in pairs. The pairs are both/and, either/or, neither/nor, not only/but also, and whether/or.

** Conjunctions 						      :drill:
Identify the correlative conjunctions below.

Both kangaroos and koala bears are marsupials and are unique to Australia.  [both/and]

Marsupials eat either plants or flesh.  [either/or]

** Conjunctions 						      :drill:
Identify the correlative conjunctions below.

Neither the platypus nor the spiny anteater is a bird, but they lay eggs.  [neither/nor]

Not only the emu but also the cassowary, two flightless birds, are native to Australia.  [not only/but also]

** Conjunctions 						      :drill:
A [subordinating] conjunction is used to connect clauses that are not equal in importance. [Subordinate] means of less importance or dependent.

** Conjunctions 						      :drill:
A subordinate ([dependent]) clause depends on the main or [independent] clause to help it make sense. It cannot stand alone.

** Conjunctions 						      :drill:
An independent clause is a group of words that expresses a complete thought. It can function as a [complete] sentence.

** Conjunctions 						      :drill:
Find the independent clause and the subordinate clause in the sentences below.

    Because the Great Barrier Reef stretches 1,250 miles along the northeast coast of Australia, it is known as the world's largest coral reef.

The independent clause is: [it is known as the world's largest coral reef. It makes sense by itself].

The dependent clause is: [Because the great Barrier Reef stretches 1,250 miles along the northeast coast of Australia]. 

It needs the [independent] clause to complete the thought.

** Conjunctions 						      :drill:
A [subordinating] conjunction introduces a subordinate clause. Here is a list of commonly used [subordinating] conjunctions.

| after      | before        | so that |
| although   | even if       | than    |
| as         | even though   | though  |
| as if      | except        | unless  |
| as long as | if            | until   |
| as soon as | in order that | when    |
| as though  | provided      | where   |
| because    | since         | whether |

** Conjunctions 						      :drill:
Look at the subordinating clauses and the conjunctions that introduce them in these sentences:

    Life in Australia is much like life in the United States and Canada.

[And is a coordinating conjunction joining the two nouns, United States and Canada.]

    Because Australia is isolated from other continents, the animals may have developed differently.

[Because is a subordinating conjunction that introduces the subordinate clause Australia is isolated from other continents.]

** Conjunctions 						      :drill:
Look at the subordinating clauses and the conjunctions that introduce them in these sentences:

    Many Aborigines were either killed by the Europeans or died of diseases the Europeans brought with them.

[Either/or is a correlative conjunction joining the verbs killed and died.]

    Australia is the world's leader not only in the production of bauxite but also in the production of lead.

[Not only/but also is a correlative conjunction that joins in the production of bauxite and in the production of lead.]


** Interjections 						      :drill:
An interjection is a [word] or [group of words] interjected, or added, into a sentence.

An interjection usually tells strong [feeling] or sudden [emotion] such as fear, anger, surprise, or joy. 

An interjection has [no] grammatical relation to the rest of the sentence.

** Interjections 						      :drill:
An [exclamation point] usually follows an interjection, but can sometimes be followed by a [comma].

** Interjections 						      :drill:
The interjection is always an [independent] unit.

This means that the interjection is not considered to be a [part] of a sentence.

** Interjections 						      :drill:
These are just a few of the many words that can be used as [interjections]:

Ah!
Alas, ...
Dear me!
Wow!
Ha! Ha!
Oops!

** Interjections 						      :drill:
If the interjection does not seem to stand by itself but seems to be part of the 
sentence, then the interjection is followed by a [comma].

** Interjections 						      :drill:
Identify the interjection in the sentences below.

Alas, the boat sank!  [Alas,]

Oh well, maybe you will hit the ball next time!  [Oh Well]

** Interjections 						      :drill:
Identify the interjection in the sentences below.

Nonsense! You can't tell me that.  [Nonsense]

Listen! Do you hear the fire alarm?  [Listen]

** Interjections 						      :drill:
Find the interjection in these sentences.

Whew! I'll never finish peeling all these potatoes.  [Whew]

You are a great person, indeed.  [indeed]

Wow! I just won the sweepstakes.  [Wow]

Aha! I caught you.  [Aha]

** Interjections 						      :drill:
Think about emotions or feelings when you are using [interjections].


** Sentences 1 							      :drill:
Sentences can be divided into two major parts: the [complete] [subject] and the [complete] [predicate].

** Sentences 1 							      :drill:
The simple subject is [who] or [what] the sentence is about.

The simple subject of a sentence can be a [noun], a [pronoun], or a [noun phrase].

** Sentences 1 							      :drill:
Identify the subject and part of speech.

Hannah is my best friend. [Hannah , noun]

She loves to read mystery books. [She , pronoun]

** Sentences 1 							      :drill:
A [complete] [subject] includes the noun, pronoun, or noun phrase functioning 
as the simple subject and all the adjectives or phrases that modify the [simple] subject.

** Sentences 1 							      :drill:
The [subject] is usually placed before the [verb]. 

Therefore, the complete subject is usually at the [beginning] of the sentence.

** Sentences 1 							      :drill:
The [predicate] is the part of the sentence that tells something about the subject.

The [verb] is the simple predicate.

** Sentences 1 							      :drill:
Identify the simple predicate in the sentences below.

The President of the United States will be speaking at the conference today.  [speaking]

Patches of slippery ice covered the sidewalk.    [covered]

** Sentences 1 							      :drill:
The [complete] [predicate] is the verb and all the modifiers that are attached to it, 
as well as the direct and indirect [objects], if the sentence has any.

** Sentences 1 							      :drill:
Identify the complete predicate in the sentences below.

The President of the United States will be speaking at the conference today.
[will be speaking at the conference today.]

Patches of slippery ice covered the sidewalk.
[covered the sidewalk.]

** Sentences 1 							      :drill:
Is it possible for either the complete subject, the complete predicate, or both to be a single word?

[True]

** Sentences 1 							      :drill:
Remember, the [complete] [subject] is who or what the sentence is about and all the modifiers.

The [complete] [predicate], which includes the verb and all its modifiers, 
is the part of the sentence that tells something about the [subject].

** Sentences 1 							      :drill:
A sentence must have both a [subject] and a [predicate] before it can be called a sentence.

It takes both of these sentence parts to express a [complete] thought or idea.

If either part of the sentence is missing, the words only form a sentence [fragment] or phrase.

** Sentences 1 							      :drill:
A [declarative] sentence is simply a sentence that makes a statement. 
In most [declarative] sentences, the subject comes before the verb.

** Sentences 1 							      :drill:
An [interrogative] sentence is one that asks a question.

[Interrogative] sentences, sentences that begin with here or there, 
and sentences that begin with negative words have a different word order.

In these sentences, the [verb] or part of the [verb] is put before the subject. 
This is called inverted word order.

** Sentences 1 							      :drill:
Identify the type of sentence.

How can humans stop the destruction of animal life?  [Interrogative]

** Sentences 1 							      :drill:
Identify the type of sentence.

There are many ways humans damage plant and animal life.  [Interrogative]

** Sentences 1 							      :drill:
Identify the type of sentence.

Nowhere is the problem worse than in the rainforests.  [Interrogative]

** Sentences 1 							      :drill:
Identify the type of sentence.

Scientists are trying to decide which animals they must protect first from extinction.  [Declarative]

** Sentences 1 							      :drill:
Identify the type of sentence.

This is called normal or natural word order. In natural word order, the subject is before the verb.  [Declarative]

** Sentences 1 							      :drill:
Are these sentences in natural or inverted order?

There are several ways humans destroy the habitat of animals.  [inverted]

Clearing the land to grow food is one major way that humans destroy animal habitats.  [natural]

Animals depend on responsible humans to protect them.  [natural]

** Sentences 1 							      :drill:
If the subject comes after the verb or any part of the verb, the sentence order is [inverted].

    There are several ways humans destroy the habitat of animals.

Ways is the subject of the verb are. The verb comes first. The sentence is [inverted].

** Sentences 1 							      :drill:
Clearing the land to grow food is one major way that humans destroy animal habitats.

[Clearing] is the subject of the verb [is]. The subject comes [first] in the sentence; therefore, it is in [natural] order.

** Sentences 1 							      :drill:
Animals depend on responsible humans to save them.

[Animals] is the subject of the verb [depend]. The subject comes [first]. The sentence is in [natural] order.

