** Pronouns 2 							      :drill:
[First] person: I, me, my, mine, we, us, our, ours

** Pronouns 2 							      :drill:
[Second] person: you, your, yours

** Pronouns 2 							      :drill:
[Third] person: she, he, it, him, her, his, hers, its, their, theirs

** Pronouns 2 							      :drill:
Personal pronouns can be classified in [three] ways.

Personal pronouns can be classified by case:  
[subjective]
[objective]
[possessive]

** Pronouns 2 							      :drill:
Subjective case pronouns are those used as [subjects] or [predicate] nominatives.

Objective case pronouns are those used as [direct objects], [indirect objects], and objects of [prepositions].

Possessive case pronouns are those used to show [ownership].

** Pronouns 2 							      :drill:
Remember: Subjective case pronouns are used as [subjects] and predicate [nominatives]. 

** Pronouns 2 							      :drill:
Obejective case pronouns are used as [objects] ([direct objects, indirect objects, and objects of prepositions]).

** Pronouns 2 							      :drill:
Identify the objective case pronouns:

Direct object: John gave them to Mary.  [them]

Indirect object: John gave her the roses.  [her]

Object of preposition: John gave the roses to her.  [her]

** Pronouns 2 							      :drill:
What type of pronoun is used to show ownership?  [Possessive pronouns].

That book is _yours_.

_Mine_ is a little older.

Jim already has _his_.


** Pronouns 2 							      :drill:
Alice scared herself when she looked in the mirror.

Herself refers or reflects back to the subject, Alice. In this sentence, herself is 
a _reflexive compound personal pronoun_. This is a long label for a short word.

When the words self or selves are added to personal pronouns, the personal pronouns become [compound] [personal] pronouns.

** Pronouns 2 							      :drill:
Because of their meaning, some of these are called reflexive pronouns. Reflexive comes from the same word as [reflection].

Reflexive pronouns are like mirrors. If you use a reflexive pronoun, you must also have a [noun] or a [pronoun] that is not reflexive.

** Pronouns 2 							      :drill:
When a compound personal pronoun receives the action of a verb (direct object), the pronoun is called a [reflexive] compound personal pronoun.

In other words, the pronoun reflects or refers back to the [subject].

** Pronouns 2 							      :drill:
Singular Compound Personal Pronouns

| Type     | 1st Person | 2nd Person | 3rd Person               |
|----------+------------+------------+--------------------------|
| Singular | myself     | yourself   | herself, himself, itself |
| Plural   | N/A        | yourselves | themselves               |

Important Note: There are no such words as theirselves, ourself, or hisself. Drop them from your vocabulary.

** Pronouns 2 							      :drill:
Some compound personal pronouns serve as [intensifiers] rather than reflectors of action.

Identify the compound personal pronouns below:

I will do it myself.  [myself]

Mother promised to bake the cake herself.  [herself]

These compound personal pronouns could actually be dropped from the sentences without changing their 
meanings. Adding the pronouns to the sentences intensifies the emphasis on the antecedents.

** Pronouns 2 							      :drill:
Personal pronouns can be classified is by person.

Person refers to whether the subject is speaking of himself or herself, is speaking to you, or is speaking about another person.

[First] person is used to refer to the [speaker].
[Second] person is used to refer to [you].
[Third] person is used to refer to [another person].

** Pronouns 2 							      :drill:
Pronouns can be classified by number. Number can be [singular] or [plural].

** Pronouns 2 							      :drill:
[Plural] means more than one.
[Singular] means one. 

** Pronouns 2 							      :drill:
What is wrong with the sentence below.

    They knew that they had struck gold when they realized that they had found the missing vase.

This sentence never identifies [they]. The message of the sentence is unclear.

** Pronouns 2 							      :drill:
Identify the person, number, and case of this pronoun:

    The archaeologists knew that they had struck gold when they realized that they had found the missing vase.

They in this paragraph is a [third] person, [plural], [subjective] pronoun.


** Pronouns 3 							      :drill:
[Interrogative] pronouns are used to ask questions. 

There are five interrogative pronouns: [who], whose, [whom], which, and what.

What is your name?
[Whom] did you ask to the dance?
[Who] will bring the sandwiches?
Whose is that book?
Which makes the most sense to you?

** Pronouns 3 							      :drill:
[Demonstrative] pronouns point out specific persons, places, and things. 

There are four demonstrative pronouns: this, that, these, and those.

This house is old.
That monkey swung from the bars.
These toys need to be washed.
Those people are late.

** Pronouns 3 							      :drill:
This and that are [singular] demonstrative pronouns. They point out [singular] items.

These and those are [plural] demonstrative pronouns. They point out [plural] items.

this house
that monkey
these toys
those people

** Pronouns 3 							      :drill:
This and these point out items that are [near]. That and those point out items that are [farther] away.

Let's plant these trees in this lot.

That tall tree can be planted with those shrubs.

** Pronouns 3 							      :drill:
[Relative] pronouns are used to introduce [subordinate] clauses.

There are five relative pronouns are who, whose, whom, which, and that.

** Pronouns 3 							      :drill:
Relative pronouns look like interrogative pronouns except for that. You can tell these pronouns apart by looking at their function in a sentence.

The boy whose bicycle was wrecked is working to buy a new one.

Whose bicycle was wrecked is the [subordinate] [clause].

** Pronouns 3 							      :drill:
[Indefinite] pronouns do not always refer to specific persons, places, or things, and they may not have [antecedents].

There are three groups of indefinite pronouns: singular, plural, and those that can be either singular or plural.

These are singular indefinite pronouns:
someone, somebody, something, each, anyone, anybody, anything, either
everyone, everybody, everything, neither, no one, nobody, nothing, one

** Pronouns 3 							      :drill:
Do you notice a pattern? All the pronouns except each, either, and neither end with one, body, or thing.

Everyone is happy about the election.

Nothing spoils John's appetite.

These pronouns are always [singular], even though sometimes it doesn't seem that they should be.

** Pronouns 3 							      :drill:
There are five [plural] indefinite pronouns: both, few, several, many, and others.

Several of the students rode their bikes to school.

Few will make it to the party.

** Pronouns 3 							      :drill:
There are five indefinite pronouns that can be either [singular] or [plural], 
depending on what they refer to. These indefinite pronouns are: all, any, most, none, and some.

If these pronouns refer to a [plural] word, they are plural. If they refer to a [singular] word, they are singular.

** Pronouns 3 							      :drill:
Identify the pronoun and whether it is singular or plural.

All the boys were riding their bikes.
[All refers to boys. Boys is plural, so all is plural.]

All the milk has spoiled.
[All refers to milk. Milk is singular, so all is singular.]

** Pronouns 3 							      :drill:
Name the indefinite pronouns in these sentences.

Everyone is to bring an arachnid to school to study.

None of the spiders were poisonous.

Although both are arthropods, spiders are different from insects.

Some of the insects obtain food by digging; others chew.

** Pronouns 3 							      :drill:
Name the indefinite pronouns in these sentences.

    Everyone is to bring an arachnid to school to study.

[Everyone] is always a [singular] indefinite pronoun and takes the [singular] verb is.

    None of the spiders were poisonous.

[None] can be [singular] or [plural]. 
It refers to [spiders], which is [plural], so [none] is [plural].

** Pronouns 3 							      :drill:
Name the indefinite pronouns in these sentences.

    Although both are arthropods, spiders are different from insects.

[Both] is always a [plural] indefinite pronoun and takes the [plural] verb are.

** Pronouns 3 							      :drill:
Name the indefinite pronouns in these sentences.

    Some of the insects obtain food by digging; others chew.

[Some] can be [singular] or [plural]. It refers to [insects], which is [plural], so [some] is [plural]. 

[Others] is always plural and takes the plural verb chew.


** Adjectives 1 						      :drill:
Adjectives are words that modify or change [nouns] or [pronouns].

** Adjectives 1 						      :drill:
[Adjectives] are words that modify or change nouns or [pronouns].

** Adjectives 1 						      :drill:
Identify the adjectives below:

    Three pretty girls went to a small, nearby town.  [three, pretty, small, nearby]

[Now we know how many girls (three) and what kind of girls (pretty) went to town. We also know what kind of town (small) and which one (nearby).]

** Adjectives 1 						      :drill:
Adjectives answer these questions: which [one], what [kind], how [many].

Which one: first girl, that boy, nearby town
What kind: pretty girls, small town, blue sky
How many: three girls, many buffalo, several boys

** Adjectives 1 						      :drill:
Identify the adjective(s) in these sentences:

Pedro Alvares Cabral claimed the largest country in South America, Brazil, for Portugal.  [largest]

All of Brazil has a relatively low elevation. Its highest mountain range rises about 9,000 feet.  [low, highest, mountain, 9,000]

** Adjectives 1 						      :drill:
Adjectives answer these questions: which one, what kind, how many.

All of Brazil has a relatively low elevation. Its highest mountain range rises about 9000 feet.

highest - [which one]

mountain - [what kind]

Notice that in this sentence, the [noun] mountain is used as an [adjective] to describe [range].

** Adjectives 1 						      :drill:
A, an, and the are called [articles].

A and an do not refer to any specific person, place, or thing, so they are called [indefinite] [articles].

The refers to specific persons, places, or things, so it is called a [definite] [article].
the house
a house
the apple
an apple

** Adjectives 1 						      :drill:
The [demonstrative] adjectives (this, that, these, those) look like the demonstrative [pronouns], 
but the difference is that when they act as adjectives, they modify nouns.

** Adjectives 1 						      :drill:
    This house is big.

This is an [adjective] that tells what kind about the [house].

    This is a big house.

This is the [subject] and cannot be a modifier. In this sentence, this is a [pronoun].

** Adjectives 1 						      :drill:
[Proper] adjectives are adjectives that are formed by using a proper noun to modify another [noun].

When the adjective is part of a title or the proper name of something, it is not considered 
an adjective. The proper noun functions together as one noun as in the sentence below.

    Brazil is bounded by the Atlantic Ocean on the east.

Atlantic Ocean is the [object] of the [preposition] by, so it must be a [noun].

    Brazil's largest cities are on the Atlantic coast.

Atlantic is a [proper] [adjective] that modifies coast by telling which one. Notice that coast is not capitalized. 
That is because it is not a proper noun. Instead, Atlantic is a descriptive word that modifies coast.

** Adjectives 1 						      :drill:
Are the highlighted words nouns, adjectives, or pronouns?

_Brazilians_ did not want to live in the _Amazon's_ interior.  ([proper noun], [adjective])

The _Amazon River_ connects few cities or towns.  ([proper noun])

The _Brazilian_ government has encouraged people to move there, but _few_ have.  ([adjective], [pronoun])

** Adjectives 1 						      :drill:
Analyze the underlined words below:

    _Brazilians_ did not want to live in the _Amazon's_ interior.

Brazilians is the [subject] of the sentence and must be a [noun]. [Adjectives] cannot be subjects. Only [nouns] and [pronouns] can be subjects.

Amazon's is the possessive case of the noun Amazon.  The possessive case of a noun is always an [adjective].

** Adjectives 1 						      :drill:
Analyze the underlined words below:

    The _Amazon River_ connects few cities or towns.

Amazon River is the [subject] of the sentence; therefore it must be a [noun].

Few is an [adjective] that tells [how] [many] about cities or towns.

** Adjectives 1 						      :drill:
Analyze the underlined words below:

    The _Brazilian_ government has encouraged people to move there, but _few_ have.

Brazilian is a [proper] [adjective] modifying the noun government and telling which [one] about it.

Few is a [pronoun], the subject of the verb have.

** Adjectives 1 						      :drill:
Adjectives that follow linking verbs and modify the subject of the sentence are called [predicate] adjectives.

    The Amazon Basin is wetter than any other part of the country, with eighty inches of rain a year.

The linking verb [is] connects the adjective [wetter] with the subject [Amazon Basin].

** Adjectives 1 						      :drill:
The [possessive] case of nouns (those that end in 's) are always [adjectives].

Cabral's discovery
Brazil's landscapes
the roof's shingles
the cat's paw


** Adjectives 2 						      :drill:
Adjectives are words that describe or modify nouns or [pronouns]. 

Adjectives also have another important use. They can be used to [compare] or [contrast] people, places, or things.

** Adjectives 2 						      :drill:
Identify the adjective in the sentence below:

    The Eiffel Tower in Paris is a tall monument.

[Tall] is an adjective that modifies the noun [monument].

** Adjectives 2 						      :drill:
Identify the adjective in the sentence below:

    It is taller than many other monuments.

[Taller] is a [predicate] adjective following the [linking] [verb] is and modifying the pronoun [it].

** Adjectives 2 						      :drill:
Identify the adjective in the sentence below:

    It is taller than many other monuments.

[Taller] is a [predicate] adjective following the [linking] [verb] is and modifying the pronoun [it].

** Adjectives 2 						      :drill:
Identify the adjective in the sentence below:

    In fact, the Eiffel Tower is one of the world's tallest landmarks.

[Tallest] is an adjective that modifies the noun [landmarks].
World's is the [possive] case of the noun [World], and therefore, also an [adjective].

** Adjectives 2 						      :drill:
The basic form of an adjective is sometimes referred to as the positive form.

The three forms of comparison for adjectives are [positive], [comparative], and [superlative].

** Adjectives 2 						      :drill:
Adjectives that compare two things are called [comparative] [adjectives]. They usually end in [er].

comparative adjectives: taller, happier, funnier, larger, greater

** Adjectives 2 						      :drill:
Three-syllable adjectives and some one or two-syllable adjectives cannot have er added to the end. 

In this case, put [more] or [less] in front of the word to form the comparative.

more intelligent
more delicious
less fun
more hopeful

** Adjectives 2 						      :drill:
Adjectives that are used to compare [three] or [more] things are called [superlative] adjectives. [Superlative] adjectives usually end in est.

Examples:  tallest, happiest, funniest, largest, greatest

** Adjectives 2 						      :drill:
Three syllable adjectives and some one or two-syllable adjectives cannot have est added to the end. 

In this case, put [most] or [least] in front of the adjective to form the [superlative].

most intelligent
most delicious
least fun
most hopeful

** Adjectives 2 						      :drill:
Identify the form of adjective (positive, comparative, or superlative) being used below:

Paris is a famous city.  [(positive or basic form of the adjective)]

** Adjectives 2 						      :drill:
Identify the form of adjective (positive, comparative, or superlative) being used below:

Paris is more famous than the city of Lyon.  [(comparative form)]

** Adjectives 2 						      :drill:
Identify the form of adjective (positive, comparative, or superlative) being used below:

Paris is one of the most famous cities in the world.  [(superlative form)]

** Adjectives 2 						      :drill:
Test yourself to see if you can correctly use the comparative and superlative forms of a few adjectives. 

big, [bigger], [biggest]
rare, [rarer], [rarest]
wealthy, [wealthier], [wealthiest]

** Adjectives 2 						      :drill:
Write the comparative and the superlative degrees of these positive forms on a piece of paper, 
then go to the next screen to compare your answers with ours.

| [Superlative]    | [Positive] | [Comparative]    |
|------------------+------------+------------------|
| [biggest]        | big        | bigger           |
| [rarest]         | rare       | [rarer]          |
| prettiest        | [pretty]   | [prettier]       |
| [most satisfied] | satisfied  | [more satisfied] |
| [sweetest]       | sweet      | [sweeter]        |
| [most flexible]  | [flexible] | more flexible    |

** Adjectives 2 						      :drill:
Write the comparative and the superlative degrees of these positive forms on a piece of paper, 
then go to the next screen to compare your answers with ours.

| [Positive] | [Comparative]    | [Superlative]    |
|------------+------------------+------------------|
| big        | bigger           | [biggest]        |
| rare       | [rarer]          | [rarest]         |
| [pretty]   | [prettier]       | prettiest        |
| satisfied  | [more satisfied] | [most satisfied] |
| sweet      | [sweeter]        | [sweetest]       |
| [flexible] | more flexible    | [most flexible]  |

** Adjectives 2 						      :drill:
Some adjectives form their comparative and superlative forms irregularly. You will need to learn these adjectives.

| Positive | Comparative | Superlative |
|----------+-------------+-------------|
| [good]   | better      | [best]      |
| ill      | worse       | [worst]     |
| bad      | [worse]     | worst       |
| many     | [more]      | most        |
| much     | more        | [most]      |


** Adverbs 1 							      :drill:
Adverbs are words that modify or change [verbs], [adjectives], or other [adverbs].

** Adverbs 1 							      :drill:
Identify the adverbs in the following sentence:

Three extremely pretty girls walked slowly to a very small nearby town.  [extremely, slowly, very]

[Extremely tells to what extent the girls are pretty. Extremely modifies the adjective pretty.]

[Slowly tells how the girls walked to the town. Slowly modifies the verb walked.]

[Very tells to what extent the town was small. Very modifies the adjective small.]

** Adverbs 1 							      :drill:
Adverbs answer these questions:

To what extent?
How?
[When]?
[Where]?
How often?

** Adverbs 1 							      :drill:
What adverb question (to what extent, how, when, where, how often) do each of the adverbs answer?

In 1991, the Soviet Union's fifteen republics willingly declared independence. Independence came quickly.  [How? willingly] and [How? quickly]

With 6,592,800 square miles, Russia is undoubtedly the largest country to come out of the breakup.  [To what extent? undoubtedly]

Moscow has not always been the capital of Russia.  [When? always]

** Adverbs 1 							      :drill:
Two [negative] words should not be used in one sentence.

    I did not find no book.

    I don't have no paper.

The result is an error called a [double] [negative]. To correct the error, remove one of the negatives or change the word to make the correction.

    I did not find any book.

    I don't have any paper.

** Adverbs 1 							      :drill:
This is a list of commonly used negatives:
neither, no, none, nobody, nowhere, never, barely, hardly, scarcely, no one, nothing, not (n't)

Be careful not to use [two] of these to express the same thought in a sentence.

** Adverbs 1 							      :drill:
Correct the _double negatives_ in the sentence.

    No other city in Russia is not as big as Moscow which has eight million people.

[No other city in Russia is as big as Moscow, which has eight million people.]

** Adverbs 1 							      :drill:
Correct the _double negatives_ in the sentence.

    St. Petersburg, which has four million people, isn't hardly as big as Moscow.

[St. Petersburg, which has four million people, is not as big as Moscow.]

** Adverbs 1 							      :drill:
Correct the _double negatives_ in the sentence.

    Russia is not considered a superpower no more.

[Russia is not considered a superpower anymore.]

** Adverbs 1 							      :drill:
Remember that n't is a contraction of not, which is a [negative].  

That means that any contraction that uses n't is a [negative] word.

Is _hardly_ is a negative?  [Yes.]

** Adverbs 1 							      :drill:
Some adjectives can be made into adverbs by adding [ly]. Sometimes, though, this leads to confusion in their use.

| adjective | adverb      |
|-----------+-------------|
| beautiful | beautifully |
| clear     | clearly     |
| happy     | happily     |

Notice that [y] was changed to i before ly was added to the word happy to make [happily].

** Adverbs 1 							      :drill:
Choose the adjective or adverb that correctly completes these sentences.

(Unfortunately, Unfortunate), Russia finds it difficult to use its natural resources.  [Unfortunately - the adverb modifies the verb finds]

The reasons are the (vastly, vast) size and the varied climate.  [vast - the adjective modifies the noun size]

** Adverbs 1 							      :drill:
Choose the adjective or adverb that correctly completes the sentence.

    Most manufacturers are far away from the resources, which makes it (expensively, expensive) to transport them.  
    [expensive - the adjective modifies the pronoun it]

To decide whether you need an adjective or adverb, look at what word is [modified]. 

If it is a noun or pronoun, use an [adjective]. Verbs, adjectives, and other adverbs require an [adverb].
