** Introduction to U.S. History  :drill:
Do you believe that who we are as a society today has nothing to do with people who lived in the past? Do you believe that history is simply a collection of facts?

Relating to the people in history is as important as relating to facts and statistics. It's important to look beyond the details and learn about the real men and women who lived before us.

People in the past had many of the same hopes and dreams and experienced many of the same events that we do today.
Their culture, technology, and politics changed their daily lives, just as we are affected today by our social and physical environments. However, our views and beliefs about historical events can affect our actions in the present and the future, even as our ancestors were affected by experiences in their past.



** Introduction to U.S. History  :drill:
As you study this lesson, you will be presented with information about history in the following areas:

•  social and cultural themes

•  natural sciences

•  humanities



** Introduction to U.S. History  :drill:
The Past – Today and Tomorrow

Why should we study history? A study of history enables a person to see the connection of how people with diverse cultures, customs, and societies framed and built the civilizations of today.

The history of the United States is a complicated story of the creation of a new nation and the accomplishments of its people. These people represented a diversity of cultures from around the world. Each individual helped forge the history of the United States with heroic deeds, visionary words, and the labors of their everyday lives.



** Introduction to U.S. History  :drill:
In the past, the technology of mass communication was limited. People relied on printed material and verbal communication to find out about current events. Unfortunately, travel was slow and books were expensive. It could take weeks or even months to find out what was happening in the world. News was rarely current.

People in the past had a difficult time knowing the big picture of what was happening in other countries or even neighboring towns.



** Introduction to U.S. History  :drill:
The Big Picture

To "look at the big picture" means to observe or analyze a particular situation as it appears in its entirety. In academics, this is called the macro view.

The big picture of the thirteen colonies is a macro view of the founding of America and includes components such as geography, state borders, and resources.



** Introduction to U.S. History  :drill:
A micro view of history looks at the separate components that come together to form the big picture. A person can study how each colony was established and why, who lived in the towns, and where the people came from. This provides a foundational understanding of the different social sciences involved in forming any culture or society.

As we study history, we have an advantage people in the past did not: we can see the macro and micro views of events and their causes and effects. From this picture of the past, we can gain knowledge that will help us make decisions affecting the present and the future.



** Introduction to U.S. History  :drill:
Building a Foundation of Knowledge

The foundation of a subject or project is extremely important. For example, before a house is built, a carpenter or contractor will prepare the home site, level the land, install gas and water pipes, and lay electrical lines. After the pre-building work is completed, the foundation for the home is constructed. The structure itself will then be built on top of this foundation.
If there is a problem with the foundation, there can be huge problems with the structure later, such as cracks in the walls and ceiling, water leaks, and more.



** Introduction to U.S. History  :drill:
When you prepare to study any subject, you should prepare foundations for learning. Distractions need to be eliminated, and a foundation of facts such as time, events, and people should be put into place. It is this foundation of facts that provides a framing construction for additional information.
For example, one man single-handedly made the horrific practice of slavery profitable for America. To build a critical analysis of this statement, you must begin with the foundational knowledge of the person (who), event (what), and time (when).

Eli Whitney
the cotton gin
1794

This provides basic facts, but it doesn't provide the whole story.



** Introduction to U.S. History  :drill:
Expanding Knowledge

Once a foundation is built, a carpenter raises the walls of a house on top of the foundation support. The walls are necessary to support the doors, windows, and roof of the house. The walls, windows, and doors provide security, comfort, and protection. The structure also expands an individual's ability to live a certain lifestyle.

A foundation of knowledge provides a support base for an expansion of facts. This expansion allows a person to review, analyze, and criticize a historical or current event. The facts lead to why, where, or how something occurred.



** Introduction to U.S. History  :drill:
When historical facts are reviewed and analyzed, the connections of people, dates, and events become clearer. Understanding how an event or person changed history and influenced society enables a person to build a broad foundation of knowledge.

Consider how the following information expands your knowledge of past slavery in America.

The invention of the cotton gin by Eli Whitney in 1794 brought a wave of technological change.
This change increased the productivity of the cotton trade, which made slave labor in Southern states profitable and necessary to the region's economy.



** Introduction to U.S. History  :drill:
Application of Knowledge

When the construction on a house is done, detail work is completed to enhance the final product. The same is true in the construction of knowledge. Social sciences, the humanities, and natural sciences contain categories of knowledge that provide the understanding of a subject through detailed analysis.

In history, this analysis enhances constructed knowledge and provides a way to view history's variances through the support of specific themes.



** Introduction to U.S. History  :drill:
Supporting Themes

In this course, the three categories of social sciences, humanities, and natural sciences are divided into seven specific supporting themes.

Click on the tabs at the right to learn more about each supporting theme.



** Introduction to U.S. History  :drill:
Linear History

History can also be examined through a linear flow chart of events, each with its own linking components.

History is not a static subject; it is in a constant state of expansion. The continual growth of history challenges learners in ways unequaled by any other course of study.



** Introduction to U.S. History  :drill:
Chronology

The placement of events in time is important. The flow of history follows time and chronology. Chronology is the identification of time, date, and order of events.
Relative chronology is the identification of two events relative to each other because they happened at the same time. An example of relative chronology would be the Revolutionary War and the Declaration of Independence.



** Introduction to U.S. History  :drill:
Absolute Chronology

Absolute chronology involves the identification of an absolute date. The Declaration of Independence was adopted on July 4, 1776. We know this fact because the original document still exists with a written date recorded on the paper.

Finding an absolute date in early history is often difficult due to the absence of written records. Calendars and methods of tracking time have also changed over the years. Different civilizations and societies use a variety of calendars, such as the Julian, Gregorian, Mayan, and Islamic calendars.
Using the concepts of foundation, expansion, application of knowledge, and supporting themes, we will examine a current event.

Through this examination, we will learn how an event begins with the basic root facts and is expanded through the knowledge and theme concepts.



** Introduction to U.S. History  :drill:
Hurricane Katrina

If you believe that history is only a record of ancient events or many useless facts about dead people, you would be wrong. Hurricane Katrina is not ancient history, but it is a historical event. History begins the instant a moment ends.

The foundation of knowledge covers valuable information about the time, event, and people involved in Hurricane Katrina.

Time: When did the event occur?
Hurricane Katrina formed on August 23, 2005, and slammed into the Gulf Coast on August 29, 2005.



** Introduction to U.S. History  :drill:
Event: What happened, and where did it happen?

Hurricane Katrina formed in the Atlantic Ocean, traveled past southern Florida and rolled over the Gulf Coast. The storm and ensuing flooding were responsible for over $81 billion in damages.
 
People: Who were the individuals or groups involved in the event?

The residents of New Orleans and inhabitants living along the Gulf Coast were the people primarily affected by Hurricane Katrina.



** Introduction to U.S. History  :drill:
Macro View

A partial macro view of Hurricane Katrina using supporting themes includes:

geographical
•  a comparison of Katrina with other hurricanes of 2005
•  a comparison of all hurricanes over the past 100 years

governmental
•  a study in emergency response preparedness
•  a prediction and legislation of government financial aid to the area
The macro view alone does not reveal the entire story of Hurricane Katrina. We also use the categories of change, continuity, and connections to truly understand the destruction of the culture and social institutions of the city of New Orleans.



** Introduction to U.S. History  :drill:
Micro View

To understand the total effect of Hurricane Katrina, we must take a micro view of the culture of New Orleans. What is a culture? The culture of a society includes the history, customs, traditions, knowledge, literature, art, language, and a belief in various elements of religion. A culture imparts rules of behavior for individuals who standardize the structure of a society.

The survival of a culture is dependent on the successful transmission of the culture from one generation to the next by the institutions of a society. The transmission of a culture can be written or spoken.
The main institutions in a society include the family, education, religions, political systems, and economic systems.



** Introduction to U.S. History  :drill:
Expanding Knowledge - What Changed

A large part of the cultural and social institutions of New Orleans was destroyed as a result of Hurricane Katrina. Many families were devastated by the loss of loved ones and the destruction of their homes, churches, schools, neighborhoods, businesses, and places of employment.
The damage to many of the social institutions of New Orleans may never be repaired or replaced, and the lives of its people have been changed forever.



** Introduction to U.S. History  :drill:
Through a cultural examination, the effect of Hurricane Katrina takes on a human element that is not revealed by the statistics of a date or the number of people who died.

Continuity - What Remains the Same

New Orleans has survived as a city. Homes and businesses are being rebuilt, and the culture of the city is in an ongoing revival of old traditions and the establishment of new ones. The city is being rejuvenated through the commitment of the inhabitants to their way of life.



** Introduction to U.S. History  :drill:
Connections

What are the connections between the past and the present? The failure of levee systems during the height of Hurricane Katrina prompted a review of the city's infrastructure and plans to protect the city from future flooding. In addition, the response of government agencies at the federal, state, and local levels brought demands for a review of emergency procedures.

A proposal was made to replace natural barriers that once protected New Orleans from flooding. Many of the past natural barriers were lost because of development along the Mississippi River.



** Introduction to U.S. History  :drill:
History is a rich and complex story about the lives of people, their social institutions, and the places where they live. How does the study of history affect you? Let's apply the foundation and knowledge of an event in history to an event in your life.



** Introduction to U.S. History  :drill:
Foundation of Knowledge

Think about the events, time, and people of your school from the macro view of an entire school year. One of the events on the school calendar is the football homecoming.
Is it enough to know that the homecoming game was held on Friday, October 20, 2006, at 7:00 PM, and the final score was 20 to 14 in favor of the home team? This information is important, but it does not tell the whole story. Let's look at a micro view of this event.



** Introduction to U.S. History  :drill:
Expansion of Knowledge

What are the changes, continuity, and connections of that school year? Perhaps this homecoming game was the first time in twenty years that the home team beat their biggest rival. Maybe the members of a team that won a state championship fifty years ago were honored at halftime.

Perhaps it was the final homecoming game for a popular head coach who was retiring at the end of the season. Any of these connections could influence how you later remembered that game and the following homecoming dance.



** Introduction to U.S. History  :drill:
Course Outline

In our study of U.S. History, we will examine events rooted in the foundation of history from a macro viewpoint. Each section of lessons will encompass a span of approximately twenty years.

The focus of this course is from 1850 to the present. The span of time is divided into two courses, U.S. History I and U.S. History II. Ten lessons spanning pre-1492 to 1850 are provided as a review to strengthen your foundational knowledge.



** Introduction to U.S. History  :drill:
Sources and Resources

Literature is part of the humanities and covers an important aspect of the study of history.

A broad definition of literature would be everything that has ever been written. This includes comic books, novels, newspapers, pamphlets, government documents, and even hieroglyphics.
Literature, the written works of a culture or civilization, could come into being only with the development and spread of a written language. Before the ability to read and write was common, wealthy leaders of a particular clan or town retained singers as part of their household to relate the tales of past and present.

Literature can be divided into many categories, including fiction, nonfiction, prose, and poetry.



** Introduction to U.S. History  :drill:
Documents

A document can be defined as written evidentiary information used to prove a fact. Examples of documents could be letters, maps, pictures, or government publications such as original charters, Supreme Court decisions, or acts of Congress. These documents can be primary or secondary sources.

Primary Sources

A primary source is material that provides a first-hand account of past events. Examples of primary sources include letters, narratives, diaries, government and court records, and journals.
Secondary Sources

A secondary source is any information about an event or person written by someone who was not at the actual event. One example is a book about Abraham Lincoln written in 1960. Secondary sources can include biographies and history textbooks.



** Introduction to U.S. History  :drill:
This primary source document is a letter given by the King and Queen of Spain to Columbus before he began his first voyage to America. The letter outlines the duties for Columbus and the expectations the monarchs had for the voyage.
Government Sources

This course uses government resources from the National Park Service sites and  other websites including:

1)  National Archives
2)  U.S. Census Bureau
3)  Statistical Abstract of the United States
4)  Congressional Record
This secondary source document describes the agreement between Columbus and Isabella.



** Introduction to U.S. History  :drill:
U.S. History on the Road

The National Park Service does an outstanding job of preserving the culture and history of America. In many of the history lessons, we will go on the virtual road to visit one or more of the National Park Service sites.

Our study of these National Park Service sites will serve as our connection to the past. "Arlington House, The Robert E. Lee Memorial" provides important information about American history. Used as a national cemetery today, it is a connection to the past and the family of George Washington.



** Introduction to U.S. History  :drill:
As you begin your journey of historical discovery, remember that you are following the footsteps of people from the past who were similar to you in many ways. They won, lost, loved, and hated; they lived and they died.

As you begin your lessons, think of America as it was when first discovered. Visualize the people who stood at the edges of pristine forests and breathed in the crisp air of a new world. Imagine how the promising but untraveled roads of their future became the faded trails of our glorious past.



** European Exploration  :drill:
Imagine that you are an explorer in the late 1400s traveling across vast lands and oceans, making new discoveries, and meeting new civilizations. What kind of impact would your discoveries have on your country and culture?

As you read this lesson, you will learn about the following topics:

•  the differences between the countries of the Old World

•  the Portuguese, Spanish, and French explorations of the New World

•  reasons people came to the New World



** European Exploration  :drill:
Old World

The countries of Western Europe including Italy, Spain, France, Portugal, and England represented the Old World.

Italy was the center of commerce and trade in the 1400s. The city-states of Italy contributed to a period of time known as the Renaissance which occurred from 1300 to 1600. The Renaissance witnessed a revival of interest in Greek and Roman culture.



** European Exploration  :drill:
Much of the Exploration and Colonial periods of literature involved personal journals and diaries from explorers and early colonists.

The Puritans, in particular, left behind many writings of early life in the English settlements of America. Anne Bradstreet settled with her husband in the Salem, Massachusetts, area in 1630. She was well known for her poetry and had the distinction of being one of the first women to have her literary works published.



** European Exploration  :drill:
Powerful monarchs ruled the countries of Western Europe in the 1500s. These leaders were eager to expand their treasuries with the riches of a colonial empire and encouraged overseas exploration.

An increase in revenue enabled monarchs to expand their armies and navies and contributed to their political power.

Rulers were also eager to establish colonies and trade opportunities.



** European Exploration  :drill:
New World

The New World consisted of the continents of North America and South America. The individuals and groups who populated the New World were the indigenous people. Indigenous means the people, plants, and animals that originate in a specific region. Native Americans are indigenous to North America.
The indigenous people of the Americas had civilizations, cultures, religions, political systems, economic systems, and languages. Some of the civilizations were more advanced than others in the New World. With the arrival of the European explorers to the New World, most of the civilizations were changed forever.



** European Exploration  :drill:
The extent of European exploration of the New World is shown on the map. Nearly all of North and South America was explored during early expeditions to the New World.



** European Exploration  :drill:
European exploration to the New World actually began around 1000 AD when the Vikings explored parts of North America.

Leif Erikson led the expedition that probably came ashore somewhere on the northern tip of Newfoundland. Erikson named the place Vinland.

However, the main focus of European exploration was to find new routes to East Asia.

** European Exploration  :drill:
Early European Travelers

"The people of Europe knew more of the lands of Asia than they knew of Vinland. For hundreds of years missionaries, traders, and travelers visited the Far East. They brought back to Europe silks and spices, and ornaments of gold and of silver. They told marvelous tales of rich lands and great princes. One of these travelers was a Venetian named Marco Polo. He told of Cathay or China and of Cipango or Japan.
This last country was an island. Its king was so rich that even the floors of his palaces were of pure gold. Suddenly the Turks conquered the lands between Europe and the golden East. They put an end to this trading and traveling. New ways to India, China, and Japan must be found…"

Channing, Edward. A Short History of the United States.



** European Exploration  :drill:



** European Exploration  :drill:
The first known European presence in the New World began with the voyage of Christopher Columbus, who landed in the West Indies in 1492.

Columbus was born in Genoa, Italy, but he sailed in service to Spain. He was convinced that Asia could be reached by sailing west. Columbus truly believed he was in Asia when he landed in the New World on the island of Hispaniola in 1492. Columbus eventually made a total of four trips to the New World.



** European Exploration  :drill:
Other explorers who followed after Columbus included:

John Cabot – sailed in service to England and discovered the continent of North America when he landed at Newfoundland.
Pedro Alvares Cabral – discovered Brazil and claimed it for Portugal.

Amerigo Vespucci – sailed in service to Portugal and Spain in the late 1400s and early 1500s. Vespucci was an Italian merchant and navigator who explored along the eastern coast of South America from 1499 to 1502. Some historians credit him as being the first to introduce the land he explored as the New World.

Giovanni da Verrazzano and Samuel de Champlain – sailed in service to France.

** European Exploration  :drill:
These men from Portugal, Spain, and France were responsible for important explorations of the New World.

Their explorations began a chain of events in the Old and New World that would form strong links to the cultures of today.



** European Exploration  :drill:
European Exploration - What Changed

"1. Towards the close of the fifteenth century the Turks cut off the old route of trade between Asia and Europe.

2. In attempting to find a new way to Asia, the Portuguese then began to explore the west coast of Africa.

3. When at last they got well down the African coast it was thought that such a route was too long."

McMaster, John Bach. A School History of the United States.



** European Exploration  :drill:
Portugal

Portugal was a leader in scientific advancements. It was the first nation to develop and use new navigational technologies.

In a quest for more trade and riches, expeditions from Portugal began to explore the Atlantic coast of Africa. Prince Henry of Portugal wanted to expand his country's trade and influence along the Atlantic Coast. An increase in trade, particularly from Africa, brought an increase of wealth through gold, and wealth brought more power to Prince Henry.
Eventually, the gold was not enough to satisfy the craving for wealth. Soon, the Portuguese looked beyond Africa to the East for trade with India.



** European Exploration  :drill:
"Shortly after establishing his school, two of Prince Henry's captains discovered the island of Porto Santo, and the following year the Madeira Islands were discovered…

Prince Henry's plan required the circumnavigation of Africa. His early voyages stayed close to the African coast. After repeated attempts, Gil Eanes finally rounded Cape Bojador on the west coast of Africa in present-day Western Sahara in 1434, a psychological, as well as physical, barrier that was thought to be the outer boundary of the knowable world…"

Federal Research Division of the Library of Congress.



** European Exploration  :drill:
Manuel I

"Manuel I assumed the throne in 1495 and completed the preparations for the voyage to India. On July 8, 1497, a fleet of four ships commanded by Vasco da Gama set sail from Belém on the outskirts of Lisbon. The expedition was very carefully organized, each ship having the best captains and pilots, as well as handpicked crews. They carried the most up-to-date nautical charts and navigational instruments. Vasco da Gama's fleet rounded the Cape of Good Hope on November 27, 1497, and made landfall at Natal in present-day South Africa on December 25.



** European Exploration  :drill:
The fleet sailed southwest for a month, and on April 22 sighted land, the coast of present-day Brazil. Cabral sent a ship back to Lisbon to report to Manuel his discovery, which he called Vera Cruz. The fleet recrossed the Atlantic and sailed to India around Africa where it arrived on September 13, 1500. After four months in India, Cabral sailed for Lisbon in January 1501, having left a contingent of Portuguese to maintain a factory at Cochin on the Malabar coast…"

Solsten, Eric, ed. Portugal: A Country Study. Washington: GPO for the Library of Congress, 1993.
In 1500 Manuel organized a large fleet of thirteen ships for a second voyage to India. This fleet was commanded by Pedro Álvares Cabral and included Bartolomeu Dias, various nobles, priests, and some 1,200 men.



** European Exploration  :drill:
Ferdinand Magellan

Ferdinand Magellan was a Portuguese sea captain who completed several trips around Africa to India and the East Indies. Magellan was convinced that a voyage to Asia would be shorter if he traveled west around the southern tip of South America. Magellan sailed on September 20, 1519, with 240 crewmembers and five ships.

Magellan landed in Brazil three months later and then continued sailing south down the east coast of South America.
The freezing temperatures and discontent of the crew led to an attempted mutiny, which Magellan successfully prevented. He then continued to sail around the southern tip of South America to the Pacific Ocean.



** European Exploration  :drill:
Upon his arrival at the Philippines, Magellan was killed in a battle with the local natives. His crew members retreated from the battle on the beach and set sail once more. They arrived back in Spain on September 6, 1522.
The first trip around the world had just been completed. Magellan's trip also determined the size of the Pacific Ocean and added mathematical confirmation to theories about the size of the world.

** European Exploration  :drill:
The Portuguese believed they could reach the East Indies by sailing south around the tip of Africa and then east to India. Portugal led the way in the search for a sea route to Asia, with Spain following closely behind. Both countries had similar goals to expand trade in Asia.

Before 1469, Spain had experienced religious issues that made it difficult to unite the country. Without unity, there was little action on the part of the monarchy to encourage exploration.



** European Exploration  :drill:
Explorers

Some historians believe that Ponce de Leon was a dreamer who believed in the stories of a magical fountain of youth. Dreamer or not, he was a dedicated explorer and traveled much of the territory of Florida in 1513 looking for gold and land he could claim for Spain. It is possible he also searched for the drink he believed would bring him eternal youth. Ponce de Leon also explored regions in the Bahamas and Puerto Rico.



** European Exploration  :drill:
Francisco Vasquez de Coronado set out on an expedition to find the legendary Seven Cities of Cibola in 1540. Coronado explored regions of the present-day states of Arizona, New Mexico, Texas, Oklahoma, and Kansas.
He found the villages of the Zuni Indians in 1540.



** European Exploration  :drill:
Hernando de Soto led another search for gold in the Southeast beginning in 1539. He sailed to the west coast of Florida from the island of Cuba. From 1539 to 1542, he explored as far north as North and South Carolina and as far west as Oklahoma.



** European Exploration  :drill:
Extent of Spanish Possessions

"Spain, at the close of the sixteenth century, held possession not only of the West Indies, but of Yucatan, Mexico, and Florida.

The Spanish explorers had traversed a large portion of the present Southern States, and of the Pacific coast. All this vast territory was claimed by the rights of discovery and possession.



** European Exploration  :drill:
"The conquests of the new world enriched Spain, which became the wealthiest and most powerful country in Europe. This made other nations all the more anxious to find the western passage to India. The routes by the Cape of Good Hope and by the Straits of Magellan were long and dangerous. To find the shorter northwestern route now became the great wish of all maritime nations, and has been anxiously sought down to the present time…"

Barnes & Co. A Brief History of the United States.



** European Exploration  :drill:
French Exploration

Spanish ships laden with gold and silver from the New World regularly crossed the Atlantic Ocean in the late 1500s. Was there another water route through or around the Americas to be found farther north? Explorers from France would search for the route to Asia, later known as the Northwest Passage.



** European Exploration  :drill:
Giovanni da Verrazzano was an Italian who sailed in the service of France in 1524. He explored the east coast of North America, searching for the Northwest Passage. He did not find a water route to Asia, but he discovered the present-day New York Harbor.



** European Exploration  :drill:
Jacques Cartier sailed to North America in 1534 in search of the Northwest Passage. He landed in Newfoundland and later explored the Gulf of St. Lawrence. He eventually discovered the mouth of the St. Lawrence River and was able to establish friendly relationships with the Iroquois Indians. The king of France proclaimed the territory explored by Verrazzano and Cartier as New France.



** European Exploration  :drill:
Brief attempts were made to colonize New France between 1541 and 1543. Later, the French focused on the economic benefits of the fur trapping trade. Most of the early settlements were only temporary quarters.
Quebec was one of the first permanent French settlements in North America and was founded in 1608 by Samuel de Champlain, a French soldier and sailor. Quebec was founded one year earlier than the English colony at Jamestown. In 1642, the French established a permanent settlement at Montreal.



** European Exploration  :drill:
The French eventually explored the territory from the Great Lakes to the Gulf of Mexico.

A French fur trader, Louis Jolliet, and a Catholic missionary, Jacques Marquette, explored the Great Lakes region. In 1613, Sieur de La Salle claimed the Mississippi Valley for France, which included the territory of the Mississippi.





Note: A portage is a location where a boat or canoe is carried because of a break in the waterways.



** European Exploration  :drill:
The territory was named Louisiana in honor of King Louis XIV of France. In 1718, French settlers established the Port of New Orleans.

The French now had two important settlements, one in the north at Quebec and one in the south at New Orleans. The French had not found the Northwest Passage, but they had gained a powerful position in the New World.



** European Exploration  :drill:
After European Exploration -
What Changed

All indigenous people who had contact with the Europeans experienced some type of change within their cultures and social institutions. For some people, even the status of their freedom was changed. Most of these changes were devastating to their cultures.

Civilizations in the Americas suffered from diseases brought to the New World by the Europeans and their livestock. These diseases killed many people and some domesticated animals.
Destruction of cities and enslavement of the people dramatically affected indigenous cultures and social institutions.



** European Exploration  :drill:
Some North American tribes were isolated from the Europeans and did not initially experience any change in their cultures. However, the civilizations and tribes were affected when the European colonists began to move across the North American continent.



** European Exploration  :drill:
Connections

Let's examine some connections from the period of European exploration to the modern world.

Look at the following demographic information about Canada, Mexico, and Brazil. Can we determine the exploration history of these countries from this information?



** European Exploration  :drill:
Canada

"Ethnic groups: British Isles origin 28%, French origin 23%, other European 15%, Amerindian 2%, other, mostly Asian, African, Arab 6%, mixed background 26%

Religions: Roman Catholic 42.6%, Protestant 23.3% (including United Church 9.5%, Anglican 6.8%, Baptist 2.4%, Lutheran 2%), other Christian 4.4%, Muslim 1.9%, other and unspecified 11.8%, none 16% (2001 census)

Languages: English (official) 59.3%, French (official) 23.2%, other 17.5%"

The World Factbook. 2007.
We can see that there was a French and English influence in Canada in the past. France was a Catholic country, and England was Protestant. These factors contributed to the diversity of religions and languages.



** European Exploration  :drill:
Mexico

"Ethnic groups: mestizo (Amerindian-Spanish) 60%, Amerindian or predominantly Amerindian 30%, white 9%, other 1%

Religions: nominally Roman Catholic 89%, Protestant 6%, other 5%

Languages: Spanish, various Mayan, Nahuatl, and other regional indigenous languages."
The World Factbook. 2007.

Current statistics often reflect the regional heritage of past inhabitants.



** European Exploration  :drill:
The influence of Spanish exploration is evident in Mexico and throughout most of Central and South America.

The mestizos are an ethnic group that account for 60% of the population in Central and South America. A mestizo is a person of mixed ancestry. The term mestizo is usually applied to someone of Native American and white ancestry in Latin America.

Spain was a Catholic country. The influence of this religious aspect of Spain is evidenced by the high percentage of Catholics in Mexico. The Spanish language is also spoken throughout most of Central and South America.



** European Exploration  :drill:
Brazil

Brazil was founded by settlers from Portugal, another Catholic European country. Most of the members of this ethnic population are descendants of people who emigrated from Portugal to Brazil. The official language is Portuguese.

"Ethnic groups: homogeneous Mediterranean stock; citizens of black African descent who immigrated to mainland during decolonization number less than 100,000; since 1990 East Europeans have entered Portugal
Religions: Roman Catholic 94%, Protestant and other 6% (1995)

Languages: Portuguese (official), Mirandese (official - but locally used)"

The World Factbook. 2007.



** European Exploration  :drill:
The effects of the European exploration of the New World can be seen even though it began over 500 years ago. European exploration has influenced the United States in the areas of architecture, customs, religions, languages, and the names of cities and states.

Los Angeles and San Francisco are examples of cities with names of Spanish influence. Detroit is a French word. Some names come from regions in the Old World such as New Hampshire, New Jersey, and New Orleans. Other names such as Mississippi and Chicago, which are taken from the Algonquin language, originate from Native American languages.



** European Exploration  :drill:
The exploration of the New World was undertaken with the intent of finding a new route to the Indies. No one realized at the time that vast continents of unknown lands, resources, and civilizations existed on the other side of the ocean. Many lands of the New World were explored and in some cases conquered all in the name of science, learning, and the powerful monarchs of Europe.



** European Exploration  :drill:
What proved to be beneficial for some civilizations was catastrophic for others. We can look back at this series of events and see a correlation in events of today. It is the duty of societies and their leaders to balance the issues of today with considerations of future consequences.



** European Exploration  :drill:
U.S. History on the Road

The National Park Service performs an outstanding job of preserving the culture and history of America. We will explore some national parks that feature a connection from the present day to the period of European exploration in North America.

Our first stop is the Acadia National Park located in Maine. This was the first national park established east of the Mississippi River.



** European Exploration  :drill:
The Great Exploration Race

With the discovery of unknown lands in the New World, early explorers and monarchs were faced with new decisions. Should money be invested for in-depth exploration of the New World, or should the search continue for a new route to the Indies?

Europeans were looking for a safe route to the source of the savory spices used to flavor food. The military might of the Turks had cut off that source of goods, blocking the land route from Europe to the Middle East. This blockade ended the Italian merchants' control of the spice trade, a control that had lasted over 400 years.



** European Exploration  :drill:
Initially, the desire for wealth won out. Exploration became a fierce competition between the Spanish, Dutch, British, and Portuguese explorers to reach the Middle East.

Leaders were not interested in the control of petroleum oil in the Middle East. In the fifteenth century, oil was not considered a valuable commodity, simply because technology did not require the use of this type of resource. Economic power was the resource desired, and the profits derived from spices were an invaluable source of wealth.



** European Exploration  :drill:
Today, it is hard to imagine eating food without any type of spices; no pepper, cloves, cumin, or cinnamon. Many spices commonly used today were once found almost exclusively in the Middle Eastern regions, throughout the Middle Ages and beyond.

The wealth generated by the sale of spices made finding a safe and inexpensive route to the Eastern regions important to the ruling class in European countries. The great exploration race to find spices and new sources of wealth had begun.



** European Exploration  :drill:
As you complete this lesson and learn about the explorers involved in the great race and the resulting colonization of the Americas, you will also make many discoveries of your own. You will find:

•  how the marital situation of King Henry    VIII of England contributed to English colonization

•  why religious dissension brought families to the New World

•  how the economic system of mercantilism was formed
•  why a strong political and economic relationship was forged between England and the British colonies in America



** European Exploration  :drill:
Early Explorers

Christopher Columbus was dedicated and persistent. He wanted to explore the New World and believed Asia could be reached by sailing to the west. Even though his own country would not support his views, he finally convinced the king and queen of Spain to finance his expeditions.

Although Columbus did not discover a westward sailing route to India in 1492, he did discover the West Indies. The West Indies proved to be a rich source of raw goods and materials for Spain.



** European Exploration  :drill:
A Portuguese explorer who was also sailing under Spain's payroll commanded the first expedition around the world.

Ferdinand Magellan sailed west from Europe in 1520. By chance, he found a water passage from the Atlantic Ocean to the Pacific Ocean off the coast of South America. This passage was later named the Strait of Magellan.

Unfortunately, Magellan died during the voyage and never lived to see his ship and eighteen of his crew members return to Spain.



** European Exploration  :drill:
Battle for Power

Although monarchs were still interested in spices, they had found a new way to make money by importing raw goods and materials from the New World.

Near the end of the 1500s, Spain was the most powerful European country to claim colonies in the New World. The wealth of the New World colonies plus the strength of the ships of the Spanish Armada put Spanish monarchs at the top of the power pyramid. The old balance of power in Europe had shifted, but not for long.
In 1588, the English Navy battled with the forces of the powerful Spanish Armada. English sailors fought and defeated the Spanish fleet of ships. Power shifted once more, and this time, England forged ahead to the number one spot.



** European Exploration  :drill:
John Cabot

With the discovery of land in the New World, the English "jumped on board." They outfitted ships and began exploring just five years after the first voyage of Christopher Columbus.

John Cabot (c.1450–1498) was Italian born and financially backed by English investors. His voyages established England's claim to the New World.

Cabot landed at Newfoundland in 1497. Despite his journey to the New World, England made few attempts to colonize.
England was busy with political and religious problems on the home front. North America was not formally colonized until eighty years after Cabot's journey to Newfoundland.

Permanent communities in the New World were not established until the British and French began to colonize North America.



** European Exploration  :drill:
British Explorations

Human curiosity was part of the reason for continued exploration by England. The allure of vast oceans and uninhabited land as far as the eyes could see was too tempting.
Sir Humphrey Gilbert (c.1537–1583), an English explorer, made a series of attempts to establish colonies in the Americas. He gave up trying to establish colonies after experiencing several misfortunes and rising debt.

Martin Frobisher (c.1535–1594) made three voyages from 1576 to 1578, searching for a northwest passage to Asia. He had little interest in colonization. Colonizing the New World involved a lot of hard labor. Most explorers were more interested in finding easy riches, such as gold and jewels.



** European Exploration  :drill:
In 1577, Sir Francis Drake (c.1540–1596) made a famous trip around the world. This was indisputable proof to Englishmen that the world was, indeed, round.

The combined voyages of all these explorers convinced England that the New World had a wealth of resources to offer. New resources and an abundance of land were powerful lures for a country with limited space.



** European Exploration  :drill:
Sir Walter Raleigh

Sir Walter Raleigh (c.1552–1618) was one of the English explorers who searched for a southern, rather than a northern, route to North America. Raleigh was also instrumental in establishing a colony in Virginia.

The efforts of Raleigh aroused an interest in England to colonize the New World. Some investors were interested in colonization because of the financial success of the Spanish colonies. Some Englishmen held out hope that a route to Asia would be found.



** European Exploration  :drill:
Other groups in England viewed the New World as an opportunity to escape religious persecution, especially after the Stuarts took power in 1603.

Most English politicians wanted to establish North American colonies to limit Spanish and French expansion in the region. For this group of people, maintaining or gaining economic and military power over other countries was more important than exploring for the sake of curiosity.



** European Exploration  :drill:
Untamed Wilderness

Imagine you left your warm, comfortable home and everything that was familiar to you. What would be the consequences of leaving behind well-stocked markets and civilization to start a new home in a sparsely inhabited and frightening wilderness?

The wilderness might contain ferocious animals, poisonous snakes, and unknown plant life.

If you had no shelter or convenient food sources, what would you do for survival? Why would anyone choose to face such daunting and arduous circumstances?

** European Exploration  :drill:
Living in the New World

The reasons for choosing to immigrate to the New World with its unexplored tracts of wilderness were as varied as the people themselves. For many people, the new lands proved to be a prosperous and successful change; for others, however, the move proved to be disastrous.
In 1587, a group of British citizens ventured across the ocean, and an attempt was made to establish a colony on Roanoke Island off the coast of North America. When the colonial governor John White returned from England with more supplies, all the colonial inhabitants had mysteriously vanished.

However, tragic events such as those on Roanoke Island did not stop people from immigrating to North America, particularly people who were looking for religious freedom.



** European Exploration  :drill:
British Religion

Religion was one of the primary reasons for the establishment of the early colonies.

Nearly all the people living in Europe before 1492 belonged to the Catholic Church. The Catholic Church controlled most of the social institutions, including economic systems, education, and family life. Most of the monarchs in Europe were Catholic and were also controlled by the Catholic Church.

A German priest named Martin Luther began a movement in 1517 that became known as the Protestant Reformation.
With the Reformation, the power of the Catholic Church was changed forever. Europe became religiously divided. This, in turn, brought an abundance of diverse religions to colonies through each country's explorers and missionaries.



** European Exploration  :drill:
The Marriage of Arthur

After the Protestant Reformation, England remained a Catholic country. Catherine of Aragon from Spain was a Catholic and the daughter of King Ferdinand II of Aragon and Queen Isabella of Castile. Queen Isabella was the monarch who supported the voyages of Christopher Columbus to the New World.
Catherine was sixteen when she first met Prince Arthur, son of Henry VII from England. Imagine sailing across a turbulent sea to land in a country where another language was spoken and customs were very different.

That is exactly what Catherine did in order to marry Prince Arthur. Her young marriage lasted only six months before her husband died from an illness. Catherine later became betrothed (engaged) to her former husband's brother, Prince Henry VIII.



** European Exploration  :drill:
The Marriage of Henry VIII

At the time Prince Henry was engaged, he was only ten years old, too young to marry Catherine. The British king, Henry VII, would not allow Catherine to return home and instead kept her at the court in England until 1509. After the death of Henry VII, his son Henry VIII married Catherine.



** European Exploration  :drill:
Despite many pregnancies, Catherine had only one child who survived to adulthood. That child was Princess Mary. Because the average life span in 1526 was approximately the mid-fifties, Catherine discovered that she was unable to conceive any more children by the time she was forty-one.

King Henry was desperate for a son and decided to annul his marriage to Catherine to marry Anne Boleyn. The obstacle to the marriage was the Catholic pope. The pope refused to annul Henry and Catherine's marriage for fear of reprisals by Charles V, the King of Spain. Catherine had asked Charles V, her nephew, to help her retain her position as Queen of England.



** European Exploration  :drill:
Church of England

Concerned over the lack of a male heir, Henry took drastic action. He broke away from the Catholic Church and many of its beliefs. In 1534, the English Parliament passed the Act of Supremacy, which declared the king as the head of the Church of England. This gave Henry the authority to grant a divorce to himself. Henry would later behead two of his wives in an attempt to marry other women who might give birth to an heir.



** European Exploration  :drill:
England was now a Protestant country, which would become an important aspect in the settlement of the thirteen original colonies. The Church of England, also known as the Anglican Church, included beliefs and ceremonies that were both Protestant and Catholic in origin.

Differences in religion among England, Spain, and France would become another source of friction in Europe and North America in the 1700s.



** European Exploration  :drill:
Puritans

One of the major religious disagreements in England involved a group known as the Puritans. The Puritans were upset because the Church of England retained too many Catholic rituals and ceremonies.

The Puritans wanted to "purify" the Church of England and eliminate anything remotely related to the Catholic religion.

James I, King of England in 1603, was loyal to the Church of England and began to persecute the Puritan people for their religious views. Many Puritans were forced to leave England.




** European Exploration  :drill:
Separatists

Another religious group, the Separatists, was also active in England at the time. The Separatists believed that the Church of England could not be reformed. These individuals started their own congregations that were separate from the Church of England. The Separatists founded the Congregational Church.

Separatist groups were considered illegal in England. Many of the members fled to other countries in Europe and eventually to America. The Pilgrims who landed at Plymouth in 1620 were Separatists.



** European Exploration  :drill:
Jamestown

Jamestown, established in 1607, was the first successful English colony in North America. The Virginia Company of London, a joint-stock company, financed the colony. The original purpose of the colony was to search for gold.

Another colony established by a joint-stock company was Massachusetts Bay in 1630. Some colonies, such as the Carolinas and Pennsylvania, were proprietary colonies. The proprietors were usually given access to these colonies because they were friends of the monarch who owned the land rights.



** European Exploration  :drill:
Mayflower Compact

The Pilgrims landed at Plymouth in 1620 and created a set of rules before going ashore. The group created a document titled the Mayflower Compact that outlined how to govern the colony. Everyone in the colony agreed to abide by the government created through this document.

The Mayflower Compact is considered by some historians to be the first written constitution in North America.



** European Exploration  :drill:
Colonial Government

All the English colonies had an elected assembly that passed laws at the local level. The Parliament in England also appointed a royal governor in each colony to carry out the policies of the English government. The royal governor reported to the English Parliament.
The royal governor also had to cooperate with the local assembly in the colony. For example, the local assembly had to approve the decrees of the royal governor as well as his salary. This gave the local people some control over their political affairs.

The colonists were allowed to have some control as long as they followed the laws and rules of the Parliament and the king.



** European Exploration  :drill:
English settlers often signed peace treaties with American Indians, even though some colonists illegally moved into native territories. This type of behavior initiated an ongoing conflict between the indigenous people and colonists through the 1700s.
The English wanted to establish populous colonies in North America. Colonial growth eventually led to a westward movement. This expansion would bring the colonists into direct conflict with the French and the American Indian tribes.



** European Exploration  :drill:
Passage to America

Puritans seeking freedom from religious persecution founded colonies in Massachusetts Bay, Connecticut, and Rhode Island. Catholics found refuge in Maryland, and Quakers usually settled in Pennsylvania. Pilgrims seeking both political and religious freedom founded the Plymouth Colony in 1620.

Many individuals found economic opportunities in the New World, although some people came to the English colonies as indentured servants.



** European Exploration  :drill:
Instead of paying for a boat ticket in cash, individuals often agreed to work for a company or individual in exchange for their tickets to the New World. This sometimes led to abusive situations for indentured people. Indentured servants often lived as slaves for a predetermined amount of time and had few rights or liberties.

African slaves were also brought involuntarily to America in the early 1600s. This was the beginning of a social issue that would later divide a nation.



** European Exploration  :drill:
Riches and Land

In the beginning days of colonization, there were three main groups of colonies in America.

New England Colonies
Massachusetts
Connecticut
New Hampshire
Rhode Island

Economy: small farms, shipbuilding, fishing, whaling, and some manufacturing






Middle Colonies
New York
Pennsylvania
Delaware
New Jersey

Economy: small farms and some manufacturing



** European Exploration  :drill:
Southern Colonies
Virginia
Maryland
South Carolina
North Carolina
Georgia

Economy: cotton and sugar and a plantation system that depended on slave labor

The settlement of colonies opened up new territories for trade. This expansion led to a huge transformation in the economies of Europe.



** European Exploration  :drill:
Entrepreneurs

Many merchants and nobles were willing to risk financing overseas ventures. The merchants who took these risks were known as entrepreneurs. Still, the risks were high. Attacks by pirates, storms, and desertion of crews could mean financial disaster for an investor.

The entrepreneurs developed systems of insurance to cover any possible losses. Some entrepreneurs developed partnerships or invested in several ventures in order to reduce the risk of losing all their fortunes.
Merchants often formed joint-stock companies that sold shares to investors. The sale of shares raised the money, or capital, to finance a voyage to the New World. If a businessman could convince a king or queen to grant a royal charter for a trading company, he was usually assured of a successful business.



** European Exploration  :drill:
Mercantilism

European monarchs realized their political power was dependent on the economic stability of their countries. Gold wasn't enough; a country needed a global market to sell goods. The economic philosophy of mercantilism was developed in the 1600s. This economic system would create a strong relationship between England and its North American colonies.

Under the system of mercantilism, England would produce manufactured goods out of raw materials sent over from the colonies.
Click the image for a larger view.



** European Exploration  :drill:
In turn, the colonies established markets where the manufactured goods from England could be sold. This created a triangular trade that was beneficial to the colonies as well as England.

The mercantile system became an important economic element of the English colonies.



** European Exploration  :drill:
Changes – The Glorious Revolution

The English kings and Parliament had a policy of salutary neglect concerning the colonies. This policy allowed the colonies to prosper without the strict enforcement of the laws passed by Parliament in England.

The colonial governments were left alone as long as there were no political or economic problems. The policy of salutary neglect lasted from 1607 to 1775, even after the Glorious Revolution. The Revolution resulted in the defeat of James II by William of Orange and Mary II.
Even though the English did try to enforce some Navigation Acts during the mid-1600s, salutary neglect changed little from 1607 to 1700.

This relationship between the English colonies changed dramatically in 1688.



** European Exploration  :drill:
Continuity – The Glorious Revolution

The Glorious Revolution in 1688 did not change the political status of the English colonies in America. Colonists still considered themselves English citizens and equal to citizens actually living in Britain.

However, the political independence enjoyed in the management of their local affairs for over eighty years was very important to the colonists.

Many adventurous individuals were still exploring the frontier, and they preferred the liberties afforded them under local rules.



** English Colonies  :drill:
Colonization

The colonization efforts of England in North America took place over an extended period of time. The first of the original colonies was established in 1607 at Jamestown. This was the beginning of the Virginia Colony.

It took 125 years to establish all of the English colonies in America. Colonization in North America under British rule would not end until the founding of Georgia by James Oglethorpe in 1732.
Many economic decisions in the colonies eventually led to a break from England and the established government of America today.



** Revolution in the Colonies  :drill:
Throughout history, war has followed in humankind's footsteps. Why do nations go to war? This question has been debated by people for centuries.
Many factors affect a nation's decision to go to war: the need for land, resources, money, and differences in politics, cultures, and religious beliefs. Any of these reasons can be the cause of a war.

A variety of political and economic issues affected the colonies from the mid-1600s to 1781 and led to war. The causes and effects of these issues resulted in the American Revolution and the eventual defeat of the British Army at Yorktown.



** Revolution in the Colonies  :drill:
How does war affect government, culture, society, and future generations? Just like people today, people in the past felt many emotions, including anger, impatience, and fear, regarding war. In our study of early colonial days, you will learn how events and emotions contributed to the following situations:

• The fear of war and its high cost caused trouble in the colonies.

• Anger over the economic and political relationship between England and the North American colonies from 1688 to 1775 led to revolution.
• Economic dependence between England and the North American colonies included the triangular trade, mercantilism, and the Navigation Acts.

• The determination and courage of colonists brought forth a generation of committed military and political leaders.



** Revolution in the Colonies  :drill:
English Monarchs from 1688 to 1820

Even though an ocean separated the colonies from England, there was a complex relationship of government and economics between them.

Let's examine the English monarchs who influenced the colonies from the time they were established until the rumblings of war began. This examination will reveal how the negative effects of this relationship finally outweighed the benefits. It will also reveal how wars across the ocean had a direct and negative impact on the colonies.



** Revolution in the Colonies  :drill:
In the New World, there were many colonies, some English, some French, and some Spanish. Wars that started in Europe between European rulers reached across the ocean and ignited confrontations in the colonial territories. These wars dramatically changed the politics and territorial possessions in the New World.

Let's meet the English monarchs who reigned from 1688 through the Revolutionary War and beyond.



** Revolution in the Colonies  :drill:
William III and Mary II

In 1688, Parliament offered the English throne to Mary (1662–1694), the Protestant daughter of James II by his first wife. The offer and acceptance of this monarchy would later be called the Glorious Revolution because it firmly placed Protestant rulers on the British throne. Mary was married to William III (1650–1702), a Dutch ruler who was also a Protestant.

William III was also known as William of Orange. William and Mary were named joint monarchs of England as King William III and Queen Mary II.



** Revolution in the Colonies  :drill:
Anne

Anne (1665–1714) was the daughter of James II and sister of Mary II. Anne was the last Stuart to sit on the throne of England. She became Queen of England in 1702. During her reign in 1707, the kingdoms of Scotland, England, and Wales were united into what is now known as Great Britain.



** Revolution in the Colonies  :drill:
George II

George II (1683–1760) became King of Great Britain upon the death of his father in 1727. He was the last British monarch to lead his troops into battle. He was the monarch at the beginning of the French and Indian War.
George I

George I (1660–1727) became the British monarch in 1714. He was a distant cousin of Queen Anne. George was a German and did not speak English very well. He knew little of English politics and relied on his minister, Sir Robert Walpole, to make political decisions.



** Revolution in the Colonies  :drill:
George III

George III (1738–1820) became king in 1760 upon the death of his grandfather, George II. Very active in politics, he reigned during the American Revolution and for many years thereafter. George eventually suffered from a mental illness, and by 1810, he was considered to be insane.



** Revolution in the Colonies  :drill:
European and Colonial Wars

Four colonial wars in the late 1600s originated from the politics of the European monarchs. The main combatants, England and France, became involved in the struggle for power and territory in Europe. Because of political events at home, England did not fully recognize the presence of the French in the New World during the 1600s.



** Revolution in the Colonies  :drill:
French and Indian Wars

"The various wars with the French and the Indians, trivial in detail as they seem today, had a profound influence on colonial life and on the destiny of America. Circumstances beyond the control of popular assemblies, jealous of their individual powers, compelled cooperation among them, grudging and stingy no doubt, but still cooperation. The American people, more eager to be busy in their fields or at their trades, were simply forced to raise and support armies, to learn the arts of warfare, and to practice, if in a small theater, the science of statecraft.
These forces, all cumulative, drove the colonists, so tenaciously provincial in their habits, in the direction of nationalism."

Beard, Charles A. and Mary R. Beard. History of the United States.

The growth of nationalism was yet another move toward independence for the English colonies.



** Revolution in the Colonies  :drill:
The Colonies and England – What Changed

Before 1688, the English kings and Parliament held a policy of salutary neglect. This policy meant the people of the colonies could buy property and goods, build homes, raise families, and earn a living, all without the strict enforcement of laws passed by Parliament in England.

The policy of salutary neglect lasted from approximately 1607 to 1775. However, the relationship between the English colonies and England changed dramatically in 1688.



** Revolution in the Colonies  :drill:
Political Issues

What brought about a change in the relationship and the salutary neglect policy? It was the Glorious Revolution in England in 1688. With a stable Protestant monarchy, England could finally turn more of its attention to the colonies.
For a brief time after the Glorious Revolution, the political status of the English colonies in America remained the same. The English colonists still considered themselves to be a part of England, even though political independence was very important to them in the management of their local affairs.



** Revolution in the Colonies  :drill:
Mercantilism

Under the mercantile system, England was the main producer and supplier of manufactured goods for the colonies. Raw materials for producing these goods would come from the colonies.
The mercantile system and triangular trade became important elements of the economy in England and its colonies.
 
Mercantilism was a closed system, meaning this type of trade was closed off to everyone except England and its colonies. What would happen to the system if some colonies sent raw materials to a foreign nation such as Spain? England would lose money. Therefore, to maintain economic control over the colonies, the English Parliament passed a series of Navigation Acts in the 1600s that were part of the mercantile system.



** Revolution in the Colonies  :drill:
The Navigation Acts

The Navigation Act of 1651 stated that products from a foreign country had to be shipped to England in English ships. In addition, three fourths of the crew had to be Englishmen. This act was designed to prohibit American colonists and the Dutch from producing trade profit between Europe and the West Indies.



** Revolution in the Colonies  :drill:
Parliament passed another Navigation Act in 1660 which required all tobacco grown in the colonies to be sent to England. The 1663 Navigation Act declared that most goods imported into the American colonies must first be brought to England.

The 1672 Navigation Act became even more restrictive. This act required that any goods sent from one colony to another must first be shipped to England, severely restricting the triangular trade in the colonies.
The New England colonies were known  for making rum, which was part of the triangular trade. One of the ingredients in rum was sugar.



** Revolution in the Colonies  :drill:
Molasses Act of 1733

The New Englanders usually purchased a lower-priced sugar from the French West Indies instead of the British West Indies. Parliament passed the Molasses Act of 1733 that levied a high duty on sugar imported from the French West Indies.

The English made an attempt to enforce the provisions of the Molasses Act. However, widespread smuggling by the colonists made it difficult to enforce. The restrictions placed on the economy and the decision to enforce the Molasses Act caused resentment among the colonists.
The Molasses Act had become a sticky situation and one of the root causes of the American Revolution.



** Revolution in the Colonies  :drill:
Many other acts were passed by Parliament in the 1700s to maintain the mercantile system. Some of the most significant economic acts were passed in the 1760s, following the end of the French and Indian War.

This map illustrates the imports from Great Britain from 1763–1776.
Click the image for a larger view.



** Revolution in the Colonies  :drill:
The Townshend Acts

The British passed many new policies, including the Townshend Acts, which affected the economies and political climate of the American colonies. These acts placed new taxes on the colonists to help fund Great Britain's wars.
Read about the effect of British policies on the colonies.



** Revolution in the Colonies  :drill:
The Navigation Acts passed by the English Parliament initiated a growth of dissension in the colonies, which led to an expansion of ideas and political viewpoints among the inhabitants. In essence, the colonies were forced to have:

•  all goods sent back and forth to England on English ships

•  shipments of products going to the colonies pass through England first

•  expensive import taxes on sugar, tobacco, and rum from certain ports



** Revolution in the Colonies  :drill:
1) He or she carried the bottle to the counter to ring up the price.

2) He or she determined the taxes on the item.

3) He or she passed the bottle to the counter for payment.

You might find the extra steps required in purchasing an item a bit irritating.

The colonists did too!
Although the acts were not consistently enforced, they imposed extra burdens on the colonists.

To identify with how these acts affected colonists, consider the following scenario.

Suppose you went to the store to buy a bottle of water, and the clerk told you to wait until the store manager performed the following tasks:



** Revolution in the Colonies  :drill:
Call for Independence

The seeds of dissension were sown. A Virginian named Richard Henry Lee introduced a resolution to the Second Continental Congress on June 7, 1776. The resolution stated:

"Resolved, That these United Colonies are, and of right ought to be, free and independent States, that they are absolved from all allegiance to the British Crown, and that all political connection between them and the State of Great Britain is, and ought to be, totally dissolved."

Lee, Richard Henry. Lee Resolution. 1776.



** Revolution in the Colonies  :drill:
Many conflicting ideas were written in pamphlets and newspapers by people who were for or against independence. Not all of the colonists supported the cause for independence. Some family members even found themselves supporting different sides during the Revolution. For example, Benjamin Franklin's son supported the English in the Revolutionary War.

The colonists were divided into three camps. One third of the colonists favored the cause for independence, one third favored the English crown, and one third was indifferent to either side.



** Revolution in the Colonies  :drill:
There were other political issues in the Second Continental Congress as the colonial leaders struggled to finance a war. Providing political leadership proved to be an ongoing battle while supplying an army without the framework of a central government.

As the people sacrificed to support the war effort, political and economic issues spread throughout the colonies and to foreign countries. Colonial representatives were trying to receive foreign aid and recognition for the New World.
Local inhabitants of the colonies began to unite and pool their resources. They also began to apply economic power and political intelligence to the problems of war and the growth of a new nation.



** Revolution in the Colonies  :drill:
U.S. History on the Road

Let's go on the road to visit some of the Revolutionary War sites from the National Park Service. These sites are an essential connection to our past and to the culture of the United States, representing only a small portion of the fighting that occurred during the Revolutionary War. Many other battles, both large and small, contributed to the victory for independence by the colonists.
Wars from overseas brought about a chain of events that impacted the colonies. These events brought war to the colonies and united a diverse group of people into a cohesive and powerful force–a force that would challenge the might of one of the greatest nations on earth and win.



** Foundation of Government  :drill:
A New Nation

As the colonists began to pull together against a common enemy, other governments in Europe began to take a special interest in the events that were unfolding across the sea. The enemies of England, particularly France, saw a possible ally but approached the situation with caution. Was it possible that such a small confederation of colonies could actually defeat the might of England? What did these colonial rebels really want from the countries of Europe, if anything?



** Foundation of Government  :drill:
In the colonies, people were still unsure of what they wanted as a result of the war, but they were united in what they did not want. They did not want to be used as an economic convenience by England; they did not want their rights as English citizens to be ignored; and they did not want absolute authority imposed over their colonial governments.



** Foundation of Government  :drill:
When people work together for a common goal, they often discover a strong sense of unity and pride. As you discover what colonists had in common and where they had differences among themselves, as well as with England, you will learn:

• how political sectionalism began to divide a recently unified nation

• how significant political events led to the writing of the U.S. Constitution

• why people were afraid of a strong federal government



** Foundation of Government  :drill:
Colonial Government

During the early years of the colonies, the English king and Parliament followed a policy of salutary neglect. The colonists were left alone to manage their own political and economic affairs.

People of the early colonies were not united politically with one another. Each colonial government interacted with British officials independently of other colonies. The independent spirit of these early governments would later be reflected in the writing of the United States Constitution.



** Foundation of Government  :drill:
Albany Plan of Union

There was an early call for a union of the colonies in 1754 at Albany, New York. Delegates from seven colonies and representatives of the Iroquois tribe attended this congress. The purpose of the meeting was to improve relations between the Native Americans and the colonists.

The Albany Plan of Union was formed under the leadership of Benjamin Franklin. This plan, however, was never implemented.



** Foundation of Government  :drill:
Colonial Wars

While the colonists were debating local issues, European monarchs were waging wars. Some of these wars were fought on North American soil. The British government expected the colonists to help pay for these wars through taxation. The colonists objected to taxation because they were not represented in Parliament.



** Foundation of Government  :drill:
Bullets and Bayonets

Petitions to England had only limited success. Soon, small fights and skirmishes began to break out between the colonists and British soldiers. On April 19, 1775, a local group of men formed a fighting force called the Minutemen. Ready to fight at a minute's notice, these men prepared to confront the march of British soldiers in Lexington.
The Minutemen believed they were English subjects trying to protect their citizens' rights. However, they did not allow themselves to be intimidated by confrontation with British soldiers. In a "shot heard 'round the world," battle broke out between the two sides. Eight colonial men were killed and ten were wounded by the bullets and bayonets of the soldiers.



** Foundation of Government  :drill:
Declaration of Independence

The confrontation in Lexington began a period of colonial dissension against England. The call for total independence from England, however, was not made until a year later.

Thomas Jefferson authored the Declaration of Independence that was proclaimed on July 4, 1776. Included with the Declaration of Independence was another list of grievances American colonists had against King George III.



** Foundation of Government  :drill:
Changes - Articles of Confederation

Change swept through the colonies as they succumbed to war. During the convention of the Second Continental Congress in 1781, colonists formed a government under the Articles of Confederation. The people in the colonies needed to be organized in order to effectively fight a war with England.

The Articles of Confederation was the first attempt of the colonists to write a constitution. The men who wrote the document were worried that a powerful central government would become too strong. The authors of the Articles of Confederation determined that for the time being, each state would retain control over any form of central government.



** Foundation of Government  :drill:
Managing the war was difficult for the Second Continental Congress without the political power of a central government.
The army needed supplies, and the soldiers had to be paid. In their fear of an overly strong central government, the colonists had not granted Congress the power to tax the states.

In 1786, a group of delegates from five colonial states met in a convention at Annapolis, Maryland. The men gathered to discuss commerce among the states but decided that the Articles of Confederation needed to be revised. A new convention was scheduled to meet in Philadelphia. The topic of conversation was the weaknesses and revision of the Articles of Confederation.

** Foundation of Government  :drill:
Continuity - Representation

The early leaders of the colonies chose a representative form of government similar to Parliament in England.

Under the Articles of Confederation, a single body called the Congress would govern the United States by the following rules:

• States would choose representatives to Congress on a yearly basis.

• Every state would have one vote in Congress.
• Congress could pass a law whenever nine or more of the thirteen states voted for it.

• The Articles could not be changed unless all the states agreed. There was no chief executive, Supreme Court, or national system of lower courts.



** Foundation of Government  :drill:
State Powers

Representatives of the states, afraid of creating a dictatorial government, refused to allow a strong central power in the colonies. Although the Second Continental Congress requested funds from each state, the requests were often ignored. The government usually operated on borrowed money because Congress had no power to enforce requests to the states for money.

Many Americans agreed that the Articles of Confederation were too weak to provide an effective government.
The Articles of Confederation remained in effect from March 1, 1781, to March 3, 1789. The Constitution replaced the Articles of Confederation.



** Foundation of Government  :drill:
Government Weakness

"During the war the thirteen States had agreed upon Articles of Confederation, but they conferred little power on Congress. It could recommend, but not enforce; it could only advise action, leaving the States to do as they pleased. Bitter jealousy existed among the several States, both with regard to one another and to a general government. The popular desire was to let each State remain independent, and have no national authority. A heavy debt had been incurred by the war.
Congress had no money and could not levy taxes. It advised the States to pay, but they were too jealous of Congress to heed its requests. "We are," said Washington, "one nation to-day, and thirteen tomorrow." In New England, large bodies of men assembled, refusing to pay their taxes and openly threatening to overturn the government. This insurrection, known as Shays's Rebellion, from the name of its leader, was put down by the militia under General Lincoln.''

Barnes & Company. A Brief History of the United States.



** Foundation of Government  :drill:
Shays's Rebellion

The event known as Shays's Rebellion took place in Massachusetts in 1786 and 1787. After only ten years of liberty, local dissension rumbled through the newly formed country.

After the war for independence, farmers returned home with empty pockets. The government could issue only promissory notes, which few farmers were able to redeem. Even though the farmers worked to reestablish productive farms, taxes began to drain away the small amount of money and goods they owned.
Upset over the possibility of debtor's prison, the farmers marched under Daniel Shays's leadership and staged a rebellion, refusing to pay a new tax on whiskey. The rebellion was eventually brought under control by President Washington's troops.



** Foundation of Government  :drill:
Nationalism

By the late 1700s, America was achieving recognition on a global scale by long established countries in Europe. Nationalism, a sense of pride and community bonding, was the result of American victories and intercontinental political recognition.

With this spirit of nationalism, the newly formed states took a detailed look at their new government and examined the strengths and weaknesses of the Articles of Confederation.



** Foundation of Government  :drill:
The Constitution

When delegates from twelve states gathered in Philadelphia, Pennsylvania, on May 25, 1787, Rhode Island was the only state not represented at the convention. The fifty-five men present were determined to have a new constitution rather than fix the problems with the Articles of Confederation.

The political leaders who authored the Constitution had differing views on how it should be interpreted. These men were worried that a strong central government would take away the political power of the states and the people.
Many of the men who first met at the Constitutional Convention in Philadelphia had fought in the Revolutionary War. They had experienced many losses, including beloved friends and family and various financial goods.



** Foundation of Government  :drill:
In the minds and hearts of these men, the tyranny of British King George III was responsible for the losses they had suffered. They were hesitant to create any form of government that might bring another tyrant into power.



** Foundation of Government  :drill:
Political Groups

There were many differing political viewpoints at the convention. Because of this, the first two political parties arose. The groups that opposed each other were known as the Federalists, led by Alexander Hamilton, and the Anti-Federalists, led by Thomas Jefferson.

Let's look at the views of these two groups.



** Foundation of Government  :drill:
There were two examples of political sectionalism and states' rights issues at the Constitutional Convention. These issues included population and slavery.



** Foundation of Government  :drill:
Population and Government

A division among the states formed over representation based on population. The population of the thirteen original states varied significantly. The census of 1790 revealed that Virginia had the largest population with 747,610 people. Of this total, almost 300,000 were slaves. Delaware had 59,094 people with approximately 9,000 slaves. Pennsylvania had a population of 434,373 with 3,737 slaves.
Each state had one vote under the Articles of Confederation. This was supported by the small population states, but some people believed this system denied fair representation to the large states.



** Foundation of Government  :drill:
Slavery and Government

The issue of political sectionalism was entangled with the issue of slavery. Massachusetts was the only original state that did not have any slaves; whereas, slavery was an important economic element of the Southern states.

These slave states included Virginia, Maryland, South Carolina, North Carolina, and Georgia. In these five states:

• total population - 1,792,710
• number of slaves - 632,593
The total number of slaves in all the states combined was 694,280. This meant that only 61,687 slaves occupied the remaining eight states.

The two issues of population and slavery had to be resolved at the Constitutional Convention. Virginia, the state with the largest population, was first to propose a model of government.



** Foundation of Government  :drill:
The Virginia Plan

The Virginia Plan included the following:

• legislature - bicameral (two houses of Congress)

• both houses based on population

• lower house - elected by the people

• upper house - elected by lower house

• three branches - executive, judicial, and legislative

• judicial and executive - both could veto laws

• Congress could force a state to abide by federal laws
The smaller states objected to the proposal of both houses being based on population. New Jersey, one of the smaller states, offered another plan of government.



** Foundation of Government  :drill:
New Jersey Plan

The New Jersey Plan called for the following rules:

• unicameral (one house) legislature - all states equal

• federal government - slightly increased power

• plural executive - elected by Congress

• only one federal court

Obviously, the large states objected to the proposal of only having one house in Congress with all states being equal.
The legitimate viewpoints of the large and small states were debated on the floor of the convention. The population issue threatened to deadlock the convention.



** Foundation of Government  :drill:
Connecticut Compromise

The delegates from Connecticut made a compromise offer.

The Connecticut Compromise proposed the following:

• a two-house legislature

• a lower house based on population

• an upper house with equal representation for each state

• all bills to raise money would originate in the lower house



** Foundation of Government  :drill:
The Great Compromise

The Connecticut Compromise, also known as the Great Compromise, combined both the Virginia and New Jersey plans with regard to representation in Congress.
An upper house would be created in which all states were equal. This became the U.S. Senate, composed of two senators per state.

A lower house would be based on population. This became the U.S. House of Representatives. The number of members in the House of Representatives is currently fixed at 435 by Public Law 62-5. As of 2015, only seven states have one representative while California has fifty-three.



** Foundation of Government  :drill:
Slavery Dispute

The Great Compromise satisfied the delegates of both the small and large states. The delegates now turned their attention to the slavery issue. Slavery was an example of political sectionalism because of its relationship to the Southern economy. Slavery was a mainstay of the plantation system in the South.

The delegates wanted to resist any effort to abolish slavery in their states. They wanted to have the slaves counted in their total population so they could have more representatives in Congress.



** Foundation of Government  :drill:
The other states believed this was unfair because they had less than 10% of the slave population. Once again, a compromise was used to save the Constitutional Convention.

The Three-Fifths Compromise determined that a slave would be counted only as three fifths of a person. This proposal meant only 60% of the slave population of 632,593 would be counted toward representation in Congress. The new total slave population for the Southern states would be 379,556.



** Foundation of Government  :drill:
Constitution Ratified

The work of the convention was finished, and the new Constitution was signed on September 17, 1787. The new Constitution was ratified by the states in 1789, and the new federal government began under the leadership of President George Washington.

Washington wrote his Farewell Address in 1796 as he was completing his second term as President of the United States. Washington addressed many subjects in his Farewell Address, including the U.S. Constitution.
Washington suggested that the people must respect and obey the government established by the Constitution as long as it exists.



** Foundation of Government  :drill:
Preamble

The Preamble of the Constitution specifically states that the people of the United States wrote the document.

"We, the people of the United States, in order to form a more perfect Union, establish justice, insure domestic tranquility, provide for the common defense, promote the general welfare, and secure the blessings of liberty to ourselves and our posterity, do ordain and establish this Constitution for the United States of America."

United States Constitution. 1787.
The new Constitution gave certain powers to the legislative branch, Congress, in Article I, Section 8.

(This material is for reference use and will not be part of the test questions.)



** Foundation of Government  :drill:
Bill of Rights

The Anti-Federalists wanted a Bill of Rights included in the Constitution. Ten amendments were added to the Constitution on December 15, 1791. The Tenth Amendment addressed the issue of the rights of the states in the new government.

''The powers not delegated to the United States by the Constitution, nor prohibited by it to the States, are reserved to the States respectively, or to the people.''

United States Constitution. 1787.
This was an important element in the structure of the new government. Article I, Section 8 told Congress what it could do, and Article I, Section 9 stated what it could not do. Anything not mentioned in either Section 8 or Section 9 is reserved to the states in the Tenth Amendment.

(This supplemental material is for reference use and will not be part of the test questions.)



** Foundation of Government  :drill:
Supremacy Clause

One more important statement was made with regard to the relationship between the states and the federal government. It was the Supremacy Clause in Article IV, Section 2.
"This constitution, and the laws of the United States which shall be made in pursuance thereof; and all treaties made, or which shall be made, under the authority of the United States shall be the supreme law of the land; and the judges in every state shall be bound thereby, any thing in the constitution or laws of any state to the contrary notwithstanding."

United States Constitution. 1787.



** Foundation of Government  :drill:
Constitutional Interpretation

The relationship between the federal government and the states would be tested many times as America expanded and developed. Political arguments over interpretation of the Constitution became a platform of debate for political parties in America.

Members of the Federalist party favored a loose interpretation of the Constitution. One of the powers of Congress allows it to "…borrow money on the credit of the United States." Hamilton used this power to create the National Bank.
Jefferson, who held a stricter interpretation of the Constitution, opposed the National Bank because it was not mentioned in the Constitution.



** Foundation of Government  :drill:
President Jefferson, however, later used a loose interpretation of the Constitution when he supported the Louisiana Purchase in 1803. There is no provision in the Constitution for the addition of new territory.

The President of the United States does have the power to make treaties with foreign countries with the advice and consent of the Senate. Jefferson based his decision for the Louisiana Purchase on the constitutional powers of the president to deal with foreign countries.



** Foundation of Government  :drill:
Alien and Sedition Acts

Another challenge to the new government occurred in 1798 with the passage of the Alien and Sedition Acts. These acts were passed by a Federalist-controlled Congress. Under these acts, it became a crime for anyone to criticize the President of the United States or Congress.

These acts also had provisions for the unequal treatment of foreigners. There were many protests to these acts, including those of the Kentucky and Virginia legislatures. Many people saw these acts as an infringement on their right of free speech.



** Foundation of Government  :drill:
Hartford Convention

The issue of states' rights and nullification was the purpose of the Hartford Convention. Delegates from five New England states met in Hartford, Connecticut, on December 15, 1814. These delegates were upset over the War of 1812.

The delegates adopted resolutions similar to the Kentucky and Virginia Resolutions. They proposed amendments to the Constitution that would weaken the political power of the Western and Southern states.
The delegates were especially upset over the number of Virginians who had been elected president. Four out of the first five presidents were from the state of Virginia (Washington, Jefferson, Madison, and Monroe).



** Foundation of Government  :drill:
Rights and Nullification

The next issue of states' rights and nullification surfaced in the southern state of South Carolina. Nullification meant that states could ignore a federal law.
Citizens from South Carolina were upset over a tariff that had been passed in 1828.

John C. Calhoun from South Carolina was Vice President of the United States. Calhoun believed that the tariff taxed one section of the country for the benefit of another.



** Foundation of Government  :drill:
Calhoun reviewed the proposals of the Virginia and Kentucky Resolutions written in 1798.

"Both sets declare

1. That the Constitution of the United States is a compact or contract.

2. That to this contract each state is a party; that is, the united states are equal partners in a great political firm."

McMaster, John Bach. A School History of the United States.
Calhoun maintained that because the Constitution was a contract, both the federal government and the states were equal partners. Therefore, any state could declare an act of Congress unconstitutional within its borders.



** Foundation of Government  :drill:
The question of nullification would be debated in Congress. The leading spokesman for nullification was Senator Robert Y. Hayne of South Carolina. Hayne called for the opening of Western lands to settlement. The Southerners wanted to form a political alliance with the West against the Northern states. The Southerners would support the opening of the public lands in exchange for the support of the Westerners on the issue of slavery.



** Foundation of Government  :drill:
Senator Daniel Webster spoke against the Doctrine of Nullification. He argued that the people, not the states, created the government. Only the Supreme Court could declare a law unconstitutional. This issue had been decided in the case of Marbury v. Madison. In this decision, the Supreme Court, led by Chief Justice John Marshall, declared a law passed by Congress to be unconstitutional.

According to Webster, the union of states would dissolve if each state could nullify an act of Congress.
The issues of states' rights and nullification did not end with the Webster-Hayne debate. It would become a central issue in the movement toward the Civil War.



** Foundation of Government  :drill:
Change, Continuity, and Connections

Many changes occurred in the United States in the first half of the 1800s. The Constitution was amended two times and was applied to questions of states' rights and nullification.

The Constitution is still in use today. As of 2008, the Constitution has been amended only seventeen times since the addition of the Bill of Rights.

It is historically significant that a document written over two hundred years ago for a small nation can still be adapted to the challenges of the modern world.
This document connects us to the early citizens of our country because we still live by many of the laws and principles first put in place so long ago.



** Foundation of Government  :drill:
Other than religious writings, consider how few documents are still in use hundreds of years after being written! The writing of the Constitution of the United States was truly a remarkable feat by a group of very courageous and dedicated men.



** American Potraits 1785 to 1825  :drill:
Early American Government

Many people have great ideas, but turning ideas into reality is sometimes difficult. That was the task the new Federal Government of the United States struggled with from 1789 to 1825 as politicians and businessmen tried to implement the newly ratified Constitution.

The nation had its governmental document of choice, but how would all of the laws and declarations actually apply to everyday life? In addition to the Constitution, there was also the Bill of Rights to consider. What was the best way to form a unified nation yet remain true to the spirit of independence?
The guiding hands of newly elected presidents would lead Americans through the many challenges facing a new country.



** American Potraits 1785 to 1825  :drill:
America's presidents would draw from many sources of strength to lead the country into the future. It would take a lot of courage and political tact to unite a country of individuals who had recently proved they could be rebellious toward authority figures.



** American Potraits 1785 to 1825  :drill:
The American Portrait lessons are a journey through the gallery of presidential leaders in the United States. Examining the foundations of presidential leadership in America will help you to:

•  Analyze the political and economic events in America from 1789 to 1825.

•  Summarize the presidencies of George Washington, John Adams, Thomas Jefferson, James Madison, and James Monroe.

•  Discuss the results of the presidential elections from 1789 to 1825.

• Evaluate how and why Washington, D.C., was established.



** American Potraits 1785 to 1825  :drill:
George Washington

Most people know that George Washington was the first President of the United States. They may even know that he served in office for seven years, 308 days, from April 30, 1789, to March 3, 1797, with John Adams as his vice president.

However, fewer people know very many personal facts about George Washington, and it is some of these personal facts that help us identify with historical figures. For example, Washington was over six feet tall, had blue eyes and auburn hair, and was considered one of the most handsome men of his time.



** American Potraits 1785 to 1825  :drill:
George Washington was also the son of a very formidable woman, Mary Washington.

Washington's mother stood in the middle of a village one day and in the presence of everyone nearby, ordered her twenty-three-year-old son to leave the village and not fight under Major-General Edward Braddock's command. Fortunately, Washington defied her wishes and remained with the army. He served under Braddock, learning many of the military skills he would use during the American Revolution.



** American Potraits 1785 to 1825  :drill:
George and Martha Washington

George Washington was born February 22, 1732, in Westmoreland County, Virginia. In 1759, Washington married a widow named Martha Dandridge Custis (1731–1802).

Martha was only five feet tall to Washington's six-feet-two-inch stature. She brought two children by her previous marriage into the relationship. The couple never had children of their own.



** American Potraits 1785 to 1825  :drill:
Washington supported many of the policies of the Federalist Party, although he did not like the idea of political parties and never joined one. He never attended college and had several occupations, including surveyor, planter, and soldier.

Washington was nicknamed the "Father of His Country" because he was the first president as well as the first commanding general of the United States. Washington fought with the colonial and British forces during the French and Indian War. Later, Washington was the leader of the Continental Army during the Revolutionary War.



** American Potraits 1785 to 1825  :drill:
Washington had a tremendous amount of work ahead of him once he took office.

His accomplishments as president included:
•  establishment of a Supreme Court (Judiciary Act of 1789)
•  establishment of cabinet positions
•  Secretary of the Treasury
•  Secretary of State
•  Secretary of War
•  Attorney General
•  enacted foreign policies and treaties
•  American Indian Wars



** American Potraits 1785 to 1825  :drill:
Washington exercised diplomacy with his own cabinet members as well as foreign officials. Thomas Jefferson, Secretary of State, and Alexander Hamilton, Secretary of the Treasury, each had very different political ideas.

One of their arguments was over the best ways to raise revenue for the United States and settle federal debts. Washington counseled both men in an effort to resolve their differences and finally sided with Hamilton, who established a national bank and the United States Mint.



** American Potraits 1785 to 1825  :drill:
Washington was granted the power by Congress to select the site for the federal capital. The official site of the capital was changed from Philadelphia to donated land along the Potomac River. Although construction was started on the White House, it was not completed in time for Washington to live there during his presidency.

George Washington published his Farewell Address on September 19, 1796. He warned the nation against forming permanent alliances with foreign nations and cautioned the people to not incur a large public debt or maintain a large military establishment.
George Washington was sixty-seven years old when he died on December 14, 1799. He is buried at his home, Mount Vernon, in Virginia.



** American Potraits 1785 to 1825  :drill:



** American Potraits 1785 to 1825  :drill:
This map shows the states that were admitted to the Union under Washington's administration.
At the end of Washington's presidency, much of North America remained unexplored. Early maps reflected the expanse of territory in the western region, including the Louisiana Purchase and lands claimed by Mexico.



** American Potraits 1785 to 1825  :drill:
John Adams

John Adams was the second President of the United States. He served from March 4, 1797, to March 3, 1801.

John Adams was a member of the Federalist Party and served two terms as vice president under George Washington. He was inaugurated at age 61, along with his vice president, Thomas Jefferson.



** American Potraits 1785 to 1825  :drill:
It is likely that Adams welcomed the role of president over his service as vice president.

Of his vice-presidency, Adams was reported to say, "My country has in its wisdom contrived for me the most insignificant office that ever the invention of man contrived or his imagination conceived."

The White House. John Adams.



** American Potraits 1785 to 1825  :drill:
John and Abigail Adams

John Adams was born October 30, 1735, in Quincy, Massachusetts. In 1764, he married Abigail Smith (1744–1818), and they had three sons and two daughters:

•  Abigail (1765–1813)

•  John Quincy (1767–1848) - who became the sixth President of the United States)

•  Susanna (1768–1770)

•  Charles (1770–1800) - Charles died on November 30, 1800, while his father was president)

•  Thomas (1772–1832)



** American Potraits 1785 to 1825  :drill:
Adams was a graduate of Harvard University. Like other early leaders, he had several occupations, including teacher, lawyer, and writer. He served in many political positions and was the first president to live in the White House in 1801.

"After eight years of loyal and important service as the nation's first Vice-President John Adams was elected to succeed George Washington and became the second president of the United States. The nation's first peaceful transfer of power succeeded as the world looked on … John Adams' term of office was one of the most difficult in U.S. History.
The turmoil that embroiled Europe following the French Revolution threatened to spill across the Atlantic and polarize America…Adams signed into law a series of measures to restore domestic tranquility and preserve the Union."

U.S. Department of the Interior. National Park Service. Adams



** American Potraits 1785 to 1825  :drill:
John Adams had large boots to fill as the second President of the United States. No one could surpass Washington in the hearts of the American people, but Adams served with the same composure and firmness for which he was known during the American Revolution.

Adams's accomplishments as president included:

• passage of the Naturalization Acts in 1798
These acts had four components:
•  the Naturalization Acts
•  the Alien Act
•  the Alien Enemies Act
•  the Sedition Act

These acts were established to place limitations on immigration and allow hostile foreigners to be removed from the country. The Sedition Act made it illegal to criticize the government in public. The passing of these acts angered many people, some of whom withdrew their support from Adams.



** American Potraits 1785 to 1825  :drill:
Even as America was settling into some semblance of calm after the Revolution, trouble was escalating across the Atlantic Ocean. France was beginning to fight with most of Europe, in particular Great Britain. Adams saw that America was heading toward a crisis if he didn't try to deflect some of the upcoming conflicts. He needed to avoid hurtling America into another war.

Several events led to the crisis:

1778: America completed an alliance with France in the war against England.
1794: The Jay Treaty. With the Revolution over, America began to open trade with England and agreed to remain neutral regarding the fighting between England and France.

In Europe, hostilities intensified between England and France.



** American Potraits 1785 to 1825  :drill:
French officials believed the 1778 alliance with America should be more important than trading with Great Britain. French ships began to raid and intercept American ships. Several battles between French and American ships took place on the seas.

Adams sent three ambassadors to speak with French officials. When the ambassadors were turned away, the insult brought cries of outrage from Americans back in the states.
Even as a group of American politicians (known as War Hawks) demanded war against France, Adams dispatched another set of ambassadors.

This time, France received the ambassadors, and the Convention of 1800 was negotiated. This agreement terminated the alliance made in 1778 with France. The Quasi-War with France ended, and Adams had averted war--for the present time.



** American Potraits 1785 to 1825  :drill:
Adams died on July 4, 1826, and is buried in Quincy, Massachusetts. In a strange coincidence, Thomas Jefferson, John Adams, and James Monroe all died on July 4.

Both Jefferson and Adams died on July 4, 1826, the 50th anniversary of the signing of the Declaration of Independence.



** American Potraits 1785 to 1825  :drill:
Thomas Jefferson

Thomas Jefferson was the third President of the United States and served from March 4, 1801, to March 3, 1809. He served one term as vice president and two terms as president.



** American Potraits 1785 to 1825  :drill:
Thomas and Martha Jefferson  

Jefferson was born April 13, 1743, in Shadwell, Virginia. In 1772, he married Martha Wayles Skelton (1748–1782), and they had five daughters and one son:

•  Martha (1772–1836)
•  Jane (1774–1775)
•  Thomas (1777–1777)
•  Mary (1778–1804) – died while her father was president
•  Lucy (1780–1781)
•  Lucy (1782–1785) – named for the deceased child
Jefferson graduated from the College of William and Mary. With Jefferson's love of knowledge, his talents extended to occupations including lawyer, inventor, architect, writer, and governor of Virginia.



** American Potraits 1785 to 1825  :drill:
Jefferson was appointed as minister to France in 1785. In 1789, he became the first Secretary of State of the United States. In 1815, he sold his private collection of books. Purchased by Congress, these books formed the new foundation of the Library of Congress. The first Library of Congress was established in 1800 and burned when the British set fire to the Capitol in 1814.



** American Potraits 1785 to 1825  :drill:
Jefferson was one of the founding fathers of America. He did much of the writing on the Declaration of Independence. Long known for his political activism and service, he was a natural in the presidency.

Jefferson's accomplishments as president included:

1803: instrumental in the acquiring of the Louisiana Purchase

1804–1806: support for the Lewis and Clark Expedition



** American Potraits 1785 to 1825  :drill:
Jefferson firmly believed in the Republic and the separation of church and state. He repeatedly argued for individual rights and simplicity in government, even though he was a slave owner.

With regard to slavery, Jefferson wrote the following in a letter, "…yet I see not how we are to disengage ourself from that deplorable entanglement, we have the wolf by the ear & feel the danger of holding or letting loose.... I shall not live to see it but those who come after us will be wiser than we are, for light is spreading and man improving."

Thomas Jefferson. 1824.



** American Potraits 1785 to 1825  :drill:
Jefferson believed that American Indians should sign secure treaties with the government and be reeducated to "civilized" standards of living. Unfortunately, many of Jefferson's actions regarding American Indians led to disastrous future policies for the tribes.

As part of his support for the Lewis and Clark Expedition, Jefferson authorized peace medals to be given to American Indian leaders encountered along the journey. By doing so, Jefferson hoped to promote integration of the American Indians with American society and secure westward lands for expansion.



** American Potraits 1785 to 1825  :drill:
James Madison

James Madison was the fourth President of the United States. He served in office from March 4, 1809, to March 3, 1817.

James Madison was born March 16, 1751, in Port Conway, Virginia. Madison practiced law after graduating from Princeton University.



** American Potraits 1785 to 1825  :drill:
Madison was a member of the Republican Party and served as Secretary of State under Thomas Jefferson. He was inaugurated at age fifty-seven and served two terms. Madison is considered the "Father of the Constitution" because he wrote most of the Constitution and the Bill of Rights.



** American Potraits 1785 to 1825  :drill:
Madison was a member of the Republican Party and served as Secretary of State under Thomas Jefferson. He was inaugurated at age fifty-seven and served two terms. Madison is considered the "Father of the Constitution" because he wrote most of the Constitution and the Bill of Rights.



** American Potraits 1785 to 1825  :drill:
The War of 1812 lasted from June 18, 1812, to December 24, 1814. The treaty that ended the war was signed in Ghent, Belgium.

Many Americans were left with bitter feelings over the war. They felt too many soldiers died for nothing because the treaty never addressed or resolved any of the political and geographical conflicts with Great Britain.

Other Americans believed the war accomplished a true sense of independence for the United States. They believed America was finally accepted by the established governments of Europe.



** American Potraits 1785 to 1825  :drill:
Madison's accomplishments as president included:

•  1812 - led America into battle against the British

•  1814 - Treaty of Ghent - ended the War of 1812

•  increased the strength of the U.S. military

•  increased roads for transporting goods between the states

•  strengthened the economy with the National Bank
•  ushered in nationalism, a sense of pride in America



** American Potraits 1785 to 1825  :drill:
James and Dolley Madison

In 1794, James married Dolley Dandridge Payne Todd (1768–1849), a widow with two sons. The couple never had children of their own.

Dolley is considered one of the best hostesses to reside in the White House. Dolley was only twenty-two and Madison was thirty-nine when they married. A span of seventeen years separated their ages, but "our hearts understand each other" was the reassurance she gave her new husband.



** American Potraits 1785 to 1825  :drill:
George Clinton served as vice president for Madison as well as Thomas Jefferson. He is one of two men to serve as vice president for two presidents. Clinton died on April 20, 1812.

Madison was very proud of his country and its accomplishments. He wrote in a note, "The advice nearest to my heart and deepest in my convictions is that the Union of the States be cherished and perpetuated."

James Madison. 1836.



** American Potraits 1785 to 1825  :drill:
This map shows the states admitted to the Union under Madison's administration.



** American Potraits 1785 to 1825  :drill:
James Monroe  

James Monroe was the fifth President of the United States. He served from March 4, 1817, to March 3, 1825. He was a member of the Republican Party and served as Secretary of State and Secretary of War under James Madison.

Monroe was inaugurated at age fifty-eight and served two terms as president.



** American Potraits 1785 to 1825  :drill:
The American System

Part of the results of the war with Great Britain in 1812 included a protection of American economic rights on the international scene. The American System, created by politician Henry Clay, was implemented after the war to help bring the country together economically.

The American System was a three-part plan to boost America's economy. The plan included:

•  a tariff, a type of cost set on goods imported or exported from the country
•  the formation of a national bank to establish a cohesive monetary system

•  internal improvements to include transportation for commerce

Despite the American System, sectionalism continued to affect the political, social, and economic issues of all regions of the country.



** American Potraits 1785 to 1825  :drill:
James Monroe faced some daunting problems during his presidency. Even though Americans were looking forward to the future with an air of optimism, certain economic and social issues needed to be addressed.

Monroe established precedents which would have far-reaching impacts on the future of America. Monroe's accomplishments as president included:

•  the acquisition of Florida from Spain
•  the Missouri Compromise
•  the Monroe Doctrine



** American Potraits 1785 to 1825  :drill:
The first crisis Monroe faced was the Panic of 1819. This period of economic depression caused many banks to close and unemployment to increase.

Monroe decided to leave much of the depression resolution in the hands of banks and financial experts. He did not believe the presidency truly had much authority to deal with the situation, and it would resolve itself. He was right, and by 1823, the depression was over.



** American Potraits 1785 to 1825  :drill:
The Missouri Compromise was one of the first legislations to deal with the slavery issue that was becoming a point of concern between the states. This compromise indicated physical boundaries on where slavery could exist in the United States. Monroe signed the Missouri Compromise into law in 1820.

The Monroe Doctrine was a tough policy enacted by James Monroe regarding the future of the North American continent.

The doctrine had these effects:

•  closed off future settlement of the Western Hemisphere by European countries
•  proclaimed America's neutrality with regard to Europe's wars

•  established a policy for any independent country threatened by the previous European owners

This doctrine made clear that Americans wanted Europe out of the colonizing business as far as North, South, and Central America were involved.



** American Potraits 1785 to 1825  :drill:
James and Elizabeth Monroe

James Monroe was born April 28, 1758, in Westmoreland County, Virginia. In 1786, he married Elizabeth Kortright (1768–1830), and they had two daughters and one son:

•  Eliza Kortright (1786-1835)
•  James Spence (1799-1800)
•  Maria Hester(1803-1850)

Monroe attended the College of William and Mary for two years. He was a lawyer, writer, and U.S. Senator and served in the Congress of the Confederation in 1783. Monroe was governor of Virginia, minister to France, and minister to Great Britain.



** American Potraits 1785 to 1825  :drill:
James Monroe had the distinction of being the first president to try a new form of transportation--the steamboat. Later, he would host a wedding in the White House for his daughter Maria, another first for a presidential executive.

Monroe and his wife lived overseas for a time when he was appointed as Minister to France. Monroe's wife, Elizabeth, is reported by some historians to be responsible for saving Marquis De Lafayette's wife from the guillotine during the French Revolution.
As First Lady, Elizabeth established more formal rules of behavior and customs in the White House. She believed that in order for America to gain more respect from European officials, Americans needed to imitate many of the European customs.



** American Potraits 1785 to 1825  :drill:
This map shows the states admitted to the Union under Monroe's administration.
Monroe died on July 4, 1831, in New York City at age 73 and is buried in Richmond, Virginia.

Learn more about Monroe's private home, Oak Hill.



** American Potraits 1785 to 1825  :drill:
From George Washington to James Monroe, the first five Presidents of the United States accomplished the extremely difficult task of leading a unique country into the reality of new-found freedoms.

While the Declaration of Independence laid the foundation for America, it was the presidents, along with many more brave men and women, who expanded those ideas and applied them through solid and productive social structures.
These following words from the foundation of the Declaration of Independence placed the tools for potential greatness into the hands of the early political leaders of our country, "We hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness…".



** A Nation Emerges  :drill:
Imagine the student population in your school tripled within a short time span. How would the administration cope with such an influx of students?



** A Nation Emerges  :drill:
Between the years 1790 and 1900, America nearly tripled in geographical size. There was tremendous growth in population, industry, and agriculture. This was a time when the constitutional foundations created in 1787 were tested by war as well as political, social, and economical issues.

This time period began with the launching of the new government under President George Washington.



** A Nation Emerges  :drill:
As you learn about the expansion of America and the growth of political policies, you will gain an understanding of the following issues:

•  westward expansion from 1787 to 1850

•  political developments in America from 1787 to 1850

•  the causes and results of the War of 1812 and the Mexican-American War

• the purpose of the Monroe Doctrine



** A Nation Emerges  :drill:
Washington's Farewell Address

George Washington published his Farewell Address on September 19, 1796. He warned the nation against forming permanent alliances with foreign nations and cautioned the people against incurring a large public debt and maintaining a large military establishment. Washington addressed many subjects in his Farewell Address, including the Constitution. He set the tone for how people should view the new Constitution.



** A Nation Emerges  :drill:
"This government, the offspring of our own choice, uninfluenced and unawed, adopted upon full investigation and mature deliberation, completely free in its principles, in the distribution of its powers, uniting security with energy, and containing within itself a provision for its own amendment, has a just claim to your confidence and your support. Respect for its authority, compliance with its laws, acquiescence in its measures, are duties enjoined by the fundamental maxims of true liberty."

Washington's Farewell Address. 1796.
In the following excerpt, Washington tells the citizens that the Constitution was written by the people without any outside interference.



** A Nation Emerges  :drill:
Revising the Articles of Confederation

The Articles of Confederation had served as the government of the United States from March of 1781 to June of 1788. The colonial leaders later met in Philadelphia in 1787 to revise the Articles of Confederation.

"When independence was about decided on, Congress appointed a committee to draft a general plan of federal government. This plan, called Articles of Confederation, Maryland absolutely refused to ratify till the states claiming land west of the Alleghany Mountains ceded their claims to Congress.
The defects of the Articles made revision necessary, and produced such distress that two conventions were called to consider the state of the country. That at Annapolis attempted nothing. That at Philadelphia framed the Constitution of the United States."

McMaster, John Bach. A School History of the United States.

The New U.S. Constitution was approved in 1788 and went into effect in 1789.



** A Nation Emerges  :drill:
Growth of a Nation

A number of significant global, political, and geographical events occurred between 1787 and 1850.

President Thomas Jefferson more than doubled the territory of the United States in 1803. He purchased the territory of Louisiana from France, led by Napoleon Bonaparte.

Meriwether Lewis and William Clark led an expedition in 1804 and 1805 to explore the Louisiana Purchase. They published some of the first maps of these uncharted lands.



** A Nation Emerges  :drill:
The United States acquired Florida from Spain in 1819. With the annexation of the Republic of Texas in 1845, America added even more territory. Originally, Texas had been part of Mexico and had gained its independence on March 2, 1836.

The United States went to war with Mexico in 1846 in a dispute over the location of the Texas border. The war, which ended in 1848, resulted in the United States gaining the territories of New Mexico and California.



** A Nation Emerges  :drill:
The United States had gained some territory from Great Britain in 1818. This area was part of the present-day states of North Dakota and Minnesota. In 1846, a treaty signed with Great Britain enabled the United States to also add the Oregon Country.

The United States added territory from Mexico with the Gadsden Purchase in 1853, which includes part of present-day Arizona. The purchase of Alaska from Russia in 1867 completed the territory of the present-day continental United States.



** A Nation Emerges  :drill:
Manifest Destiny

Americans were moving westward, settling the territory from the Appalachian Mountains to the Mississippi. The purchase of the Louisiana Territory moved the western frontier west to the Rocky Mountains.

Americans began to believe their country would someday expand all the way to the Pacific Ocean. This popular thought was known as Manifest Destiny, a phrase first stated in 1845 by the editor of a newspaper.



** A Nation Emerges  :drill:
Territorial Expansion

The expansion of the territory of the United States between 1787 and 1850 was remarkable.

This map shows the territorial growth of the United States to 1853.



** A Nation Emerges  :drill:
The Rising West

"The dull times on the seaboard, the cheap land in the West, the love of adventure, and the desire to 'do better' led, during 1814–1820, to a most astonishing emigration westward.

The rush of population into the Mississippi Valley caused the admission of six states into the Union between 1816 and 1821.

The question of the admission of Missouri brought up the subject of shutting slavery out of the country west of the Mississippi, which ended in the Missouri Compromise and the establishment of the 36°30' line.



** A Nation Emerges  :drill:
"The rises of the new states in the West, and the appearance of the steamboat on the Mississippi, were the causes of a great revival of public interest in internal improvements.

The first to build a great western highway was New York state, which between 1817 and 1825 built the Erie Canal. This cut down the cost of moving freight to the West, led to settlement along the banks of the canal, and made New York City the metropolis of the country.



** A Nation Emerges  :drill:
"It was during this period, 1815–1830, that many inventions, discoveries, and improvements were made in the arts and sciences. The railroad was introduced, and the steam locomotive successfully used. The cities grew, and in New York the omnibus and the street car began to be used.

The movement of population into the West.--The formation of new states there.--The rise of manufactures in the East.--The fine market the West offers for the products and importations of the Eastern States."

McMaster, John Bach. A School History of the United States.



** A Nation Emerges  :drill:
The movement west would have a profound effect on Native Americans in the United States. Some tribes were isolated from the Europeans during the exploration and early colonization period. Most of the tribes would now face removal from their lands as a result of warfare and government policy.



** A Nation Emerges  :drill:
Global, Economic, and Political Growth

The period between the election of James Monroe in 1816 and John Quincy Adams in 1824 was known as the Era of Good Feelings, even though there was an ongoing struggle between the states and federal government.

This struggle was the source of the development of political parties. The country was facing economic, political, and social issues that would dominate America from 1820 to 1850.



** A Nation Emerges  :drill:
Slavery was a social, economic, and political issue that had been part of America since 1619. The issue of slavery was addressed in the Missouri Compromise in 1820. This Compromise lasted until 1850 when California was ready to join the Union. Part of the argument over slavery revolved around the rights of the states.



** A Nation Emerges  :drill:
The issue of states' rights led to a period of disarray beginning with the election of Andrew Jackson in 1828. Jackson vetoed the charter of the Second National Bank.

The Jacksonian Age expanded democracy to the common man as more people were allowed to vote. The population of America was growing, and people were moving westward.



** A Nation Emerges  :drill:
The federal government was a project under development from 1790 to 1850.

•  The issue of the National Bank dominated the economic system of the country.

•  Supreme Court decisions defined the power and role of the federal government.

John Marshall, the Chief Justice of the Supreme Court, established the policy of judicial review in the case of Marbury v. Madison. In this decision, the Supreme Court declared a law passed by Congress to be unconstitutional.



** A Nation Emerges  :drill:
America went to war in 1812 during the presidency of James Madison over the issue of freedom of the seas. This war was fought with Great Britain and is sometimes referred to as the second war for independence. Although little changed as a result of the war, Americans felt their independence had been solidified in the eyes of the world.

The country experienced another wave of nationalism following the War of 1812.



** A Nation Emerges  :drill:
The United States 1787–1850: What Changed

The first census in 1790 determined there were 3,929,214 people living in the United States. By 1850 the population had grown to 23,191,876.

The size of the United States was 864,746 square miles in 1790 compared to 2,940,042 square miles in 1850.

In 1790 there were 4.5 people per square mile in the United States compared to 7.9 people per square mile in 1850.



** A Nation Emerges  :drill:
The number of states in the Union grew from the original thirteen in 1790 to thirty-one in 1850. The addition of territory led to a massive movement of people within the United States. These people moved into the territory between the Atlantic coast and the Mississippi River.



** A Nation Emerges  :drill:
Political Parties

The first ten amendments to the U.S. Constitution became known as the Bill of Rights. The political arguments over the Constitution were the source for the creation of political parties in America. The first two parties were known as the Federalists, led by Alexander Hamilton, and the Democratic-Republicans, led by Thomas Jefferson.

The Republican Party of Jefferson is not related to the present-day Republican Party.



** A Nation Emerges  :drill:



** A Nation Emerges  :drill:
Read about objections to the Constitution and the first ten amendments.



** A Nation Emerges  :drill:
Historical Connections

The French explorer Robert Cavelier, Sieur de la Salle, reached the mouth of the Mississippi in 1682. He claimed the territory for France and named it Louisiana for the French King Louis XIV. Spain was granted the Louisiana Territory by the Treaty of Paris in 1763, which ended the French and Indian War.

The Treaty of Paris marked the middle of the Mississippi River as the territorial division in North America between Great Britain and Spain.
Treaty of Paris

"… the confines between the dominions of his Britannick Majesty and those of his Most Christian Majesty, in that part of the world, shall be fixed irrevocably by a line drawn along the middle of the River Mississippi, from its source to the river Iberville, and from thence, by a line drawn along the middle of this river."

"Treaties and Other International Acts of the United States of America." Ed. by Hunter Miller. Vol 2. Washington: Government Printing Office, 1931.



** A Nation Emerges  :drill:
Treaty of San Iledfonso

The Spanish gave the Louisiana Territory back to France in the Treaty of San Ildefonso in 1800. Napoleon Bonaparte, the leader of France, was in desperate need for money because of the cost of the wars in Europe. He was willing to sell the Louisiana Territory to the United States in 1803 for the sum of fifteen million dollars. The Treaty of San Ildefonso did not specify the actual boundaries of the Louisiana Territory. The size of the region was a point of dispute between the United States and Spain following the Louisiana Purchase in 1803.



** A Nation Emerges  :drill:
Wars

The United States was involved in two wars in the first half of the 1800s. The first was fought in the early part of the century against Great Britain, and the second was fought in the late 1840s against Mexico.



** A Nation Emerges  :drill:
Monroe Doctrine

In 1824, the Monroe Doctrine declared that both Americas would be off limits to any more European colonization. The Monroe Doctrine was related to political movements in Central and South America as many countries gained their independence from Spain. President Monroe publicly stated the new policy of the United States toward the European colonies in the Americas.



** A Nation Emerges  :drill:
There were many other European colonies in North America in addition to the English colonies. The successful revolutions in the United States and France inspired the people in Central and South America. Some of these colonies had lived under Spanish control for over three hundred years. During that time, a rigid political and social structure had emerged.

Events in the early 1800s occupied the political attention of the countries of Europe. France, led by Napoleon, was fighting Spain and other European countries.
The people in some of the Spanish colonies in the Americas took this opportunity to set up their own governments.



** A Nation Emerges  :drill:
Independence in the Americas

Spain controlled most of the territory in Central and South America. The map on the following page illustrates the extent of the Spanish Empire in the New World at the beginning of the 1800s.

Ferdinand VII became the King of Spain in 1815 following the defeat of Napoleon. He wanted to once again establish control over the Spanish colonies in the Americas. By this time, the Spanish colonists, led by men such as Simon Bolivar and Jose de San Martin, were moving toward independence.
These men had been educated in Europe and were influenced by revolution and the cause of freedom.

Mexico gained its independence from Spain in 1821. In 1823, the United Provinces of Central America included modern-day Nicaragua, Costa Rica, Honduras, El Salvador, and Guatemala. Most of the former Spanish colonies were independent by 1825.



** A Nation Emerges  :drill:



** A Nation Emerges  :drill:
The countries of Europe retained some of their colonies. Spain wanted help from its European allies to regain control of Spanish colonies in the Americas. Both Great Britain and the United States opposed any European influence in North or South America.

One-time political opponents America and Great Britain began to work through their differences and today are firm allies. The powerful alliance forged between the two countries would later be severely tested with the outbreak of World War II.



** American Portraits 1825 to 1849  :drill:
American Portraits 1825–1849

By 1825, the foundations of the new American government were established and fully functioning. Americans were looking to the future and fine-tuning the details of running a country. As you read this lesson, you will discover how the leadership of the next six presidents of the United States searched for ways to fairly execute the duties of the executive branch.



** American Portraits 1825 to 1849  :drill:
In this lesson, you will gain knowledge and understanding that will help you achieve the following skills:

• Discuss the significant political and economic events that occurred in America from 1825 to 1849.

• Describe the presidencies of John Quincy Adams, Andrew Jackson, Martin Van Buren, William Henry Harrison, John Tyler, and James Polk.

• Discuss the results of the presidential elections and noteworthy news events from 1825 to 1849.



** American Portraits 1825 to 1849  :drill:
Suppose you ran for student body president, and although a majority of the students voted for you, you still didn't win the election. Would you wonder how that could happen? Would that seem fair?

We usually consider a majority vote to be the winning criterion, but in the presidential election of 1824, the majority didn't rule.



** American Portraits 1825 to 1849  :drill:
John Quincy Adams

John Quincy Adams was the sixth President of the United States. He served from March 4, 1825, to March 3, 1829. Although he hoped to win the presidency in 1824, Adams was surprised to learn that he won the election. He did not receive the majority of the popular vote but managed to win the required number of electoral votes.



** American Portraits 1825 to 1849  :drill:
Surprise Election

Adams's election was a surprise to his contender, Andrew Jackson. After all, Jackson carried the election as far as the highest count of popular and electoral votes. However, a majority of the electoral votes was required to win the presidency. Jackson's 99 electoral votes did not win the majority for him.

The election was sent to the House of Representatives that voted on their choice for president. Knowing he could not win, Henry Clay used his influence to persuade House members to vote for Adams. After Adams was elected, he appointed Clay as his Secretary of State.
Jackson believed the partnering between Adams and Clay was the result of secret bargaining. This belief started a series of rumors that would haunt the presidency of Adams and cost him the election in 1828.



** American Portraits 1825 to 1849  :drill:
A Life of Service

President Adams was inaugurated at age fifty-seven and served one term as president.

Adams's family had a long history of political involvement, including the presidential service of his father, John Adams.
As a young boy, John Q. Adams was witness to one of the early military actions of the Revolution, the Battle of Bunker Hill. Nearly all of Adams's life had centered on politics and conflict. He even traveled at a young age, accompanying his father to his many political posts abroad.

John Q. Adams was a member of the Republican Party and began his political life early. He was likely influenced by his father's politics and past presidential service and was highly regarded for his ability to handle important positions of state.



** American Portraits 1825 to 1849  :drill:
John Quincy Adams's Presidency

Adams's accomplishments as president included:

• expansion of the American System (Adams wanted to create federally sponsored universities and promote the sciences through astronomy observatories and research.)

• endorsement of a tariff, later called the Tariff of Abominations
• opening of the Erie Canal between Albany and Buffalo, New York (Adams had always been an advocate of the arts and sciences and wanted the government to lend its support to new art and technology.)



** American Portraits 1825 to 1849  :drill:
Even though politicians and businessmen hailed the 363-mile-long Erie Canal as one of the greatest engineering feats to date, Congress would still not back Adams's promotion of the arts and sciences.

Most of Adams's ideas for American growth were never established because of this resistance in Congress.



** American Portraits 1825 to 1849  :drill:
Tariff of Abominations

Adams was against the tariff in 1828 that would place a high cost on items imported into the country. Northern manufacturers wanted the tariff to prevent cheaper foreign goods from competing on the market for American-made products.

Southern states hated the tariff because they needed the cheaper imports to use in their production of cotton. Believing that the power of veto was only for unconstitutional laws, Adams reluctantly signed the tariff into law. This, too, would later hurt his reelection campaign as he lost the support of the Southern states.
"In his first message in December of 1825, John Quincy set forth his vision for the United States…

 Adams had little use for those who favored state's rights at the expense of the common national good…

Adams also advocated an extensive system of internal improvements (mostly canals and turnpikes) to be paid for out of increasing revenues from western land sales and a continuing tariff on imports."

U.S. Department of the Interior. National Park Service.



** American Portraits 1825 to 1849  :drill:
John and Louisa Adams

Adams was born July 11, 1767, in Quincy, Massachusetts.

In 1797, he married Louisa Catherine Johnson (1775–1852), whom he had met while he was abroad. Louisa was the daughter of an American merchant and was born overseas.

Adams's father, former President John Adams, was against the marriage. Even though Louisa was an American, Adams's father wanted his son to marry someone born on American soil. Later, Adams's political enemies often referred to Louisa Adams as "that English-born woman" to try to make Adams appear less patriotic.



** American Portraits 1825 to 1849  :drill:
A Life of Political Service

John Q. Adams was a graduate of Harvard and initially chose law as his career. He was appointed minister to the Netherlands in 1794 and was elected to the U.S. Senate in 1803. Adams served as minister to Great Britain in 1815 and became Secretary of State in 1817.

He later served in the U.S. House of Representatives for seventeen years, from 1831 until his death. He died on February 23, 1848, at age eighty and is buried in Quincy, Massachusetts.
Adams National Historical Park

The National Park Service maintains the homes of John Adams and his son John Quincy Adams in Quincy, Massachusetts.



** American Portraits 1825 to 1849  :drill:
Andrew Jackson

Andrew Jackson was the seventh President of the United States. He served from March 4, 1829, to March 3, 1837. He was born on March 15, 1767, in Waxhaw, South Carolina. Jackson was inaugurated as president at age sixty-one and served two terms.

Jackson was elected to the House of Representatives in 1796 and served as a U.S. Senator in 1797 and 1823. He was a member of the Democratic Party and was one of its founders.



** American Portraits 1825 to 1849  :drill:
By the time the election of 1828 occurred, Jackson was ready for a victory. He still felt cheated after the last election, and this time he was determined to win. The political battle for president would become a mud-slinging debate between Jackson's and Adams's supporters.

Some of the reported slings included:

• Adams was considered a snob.

• Jackson was considered uncivilized.
• Adams was accused of traveling on Sunday (work-related activities on the Sabbath were considered offensive by some religious groups).

• Jackson was accused of being too callous in his harsh treatment of military deserters.



** American Portraits 1825 to 1849  :drill:
Some historians believe that Jackson won the vote because of his image as a rough and tumble frontiersman. He was known for his quick temper, his harsh fighting tactics, and for being a common man.

More "common men" voted in this election than any other election to date. Most states had removed the stipulation that a man had to own property in order to vote. In all but six states, most white males were eligible to vote, and they flocked to the polls to do so.

Over a million votes were cast in the 1828 election as opposed to slightly more than three hundred thousand cast in 1824.



** American Portraits 1825 to 1849  :drill:
Jackson's Presidency

Jackson's accomplishments as president included:

• 1830 - Indian Removal Act - 1832 - Nullification Act - When South Carolina threatened to nullify a federal law, Jackson reacted swiftly. He sent troops and ships to South Carolina with stern warnings to remain in compliance with federal laws or risk the consequences.

• The Panic of 1837 - This event was brought on by the Specie Circular signed into law by Jackson that required all payments for public land to be made in gold and silver and Jackson's failure to renew the charter of the Second Bank of the United States.



** American Portraits 1825 to 1849  :drill:
Jackson was known for his heavy hand when it came to signing vetoes. He vetoed more Congressional bills than any president before him.

Being a man of the people, Jackson also believed in elevating the common man to government positions. He placed so many of his friends and acquaintances in government jobs that Jackson became known as the "King of the Spoils System" by some of his political opponents.



** American Portraits 1825 to 1849  :drill:
Indian Removal Act

With the discovery of gold in some of the Southern states and the desire for more land, Jackson was determined to see the Native Americans removed from their territory. Jackson had fought and defeated the Creeks in 1814 in the Battle of Horseshoe Bend. He had little patience or liking for Native Americans.

He signed the Indian Removal Act into law, and by the late 1830s over 4,000 Cherokee people had died during their removal from tribal lands. This removal from the Smoky Mountains to Oklahoma would later be called the Trail of Tears.
Davy Crockett, a representative from Tennessee, was so outraged over this piece of legislation that he eventually left politics and traveled west where he met his fate at the Alamo.
Click on the image to enlarge it.



** American Portraits 1825 to 1849  :drill:
Politics and Romance – Andrew and Rachel Jackson

In 1791, Jackson married Rachel Donelson Robards (1767–1828), and he considered her the love of his life. The couple never had any children.

They married believing Rachel's divorce to her first husband had been granted. They later learned that the divorce had never been granted. Horrified, they quickly took steps to legalize the divorce and remarry. This scandal followed Jackson and his wife for the rest of their days together.



** American Portraits 1825 to 1849  :drill:
Mourning at the White House

Rachel died shortly before Jackson's first inauguration. He blamed his political opponents for his wife's stress and subsequent death. He first entered the White House in mourning clothes and always carried the bitter loss of his wife with him.
After entering presidential service, Jackson ordered a beautiful limestone monument built in the graveyard as a tribute to his wife. He included an epitaph which read in part "… A being so gentle and yet so virtuous, slander might wound but could not dishonor…."

Jackson's niece Emily Donelson served as White House hostess.



** American Portraits 1825 to 1849  :drill:
Jackson did not attend college; however, Harvard University conferred an honorary law degree on him in 1833. His various occupations included soldier, frontiersman, tailor, and later a judge, planter, and governor of Tennessee. He was also involved in many duels during his lifetime.

Jackson died on June 8, 1845, and is buried at the Hermitage Estate in Nashville, Tennessee.



** American Portraits 1825 to 1849  :drill:
U.S. History on the Road

The Hermitage, located in Tennessee, was the home of President Andrew Jackson.



** American Portraits 1825 to 1849  :drill:
Martin Van Buren

Martin Van Buren was the eighth President of the United States. He served from March 4, 1837, to March 3, 1841. He was born December 5, 1782, in Kinderhook, New York. Van Buren served as vice president under Jackson. He was inaugurated as president at age fifty-four and served one four-year term.

Van Buren became a lawyer despite the fact that he never attended college. He served as a U.S. Senator from New York and as governor of New York. He was a member of the Democratic Party.



** American Portraits 1825 to 1849  :drill:
Van Buren's Presidency

Sometimes presidents inherit the troubles and problems created by their predecessors. Van Buren had the misfortune of arriving in office after the results of President Jackson's Specie Circular policy.

This policy resulted in the Panic of 1837, an economic depression of five years. This depression was highlighted by a large number of banks failing and by widespread unemployment. Van Buren was blamed for the panic and ensuing depression. Van Buren's decision to avoid government involvement with banks cost him a chance at a second term.



** American Portraits 1825 to 1849  :drill:
Events during Van Buren's presidency included:

• The Panic of 1837 – The events initiating the economic depression of 1837 were set in motion by President Andrew Jackson. Unfortunately, the event itself was inherited by Van Buren who was blamed historically for the crisis. Van Buren added to the depression by cutting off funds to federal improvement programs.
• 1840 - The Manifest Destiny - Westward expansion of the United States began. After the removal of the Native Americans, white settlements quickly formed on the vacated lands. Van Buren argued against the annexation of Texas because he did not want another slave state added to the Union. He also predicted war with Mexico if such a move was made. Ultimately, he was proved right.



** American Portraits 1825 to 1849  :drill:
Martin and Hannah Van Buren

In 1807, Van Buren married Hannah Hoes (1783–1819), and they had five sons:

Abraham (1807–1873)
John (1810–1866)
Martin (1812–1855)
Winfield Scott (1813–1813)
Smith Thompson (1817–1876)

Hannah died before her husband was ever elected to presidential office. Van Buren entered the White House as a widower. The wife of one of his sons later served as White House hostess.
Van Buren died July 24, 1862, at age 79 and is buried in Kinderhook, New York.



** American Portraits 1825 to 1849  :drill:
William H. Harrison

William Harrison was the ninth President of the United States. He served from March 4, 1841, to April 4, 1841. He was born on February 9, 1773, on his father's Virginia plantation, called Berkeley. William attended Hampden-Sydney College, also in Virginia.

He was a soldier, a member of the House of Representatives, a U.S. Senator, and minister to Colombia.



** American Portraits 1825 to 1849  :drill:
Swift Endings

Harrison was inaugurated as president at age sixty-eight with John Tyler as his vice president. On a cold, windy day, he delivered the longest inaugural speech in history. (The inaugural speech was edited by politician and friend Daniel Webster and finished out at 8,445 words.)

Harrison later rode in the inauguration parade. He developed a cold which became progressively worse, and he died of pneumonia at the White House on April 4, 1841. He served only thirty-two days as president.



** American Portraits 1825 to 1849  :drill:
William and Anna Harrison

In 1795, Harrison married Anna Tuthill Symmes (1775–1864). They had six sons and four daughters:
Elizabeth Bassett (1796–1846)
John Cleves Symmes (1798–1830)
Lucy Singleton (1800–1826)
William Henry (1802–1838)
John Scott (1804–1840, the father of Benjamin Harrison, the twenty-third President of the United States)
Benjamin Harrison (1806–1840)
Mary Symmes (1809–1842)
Carter Bassett (1811–1839)
Anna Tuthill (1813–1865)
James Findlay (1814–1817)



** American Portraits 1825 to 1849  :drill:
William's wife, Anna, remained loyally at her husband's side until shortly before his election to the presidency. At the age of sixty-five and ailing, Anna urged her husband to go on to the White House without her. She planned to travel to Washington, D.C., after her recovery. Unfortunately, Harrison died before Anna could join him.

The once lovely bride of twenty-two who ran off with the handsome soldier against her father's wishes would never see her William alive again.



** American Portraits 1825 to 1849  :drill:
Harrison never had time to accomplish all the political changes he wanted to initiate. He had begun proceedings for a special session of Congress, but unfortunately, he fell ill and died even before he could appoint his cabinet members.

Harrison is buried in William Henry Harrison Memorial State Park in North Bend, Ohio.



** American Portraits 1825 to 1849  :drill:
John Tyler

John Tyler was the tenth President of the United States. He served from April 6, 1841, to March 3, 1845. Elected as vice president, John was elevated to the presidency by the abrupt death of President William Henry Harrison. John was fifty-one years of age.

Tyler was born on March 29, 1790, in Charles City County, Virginia. Tyler was a member of the Whig Party.



** American Portraits 1825 to 1849  :drill:
John Tyler's Presidency

When Tyler assumed the presidency, many of his opponents called him an "accidental president." Although the vice presidency had been created as a fail-safe method of continuing leadership in this country, people were surprised and shocked that the method would ever need to be implemented. Some politicians believed the vice president should lead the country for only a short time until another president was elected.

Tyler had other plans for his new role. He believed that his position required a transition to the presidency with full executive powers.
He took the reins of the country with authority and confidence and assumed presidential leadership.



** American Portraits 1825 to 1849  :drill:
Tyler's accomplishments as president included:

• multiple vetoes - When Tyler vetoed the re-establishment of a federal bank, his entire cabinet except one person resigned. Tyler's veto of several higher tariff bills infuriated Congress, which began impeachment proceedings against him.

• 1842 - Webster-Ashton Treaty: The signing of this treaty established border boundaries around Lake Superior and in Maine. This calmed relationships with Great Britain, which had disputed some of those boundaries.
• 1844 - Treaty of Wanghia: The first ever treaty with China was established, which included allowing foreigners to learn the Chinese language.

• 1845 - annexation of Texas: Tyler insisted on submitting a resolution on a Texas statehood bill to Congress before leaving office.

• 1845 - veto override: For the first time, Congress refused to let a president's veto stand and overrode Tyler's veto of a shipping bill.



** American Portraits 1825 to 1849  :drill:
John and Letitia Tyler

In 1813, he married Letitia Christian (1790–1842), and they had three sons and five daughters:

Mary (1815–1848)
Robert (1816–1877)
John (1819–1896)
Letitia (1821–1907)
Elizabeth (1823–1850)
Anne Contesse (1825–1825)
Alice (1827–1854)
Tazewell (1830–1874)
Letitia became the first First Lady to die while married to an actively serving president. John was the first president to become widowed while serving in office and the first to marry another woman during his presidential term.



** American Portraits 1825 to 1849  :drill:
John and Julia Tyler

In 1844, John married Julia Gardiner (1820–1889), and they had five sons and two daughters:

David (1846–1927)
John Alexander (1848–1883)
Julia (1849–1871)
Lachlan (1851–1902)
Lyon (1853–1935)
Robert Fitzwalter (1856–1927)
Pearl (1860–1947)

Julia was nearly thirty years younger than John, and her family initially protested the marriage.
When Julia's father was accidentally killed during a naval outing, the family relented and allowed her to wed.
Tyler died January 18, 1862, at age 71 and is buried in Richmond, Virginia.

** American Portraits 1825 to 1849  :drill:
James Knox Polk

James Knox Polk was the eleventh President of the United States and served from March 4, 1845, to March 3, 1849. Polk was born on November 2, 1795, in Mecklenburg County, North Carolina.

Polk graduated from the University of North Carolina and was a member of the Democratic Party. At the age of forty-nine, he was inaugurated as president and served one term.



** American Portraits 1825 to 1849  :drill:
Polk's Presidency

Events during Polk's presidency included:

• Manifest Destiny: Polk was responsible for acquiring land, fulfilling the spirit of the Manifest Destiny. During his administration, the United States was expanded by over 800,000 square miles.

• 1846 - Mexican-American War: Polk was president during the Mexican-American War. The Mexican-American War and the desire for completion of the concept of Manifest Destiny would be major factors in the Civil War that would later divide America.



** American Portraits 1825 to 1849  :drill:
Mexican-American War

Texas and Mexico went to war over a border dispute in 1846. Although the people living in Texas thought of themselves independent of Mexico, Mexican authorities considered the people rebels.

In resolving the war, the Treaty of Guadalupe Hidalgo was signed, adding nearly 500,000 square miles of land to the United States, including California, Nevada, Utah, and parts of the future states of Colorado, New Mexico, Wyoming, and Arizona.
This acquisition of land brought the slavery issue to the foreground, with each political faction wanting the new lands brought in as either slave or free states. Shortly after Polk left office, the Compromise of 1850 was implemented to help resolve disputes over newly acquired lands in America.



** American Portraits 1825 to 1849  :drill:
James and Sarah Polk

In 1824, Polk married Sarah Childress (1803–1891). The couple did not have children.
Polk decided to retire after serving one term as president. He died June 15, 1849, at age fifty-three, only three months after leaving office. He is buried in Nashville, Tennessee.



** American Portraits 1825 to 1849  :drill:
The men examined in this lesson exemplify how imperfections and individual beliefs can affect any person's decision-making abilities, including someone as powerful as an American president.

From the years 1825–1849, America saw a surge of growth politically, economically, and geographically. Some of this growth was for the good of the country but resulted in misfortune for some segments of the population.
However, for good or bad, the strong guidance of the presidents and Congress contributed to the rapidly expanding growth of the United States.

This expansion and growth in global influences and natural resources would eventually thrust the United States into the forefront of global power. The dream of Manifest Destiny would soon be fulfilled as America took on the role as one of the most powerful nations in the world.



** American Portraits 1825 to 1849  :drill:
To read more information about early political parties in the United States, please follow the links.



** Sectionalism and Slavery  :drill:
E Pluribus Unum

The Great Seal of the United States contains the Latin motto E Pluribus Unum. The translation of this phrase is "out of many, one." The phrase describes the creation and development of the United States of America. Under the government of the Articles of Confederation, thirteen colonies became thirteen states. These thirteen states then formed a new government when the Constitution was ratified.



** Sectionalism and Slavery  :drill:
Today, the Latin phrase is an important aspect of our government. It describes how the fifty states of the United States together form one federal government.

This commitment to be united is fulfilled in the Preamble to the U.S. Constitution. One of the goals is "to promote the general welfare." This means the power of the federal government as authorized by the people can be used to provide assistance to those in need.



** Sectionalism and Slavery  :drill:
What would you do if your city or town experienced the harsh effects of a natural disaster that damaged all the homes in your neighborhood? On a local level, who would be responsible for the general welfare and recovery of the neighborhood? Who should decide what are the priorities for the people? The Federal Government's task is to find fair solutions for all citizens.

The knowledge and information gained in this lesson will help you understand:

• the contribution of economic issues of tariffs, national banks, and internal improvements to sectionalism in the first half of the 1800s
• the political effects of sectionalism in the United States from the addition of territory and the issue of slavery

• the relationship between the Missouri Compromise (1820) and the Compromise of 1850

• the elements of the economies of the three sections (North, South, and West) during the first half of the 1800s



** Sectionalism and Slavery  :drill:
No one would disagree with the federal government providing emergency services to a town that had been devastated by a tornado or hurricane. Federal money is used to construct bridges, dams, or roads that many states or cities cannot afford to build. Federal funds may be used to partially finance a subway in a large city, even though this project would not benefit anyone living in a small, rural town in Montana. However, a new dam may provide cheaper electricity, drinking water, or water for irrigation in this same Montana town. These projects are known as internal improvements.



** Sectionalism and Slavery  :drill:
Sectionalism

The foundation of our government today is "out of many, one." Having these words on the Great Seal of the United States did not necessarily guarantee this was true in the early 1800s. In fact, the states were divided into sections based on economic and political issues.

Even though America was now a unified group of states, sectionalism was beginning to divide the new government. Sectionalism is a division of interests and needs. One aspect of sectionalism is a political loyalty to a group of people or a particular region of a country.



** Sectionalism and Slavery  :drill:
The issue of sectionalism was an integral part of the political, economic, and territorial expansion of the United States from the beginning until the mid-1800s. States became divided into sections over various issues that would eventually explode into the Civil War on April 12, 1861.



** Sectionalism and Slavery  :drill:
Geographic Regions

The issues of states' rights and nullification were raised in both the Northern (Hartford Convention) and Southern states (Virginia, Kentucky, and South Carolina) in the early 1800s. At that time, the United States was divided into three general geographic regions, the North, South, and West.

Each of these regions had specific economic interests. The Northern states depended on manufacturing, commerce, fishing, and shipbuilding. The economy of the West was mostly based on small farms, although not all Westerners were farmers.
The South's economy depended on the plantation system.

This map displays the economic divisions during the early 1800s.



** Sectionalism and Slavery  :drill:
"But not everyone in the South was a cotton planter. Tobacco, rice, sugar, hemp, peas, beans, livestock, and wheat were also widely grown products. Less than 1 percent of all Southerners owned more than 50 slaves, and most Southern farmers owned no slaves at all. On the other hand, most farmers aspired to own slaves and become large planters. The economic importance of cotton as a way to financial success would be significant in giving conscious identification to the South as a political entity."

Department of the Interior. National Park Service. Founders and Frontiersmen. Economic Expansion and Sectionalism.



** Sectionalism and Slavery  :drill:
Nationalism

A wave of nationalism arose in the United States in the period following the War of 1812. Nationalism can be defined as a loyalty to an entire nation and not just one geographical section.

The United States had just fought a war against Great Britain. The economy of the country was doing well, and the nation was expanding as new states were added to the Union.



** Sectionalism and Slavery  :drill:
American System

President James Madison used this new national spirit as the theme of his annual message to Congress in 1815. He proposed a program that included a protective tariff, banks, and internal improvements such as roads and canals. Representative Henry Clay of Kentucky referred to the plan of the tariff, national bank, and internal improvements as the American System. The American System included:

• a protective tariff
• the formation of a national bank
• a strengthening of the national infrastructure including transportation improvements



** Sectionalism and Slavery  :drill:
National Bank

A national bank was another important economic issue that contributed to the growth of sectionalism. The First Bank of the United States was created on February 23, 1791. It would be used as the financial agent for the federal government. Any income paid to the government, such as taxes or import duties, would be deposited into a national bank. The bank would also issue bank notes to ease the shortage of paper currency. These bank notes could be used to pay taxes or to buy goods.
Madison chartered the Second National Bank on April 10, 1816.



** Sectionalism and Slavery  :drill:
To encourage manufacturing in America, Madison proposed a protective tariff which was passed in 1816. A protective tariff would charge a tax, or duty, on goods imported into the United States. This would limit the number of imports and protect the American manufacturers who produced these goods.

On April 16, 1816, Madison signed the bank bill that reestablished the new national bank. The only issue that remained was internal improvements.



** Sectionalism and Slavery  :drill:
John C. Calhoun, a representative from South Carolina, proposed what he called a Bonus Bill that would fund internal improvements. He wanted to finance these improvements with a 1.5 million dollar charter from a new bank of the United States. Congress passed Calhoun's bill in February 1817.

The support of the American System was an attempt to unite the sections of the country. The people of the North, South, and West had mixed emotions about supporting these proposals.



** Sectionalism and Slavery  :drill:
The fate of the American System would set the political tone in the United States from 1815 to 1850. Some people believed the American System was an opportunity to fulfill the motto of E Pluribus Unum on the Great Seal of the United States. The opportunity to truly become "out of many, one" was at hand. Each section of the country would benefit from at least one aspect of the American System.



** Sectionalism and Slavery  :drill:
The American System did not receive widespread support in Congress. In 1816, there were nineteen states in the Union.
The states of Pennsylvania, New York, and New Jersey supported all three components of the American System. The Western states opposed the national banks because they wanted state access to paper money and loans. The Southern states opposed the tariff but supported some of the internal improvements. Some Southern leaders believed that accepting federal money for internal improvements would bring too much federal control into their states.



** Sectionalism and Slavery  :drill:
Economy and Internal Improvements—What Changed

President Madison reversed his position on the internal improvements he first proposed. Madison vetoed Calhoun's Bonus Bill because he did not believe Congress had the constitutional authority to fund the internal improvements. This began a chain of events that brought significant changes to sections in the West, North, and South.

The Western sections and some regions in the South were in need of these internal improvements.
The Northern section had the money to fund internal improvements and eventually built roads, railroads, and canals to the West. These improvements bound the two regions together economically.



** Sectionalism and Slavery  :drill:
While the economies of the Northern states continued to thrive, the South did not have the money to fund internal improvements. Internal improvements financed by the American System might have changed the economy in the South. A mixed economy of agriculture, manufacturing, and small farms may have lessened the South's dependence on slavery and changed the course of history.



** Sectionalism and Slavery  :drill:
The Westerners and Southerners also wanted internal improvements of roads and canals to help tie the sections together. Some internal improvements helped unite the country, but there was still a lack of total unification among the states economically, politically, and geographically.



** Sectionalism and Slavery  :drill:
Population

Early politicians wanted a way to measure the population of the United States. This would become very important in the results of presidential elections and representation in Congress. In 1790, U.S. Marshals were sent out to take a count of the population. Imagine how long it would take men on horseback to count 3.9 million people, the population in 1790.

The U.S. Census Bureau began to identify the mean center of the population every ten years.
The mean center pinpoints the imaginary line through the United States where there are as many people on one side as the other. The mean center of population in America in 1790 was 23 miles east of Baltimore, Maryland. In 1850, the mean center had moved 320 miles west to Parkersburg, West Virginia. In 1850, Parkersburg was part of the state of Virginia.

The 2000 Census identified the mean center of population in Phelps County in the state of Missouri.



** Sectionalism and Slavery  :drill:
The issue of a national bank would become an important aspect of the presidency of Andrew Jackson, who served from 1829 to 1837.

"During his first term, Jackson vetoed a bill renewing the charter of the United States Bank…When the public money, which had been withdrawn from the Bank of the United States, was deposited in the local banks, it became easy to borrow money. Speculation extended to every branch of trade but especially to western lands."

Barnes and Co. A Brief History of the United States.



** Sectionalism and Slavery  :drill:
Bank Speculations

President Jackson did not support the use of paper money to buy public land. He issued the Specie Circular  in 1836, which required the purchase of public land to be made in gold or silver. This requirement ended the land boom in the West. The federal government now had a surplus of money.



** Sectionalism and Slavery  :drill:
"The mid-1830s witness an economic boom, characterized by inflation and speculation in public land sales and road and canal projects. The speculation is fueled, in part, by the following three policies:

• The removal of federal funds from the official bank of the United States and from other banks.

• A distribution of the federal surplus from these banks to state banks.

• A requirement that specie (gold or silver coin) be used to buy public lands (which leads to falling land sales and specie shortages).
The pressure on many banks increases and a lack of confidence in the state banks abounds. The resulting bank panic in 1837 causes many banks to fail over several years."

Federal Deposit Insurance Corporation.



** Sectionalism and Slavery  :drill:
1815 - What Remained the Same

Tariff

The protective tariff passed in 1816 was one aspect of the American System that survived. During the presidency of John Quincy Adams, the Tariff of 1828 became a political issue. This tariff created new duties and raised others. It was passed by Congress and became known as the Tariff of Abominations in the South.



** Sectionalism and Slavery  :drill:
The country also had to address the political, social, and economic issues of slavery. The U.S. Congress faced the political issue of slavery for the first time in 1820.

By 1819, three more states had been added to the Union.



** Sectionalism and Slavery  :drill:
Economic Division

Some of the states such as Kentucky and Tennessee were considered part of the Southern and Western regions in the early 1800s. Delaware aligned with the Southern states over some issues and the Northern states over others. Delaware was originally a Middle colony and later became a slave state.

The economic divisions between the North, West, and South were not clearly defined. The issue of slavery widened the chasm of sectionalism between the states.



** Sectionalism and Slavery  :drill:
The Missouri Compromise

The population of the state of Missouri was growing rapidly, and by 1818, it had reached 60,000. Many of the settlers who came to Missouri were from the Northern territories where slavery had been forbidden. Others had migrated to Missouri from the slave states of Kentucky and Tennessee.
The admission of Missouri would upset the balance in the U.S. Senate of eleven free states. This was important to the South because the North, with a larger population, had more representatives in the House of Representatives. Do you remember the large and small state arguments at the Constitutional Convention?



** Sectionalism and Slavery  :drill:
The Tallmadge Amendment

James Tallmadge, a representative from New York, proposed an amendment to the bill to admit Missouri to the Union. The Tallmadge Amendment would stop any new importation of slaves into Missouri after its admission as a state.

The balance of free and slave states was maintained from 1820 to 1850 with the admission of three free states and three slave states.



** Sectionalism and Slavery  :drill:
Texas

The question of slavery in the territories was not raised again until after the annexation of Texas at the end of the Mexican-American War in 1848.



** Sectionalism and Slavery  :drill:
California

There were events in California that would challenge the political viewpoints in all sections of the country. The territory of California had enough settlers to apply for statehood by 1849, and the search for gold brought many people to the area. The territory's representatives requested admittance to the Union as a free state.

The admission of California would change the balance of the fifteen free and fifteen slave states in the Senate. The Senate also had to abide by the requirements of the Missouri Compromise.
The dividing line established by the Missouri Compromise passed through the middle of California.



** Sectionalism and Slavery  :drill:
U.S. History on the Road

The U.S. History on the Road section serves as your connection to the past. You are encouraged to research any topic in this lesson.

Click here to read about the Chesapeake and Ohio Canal, the Allegheny Portage Railroad, and the Erie Canal.
Remember, the foundation of our government today is "out of many, one." The American System addressed the issues of the tariff, internal improvements, and a national bank, which contributed to the movement toward sectionalism.

Despite the differences that resulted from various policies and laws, Americans needed to find a way back to a nationalism and solidarity. A sense of unity would be required to solve issues that divided the states, especially the issue of slavery. Without this unity, the nation would continue toward the path of civil war.
